### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-dashboard#1]
Need to have a clear guide on how to migrate from the current `node-red-contrib-ui` to `node-red-dashboard`.

**Comment by natcl** [comment]
Some comments:
No more radio buttons (they were on the master branch)
If they are too tricky to implement a dynamic menu/select widget would be really nice...

**Comment by ukmoose** [comment]
also think you mean ~/.node-red in the README notes rather than cd ~\.node-red :-)

**Comment by s00500** [comment]
Also the old ui_tab config nodes seem to make some problems... I had to recreate all of them when updating...
