### ISSUE TITLE
Angular dependencies not installed for dev version

### ISSUE THREAD

**Issue by s00500** [node-red/node-red-dashboard#10]
Strangely I had to manually install these 3:

node-red-dashboard@2.0.0 /root/.node-red/node_modules/node-red-dashboard
├── angular-messages@1.5.5  extraneous
├── angular-mocks@1.5.5  extraneous
└── angular-route@1.5.5  extraneous

(I got these warnings before:
npm WARN angular-material@1.0.8 requires a peer of angular-messages@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-mocks@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.0.8 requires a peer of angular-route@>=1.3 <1.6 but none was installed.
)

**Comment by dceejay** [comment]
anyway you can retry this with the latest build ?

**Comment by s00500** [comment]
Still a problem

**Comment by dceejay** [comment]
what node.js version ? OS ? npm version ?

**Comment by s00500** [comment]
npm version 3.6.0,
node version v5.6.0

The problem is that angular-material just names these as peerdependencies and if no other paclkage installs them they will be missing
https://nodejs.org/en/blog/npm/peer-dependencies/

I think the correct way is to add them as dependcies in the main package.json

Also jshint seems to be missing 
(npm WARN gulp-jshint@2.0.1 requires a peer of jshint@2.x but none was installed.)

add 
        "angular-messages": "^1.5.0",
        "angular-mocks": "^1.5.0",
        "angular-route": "^1.5.0",
        "jshint": "^2.9.2",

as dependencys

**Comment by dceejay** [comment]
well jshint is only for dev so shouldn't be needed. Also currently we specify Node 4 LTS , and Npm 2. But yes need to look at this going forwards.

**Comment by dceejay** [comment]
Ok - using node.js v5.11.1 and npm 3.9.2 - if I install 

    npm i node-red/node-red-dashboard

ie the distribution version - it works fine..
so those dependencies seem to be only for the dev version - so shouldn't be a big problem for when we release on npm.

**Comment by dceejay** [comment]
Ok - using node.js v5.11.1 and npm 3.9.2 - if I install

    npm i node-red/node-red-dashboard

ie the distribution version - it works fine..
so those dependencies seem to be only for the dev version - so shouldn't be a big problem for when we release on npm.

**Comment by dceejay** [comment]
closed by commit 1b40d4673b9fcc1faddd26ebf39d111d494ee602
