### ISSUE TITLE
Support for Internet Explorer 11

### ISSUE THREAD

**Issue by jwende** [node-red/node-red-dashboard#109]
Hi,
I wonder if you could update index.html with:

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

That would give us support for IE11.

Thanks
Joerg

**Comment by dceejay** [comment]
Hi,
from http://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do
seems to say that  <!DOCTYPE html> should be enough to trigger edge mode...  and we have that already...
