### ISSUE TITLE
Template node: width and height

### ISSUE THREAD

**Issue by s00500** [node-red/node-red-dashboard#11]
the template node needs fields for height and width

**Comment by natcl** [comment]
Shouldn't the template resize automatically according to the content that's in it ? (for height at least)

**Comment by s00500** [comment]
That would also be nice.. but using the same grid as for all other controls can also be a good thing

**Comment by natcl** [comment]
What happens then if you want to put dynamic content in a template (like a list of buttons that can change ?) Or if you just want to put text and have the template resize in height according to the length of the text ?

**Comment by s00500** [comment]
I put in a colorpicker an no resize happened at all, the box was at its default 6x1 in the grid and the colorpicker overlapped with other elements

**Comment by natcl** [comment]
It used to work fairly well with the older ui, perhaps an option to have an infinite height with the template as well as fixed size could be an option for the future.

**Comment by jdp1g09** [comment]
There is a plan to put width option on the template node. May have that in tomorrow.

The height should be automatically scaling based on the content for the template node. There was a push last week that fixed an issue with that, so it may just be a matter of updating to newest version depending on which one you're using.

**Comment by jdp1g09** [comment]
It is also worth mentioning that the 'text input' node has a 'color' mode which provides a color picker.

**Comment by s00500** [comment]
The colorpicker in the textinput is very nice but it needs more than one tap for interaction (I'm currently using the dashboard on wallmounted android displays) therfore I still like my current solution better (which is based on this: http://tech.scargill.net/node-red-ui-miracles/ ) 
I just pulled from master again and still the template's card does not resize with the colorpicker
![screen shot 2016-05-16 at 16 30 26](https://cloud.githubusercontent.com/assets/1556271/15292520/bc88472e-1b83-11e6-89b7-a33f4631a673.png)

(Browser is Vivaldi but it looks the same on Android's Browser)

**Comment by jdp1g09** [comment]
Interesting, my guess is that the CSS for the picker has absolute positioning, i.e. the template doesn't take it into account...?

**Comment by s00500** [comment]
Hm... there is a span tag around the input that has position: relative; and also the parts of the picker all have position set to relative

**Comment by jdp1g09** [comment]
try changing the <span> to a <div>
