### ISSUE TITLE
Theme reverting at random

### ISSUE THREAD

**Issue by scargill** [node-red/node-red-dashboard#110]
As requested - an issue in here.

At least 3 of us have noticed the same thing - not easy to reproduce but it is happening..

Select DARK theme - run - use.

Occasionally on power off or restarting node-red - it reverts back to the light theme.

Can't be more precise - it has done this to me maybe 4 or 5 times - thought it was just me but apparently not.

**Comment by dceejay** [comment]
ok - will keep an eye out, but unless we can replicate we will struggle to fix it, as once it's written in the flow file it isn't going to move.

**Comment by Paul-Reed** [comment]
I've had my 'dark' theme revert back to 'light' 3 times now after either a reboot or a NR stop/start.
Most recently, it occurred following update to v0.16, where I stopped and restarted NR, and suddenly I had changed to the light theme. On previous occasions I've re-selected 'dark' form the Dashboard tab theme setting, deployed and the dark them was then in play, but on this occasion I didn't and found the following which may help.
I downloaded the current flows_raspberrypi.json (confirmed that it's the same one described in NR log) and searched through it for `nr-dashboard-theme` (which I presume is the selected theme) and found just 2 occurrences as follows;
`.nr-dashboard-theme-dark ui-card-panel {\n \tbackground-color: #222;\n \toutline: 1px solid #4F4F4F;\n \t  }\n</style>","storeOutMessages":false,"fwdInMessages":false,"x":642,"y":26,"wires":[[]]},{"id":"2133cb54.f37f94","type":"ui_template","z":"a444a9ff.e7a408","group":"a9c0b162.e0664","name":"","order":0,"width":"0","height":"0","format":"<link rel=\"stylesheet\" href=\"/weather-icons/mycss/weather-icons.min.css\">\n<style>\n    .nr-dashboard-theme-dark ui-card-panel {\n \tbackground-color: #222;\n \toutline: 1px solid #4F4F4F;\n \t  }\n \t  md-toolbar.md-default-theme:not(.md-menu-toolbar),`
In both cases it appears to still show the dark theme active, despite screenshots below showing that the 'light' theme is in play.

A further NR stop/start does not change things.

I haven't yet redeployed the dark theme in case you want further tests.

![light theme](https://cloud.githubusercontent.com/assets/973580/21906380/09d6e502-d903-11e6-924e-57b31300ca29.PNG)

![settings](https://cloud.githubusercontent.com/assets/973580/21906391/13e5c6d0-d903-11e6-9461-519f7a78db7b.PNG)

**Comment by dceejay** [comment]
Andy chance you can share the entire flow file with me (via email) ?
Thanks

**Comment by Paul-Reed** [comment]
Sent to your gmail

**Comment by scargill** [comment]
Well, while commiserating with your problem I am glad it is not me. I simply cannot use the dark theme for fear of it reverting back to white - and I REALLY would like to use it as I want to use grey panels on dark backgrounds -  I will watch this with a keen eye...

**Comment by dceejay** [comment]
Pete - we think we may have found it...

The ui_base node that holds the theme is a config node. Every now and then something will trigger a message on deploy saying there are unused config nodes and suggesting you tidy up... Which not un-naturally the user does... only - if they delete the ui_base node (that has no actual direct users) - them the theme reverts to nothing/light....



![image](https://cloud.githubusercontent.com/assets/5375409/21911292/19e92724-d918-11e6-86a0-20368cfd9f28.png)

So top tip is don't delete the ui_base node... while we work out how to hide that, so you won;t be tempted to delete it.

**Comment by Paul-Reed** [comment]
I feel pretty confident that you've nailed it, having just run through the scenario again;

- Select dark theme & deploy - result - dark theme
- Make a change & deploy - popup saying that the ui-base node is unused
- Delete the 'unused' node - result - still dark theme
- Stop & start NR - result - deja vu - light theme!

Paul

**Comment by dceejay** [comment]
well the popup should be because some other node is unused... the ui_base shouldn't trigger it on it's own (yes you did I recall -  but not going to post it here)

**Comment by Paul-Reed** [comment]
Yes, in the example scenario, I dropped a (random) node from the pallet
(which was unused), just to enable a deploy to take place.

**Comment by dceejay** [comment]
need to make sure that the ui_base node does not appear unused in the the configuration nodes menu - so users won't be tempted delete it.

**Comment by dceejay** [comment]
Actually now fixed with a patch to core in version 0.16.1
a03ccd7b59fd3d5cb095d1c02bcfd9e9d708ce63

**Comment by scargill** [comment]
Well done
