### ISSUE TITLE
Menu switch - option to hide menu - option to hide top bar

### ISSUE THREAD

**Issue by scargill** [node-red/node-red-dashboard#111]
I've been thinking about this - blogged it only tonight... as Dashboard has a node to switch pages - which could be handled by buttons - BIG buttons - it would INCREDIBLY improve dashboard if you'd add a tick box to turn off the menu and top line COMPLETELY (or worse case just the menu - or TWO tickboxes if you like).

You have the ability to use buttons or anything to change pages via the node - so on a small (5") touch screen the otherwise excellent menu system is more of a liability in the hands of an end user like the spouse when on a wall as it is too small. Much better a graphical HOME button and NEXT buttons or similar which of course are easy with buttons or templates... making the menu somewhat redundant FOR THAT PURPOSE.

ANY chance you could consider this?  I've just added style one-liner to get rid of the mouse pointer which is more of an annoyance when using a touch-screen - that works great - a toggle on the menu would nicely turn this into a great kiosk-style controller for everything from Thermostats to public places.

**Comment by dceejay** [comment]
Pete,
can we have discussion for features on the mailing list or slack please, and keep th eissues for actual problems ? thanks

**Comment by knolleary** [comment]
This was on the mailing list: https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/node-red-contrib-ui/cYUbXolc-4c

Peter: when raising issues that have been discussed we don't need a full replay of what was discussed. Makes it hard to see the specific thing being proposed.

I see this as a sensible option in the context of custom themes.

**Comment by dceejay** [comment]
oops - sorry Pete . Dunno how I missed that one. Can only blame day job getting in the way :-)

Yes - guess it could be added to the site wide styling options.... like re-enabling swipe.

**Comment by dceejay** [comment]
now on master
