### ISSUE TITLE
Bug on Compass / Donut with negative range

### ISSUE THREAD

**Issue by Swunn** [node-red/node-red-dashboard#113]
With Range min set to negative values the Compass and Donut gauge nodes look strange.

![donut](https://cloud.githubusercontent.com/assets/24499427/21076626/6ca045ee-bf30-11e6-9e25-d7fec88bd679.jpg)
![compass](https://cloud.githubusercontent.com/assets/24499427/21076628/71ec33aa-bf30-11e6-81d6-645f6854c6cd.jpg)

**Comment by dceejay** [comment]
this is a known issue with the underlying library... 

https://github.com/toorshia/justgage/issues/248

**Comment by combefis** [comment]
Just quickly fixed the issue right now! Waiting for the owner of the underlying library to check and eventually accept it!

https://github.com/toorshia/justgage/pull/312

**Comment by dceejay** [comment]
Nice work... shout if they don't respond. I can probably monkey patch it here at the install step if we had to.

**Comment by DDDanny** [comment]
Dear folks,
do you think this patch will also fix the normal gauge display for non numeric values?

My Problem is that the (internal) gauge value is always converted to 0.
If the min value is greater 0, then this is no ok, because 0 will not be filled up.

But if you have a <= zero base, then this happens :
![grafik](https://user-images.githubusercontent.com/31635744/38442610-24351f0c-39e9-11e8-8b2e-3140564b9902.png)
Hint: I hide the pointer on this INVAL scenario

If not, I wasn't able to locate the justgage lib in the  node-red-dashboard folder - is it remotly loaded?

Thanks a lot
Danny

**Comment by dceejay** [comment]
Hi - I don't think that the justgage library has a simple way to "remove" the fill and pointer for an invalid or null value... though it could be interesting to add if you can think of a way.

The library is in the source - but is bundled into the dist/js/app.min.js file as part of the build process

**Comment by DDDanny** [comment]
Thanks you.
for values >= 0 this will work fine - I'll test this tonight in detail. I expect the same results as for my left gauges (the green ones) - without having to set ui_control.options - which would it make more clear...
for values <0 the justgage.js seems buggy. As setting e.g. -100 the libary will set in it internally to lowest min. e.g.  -20 on top right red gauge. But it will still display up to zero.
That was why I asked as it might be related to the neagtive number issue in compass / donut.
But I'll come with detail testing and with ideas how to fix...

**Comment by dceejay** [comment]
Not sure I get what you mean - if I now send -100 I get
![image](https://user-images.githubusercontent.com/5375409/38456535-9c99a924-3a7d-11e8-92b7-1f40ba38dc94.png)
so yes in my case I haven't hidden the pointer - but the value is correct - just the indicator is just like a real dial and stuck on the bottom stop.

**Comment by DDDanny** [comment]
Yes. If I send it as value.
I send INVALID as value and set the ui _ control.options.value to e.g. -100.
Then it uses 0 for the scale instead of -100.
I'm currently not at home. As said I'll come back. Also with a small codebase to make it clear.

**Comment by DDDanny** [comment]
confirmed, the new code works like a charm! Now the gage is showing correctly including negative scales

![grafik](https://user-images.githubusercontent.com/31635744/38461411-76ca4d3c-3acf-11e8-9cca-4d1d10c9947e.png)
