### ISSUE TITLE
Time axis error on v2.2.0

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-dashboard#124]
Dashboard originally created using dashboard v2.1.0 
If you change the size of a Chart node, it no longer displays the time on the axis, but displays HH:mm:ss instead.
**Example;**
The existing chart node looks like;

![old](https://cloud.githubusercontent.com/assets/973580/21297098/5943c36c-c571-11e6-8688-4eb60726d094.png)

Now edit the chart node, change the size from 'auto' to 6 x 4 and deploy, now looks like;

![new](https://cloud.githubusercontent.com/assets/973580/21297104/80f426ea-c571-11e6-8737-4d0836fed59a.png)

Changing the node size back to 'auto' and deploying, still results in HH:mm:ss being displayed instead of the time, and clearing the browser cache, or reselecting the node time format does not fix.

**Comment by dceejay** [comment]
Can you check, and maybe change the x-axis units, save and redeploy.

**Comment by dceejay** [comment]
Oops. Sorry. Saw you have done that

**Comment by Paul-Reed** [comment]
Hang on, I think this is my fault

**Comment by Paul-Reed** [comment]
I had reverted back to v 2.1.0 to moan about the wasted space, and forgot to update back to v2.2.0.
Updating back to v2.2.0 resolves the issue.

Sorry to waste your time
