### ISSUE TITLE
Theme customisation issues

### ISSUE THREAD

**Issue by DanCunnington** [node-red/node-red-dashboard#137]
This is to keep track of small issues and upcoming features related to the theme work (styling branch).

**Done**
- ~~Fix runtime error when upgrading from an old flow file (`error evaluating function lighten: a.toHSL is not a function`).~~ ✅ 
- ~~Compass gauge pointer colour does not update when changing theme.~~ ✅ 
- ~~name field in globalDashboardNode is not sticking.~~ ✅ 
- ~~allow chart series colours to be customised in the chart node - similar to gauges.~~ ✅ 
- ~~check that old base node is removed when upgrading.~~ ✅ 
- ~~if no dashboard widgets are added, theme does not change.~~ ✅ 
- ~~fix colour picker issue on safari. currently the hex value is displayed, it is not obvious that the style is editable.~~ ✅ 
- ~~ensure themes are backwards compatible.~~ ✅ 
- ~~Fix filename issue when saving theme.~~ ✅ 
- ~~Don't delete the old base node, just update existing.~~ ✅ 
- ~~Can we refactor globalDashboardNode?~~ ✅ 
- ~~Investigate the removal of the 'users' and 'url' fields in globalDashboardNode.~~ ✅ 
- ~~Do we really need to specify defaults in main.js for backwards compatibility?~~ ✅ 
- ~~Check using old flow file works with old theme and old site name.~~ ✅ 

**To Do**
- extend site tab 
  - ~~control swiping between pages~~ ✅
  - ~~hide/show top bar~~ ✅
  - ability to specify favicon
  - allow optional "status" widgets on top bar - eg clock - or maybe "any" widget ?
  - ~~expose fundamental geometry numbers ?~~ ✅

**Comment by kmozurkewich** [comment]
Any best-practices for externalizing the theme/style profiles?  When I export the library, the color changes work, but none of the site information gets exported.  Goal is to get a custom theme/style auto-loaded when node-red is fired up for the first time.

**Comment by dceejay** [comment]
The site info should be there... it's in the file if you look...
![image](https://cloud.githubusercontent.com/assets/5375409/24425759/36ba54c0-13fd-11e7-8dbc-7ae5cc498707.png)
.. BUT...  yeah - they don't seem to get imported again correctly... that's a bug

**Comment by kmozurkewich** [comment]
I'll open an issue on it for you - thanks.  I do see the site json there on my end...

**Comment by felipeplets** [comment]
Hello @DanCunnington, 

We are using the latest version and is very nice the new theme features!
Is there any plans to implement an auto swipe? We have the dashboard on a wall in our startup and we would love to auto-swipe it from time to time. 

All the best, 
Felipe

**Comment by dceejay** [comment]
Hi. In general we prefer general questions on the mailing list or via the slack channel... But you can use the ui_control to swap tabs at any time you like.
