### ISSUE TITLE
chart performance

### ISSUE THREAD

**Issue by jjssoftware** [node-red/node-red-dashboard#144]
node v6.9.1
node-red v0.15.2
node-red-dashboard v2.2.1

There were no takers to this comment on slack: https://node-red.slack.com/archives/general/p1483395921001718

> For anyone here using the node-red-dashboard chart node - have you ever seen a performance issue on initial page load with a small(ish) number of points? Let's say 1500 points on a line chart.

Is this a known issue?

Cheers
Joe

**Comment by Paul-Reed** [comment]
Hi Joe, I did read the post on slack, but assume that you didn't get a reply because nobody else is seeing this as an issue.
I'm loading a similar number of datapoints, with no problems.

**Comment by jjssoftware** [comment]
Cheers Paul for responding. Not a known issue then. In fact it's the opposite of that, it's all good and it must somehow be me 😀

**Comment by dceejay** [comment]
loads of points can always be a problem - see this thread on the mailing list
https://groups.google.com/forum/#!topic/node-red/shZxX9ySZkQ

**Comment by jjssoftware** [comment]
aha thanks for the heads up Dave. Time rewind..a known issue it is.

In my case I saw this phenomenon when I had a bug in my flow causing a new message to flow into the chart every minute rather than on state change. After about a day, chart initial page load had pretty much ground to a halt in mobile Chrome latest (v55) on Android 6.0.1 running on a reasonably specced OnePlus 2 handset.

I fixed my flow bug, data point volume is now hugely reduced and I no longer have an issue.

I'll let you project owner / maintainer type guys decide whether you want to close this issue down or if you prefer to leave it open. 

Cheers
Joe

**Comment by dmdelorme** [comment]
I am a loss about what is going on. the data amount is not that large (size but it chokes the system ie node-red..
very frustrating.
I have the same problem with another web app not relate to node-red.. +10000 data points, it might be cheaper CPU wise to generate a png. it seems weird that i can stream netfilx but crap out on a few thousand data points.  
Or am i missing something?

**Comment by dreamfalcon** [comment]
Same problem here in a galaxy s6. 
The performance of the charts is very bad comparing with CanvasJS that I use in my  applications.  Can draw 100.000 points in a few milliseconds. 
With node red I have to limit at 1000 points in order to have a acceptable experience.

**Comment by dceejay** [comment]
Hi - would really appreciate someone else getting involved in this. How do you manage so many points dynamically ? how do you trim the array size ? (either by time or number of points).How do you re-sync front and back end for page refreshes / late joiners and then continue to add points dynamically (without sending the whole array every time).

**Comment by jjssoftware** [comment]
@dceejay I'm not entirely sure what group of people your last comment was intended for. So far I've seen nothing to suggest that node-RED users are resolving this problem by doing special things with chart data in this issue, in the google mailing list or in slack. Is anyone developing custom node-RED nodes on the server side or manipulating chart render with the chart JS code on the client side to work around this issue? 

Perhaps you intended for your comment to be a call for help to anyone with general chart.js experience with angular? If so that type of request might work better here: https://github.com/chartjs/Chart.js/issues

**Comment by dceejay** [comment]
Well it's intended for anyone reading this issue who may have some time to offer suggestions and help. Can't think it's a generic charts.js issue as prior to moving to it people were saying how great it was... so must be something about the way we are using it.

**Comment by dceejay** [comment]
This 5d20ac6f4fe37ea25201a41172f8cd01490e16a2 using a  newer more direct format should be better...

BUT still more could be done re handling of the underlying websocket

**Comment by QAnders** [comment]
For anyone stumbling upon this and are running on a Raspberry PI/Beaglebone, etc. with limited memory (e.g. 1 GB for the Raspberry PI), run your Node-red with flag `--node-args="--max-old-space-size=256"` to limit the memory the Node-red can munch!
(And use the Delay Node to slow down any sensors publishing more often than once a second!)
(In newer Node-RED versions there is a "Delay" node...)

It runs perfectly after adding the memory restriction!

**Comment by coffeegoat** [comment]
Just another comment with a workaround for Raspberry PI users, we've run into issues with charts with large amounts of data as well.  The approach we've taken is actually to completely avoid the charts built into Dashboard and instead use an Influx/Grafana approach.  If you're creating a bunch of data you're probably already pushing it into a database (in our case we use InfluxDB) which means it's already in a relatively optimal place.  Using a template node you can easily embed a grafana dashboard which comes with all the chart goodies grafana has built in.  Our Grafana Dashboard runs an update every 5 seconds or so and re-plots if there is new data in the database which entirely unloads Node Red to run a bit more snappy which makes the rest of our Dashboard UI much more pleasant to use.

**Comment by leeoniya** [comment]
if your time-series charts are rendered in the browser, you should try https://github.com/leeoniya/uPlot
