### ISSUE TITLE
Configurable Colour for UI Toast

### ISSUE THREAD

**Issue by hpgmiskin** [node-red/node-red-dashboard#145]
If this is not already possible it would be amazing to configure the colour of the notification so that information and errors can be displayed differently to the user. Thanks

**Comment by dceejay** [comment]
When you say colour the notification... do you mean the text or the background.
In theory the background should be part of the site style (if we are trying to stay anywhere near the Material design guidelines)

**Comment by hpgmiskin** [comment]
The colour of the notification box would be ideal to make it very obvious to the user.

I think it makes complete sense to conform to Angular Material so perhaps just allowing selection of an accent or selecting a Material class, `md-warn` for example.

**Comment by dceejay** [comment]
apologies for not being a design person... but there is only the text colour of the title (if set by topic), the actual text and the background... where would the accent be ?

**Comment by dceejay** [comment]
Though there is a border as well...

![image](https://cloud.githubusercontent.com/assets/5375409/21743991/2198c608-d505-11e6-87ea-85252a5f3b23.png)

If so then should the Title match the border ?

**Comment by dceejay** [comment]
Hi @hpgmiskin - any feedback on the above ?

**Comment by hpgmiskin** [comment]
@dceejay this looks really good as will easily display to the user that there has been an error. What branch are you working on? I would love to try this out on my own computer. Thanks

**Comment by dceejay** [comment]
Hi, ok have pushed it to master on github... 

     cd ~/.node-red && npm i node-red/node-red-dashboard

if you want to try it

**Comment by bonastreyair** [comment]
It seems like there s a bug with the border color that stays for about one second while the actual "pop-up" is sliding away

Check the photo steps example. It's kind of anoying as UX to see the pop-up with colors and then that the color stays on screen...

![Screenshot 2019-08-15 at 18 50 55](https://user-images.githubusercontent.com/37800834/63090374-a588a300-bf8d-11e9-8c6c-05e3c3c4d01b.png)

Thanks,

**Comment by m-obi** [comment]
Yeap, it's annoying and the border doesn't work for a dialog.

**Comment by dceejay** [comment]
Improved by f6ebaf75bd54dddbad607d020cbbc355c77da8c2 in master

**Comment by m-obi** [comment]
Still not working at the dialog and the border stay still there after the popup is sliding away.
