### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by marciogranzotto** [node-red/node-red-dashboard#148]
is there any way to protect the dashboard with an username and password?

**Comment by knolleary** [comment]
Currently the only way to do it is via the `httpNodeAuth` option in the settings file.

It isn't an ideal solution and better auth options is on the to-do list.

**Comment by marciogranzotto** [comment]
@knolleary also it would be nice to have like a "read-only" mode, where the unauthenticated user can only see the data but can't make actions, like clicking buttons and such

**Comment by Quentintin** [comment]
Any evolution about this issue ?
