### ISSUE TITLE
numeric bugs

### ISSUE THREAD

**Issue by jjssoftware** [node-red/node-red-dashboard#150]
node v6.9.1
node-red v0.15.2
node-red-dashboard v2.2.1
Linux Mint 17.3
Chromium 53.0.2785.143

I'm seeing a couple of problems with the ui_numeric node:

1. When specifying a step value of 0.1, incrementing the step value in the dashboard on the numeric can on occasion result in a very long number with many decimal places. Looks like a rounding bug.
2. When incrementing / decrementing the step value in the dashboard on the numeric, the numeric selection can become 'erratic'. This problem manifests itself as the user selection getting 'stuck' resulting in the numeric automatically spinning all the way down to the minimum value or spinning all the way up to the maximum value. When this happens, the page requires a refresh to get the numeric responsive again. Not sure what's going on here..

Here's a small sample to reproduce (a single numeric with a single input initial inject, was placed on an empty dashboard with no other nodes) :
```
[{"id":"db564ccd.d9328","type":"ui_numeric","z":"c04d59f2.5aeb68","name":"Target Temperature","label":"Ideal Temperature","group":"7d9d74ff.22677c","order":0,"width":0,"height":0,"passthru":true,"topic":"targetTemperature","format":"{{value}}","min":"15","max":"25","step":"0.1","x":300,"y":103,"wires":[[]]},{"id":"e677ecaf.380df","type":"inject","z":"c04d59f2.5aeb68","name":"","topic":"","payload":"21","payloadType":"num","repeat":"","crontab":"","once":true,"x":101,"y":98,"wires":[["db564ccd.d9328"]]},{"id":"7d9d74ff.22677c","type":"ui_group","z":"","name":"Numeric Test","tab":"d2616a89.b16038","order":1,"disp":true,"width":"6"},{"id":"d2616a89.b16038","type":"ui_tab","z":"","name":"Numeric Test","icon":"dashboard","order":5}]
```

![screenshot 2017-01-17 07 56 51](https://cloud.githubusercontent.com/assets/536164/22012149/93a23e3c-dc8a-11e6-88b8-831a03cbdf39.png)

**Comment by jjssoftware** [comment]
Hi @dceejay thanks massively for taking a look at this. I'm sure it must be me doing something wrong because I'm not seeing this fix at the moment. These are the things I've done to attempt to get this fix from git:

```
cd ~\.node-red\node_modules
git clone https://github.com/node-red/node-red-dashboard.git
cd node-red-dashboard
npm install
```

then
`gulp

I then verified that I could see this fix present in the minified/refreshed .node-red/node_modules/node-red-dashboard/dist/js/app.min.js file - it is there. I also verified that .node-red/node_modules/node-red-dashboard/dist/dashboard.appcache was rebuilt with gulp and it was, it has a new timestamp.

I then stopped and restarted node-red.

I then completely removed the browser client app-cache via chrome://appcache-internals.

Can you see anything wrong with anything I've done here? 

Cheers
Joe

**Comment by dceejay** [comment]
no need… you can pull direct from master     cd ~/.node-red && npm i node-red/node-red-dashboard, then restart Node-RED and refresh the browser page a couple of times

**Comment by jjssoftware** [comment]
oh thanks for that..but never mind my bad. One thing I hadn't done after doing all of the above was reboot my box. I done that and I can now see the fix, it's working fine. Thanks again for taking a look, it's very much appreciated.

**Comment by Paul-Reed** [comment]
Setting the step from 0.1 to 0.01 brings a strange reaction. Are you seeing the same Joe?

![test](https://cloud.githubusercontent.com/assets/973580/22042132/c001e8b6-dd01-11e6-8822-a723083d3dc6.gif)

**Comment by dceejay** [comment]
ahhh - hmm -  seems to be something to do with moving the mouse out while still pressing the button - darn users !

**Comment by jjssoftware** [comment]
ah yeah good spot - called it too early ;)

**Comment by Paul-Reed** [comment]
Can confirm fixed, thanks Dave.

Paul
