### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by bsculley** [node-red/node-red-dashboard#152]
I am attempting to install node-red-dashboard on BeagleBone Black running Debian Jessie (Linux arm 4.4.12-ti-r30).  Node Red installs and works ok.  The dashboard seems to install ok, but afterward there is no dashboard tab in Node Red and the :1880/ui url doesn't work (Cannot GET /ui).

The result of the install is:

 npm install node-red-dashboard
/home/pi/.node-red
└── node-red-dashboard@2.2.1

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.

I don't understand the missing package.json file.  I tried creating one and the message went away, but the dashboard still didn't work at all.

Am I missing something?

**Comment by dceejay** [comment]
those are just warnings and can be ignored.

what does the top of the console log say when you start node-red ? It should be something like


25 Jan 10:50:19 - [info] Node-RED version: v0.16.1
25 Jan 10:50:19 - [info] Node.js  version: v4.7.2
25 Jan 10:50:19 - [info] Darwin 16.3.0 x64 LE
25 Jan 10:50:19 - [info] Loading palette nodes
25 Jan 10:50:20 - [info] Dashboard version 2.2.2-beta started at /red/ui
25 Jan 10:50:21 - [warn] ------------------------------------------------------

**Comment by gigajoules** [comment]
So did you ever fix this@?

**Comment by dceejay** [comment]
there was nothing to fix
