### ISSUE TITLE
'Maximum call stack size exceeded' when msg originates from HTTP In

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-dashboard#153]
If a message that originates from an HTTP In node is passed to a ui_template node you get the error:

    RangeError: Maximum call stack size exceeded

This is presumably because the node is trying to JSON encode the message so it can be passed to the dashboard. In this instance, the msg.req and msg.res objects contain circular references (and are BIG objects to encode anyway).

The workaround is to delete these properties before passing to a dashboard node, but it would be better if the nodes just handled this scenario.

There are two possible solutions:

1. use `json-stringify-safe` module (as we do with debug) to avoid the circular rabbit holes - which would solve it for all cases
2. check for and remove `msg.req` and `msg.res` if they occur

**Comment by patricktokeeffe** [comment]
I still observe this issue using v2.4.3 with node-red 0.15.3.
```
pi@dashboard:~/.node-red $ npm list node-red-dashboard
/home/pi/.node-red
└── node-red-dashboard@2.4.3 

pi@dashboard:~/.node-red $ apt-cache policy nodered
nodered:
  Installed: 0.15.3
  Candidate: 0.15.3
  Version table:
 *** 0.15.3 0
        500 http://archive.raspberrypi.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
pi@dashboard:~/.node-red $ 
```
An HTTP Input node piped to UI Text output produces
```
Sep 06 08:50:00 dashboard Node-RED[413]: 6 Sep 08:50:00 - [error] [ui_text:80e87f8a.b708e] RangeError: Maximum call stack size exceeded
Sep 06 08:51:00 dashboard Node-RED[413]: 6 Sep 08:51:00 - [error] [ui_text:80e87f8a.b708e] RangeError: Maximum call stack size exceeded
Sep 06 08:52:00 dashboard Node-RED[413]: 6 Sep 08:52:00 - [error] [ui_text:80e87f8a.b708e] RangeError: Maximum call stack size exceeded
```

But the issue is resolved with I add a function node containing:
```
delete msg.req
delete msg.res
return msg;
```

**Comment by patricktokeeffe** [comment]
No, actually I don't see this after all. I think the server must not have been restarted. Sorry nvm

**Comment by durgapadhu** [comment]
How to solve " [error] [http request:dd85e6b6.490818] RangeError: Maximum call stack size exceeded" in node-red?

**Comment by durgapadhu** [comment]
I closed my project's browser window.

**Comment by durgapadhu** [comment]
still, i cant run node red. how to clear all the flows created earlier?

**Comment by knolleary** [comment]
@durgapadhu please use the node-red mailing list or slack channel (link from nodered.org) to ask questions - your problem is not related to this specific node-red-dashboard bug that was fixed a few months ago.
