### ISSUE TITLE
Tabs rolling over when scrolling on mobile device

### ISSUE THREAD

**Issue by psyc0** [node-red/node-red-dashboard#158]
Hi, 
im currently running 2.2.0 of dash , im not sure what introduced this problem because i did not have it on my old install, other than adding more nodes to the flow, but the setup of dash is two tabs and some groups:
- Lights group
-- Sonoff 
-- Leds 
-- Kitchen 
-- Scenes 
- Remotes group 
-- Emotiva 
-- Sony Bravia 
-- JVC X30

the problem im getting on both my Samsung S6 and Sony Z2 tablet is that scrolling on one tab jumps to the next, even before I can scroll to the bottom of the page, making the tabs useless. Is it an intended feature to change tab for e.x when you hit the bottom of one?
Not quite sure how i will go about debugging this, though id change to 2.2.1 but the Node doesnt provide any upgrade functions from UI, is it just npm update ?

**Comment by knolleary** [comment]
The swipping between tabs was disabled in the latest release.

You need to use npm to upgrade.

In ~/.node-red run `npm install node-red-dashboard` and restart node-red.

**Comment by dceejay** [comment]
cd (rather than ln)
cd ~/.node-red && npm i node-red-dashboard

**Comment by psyc0** [comment]
Im running the dockerized version of node so manually intervening with the packages in a image is not always stateful but I´ll give that a try.

**Comment by psyc0** [comment]
Its still doing it on 2.2.1, I ran npm install node-red-dashboard in my docker-container, restarted it , verified version in palette is updated but I still have the same behavior.

**Comment by dceejay** [comment]
Did you refresh your browser cache also ?

**Comment by psyc0** [comment]
in the sense that I killed it completely so that it reloaded now when you mentioned it, I had to open chrome and find the server and manually clear all data, now it works :+1:
