### ISSUE TITLE
remove whitespace above gauge when there is no title

### ISSUE THREAD

**Issue by corbosman** [node-red/node-red-dashboard#159]
When you omit a title, it would be nice if the whitespace above the gauge was removed so one could add a row of icons and/or your own title without having a huge amount of whitespace. 

<img width="1146" alt="screen shot 2017-01-29 at 08 38 54" src="https://cloud.githubusercontent.com/assets/1389007/22404553/6e379b28-e609-11e6-80f8-2afa3b6728c3.png">

**Comment by dceejay** [comment]
sort of like this ?
![image](https://cloud.githubusercontent.com/assets/5375409/22406482/b96923a4-e64b-11e6-862e-965c1fe2e9bf.png)

**Comment by corbosman** [comment]
That looks great.

**Comment by Paul-Reed** [comment]
@corbosman - Hhmm, I thought that you meant collapse the title area if the title was left blank, so to remove the 'unused' space. That would then allow you to use a text or template node below the chart to display whatever you wanted...

![power](https://cloud.githubusercontent.com/assets/973580/22407514/b91e3a88-e65f-11e6-8fc9-de49e4c48cd1.PNG)

**Comment by corbosman** [comment]
I did mean that @Paul-Reed. I assumed, perhaps mistakenly, that that is what dceejay had done, and had added a separate row of 1x1 gauges above it. To be clear, I mean exactly what you are showing in your example @Paul-Reed

**Comment by dceejay** [comment]
Yes removing the title collapses it. I added a row of 1x1 just to check alignment. You can add a text widget below as Paul suggests.

**Comment by dceejay** [comment]
Now on master (not yet on npm)
