### ISSUE TITLE
ng-click doesn't work on object tag

### ISSUE THREAD

**Issue by bsculley** [node-red/node-red-dashboard#160]
I am using an object tag to display SVG in a template node.  That works great, but I can't get the ng-click event to fire when clicking it.  Here is my html:

```
<div ng-click="send({payload: 'Clicked'})" style="cursor: pointer;">
X
    <object 
            id="btn_1" width="80" height="80" 
            type="image/svg+xml" 
            data="/myicons/Arrow_icon.svg" >
    </object>
</div>
```
The button displays perfectly and if I click on the "X" I get an event, but clicking on the SVG graphic has no effect.  Also the cursor: pointer doesn't work when the cursor is over the object.

I've tried putting the ng-click and cursor: pointer style directly on the object as well but that didn't work either.

Is this something I'm doing wrong?  Any suggestions for a way to make this work?  

SVG buttons are a good fit here and I'd like to be able to use them.

You can download the SVG from here if you want to try it:

[https://commons.wikimedia.org/wiki/File:Arrow_icon.svg](https://commons.wikimedia.org/wiki/File:Arrow_icon.svg)

**Comment by knolleary** [comment]
Hi,

for general how-to questions, or if you're not certain if something is behaving correctly, please use the mailing list in the first instance as that often leads to a quick response.

It would appear that `<objects>` don't receive events. In general, there's no need to use an object tag these days (Unless you really need IE8 support...). So replace your `<object>` with an `<img>` and it works fine.

```
<div ng-click="send({payload: 'Clicked'})" style="cursor: pointer;">
X
    <img 
            id="btn_1"
            src="/myicons/Arrow_icon.svg" />
 
</div>
```
