### ISSUE TITLE
Gauge wasted space & title format

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-dashboard#162]
There seems to be a disproportionate amount of padding (wasted space) for the Gauge node, compared with other nodes, such as the text node above (temperature) in the screenshot. The gauge itself could probably be about 30% larger to be consistent with the layout of other nodes.
In my example, the gauge element is 83.57 x 83.57px, whilst the container is 156 x 144px.

Also, should the Gauge 'title' be the same size as the other nodes (and called 'label')??
@knolleary commented in Slack "If its the gauge library doing it, can we stop asking the library to display a title at all, and put one in ourselves that is consistent with the other widgets?"

Paul

![gauge](https://cloud.githubusercontent.com/assets/973580/22824008/1003e362-ef7e-11e6-92de-f067ffeb0ba3.PNG)

**Comment by dceejay** [comment]
so something like this ?
![image](https://cloud.githubusercontent.com/assets/5375409/22830298/dff7b9e4-ef9d-11e6-8aef-42f7ef819ae8.png)

**Comment by Paul-Reed** [comment]
Yes, that's much better. The label size now matches the other widgets.

If the gauge was presented lower in the frame, rather than centered, would
it allow an increase in gauge size, so the space at the bottom and sides
wouldn't be as prominent.

Thanks

Paul

**Comment by dceejay** [comment]
it is lower in the frame ??? It can't be bigger or it would crash the label.
That is 3x2... this is 3x3
![image](https://cloud.githubusercontent.com/assets/5375409/22831376/135f426c-efa2-11e6-87b1-e9d96097ca15.png)
You have to remember the actual size of the gauge is a circle beyond the end of the tip of the pointer at top bottom and sides.

**Comment by Paul-Reed** [comment]
Aahh right. I was looking at the below screenprint which defines the gauge (but not including the pointer).

![space](https://cloud.githubusercontent.com/assets/973580/22836865/0b20d3fe-efb6-11e6-91f1-c5622633c154.png)

**Comment by Paul-Reed** [comment]
I think that part of the issue is that unlike the chart node, the gauges only scale themselves up to a maximum 1 x 1 widget size of 52 x 52.
If the widget size is any more than 52 x 52, then the gauge remains the same size, regardless of the widget size, and there is therefore increased unused space around it.
My last screenshot above was with a widget size of 58 x 58.

**Comment by dceejay** [comment]
ah right !

**Comment by dceejay** [comment]
Fixed by ed431435fd92d9463ad3ec6dda3bd220be259372
