### ISSUE TITLE
Numeric widget doesn't set min and start values correctly

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red-dashboard#163]

**Comment by pdegior** [comment]
I have 2 numeric inputs on a dashboard.  The first has a limit of 0-10 and works as expected.  The second has a limit of 90-100.  After stopping and starting node-red, the 90-100 doesn't work at all.  The up button does nothing.  As a test a set the limit from 10-100 and restarted node-red.   Clicking the up button caused the number to immediately jump to 100.  I am able to reproduce the problem on other numeric inputs

**Comment by dceejay** [comment]
Now fixed on master (not on npm yet)
