### ISSUE TITLE
Swipe/scroll not working correctly on Chrome on Android

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red-dashboard#164]
seems to be related to this

https://github.com/angular/material/issues/10187

(well the symptoms are the same)

Issue raised just to track the upstream issue so we can re-visit when fixed.
In the meantime... Firefox on Android works fine :-)

**Comment by dceejay** [comment]
Partial fix (for sliders at least) - 9d9ba42b6202ac287cf1e8a9225654b3c18d00b3

**Comment by Paul-Reed** [comment]
Could this be a way forward?

![capture](https://cloud.githubusercontent.com/assets/973580/23334764/a69f4426-fb9d-11e6-8105-1208c83d61a9.PNG)

**Comment by dceejay** [comment]
maybe - but the console then says
```You are using the ngTouch module. 
Angular Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with Angular Material!```
so - not looking likely (as we need Angular Material)

**Comment by jjssoftware** [comment]
Swipe appears to be working for me in chrome on android with 2.3.3..with a caveat: I have to swipe left/right on a dashboard element for it to work as expected (swipe doesn't work when attempting it at the bottom of the page where there's no rendered content).

So I'm sort of halfway happy here. To coin a phrase perhaps I'm 'swiping it wrong' 😉
