### ISSUE TITLE
dark theme, gauge and dashboard menu problems

### ISSUE THREAD

**Issue by jjssoftware** [node-red/node-red-dashboard#166]
Since updating to 2.3.0 on npm a few things appear to have gone wrong:

1. The dashboard menu seems to be completely empty in node-red admin
2. Use of the gauge node is causing some errors in the log and the gauge doesn't appear to be working in dashboard pages: 
`18 Feb 10:19:42 - [error] [ui_gauge:e970ded.4544f2] TypeError: Cannot read property 'sizes' of undefined`
3. There's some css issues in the dark theme where some elements have an incorrect background colour / not all elements are dark (which might be fixed if I could get to the dashboard menu)

I've attempted a complete uninstall / clean down / reinstall but that hasn't helped.

![screenshot 2017-02-18 10 30 00](https://cloud.githubusercontent.com/assets/536164/23092531/4931e510-f5c5-11e6-8016-bfd7a32834a7.png)
![screenshot 2017-02-18 10 29 05](https://cloud.githubusercontent.com/assets/536164/23092532/4932ac70-f5c5-11e6-9d7a-cd3136deaedd.png)

**Comment by jjssoftware** [comment]
I reverted back to 2.2.1 from npm and all working again here now

**Comment by michal-konopinski** [comment]
Same here :(

**Comment by rozling** [comment]
Same issue.  Tried deleting all dashboard components & starting from scratch. I was then able to see the dashboard sidebar, but was still having the CSS issues.

For me some widget text becomes invisible, even when playing with custom CSS theme values.

For anyone looking, the command to revert back to 2.2.1 is: `npm install node-red-dashboard@2.2.1`

**Comment by dceejay** [comment]
Did you reload/refresh the page at least twice to flush the cache. Any chance I could get a copy of the original flow file to test against ? Direct email to me is fine.

**Comment by jjssoftware** [comment]
Hi Dave, I performed a few 'empty cache and hard reload' refreshes in chromium in node-red admin and the dashboard page but no luck. I'll happily fire my complete flow over to you - what's your email address?

**Comment by Paul-Reed** [comment]
I've just removed my 'git' version of dashboard, and stock npm installed it again, and everything looks fine here in chromium.
To rule out caching issues can you try loading it from your local IP address, ie 192.168.1.10:1880/ui from a different browser, or incognito window.
I did experience some caching issues when I first loaded the styling branch a few weeks ago, which took a while to clear.

**Comment by jjssoftware** [comment]
Hi @Paul-Reed your comment convinced me to give it another try:

- I uninstalled 2.2.1
- I completely manually cleared down my /.node-red/node_modules folder
- I installed 2.3.0 fresh from npm
- I restarted node-RED
- I performed a bunch of hard refreshes in chromium in both node-red admin and dashboard pages
- I continue to experience all of the problems that I reported in the first comment in this issue

It really doesn't stack up this is solely a browser caching issue because that wouldn't cause the gauge related errors in (2) in the node-RED log. 

I'm also seeing a failed request for /ui_base/js/tinycolor-min.js in node-red admin which I guess could be the cause of the dashboard tab being empty..uninstalled 2.3.0 and reverted to 2.2.1 again

![screenshot 2017-02-18 14 59 08](https://cloud.githubusercontent.com/assets/536164/23094182/219f1582-f5ec-11e6-82f4-d9977b28d5e7.png)

**Comment by Paul-Reed** [comment]
Yes if tinycolor isn't loading, the dashboard tab will be blank. I had this issue a week or so ago which I thought had been fixed by https://github.com/node-red/node-red-dashboard/commit/a9c7e14491def0ea3110c600683d63eb25fed101

**Comment by jjssoftware** [comment]
I've tracked down @dceejay via email and sent my flow over

**Comment by Paul-Reed** [comment]
It would be interesting to know what you get if you tried the url https://192.168.0.2:1880/ui_base/js/tinycolor-min.js
...but I'm sure dceejay will sort 😉

**Comment by dceejay** [comment]
Version 2.3.1 pushed to fix @jjssoftware flow.
The gauge was not being initialised correctly on first invocation of the upgrade, and that then stalled the rendering of the whole sidebar...

**Comment by Paul-Reed** [comment]
The tinycolor browser error mentioned above still persists from the editor page.

But note that the dashboard **successfully** loads tinycolor via;
Request URL:https://192.168.1.10:8443/dash/js/tinycolor-min.js

Whilst the editor **fails** to load tinycolor via;
Request URL:https://192.168.1.10:8443/admin/ui_base/js/tinycolor-min.js

**Comment by dceejay** [comment]
odd - in an incognito browser - mine loads ok - http://localhost:1880/admin//ui_base/js/tinycolor-min.js 

any more details on how admin (and other settings) are configured ?

**Comment by Paul-Reed** [comment]
Don't know about Joe, but my settings are;
uiPort: process.env.PORT || 8443,
httpAdminRoot: '/admin',
ui: {path: 'dash'},

Just tried (again) in incognito browser - still the same.

Is the second // in your url a typo?

**Comment by dceejay** [comment]
sorry yes.. - now set same a you 
http://localhost:8443/admin/ui_base/js/tinycolor-min.js
still good here...

**Comment by Paul-Reed** [comment]
Lets see if it persists with @jjssoftware 
Only commonality between Joe and I is that we both use https, whilst you are using http. Probably of no consequence though...

**Comment by dceejay** [comment]
ah ... yes totally relevant.

**Comment by Paul-Reed** [comment]
see Slack pm...

**Comment by Paul-Reed** [comment]
tinycolor error now fixed by https://github.com/node-red/node-red-dashboard/commit/2837f4174f37a28a64b168360edb68535219da21
- not on npm yet

**Comment by jjssoftware** [comment]
I updated to git master v2.3.2 here and that fixed all the problems I reported including the failing request for /ui_base/js/tinycolor-min.js. 

Thanks massively @dceejay, very much appreciated.

Feel free to close this one when you're ready.

**Comment by dceejay** [comment]
thanks - will do...
others have reported some other wrinkles - so when I sort those (hopefully later today) I'll update and finally push 2.3.2
