### ISSUE TITLE
Dashboard UI audio node - focus issue

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red-dashboard#167]
Hey Dave,

Some weeks ago I started a [discussion](https://groups.google.com/forum/#!searchin/node-red/butenaers%7Csort:relevance/node-red/40HqZ665rgM/7dOZLeAqBgAJ) on the forum about the **audio element only playing sound when in focus**.    Since nobody joined the discussion anymore for a more general solution (to add a header tab in the dashboard tree), it would be great if you could just add a checkbox to allow us to play sound even if the audio element has no focus.  

I.e. a checkbox that can overrule the IF condition in the [main.js](https://github.com/node-red/node-red-dashboard/blob/master/src/main.js#L250) file:
```javascript
         events.on('ui-audio', function(msg) {
            if (!msg.always) {
                var totab;
                for (var i in main.tabs) {
                    if (msg.tabname === main.tabs[i].header) { totab = i; }
                }
                // only play sound/tts to tab if in focus
                if (totab != parseInt($location.path().substr(1))) { return; }
            }
```

Thanks in advance!
Bart Butenaers

**Comment by dceejay** [comment]
Ah - sorry - this was fixed back on 27th just after you raised it - 
forgot it got swept into - 7a8576dc8ea20d33eb0ff4a5d038f1c503c5ecef
Added a checkbox that should do what you wanted...
