### ISSUE TITLE
More and more reset buttons appear when switching between tabs in node red

### ISSUE THREAD

**Issue by ControlTheBit** [node-red/node-red-dashboard#169]
This is a very small issue, but still... :-)

If you switch between the dashboard and the info tab forth and back, the dashboard page gets more and more reset buttons added.

![screen shot 2017-02-18 at 7 31 33 pm](https://cloud.githubusercontent.com/assets/9163917/23095834/0b14c0e4-f611-11e6-9c46-9e03103ffedc.png)

Chrome on Mac OSX: 56.0.2924.87 (64 bit)

**Comment by dceejay** [comment]
Thanks - good spot.

**Comment by dceejay** [comment]
closed by release of 2.3.2 - 2837f4174f37a28a64b168360edb68535219da21
