### ISSUE TITLE
Embedded Node-red ?

### ISSUE THREAD

**Issue by markrey** [node-red/node-red-dashboard#17]
Hi,

I am trying to install the same in Embedded version of Node-red.
I get below error. Any suggestions ?

/node_modules/node-red-dashboard/ui.js:235
        to.emit('ui-controls', {
          ^

TypeError: Cannot read property 'emit' of undefined
    at /node_modules/node-red-dashboard/ui.js:235:11
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

I created the same issue at node-red-contrib-ui

**Comment by dceejay** [comment]
How are you embedding Node-RED ? How are you installing node-red-dashboad ? Which platform ? Which OS ? a bit more context please.

I have a package.json that includes something like
 "dependencies": {
        "node-red": "^0.13.4",
        "node-red-dashboard": "node-red/node-red-dashboard", ... etc

**Comment by markrey** [comment]
Sorry my mistake. HTTPNODE was not rightly routed in the application.

**Comment by dceejay** [comment]
Thanks for letting us know.
