### ISSUE TITLE
mobile scroll

### ISSUE THREAD

**Issue by harveymoon** [node-red/node-red-dashboard#172]
On android and on dev tools, mobile devices do not scroll. No interaction can move down to lower items. On dev tools, the mouse wheel does work but phones don't have wheels yet. I suggest making the background a draggable region.

**Comment by Paul-Reed** [comment]
Already reported - https://github.com/node-red/node-red-dashboard/issues/164

**Comment by dceejay** [comment]
closing as already being tracked in #164
