### ISSUE TITLE
ui not working in embedded node red

### ISSUE THREAD

**Issue by mknj** [node-red/node-red-dashboard#173]
Following 
https://nodered.org/docs/embedding
and installing node-red-dashboard inside /home/nol/.nodered/
the ui is not accessible
/red works for editor (dashboard nodes are visible, so install inside userdir succeeded)
/api and /ui are not working for dashboard

How can i add the dashboard to my express application?

**Comment by dceejay** [comment]
Hi,
not sure that the dashboard has been built to be embedded.
If you look at https://github.com/node-red/node-red-dashboard/blob/master/ui.js#L226
you can see what it is trying to attach to where... I suspect this won't work well when embedded, but happy to discuss changes if it can be made to work sensibly.

**Comment by mknj** [comment]
hello, 

i'll send a pull request when nested routing is working. i think the current approach of forwarding the app object into the dashboard and modifying it there is not optimal.

**Comment by mknj** [comment]
It is working. The dashboard is served under /api/ui/.
