### ISSUE TITLE
dashboard elements no longer visible

### ISSUE THREAD

**Issue by devleaks** [node-red/node-red-dashboard#174]
Got this js error in console:

onchange — red.min.js:21:7529: TypeError: undefined is not an object (evaluating 'globalDashboardNode.site.name')

No more dashboard elements in tab after node-red restart.

Node-red v0.16.2, Dashboard version 2.3.0-beta started at /ui.
Node.js  version: v7.4.0, Darwin 14.5.0 x64 LE.

**Comment by devleaks** [comment]
Reverted to node-red-dashboard@2.3.2 and elements appear. So 2.3.0-beta breaks it.

**Comment by dceejay** [comment]
err - where did you get 2.3.0-beta ?   that is/was pre- 2.3.2
latest should be 2.3.3 on master (but not npm)
`npm i node-red/node-red-dashboard`

**Comment by devleaks** [comment]
If I remember, I git cloned it to be able to create my own theme. (I have 3 different environments and they may not have the same version of contrib.)

**Comment by dceejay** [comment]
OK to close ?

**Comment by devleaks** [comment]
Yup. But still, how do I get this error? Doesn't need fixing?

**Comment by dceejay** [comment]
You got it by running an older beta release version that  we made available to help find these sort of issues... but the more recent released version should have fixed it - so no - it doesn't need fixing.
