### ISSUE TITLE
hiding widget / group

### ISSUE THREAD

**Issue by MaxRei-dev** [node-red/node-red-dashboard#177]
Hi,
an option ala "msg.enabled" (maybe msg.hide) for hiding / showing (not only disable) Widgets or Groups would be very useful.
eg. for showing a widget only at night, or if its time to water your plants.

**Comment by dceejay** [comment]
related to #73, should be considered together ?

**Comment by MaxRei-dev** [comment]
i don't think so. because using a msg.* you can use a timer eg. for schow/hide.

**Comment by dceejay** [comment]
well they are both to do with the state of a thing... visible/hidden open/closed
so certainly 73 should be considered as part of this even if not vice-versa

**Comment by MaxRei-dev** [comment]
perfect. sounds good.

**Comment by hobbyquaker** [comment]
I implemented widget hiding here: https://github.com/hobbyquaker/node-red-dashboard/commit/8393beef29d56a84038bdf36b31785e89dacea7d

If you like that I will create a PR, but I'm not really satisfied yet. I'd like to call the `refreshLayout()` function of `ui-card-panel-ctrl-js`when the hidden attribute changes - but I don't know how, I'm not really into Angular... Did find out where to hook in the update-value handler, but have no clue how to find the group a widget resides in and how to call the refreshLayout then...

**Comment by hobbyquaker** [comment]
Group hiding would be great too, but there I don't see where one could pass the message in, because the groups aren't nodes?

**Comment by dceejay** [comment]
the suggestion was to use the ui-control node to pass in the messages for groups... but still need to then work out how to target them to the individual groups. 

As per above I'm not sure I'm a fan of hiding widgets on their own - too much "things moving around". Also I think you should be able to do the same as you have (albeit at the cost of losing disable...) by using a template node to override the existing disable style with your hidden style.
At the top of each node there ui is "required"...   you can then use ui.updateUi(); to get it to refresh the page....  use sparingly or the whole screen flickers like mad....

**Comment by MaxRei-dev** [comment]
hmm. just thinking about what dceejay commented. What about just the option of "passing" a css class to an widget. the css could be in an template node an you can use/do whatever you like.....

**Comment by hobbyquaker** [comment]
I like the "pass a class to a widget" idea. Will try to implement this. But I also want the "hide with resize" thing - I hope you can accept this dceejay, I think as long as it's the users choice if he want's to live with "things moving araoung" it should not harm anyone ;-)

**Comment by dceejay** [comment]
current thinking / discussion on slack dashboard-ui channel is to add a class field to the group config. 
Then you could use existing ng classes (like hide etc) - and also add your own (via template).
though the resize still needs thinking about.

**Comment by dceejay** [comment]
though - this is doing things at the widget level... I would prefer we target the group level.

**Comment by hobbyquaker** [comment]
So that means you won't accept the Widget-Hiding-with-resize PR? I must admit I don't understand why, this isn't breaking anything and those who don't need it just don't use it. But I really want that feature, I have different usecases where I need to hide single widgets - not groups.

**Comment by M0ebiu5** [comment]
+1 for the possibility to hide widgets.
Also, the ability to dynamically (re)configure the ui nodes would be nice (eg: send msg.Label to change the Label, msg.Colour...and so on).

**Comment by michal-konopinski** [comment]
+1 for msg.label :)

**Comment by dceejay** [comment]
please don't add things that aren't part of this issue, (or +1 them). Use the mailing group for discussion of possible features.

The text widget will already accept {{msg.topic}} or {{msg.whatever-you-want}} as the label
