### ISSUE TITLE
Chart node: Tooltip / Hovering not disapperaring after some time

### ISSUE THREAD

**Issue by mapero** [node-red/node-red-dashboard#18]
Hi,

when using chart node and hovering over points a tool tip is showing the actual value and time. In some cases, when using multiple charts it happens quite frequent, the tool tip is not disappearing. You have to reload the page. Changing the Tab does not solve the problem.

Node-RED version: v0.13.4
Node.js  version: v5.10.1
node-red-dashboard (current from github)
Chromium Browser

See the problem on the screenshot.

Thanks

![bildschirmfoto von 2016-05-23 16-44-14](https://cloud.githubusercontent.com/assets/1754967/15474748/8f13fd14-2106-11e6-9abc-450d23df020d.png)

**Comment by dceejay** [comment]
I'm guessing it's similar  related to this - https://github.com/krispo/angular-nvd3/issues/172 - though this has been fixed...

**Comment by dceejay** [comment]
Charts now re-implemented using charts.js so closing this..
0fe76c294fe1c6894e3b8bc6ce4f8ccd6ed8d8ae.
