### ISSUE TITLE
Gauge memory leak

### ISSUE THREAD

**Issue by machadotiago** [node-red/node-red-dashboard#183]
I have observed some issues when using the gauge node from Node-RED Dashboard, it is using a huge amount of memory after running for a couple of hours. 
I created this flow below for "debugging" and I could see in the Chrome Task Manager that the tab was using 820 MB of memory after running for 10 minutes.

`[{"id":"c8797805.76d148","type":"tab","label":"Flow 1"},{"id":"3712655c.064d7a","type":"ui_gauge","z":"c8797805.76d148","name":"","group":"41f34a7.80f8db4","order":0,"width":"12","height":"6","gtype":"gage","title":"Gauge","label":"units","format":"{{value | number:1}}","min":0,"max":"1","colors":["#00b500","#e6e600","#ca3838"],"x":470,"y":60,"wires":[]},{"id":"5859fad3.c1dae4","type":"ui_gauge","z":"c8797805.76d148","name":"","group":"41f34a7.80f8db4","order":0,"width":"12","height":"6","gtype":"gage","title":"Gauge","label":"units","format":"{{value | number:1}}","min":0,"max":"1","colors":["#00b500","#e6e600","#ca3838"],"x":470,"y":140,"wires":[]},{"id":"4d488edc.3ae6d","type":"ui_gauge","z":"c8797805.76d148","name":"","group":"41f34a7.80f8db4","order":0,"width":"12","height":"6","gtype":"gage","title":"Gauge","label":"units","format":"{{value | number:1}}","min":0,"max":"1","colors":["#00b500","#e6e600","#ca3838"],"x":470,"y":100,"wires":[]},{"id":"f1a70dfa.8b886","type":"ui_gauge","z":"c8797805.76d148","name":"","group":"41f34a7.80f8db4","order":0,"width":"12","height":"6","gtype":"gage","title":"Gauge","label":"units","format":"{{value | number:1}}","min":0,"max":"1","colors":["#00b500","#e6e600","#ca3838"],"x":470,"y":180,"wires":[]},{"id":"8765ae7f.4548d","type":"inject","z":"c8797805.76d148","name":"trigger","topic":"","payload":"false","payloadType":"bool","repeat":"0.1","crontab":"","once":true,"x":100,"y":120,"wires":[["876f59f3.a15568","db138f23.60c1f","382b86c3.b5f8ca","83126ccc.787d9"]]},{"id":"876f59f3.a15568","type":"function","z":"c8797805.76d148","name":"random","func":"msg.payload = Math.random()\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":60,"wires":[["3712655c.064d7a"]]},{"id":"db138f23.60c1f","type":"function","z":"c8797805.76d148","name":"random","func":"msg.payload = Math.random()\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":100,"wires":[["4d488edc.3ae6d"]]},{"id":"382b86c3.b5f8ca","type":"function","z":"c8797805.76d148","name":"random","func":"msg.payload = Math.random()\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":140,"wires":[["5859fad3.c1dae4"]]},{"id":"83126ccc.787d9","type":"function","z":"c8797805.76d148","name":"random","func":"msg.payload = Math.random()\nreturn msg;","outputs":1,"noerr":0,"x":300,"y":180,"wires":[["f1a70dfa.8b886"]]},{"id":"41f34a7.80f8db4","type":"ui_group","z":"","name":"Default","tab":"f720a789.18b548","disp":true,"width":"24"},{"id":"f720a789.18b548","type":"ui_tab","z":"","name":"Alerts","icon":"dashboard","order":3}]`

Is this a known issue for this node ?

btw, I'm using the following versions:
NR: v0.16.2
Node.js: v4.4.4
Dashboard: v2.3.3

**Comment by dceejay** [comment]
no - but you are trashing it somewhat.
My Mac seems to sit steady at around 500k
![image](https://cloud.githubusercontent.com/assets/5375409/23530926/e969380a-ff9b-11e6-8ab3-e03140c845dc.png)
If I drop the update to 1 per sec then I sit around 50k
![image](https://cloud.githubusercontent.com/assets/5375409/23531039/43ed2534-ff9c-11e6-864f-8d6b74ab579f.png)

**Comment by machadotiago** [comment]
Hum...interesting. I also changed the trigger to 1 sec and as soon as I opened the tab my Chrome Task Manager was showing 174MB 
![image](https://cloud.githubusercontent.com/assets/3775353/23532491/735d5c24-ff8a-11e6-83f6-26cb4fd1d658.png)
and a few minutes later it jumped to 300MB
![image](https://cloud.githubusercontent.com/assets/3775353/23532719/b1421ace-ff8b-11e6-806d-4ff19296a309.png)

**Comment by sunrutcon** [comment]
I'm having similar problem when running nr with dashboard on my rpi and when dashboard is open on chrome on rpi, after one hour rpi is not responding or is really slow. I have monitored memory and chrome took all the memory for dashboard rendering. I had few gauges and few charts. Since I had to go in production with this, I'm monitoring dashboard on another pc (laptot) that is much stronger than rpi, and rpi just for nod-red, mqtt. It might be the problem with chrome, and now I'm looking for alternative to render gauges and charts, or just waiting enough for problem to solve with this workaround.

**Comment by dceejay** [comment]
yes - I'd always recommend running Pi headless, rather than running the browser on it. Over the last year Pi has moved from Epiphany to Firefox to Chromium- each has got bigger (but more capable) - and Chrome is a well know user of memory...   Often the use of memory is due to not cleaning up fast enough - so one question that could be tuned is how fast are the updates coming through to the dashboard ?

If you have to run the browser on the Pi then there may be better options.

**Comment by machadotiago** [comment]
Our problem here is exactly the same. We left a Pi 3 running Raspbian Lite + Node-RED + Dashboard up on Electron and at least once in a week we had a crash because the Pi was running out of memory. After removing the gauges we had no more failure reports. Unfortunately we are too busy to have a deep looking on it :(

**Comment by sunrutcon** [comment]
Ok, I'll try to install some other browser on pi. Do you have some suggestions?
I'm also thinking about desktop application for dashboard (but would like to avoid doing this) since I would really like to monitor my processes and data on the same machine and to make use of that hdmi.

**Comment by dceejay** [comment]
I'd try midori - but as I said key will be to check and try to reduce the update rates as much a possible.

**Comment by dceejay** [comment]
hoping this now closed by better handling in 5d20ac6f4fe37ea25201a41172f8cd01490e16a2

(but only if you use the newer format - IE untick the "use old format" tickbox  and update and storage / replay you may have built
