### ISSUE TITLE
Multiple 'Connection Lost' toasts on dashboard, no warning on editor

### ISSUE THREAD

**Issue by rozling** [node-red/node-red-dashboard#184]
Getting this behaviour with my local MacBook server (latest node-red & node-red-dashboard).

My understanding from [this issue](https://github.com/node-red/node-red-dashboard/issues/67) is that these toasts should pop up when connection is completely lost to the server.  

However I'm getting repeated popups on the dashboard and none on the editor.

Any tips for how to diagnose this further?

**Comment by dceejay** [comment]
Well it does what it says on the tin, so it's losing connection to the server. It does try to automatically reconnect so may then fail again...  When you say repeated - what do you mean ? multiple times a minute ? now and again ? Is this all on the one machine ? or across a network.

**Comment by dceejay** [comment]
any more info ? or ok to close ?

**Comment by rozling** [comment]
Sorry I haven't been able to test since - should be able to check tomorrow.

But can you confirm whether I should be seeing connection lost errors in
the main node-red view at the same time as dashboard toasts?

**Comment by dceejay** [comment]
Well they ought to occur at the same time if the connection breaks - BUT... the editor uses pure websockets and the dashboard uses the sockets.io library which can use other type of connection if it detects them to be more appropriate. If that isn't websockets then one may disconnect and not the other... - (but would be unexpected - on a local lan).

**Comment by rozling** [comment]
Ah ok, yes I am getting these reported disconnections (which I think are false positives) when the node-red server, web editor & dashboard ui are open on the same machine.

My flows are a bit complex & probably inefficient so I wondered if I am coming up against some limitation on the number of nodes/tabs/ui widgets

**Comment by dceejay** [comment]
unaware of any - but....

**Comment by rozling** [comment]
It seems to happen at almost random times.  I've tried raising the logging level to `debug` and then `trace` - all that shows up in browser console is `ui/js/angular-chart.min.js.mapFailed to load resource: the server responded with a status of 404 (Not Found)` which I think was related to a different issue.

Is there anywhere else that these dropped connections might be getting logged (maybe from sockets.io?) - I'm a bit out of my element with this websocket stuff.

**Comment by dceejay** [comment]
mainly in the browser log...  the ...map error isn't really an error - it's an artefact of the minimisation and removing those files that are only there for source debug...  so not needed for runtime.

**Comment by Hugobox** [comment]
Hi! Also getting these Dashboard disconnects on lan. Sometimes multiples times per minute. When it happens chrome console shows: Websocket is already in CLOSING or CLOSED state.

**Comment by JayNaire** [comment]
I have exactly the same issues with dashboard disconnects/toasts every 60 seconds:
Node red v0.17.5 runs on a lightly loaded RPi Jessie server via wireless lan.
Dashboard is 2.4.3.
Editor runs in Chromium on Mint 18 and is always faultless.
Dashboard served to either Android Chrome or Linux Chromium or Firefox.
It runs fine until either:
  an (unquantifiable) number of flow updates are deployed from the editor (maybe 1, maybe 10+)
or:
  overnight - even though there are no dashboard or editor users

I cannot find any relevant error messages anywhere in NR, or client/server system logs.

The only remedy is to restart NR.

**Comment by dceejay** [comment]
can you re-try with latest dashboard - 2.6.2 ?

**Comment by dceejay** [comment]
no reply - closing

**Comment by JayNaire** [comment]
Oh, my apologies dceejay; I got ill and missed your reply.
The problem was not NR; simply RPi running into swap and timing out.
Thanks for your support!
