### ISSUE TITLE
Update numeric node with decimal value

### ISSUE THREAD

**Issue by sunrutcon** [node-red/node-red-dashboard#185]
When trying to update numeric node over mqtt with decimal value, numeric node truncates decimal value. Without update increasing with decimal step like 0.1 works.

**Comment by sunrutcon** [comment]
tnx.

**Comment by dceejay** [comment]
Thanks for spotting it !

turns out it was only doing that to strings (which is what MQTT nodes returns by default)... and numbers would have worked... - but also had a problem in that you good have too many decimal places !
