### ISSUE TITLE
Form node data entry fields have a color of white (#ffffff) on a white background

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-dashboard#186]
The form node has it's input fields set to white (#ffffff) on a white background

Line 299 of the inline style sheet:
```
.nr-dashboard-theme .nr-dashboard-form form md-input-container input {
    border-color: #111111;
    color: #FFF;
```
which makes it difficult to see (grin)

**Comment by dceejay** [comment]
ack that. In fact there are a few colours not being set properly to match the theme...  will be sorted.
