### ISSUE TITLE
Gauge node: gauge has fixed size

### ISSUE THREAD

**Issue by mapero** [node-red/node-red-dashboard#19]
Hi,

the gauge is not resizing with the size of the card. It seems it has a fixed size.

![gauge](https://cloud.githubusercontent.com/assets/1754967/15475272/8433799e-2109-11e6-8470-fa38ce2bf8ce.png)

Please make the gauge fill the available space.

Thanks.

Jochen

**Comment by dceejay** [comment]
Hi,

I think this is already fixed in e7488e933b2b2ca457850cd7e2894e3f8c60bee5
