### ISSUE TITLE
missing node-types

### ISSUE THREAD

**Issue by umer990** [node-red/node-red-dashboard#190]
I am running latest node-red version, and even having node-red-dashboard installed in node-modules I am getting missing node-types
- ui_base
- ui_form
- ui_text

getting ui_base] Error: Cannot find module 'encodeurl' on loading nodes.

Node.js  version: v6.10.0
Node-RED version: v0.16.2

/Umer

**Comment by dceejay** [comment]
Hi,
Which version of dashboard is installed ? 2.3.6 is the latest. It's reported in the console.log during startup.

Have you upgraded node.js and core node-red recently ? If so how did you upgrade ? Did you npm rebuild any nodes / modules that have native code that needs recompiling/reinstalling ?

**Comment by umer990** [comment]
It was 2.2.1 dashboard version! But I could manage to solve the issue by installing the node version 6.9.1.

**Comment by dceejay** [comment]
So Ok to close this issue ?

**Comment by umer990** [comment]
Yes! Sure
