### ISSUE TITLE
Guage issues

### ISSUE THREAD

**Issue by biowayllis** [node-red/node-red-dashboard#192]
Pls I used the gauge to record my sensor data values. but I noticed that whenever I switch off my sensor data the gauge readings does not return to zero level. instead, it just stayed at the last value before switching off my data source. please what should I do to return the gauge readings beck to zero when data souce is not switched on

**Comment by dceejay** [comment]
Hi,  as per the contribution guidelines, please ask general questions on the google groups mailing list or slack channel.

In this instance - use a trigger node wired in parallel to the existing input - set to send nothing - then after a time period send 0 - and extend the time every time something arrives. As long as something arrives it'll not send the 0. If nothing arrives for xx seconds/minutes etc - it will then send the 0.
