### ISSUE TITLE
node-RED crash with histogram chart

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-dashboard#193]
I'm feeding histogram with multiple instances of the same topic, which I believe will allocate a bar to a topic and then wiggle the bars up and down as the values change.
I get a load of these messages 
TypeError: data[0].values.data[i].map is not a function
in the debug tab, and then one crashed Node-RED... 

27 Mar 18:52:59 - [red] Uncaught Exception:
27 Mar 18:52:59 - TypeError: data[0].values.data[i].map is not a function
    at Object.ChartNode.options.convertBack (/Users/andysc/.node-red/node_modules/node-red-dashboard/nodes/ui_chart.js:44:60)
    at ChartNode.<anonymous> (/Users/andysc/.node-red/node_modules/node-red-dashboard/ui.js:168:35)
    at emitOne (events.js:77:13)
    at ChartNode.emit (events.js:169:7)
    at null._onTimeout (/Users/andysc/.node-red/node_modules/node-red-dashboard/nodes/ui_chart.js:198:18)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by andysc** [comment]
turns out to be the debug node I attached to the top output pin...  disconnected that, and it's fine now.
Would be good to know what that crashes NR, though!
Here's a sample flow...

`[{"id":"ca892f70.2f43b8","type":"inject","z":"9906d8a5.6d0ff8","name":"","topic":"wibble","payload":"5","payloadType":"num","repeat":"","crontab":"","once":false,"x":100,"y":400,"wires":[["6065438a.184a14"]]},{"id":"6065438a.184a14","type":"ui_chart","z":"9906d8a5.6d0ff8","name":"","group":"9d8219ad.44c838","order":0,"width":"0","height":"0","label":"chart","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"x":310,"y":440,"wires":[["cadf29e7.94d518"],[]]},{"id":"8f1318f4.f8934","type":"inject","z":"9906d8a5.6d0ff8","name":"","topic":"bibble","payload":"10","payloadType":"num","repeat":"","crontab":"","once":false,"x":100,"y":440,"wires":[["6065438a.184a14"]]},{"id":"c7137797.e1b8a8","type":"inject","z":"9906d8a5.6d0ff8","name":"","topic":"zibble","payload":"15","payloadType":"num","repeat":"","crontab":"","once":false,"x":100,"y":480,"wires":[["6065438a.184a14"]]},{"id":"cadf29e7.94d518","type":"debug","z":"9906d8a5.6d0ff8","name":"","active":true,"console":"false","complete":"false","x":470,"y":420,"wires":[]},{"id":"9d8219ad.44c838","type":"ui_group","z":"","name":"Default","tab":"8543b06c.a4f4b","disp":true,"width":"10"},{"id":"8543b06c.a4f4b","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]`

**Comment by dceejay** [comment]
what version of dashboard are you using ?

**Comment by andysc** [comment]
2.2.1 in Safari

**Comment by andysc** [comment]
it crashes on deploy of a flow with a debug linked to the top output pin.
Same on Firefox on Mac, also

**Comment by dceejay** [comment]
can you first try upgrading to latest 2.3.5 ?

**Comment by andysc** [comment]
yup - that's fixed it - thanks!

**Comment by DBattou** [comment]
Hi andysc, I wanted to use the bargraph to display how much electricity i used each hours of the day. Do i need to make 24 different topics to fill every bars of the chart ? 

Maybe I could write a  function node with 24 outputs and connect it to the barchart, but I feel this is not the right way to do this.

**Comment by dceejay** [comment]
currently yes - you need one topic per bar.
