### ISSUE TITLE
histogram layout problem

### ISSUE THREAD

**Issue by andysc** [node-red/node-red-dashboard#195]
This seems to happen quite often (see attachment). Seems it can't decide whether to fill the whole box, or just use the top left corner. I can't seem to force it one way or the other.
Latest version, and the older version I had did it too.
On Safari
<img width="1084" alt="screen shot 2017-03-28 at 13 23 23" src="https://cloud.githubusercontent.com/assets/2693674/24404596/0dc923fe-13ba-11e7-8770-b98872545529.png">

**Comment by andysc** [comment]
reload fixes it in latest version (it didn't in the older version)... so it's getting better ;)

**Comment by andysc** [comment]
oh, it's on "auto" size, and default everything

**Comment by dceejay** [comment]
Is this still being seen ? - any more details ? or can we close ?

**Comment by andysc** [comment]
I haven't used dashboard for quite a while - let me try it again and get back to you
