### ISSUE TITLE
Text input with Delay @ 0 sends payload twice on Enter AND loss of focus

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#196]
I am used to press enter after inputting text and then I click on something else and it results in sending the payload twice, which in my case is not the desired behavior (deleting lines of text).

It would be better to either leave the choice with checkboxes and/or detect Tab instead of loss of focus.
Thanks!

**Comment by dceejay** [comment]
pushed a change/fix to master 82361ab4eae4abf981907fb912ace4eb9f4740bf
