### ISSUE TITLE
chart does not clip correctly

### ISSUE THREAD

**Issue by tve** [node-red/node-red-dashboard#198]
I set Y min to -5000 and max to 5000, see the results.
![image](https://cloud.githubusercontent.com/assets/39480/24599230/075fa206-1804-11e7-9336-2245427dbe5c.png)

**Comment by dceejay** [comment]
Currently they are scale values. If you need to clip the data then you should do that in a preceding node.

**Comment by dceejay** [comment]
Have found a way to just not render values out of range...
