### ISSUE TITLE
Not published to npm as node-red-dashboard

### ISSUE THREAD

**Issue by ssadams11** [node-red/node-red-dashboard#20]
Step 22 : RUN npm install -g node-red-dashboard
 ---> Running in 2ff11af0851d
npm ERR! Linux 3.16.0-67-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-red-dashboard"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/node-red-dashboard
npm ERR! 404 
npm ERR! 404 'node-red-dashboard' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
The command '/bin/sh -c npm install -g node-red-dashboard' returned a non-zero code: 1

**Comment by knolleary** [comment]
Hi, yes, we know this isn't published. As has been said on the mailing list a few times, this is a work in progress, with a number of breaking changes coming. Once it is ready for general usage it will be announced and published to npm etc.

For now, if you want to try it, you can `npm install node-red/node-red-dashboard` to pull in the latest from git - but be aware **there are breaking changes coming**.

**Comment by ssadams11** [comment]
Great!  Thanks.  Looking forward to the new improvements.  THis project has been a game changer for node-red.  Excellent work!
