### ISSUE TITLE
Dropdown node stops working

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-dashboard#200]
I'm using a dropdown node to select a weather forecast by day which normally works great, but for some reason after a week or so, the node stops producing an output when a different dropdown value is selected.
In the pasted image, you can see that I've pulled the 'dead' node (dropdown) out of the flow, and added a debug node, as well as a 'new' dropdown node formatted the same (Working).
In my ui, selecting different values in 'Working' does produce the expected values, but the 'dropdown' node produces nothing whatsoever.
![dropdown](https://cloud.githubusercontent.com/assets/973580/24773279/67e49450-1b0c-11e7-8d5b-f27a9508ce14.PNG)
Maybe a coincidence, but this problem started about the time I added a 'looptimer' node in the flow... is it possible that a node can somehow cause problems for a preceding node?
![flow](https://cloud.githubusercontent.com/assets/973580/24773347/b163cc4a-1b0c-11e7-93a9-c445ffe52e0e.PNG)
There is nothing in the log or debug to indicate an error.
If I add an inject node to the non-working dropdown node, then the injected value does appear in debug.

**Comment by dceejay** [comment]
actually - yes a following node can (thanks to javascript passing things by reference) affect a previous node. One way to paper round this to test would be to...

      disconnect the dropdown from the next node...
      wire it to a debug node...
      deploy
      add the wire to loop back in  (leaving the debug in place)
      re-deploy

what this does is force us to have to clone the message coming out of dropdown... so if loop does mess with it, it shouldn't kick the dropdown. Not the answer - but would help isolate.

**Comment by Paul-Reed** [comment]
Thanks, I made the changes last night.
I'll report back after a period of testing.

**Comment by dceejay** [comment]
any news ? goor or bad.

**Comment by Paul-Reed** [comment]
So far so good!
I think 3 weeks is probably a definitive test, but if you want to close this - it can always be re-opened.
I've emailed the author of looptimer and also PM'd him/her on Slack, but they don't seem to want to respond. Also searched github, but not found the repo.

**Comment by dceejay** [comment]
can leave it while longer - not a problem - you can also close it if/when you are happy...

**Comment by Paul-Reed** [comment]
No further problems since adding the workaround as above, so it's probably fair to say that there is an issue with the looptimer node.
Since the author isn't engaging, I suppose it's time to delete looptimer and find a better solution.
It's a shame we can't add comments to the node listing to alert other potential users.
