### ISSUE TITLE
Text input and Dropdown misaligned

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#201]
Text input and Dropdown menu on the same line is unaligned and the lines are not same thickness (Dashboard v.2.3.5)

![pasted_image_at_2017_04_07_10_32_am](https://cloud.githubusercontent.com/assets/15982264/24806352/96b8ccda-1b82-11e7-8ed0-150cfc3825da.png)

**Comment by dceejay** [comment]
![image](https://cloud.githubusercontent.com/assets/5375409/24821965/abe6f084-1be9-11e7-8ef5-8b32bdbd3653.png)
