### ISSUE TITLE
Default text of the dropdown "Select an Option" is not changeable

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#202]
It would be great if the default text of the Dropdown "Select an Option" would be changeable.
Thanks!

**Comment by dceejay** [comment]
![image](https://cloud.githubusercontent.com/assets/5375409/24821981/d3990928-1be9-11e7-9d29-7f3a2cb4b084.png)

**Comment by Hugobox** [comment]
Thank you! Greatly appreciated!
