### ISSUE TITLE
Crash on reload when embedding base64 images

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red-dashboard#203]
Node-red crashes on reloading a dashboard page, if too many or too large images are embedded - using a base64 encoded string and a template node. (Dash 2.3.6, nr 0.16.2)
Error code: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

How to reproduce the bug: Generate a page with embedded images (attached flow). Reload the page -> crash occurs. (Maybe change img url to a local resource to prevent server load.) 

`[{"id":"c5e53fed.3b24f","type":"ui_template","z":"bce9a3c4.6de25","group":"3ac0b01.048e85","name":"Display Image","order":8,"width":"10","height":"7","format":"<img width=\"100%\" height=\"100%\" src=\"data:image/jpg;base64,{{msg.payload[2].payload}}\"/>\n<img width=\"100%\" height=\"100%\" src=\"data:image/jpg;base64,{{msg.payload[1].payload}}\"/>\n<img width=\"100%\" height=\"100%\" src=\"data:image/jpg;base64,{{msg.payload[0].payload}}\"/>\n","storeOutMessages":false,"fwdInMessages":false,"x":1232,"y":2130,"wires":[[]]},{"id":"53594d6e.25a594","type":"function","z":"bce9a3c4.6de25","name":"AdvJoinV5","func":"var countmsg = 3;          //how many items to join?\nvar nodublicates = false;   //only join if payload unequal existing payload\nvar limit;                 //only join if payloads are on both sides of the limit\nvar hysteresis;      //hysteresis \nvar clearaftersend = false;//clear queue after sending\n//------------ different topic mode ------------------\nvar diftopics = false;      //true: join only different topics; false: join only same topics\n\nvar inmsg = msg;\nvar outmsg = { \"topic\": inmsg.topic , \"payload\": \"\"};\nvar msgs = context.get(\"aggmsgs\")||{};\nvar topicmsgs = msgs[inmsg.topic]||[];\nvar lastval = context.get(\"lastval\");\n\nif (typeof inmsg.reset != \"undefined\") {\n    msgs = {};\n    topicmsgs = [];\n    lastval = undefined;\n}\nif (typeof inmsg.resettopic != \"undefined\") {\n    topicmsgs = [];\n    lastval = undefined;\n}\nif (typeof hysteresis !== 'undefined' && typeof lastval !== 'undefined') {\n    if (Math.abs(inmsg.payload - lastval) <= hysteresis) {\n        return null;\n    }\n}\nif (typeof lastval !== 'undefined') {\n    if (nodublicates && lastval == inmsg.payload)\n        return null;\n    if (typeof limit !== 'undefined' && countmsg == 2) {\n        if (!((lastval <= limit && inmsg.payload >= limit) || (lastval >= limit && inmsg.payload <= limit)))   \n            return null;\n    }\n} \n\nif (diftopics) {\n    if (topicmsgs.length > 0) {     //msg with same topic -> replace old msg\n        topicmsgs.shift();\n    }\n    topicmsgs.push(inmsg);\n    msgs[inmsg.topic] = topicmsgs;    \n    context.set(\"aggmsgs\",msgs);\n    context.set(\"lastval\",inmsg.payload);\n    if (Object.keys(msgs).length == countmsg) {\n        var aout = {};\n        outmsg.topic = \"\";\n        for (var tmsgs in msgs) {\n            if (msgs.hasOwnProperty(tmsgs)) {\n                aout[tmsgs] = msgs[tmsgs][0];\n                outmsg.topic += tmsgs + \"_\";\n            }\n        }\n        if (clearaftersend) {\n            context.set(\"aggmsgs\",undefined);\n            context.set(\"lastval\",undefined);\n        }\n        outmsg.topic = outmsg.topic.substr(0,String(outmsg.topic).length-1);\n        outmsg.payload = aout;\n        return outmsg;\n    } else\n        return null;\n} else {\n    if (topicmsgs.length == countmsg){\n        topicmsgs.shift();\n    }\n    topicmsgs.push(inmsg);\n    outmsg.payload = topicmsgs;\n    \n    msgs[inmsg.topic] = topicmsgs;\n    context.set(\"aggmsgs\",msgs);\n    context.set(\"lastval\",inmsg.payload);\n    \n    if (topicmsgs.length == countmsg) {\n        if (clearaftersend) {\n            msgs[inmsg.topic] = undefined;\n            context.set(\"aggmsgs\",msgs);\n            context.set(\"lastval\",undefined);\n        }\n        return outmsg;\n    }\n    else\n        return null;\n}\n\n","outputs":1,"noerr":0,"x":979,"y":2134,"wires":[["c5e53fed.3b24f"]]},{"id":"e252b257.78933","type":"base64","z":"bce9a3c4.6de25","name":"Encode","x":797,"y":2138,"wires":[["53594d6e.25a594"]]},{"id":"d4f7dc1c.bc17c","type":"http request","z":"bce9a3c4.6de25","name":"","method":"GET","ret":"bin","url":"https://1.bp.blogspot.com/-eUyyO_yEIpo/V1jVs78XlgI/AAAAAAAAATY/WjrJq3Q9ezcWZz2QNuJoXiHoesgtiAp4QCLcB/s640/WIO-26.PNG","tls":"","x":607,"y":2142,"wires":[["e252b257.78933"]]},{"id":"ce8de9b6.356f18","type":"inject","z":"bce9a3c4.6de25","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":412,"y":2150,"wires":[["d4f7dc1c.bc17c"]]},{"id":"3ac0b01.048e85","type":"ui_group","z":"","name":"Test","tab":"4416e608.228a38","disp":true,"width":"10"},{"id":"4416e608.228a38","type":"ui_tab","z":"","name":"Test","icon":"dashboard","order":1}]`

**Comment by dceejay** [comment]
What platform are you running on ? What command are you starting Node-RED with ? How often are you updating ? How large are the images ?

**Comment by M0ebiu5** [comment]
Platform: Linux (i5-3475s, 16GB ram). 

Cmd: node-red: --max-old-space-size=128 /opt/iobroker/node_modules/iobroker.node-red/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js. 

How often i update? Update what?
Image in the attached sample is 230kb.

**Comment by dceejay** [comment]
Updating = refreshing the image.
Looks like you shouldn't be anywhere near the limits of the hardware you have so I'm surprised it's breaking. So far I've not managed to make that flow break on my mac.

**Comment by M0ebiu5** [comment]
It crashes on the first update (manual reload of dashboard via browser button). But the implicit load of the images, when they are pushed to the template, is working.
I'm sure that it's not a hardware problem - the machine is stable and uses only 4 of the 16GB.
Whats the best way to track it down?

**Comment by M0ebiu5** [comment]
Tried it now on a clean node-red instance and the error did not occur. So it seems somehow related to io-broker, who runs node-red in the first scenario, but even with the same settings and all flows imported, i couldn't reproduce the error.

**Comment by dceejay** [comment]
thanks for reporting back
