### ISSUE TITLE
Avoid double slash when serving at root

### ISSUE THREAD

**Issue by vicary** [node-red/node-red-dashboard#204]
When setting `httpNodeRoot: '/'` and `ui: { path: '/' }`, clicking the `fa-external-link` icon from the sidebar opens `http://localhost:1880//` with double trailing slashes.

Most of the things works, only that socket.io does not normalize request paths, hence, does not serves it's client js.

**Comment by Paul-Reed** [comment]
If you look at https://github.com/node-red/node-red/blob/master/settings.js#L85 and https://github.com/node-red/node-red/blob/master/settings.js#L102 both are commented out for the content to be served from root (by default).
By un-commenting and adding a backslash in the settings, are you creating the double backslash in the url?
i.e. if you want them to be served from root, just leave them commented out.

**Comment by vicary** [comment]
I tried commenting out `ui: { path: '/ui' }`, it falls back to default which is `/ui` instead of root.

**Comment by Paul-Reed** [comment]
Yes, but if you comment out the` httpNodeRoot` and add `ui: { path: '/' }` doesn't that resolve the issue?
Is adding a backslash to `httpNodeRoot` in settings creating the double backslash?

**Comment by knolleary** [comment]
Regardless of how the various config options are set, we should be forgiving and do the right thing.

It's a trivial fix to avoid duplicate slashes - and doing so means the user doesn't have to even know about it.

**Comment by vicary** [comment]
Manually entering URL works in both cases, it's the `fa-external-link` button in editor sidebar generates a wrong URL.

This time it strangely still generates `/ui` with `ui: { path: '/' }` in use and `httpNodeRoot` commented out.

**Comment by dceejay** [comment]
did you try `ui: { path: "" }`  ?

**Comment by Paul-Reed** [comment]
I tried it, but it does then default to /ui

**Comment by dceejay** [comment]
really ? which version of dashboard ?
(for me it goes correctly... aargh)

**Comment by Paul-Reed** [comment]
The current git version.

![1](https://cloud.githubusercontent.com/assets/973580/25027401/513d672a-20a4-11e7-8ba8-615fe83a808e.PNG)

results in;

![3](https://cloud.githubusercontent.com/assets/973580/25027417/6561401e-20a4-11e7-9329-eadfad8b1b2d.PNG)

whilst;

![2](https://cloud.githubusercontent.com/assets/973580/25027437/81225f9a-20a4-11e7-819d-3d89c997e481.PNG)

**Comment by dceejay** [comment]
did you stop and restart node-red and reload the browser before trying that ?

**Comment by Paul-Reed** [comment]
Yes for both.
I double checked by using incognito,
and yes, my normal setting is `ui: { path: 'dash' }` 
I just changed it to try and help vicary.

**Comment by Paul-Reed** [comment]
`ui: { path: "" }` works fine now, and serves the dashboard from /

**Comment by knolleary** [comment]
With this fix what does a ui path of `/` result in? To me, settings the desired path to `""` is not Intuitive if what i really want is `/`.

**Comment by dceejay** [comment]
it is relative to httpRoot   so if that is already / then  how else to we say add nothing ?

**Comment by knolleary** [comment]
The HTTP In node lets you specify the path it listens on. Sometimes a user will specify a leading /, sometimes they don't. But we do the right thing so we don't end up listening on a path with a double / in it.

Why is this different? If a user specifies a desired ui path of /, that is relative to httpNodeRoot. And i bet they never want //. So why don't we do the simple tasks of avoiding a dbl slash on behalf of the user?

**Comment by dceejay** [comment]
fair enough

**Comment by vicary** [comment]
Thanks everyone here for the follow up. 😄
