### ISSUE TITLE
The page does not scale when viewed on a mobile device.

### ISSUE THREAD

**Issue by Bebebe1974** [node-red/node-red-dashboard#207]
Hi.
The page does not scale when viewed on a mobile device (Microsoft Lumia 640 Windows Mobile 10). Also does not work scrolling.

**Comment by dceejay** [comment]
Hi,
what do you mean ? the dashboard groups size is set in units of approximately 50px - default 6 units, so approx 300px - so it doesn't scale per se. It will/should move columns around to fit the screen as best it can.

Which scrolling doesn't work ? within a page ? or using scroll to move between tabs ? (sideways)

Which browser ?

**Comment by Bebebe1974** [comment]
Hi. Thanks for the answer.
Scrolling doesn't work within a page and the scale does not change. Therefore, I can not completely manage my device from a smartphone. Browser - Microsoft Edge on Windows Mobile10. I made a video.  
I apologize for my bad English.
https://youtu.be/N11W4_EBZPk

**Comment by dceejay** [comment]
Thanks - much clearer - seems to be a specific Edge problem... will see if there is a workaround.

**Comment by dceejay** [comment]
Hi - have added a line to the CSS that people report may help... but I don't have a device to test... so over to you :-)

You will need latest from master   `npm i node-red/node-red-dashboard`
Thanks

**Comment by Bebebe1974** [comment]
Thank you. I will be test this, but later. After 25.04.2017. I will necessarily report the result.

**Comment by Bebebe1974** [comment]
I am testing this update - work fine. If necessary, I can show the result on the video. Thanks for good job. Now I can continue my project.

**Comment by dceejay** [comment]
Phew ! - just released as 2.3.9 on npm - so glad it worked !
