### ISSUE TITLE
apple touch icon stopped working

### ISSUE THREAD

**Issue by corbosman** [node-red/node-red-dashboard#208]
Hi, the icon.png was renamed but the apple touch icon wasnt changed with it. So now if you 'Save to HomeScreen' you get a bit of an ugly dynamic icon. Should be changed to reflect one of sized icons.

**Comment by dceejay** [comment]
yup - what size should it be ideally ?

**Comment by corbosman** [comment]
Well, if you want to really be fully compatible there should be several:

<link rel="apple-touch-icon" href="older-iPhone.png"> // 120px  
<link rel="apple-touch-icon" sizes="180x180" href="iPhone-6-Plus.png">  
<link rel="apple-touch-icon" sizes="152x152" href="iPad-Retina.png">  
<link rel="apple-touch-icon" sizes="167x167" href="iPad-Pro.png">  

Each apple device will pick the right size. If you think that's too much hassle, the default 120x120 would work i think. 

more info:  https://sympli.io/blog/2017/02/15/heres-everything-you-need-to-know-about-favicons-in-2017/
