### ISSUE TITLE
Vertical Widget Size not recognized

### ISSUE THREAD

**Issue by sbolten** [node-red/node-red-dashboard#210]
When changing the vertical widget size it is not recognized. It looks like the horizontal size is also taken as the vertical. Effect: When changing the horizontal (bigger value) the the widgets increases horizontally but also vertically (less rows fit on the screen). Running latest version of the node (2.3.8).

Regards, Stephan

**Comment by dceejay** [comment]
which widget ? do you have an example of the sizes that cause problems ?

**Comment by sbolten** [comment]
I am using text, slider, switch and dropdown widgets - all the same.

Horizontal: 60
Vertical: 48

looks exactly the same as 

Horizontal: 60
Vertical: 60

If I set Vertical to a big value (100) or a very small value (1) has no impact on the row size.

If you want I could attach screenshots.

Stephan

**Comment by dceejay** [comment]
no need - got it .
