### ISSUE TITLE
Chart is clear

### ISSUE THREAD

**Issue by marshalab** [node-red/node-red-dashboard#214]
Chart not work. I see blank frame and no any grapfix.

![image](https://cloud.githubusercontent.com/assets/8924352/25328596/a37f52e4-2902-11e7-86bd-686590cee4a2.png)

The data send to Gauge and Chart. And Chart not worked.
And i try install 
npm i node-red/node-red-dashboard
it is not work, i get ERROR intall.
npm i node-red-dashboard     worked greate.

Sorry my English.

**Comment by dceejay** [comment]
which platform/OS ? which browser ? which version of Node-RED ?
The layout itself seems very odd - there shouldn't be that gap between the columns on the actual dashboard.

**Comment by marshalab** [comment]
OS Jessie 2017-04-10 from dietpi
Node-Red 0.16.2
dashboard 2.3.7
my desktop is windows 7 + Browser Chrome (last update) and Firefox 52.0.15.911 (32-bit)

The layout is normal. I am test many components on one board. 
Then delete other component. it i ssee better.
![image](https://cloud.githubusercontent.com/assets/8924352/25329444/e9971908-2905-11e7-9a6d-bc8983ddf896.png)

**Comment by marshalab** [comment]
Clear test chart. 
Inject data, Gauge see, Debug see, Chart not see.

![image](https://cloud.githubusercontent.com/assets/8924352/25329631/cf5c16aa-2906-11e7-9194-576fd76665fd.png)

**Comment by marshalab** [comment]
Update.
Then kill process node-red. And start in the terminal node-red again. I see clear node-red, without nodes component. Install node-red-dashboard, get sample chart, and IT IS WORK !
![image](https://cloud.githubusercontent.com/assets/8924352/25332070/7ba978b4-290f-11e7-97a4-61ed5c5a169c.png)

The next step, found  bug. Why chart not view on the startup node-red ?

**Comment by marshalab** [comment]
Tneh start node-red-start, get error "Unit nodered.service entered failed state."
But then start node-red by hand - it is work fine.

root@DietPi-MQTT:~# node-red-start

Start Node-RED

Once Node-RED has started, point a browser at http://192.168.1.100:1880
On Pi Node-RED works better with the Firefox browser

Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot

To find more nodes and example flows - go to http://flows.nodered.org

Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
Started Node-RED graphical event wiring tool..
nodered.service: main process exited, code=exited, status=217/USER
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
Started Node-RED graphical event wiring tool..
nodered.service: main process exited, code=exited, status=217/USER
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
Started Node-RED graphical event wiring tool..
nodered.service: main process exited, code=exited, status=217/USER
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
Started Node-RED graphical event wiring tool..
nodered.service: main process exited, code=exited, status=217/USER
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....
nodered.service start request repeated too quickly, refusing to start.
Failed to start Node-RED graphical event wiring tool..
Unit nodered.service entered failed state.

**Comment by marshalab** [comment]
![image](https://cloud.githubusercontent.com/assets/8924352/25335584/dc4e0780-291d-11e7-93ed-6b9fd942316a.png)

root@DietPi-MQTT:~# sudo systemctl start nodered.service
root@DietPi-MQTT:~# sudo systemctl status nodered.service
● nodered.service - Node-RED graphical event wiring tool.
   Loaded: loaded (/lib/systemd/system/nodered.service; enabled)
   Active: failed (Result: start-limit) since Mon 2017-04-24 18:34:50 +07; 1s ago
     Docs: http://nodered.org/docs/hardware/raspberrypi.html
  Process: 1798 ExecStart=/usr/bin/node-red (code=exited, status=203/EXEC)
 Main PID: 1798 (code=exited, status=203/EXEC)

Apr 24 18:34:50 DietPi-MQTT systemd[1]: nodered.service holdoff time over, scheduling restart.
Apr 24 18:34:50 DietPi-MQTT systemd[1]: Stopping Node-RED graphical event wiring tool....
Apr 24 18:34:50 DietPi-MQTT systemd[1]: Starting Node-RED graphical event wiring tool....
Apr 24 18:34:50 DietPi-MQTT systemd[1]: nodered.service start request repeated too quickly, refusing to start.
Apr 24 18:34:50 DietPi-MQTT systemd[1]: Failed to start Node-RED graphical event wiring tool..
Apr 24 18:34:50 DietPi-MQTT systemd[1]: Unit nodered.service entered failed state.
root@DietPi-MQTT:~#

I did not understand. When I start as a service through the systemd - it does not work. If you run "node-red" manually from terminal, it works.

**Comment by marshalab** [comment]
Oh & Ah.... 
My Issues: in the dietPi distributive not autorun Node-red (dietpi-launcher). For autostart NodeRed on boot i am do this instruction
https://nodered.org/docs/getting-started/running
it is install PM2 node.js process manager with autostart.
And run /usr/local/bin/node-red 
![image](https://cloud.githubusercontent.com/assets/8924352/25338933/24704494-292b-11e7-9d35-972a3b0f559d.png)

Charts work. I want slip. Thanks/

**Comment by dceejay** [comment]
Hi - so is it working now ? If so can we close this issue ?
On Diet Pi - I think you can also use the normal debian instructions rather than PM2 if that is causing problems - http://nodered.org/docs/hardware/raspberrypi#adding-autostart-capability-using-systemd

**Comment by marshalab** [comment]
On the contrary. The standard method through systemd - did not work. When running via PM2 - it works. I did not go deeper into the problem. I'm using PM2. The topic is closed.
