### ISSUE TITLE
On rpi3 with updated node & node-red, dashboard is not created along with info & debug tabs

### ISSUE THREAD

**Issue by msw4chl** [node-red/node-red-dashboard#215]
I have installed this in a half dozen places, works great. Works great on Raspberry Pi 3 (RPI3) with completely updated node and node-red, BUT the dashboard tab isn't created.  Flows migrated to RPI3 from a docker under MacOS work fine, too, but the dashboard tab never rears it's head. 

What can I do to enable the dashboard on our RPI3 node-red installs?

Tx, Mark 
PS - yes, this is a NOOB build, but uninstalled node and node-red and installed the latest from github. don't have the pi3 boards accessible at this moment, but node-red is v0.16.2

**Comment by knolleary** [comment]
What version of node-red-dashboard have you installed and how/where did you install it?

**Comment by dceejay** [comment]
Hi can you try latest on github (rather than npm)
    `cd ~/.node-red && npm i node-red/node-red-dashboard`

Thanks

**Comment by msw4chl** [comment]
OK, very confusing. I have two Element 14 RPI3 boards. On the A board, which has a cloned uSD card from the B board, the dashboard shows up. Both have same level of node-red (v0.16.2) and both have same level of node.js (v6.10.2). The cloned board is at work, I'll uninstall node-red and node.js and retry on the B board which is at work. If dashboard doesn't show up I'll try the github version. tx.

**Comment by dceejay** [comment]
Please try the github version before the uninstall/reinstall.

**Comment by msw4chl** [comment]
will do...

Mark Smith IT Services Architect
http://bit.ly/7t-public-trello

On Wed, Apr 26, 2017 at 1:50 AM, Dave Conway-Jones
notifications-at-github.com |github1-w4chl/OldRadio| <

**Comment by dceejay** [comment]
(actually now pushed to npm as version 2.3.9)

**Comment by msw4chl** [comment]
Had exchange with some off-github, after updating Jessie, especially npm, re-installing node.js and Node-RED, the two rpi3b boards now behave as expected and dashboard comes up fine.
