### ISSUE TITLE
Feature request: more flexibility in menu ordering

### ISSUE THREAD

**Issue by natcl** [node-red/node-red-dashboard#216]
Hello,

Currently dashboard links always appear below dashboard tabs.  It would be nice if there was a way to interleave those so one could put a link above a tab.

**Comment by dceejay** [comment]
Currently these are held as two separate arrays and treated individually in the ui (dashboard tab). To allow interleaving would require them to be merged. 
While do-able, it is non-trivial so must be considered a long lead time item.

**Comment by dceejay** [comment]
was closed by #234 
71758258dfa7ff6adae7ebc9b72f33f13b1481f4
