### ISSUE TITLE
Sending empty array to "Bar chart" or "Bar chart (H)" causes a TypeError message

### ISSUE THREAD

**Issue by Lroy** [node-red/node-red-dashboard#217]
When sending data to a chart widget, with msg.payload = [], the charts clear all memory of previous data, as it did in earlier releases of the dashboard.

When using a "Line chart", this still works.

When using a "Bar chart", "Bar chart (H)", or "Pie chart", Node-RED emits a message:

TypeError: Cannot read property "push" of undefined

I have created the following flow to illustrate the issue:

[{"id":"c0a8c094.51f29","type":"tab","label":"Page 1"},{"id":"22b2f2da.3e7e9e","type":"ui_chart","z":"c0a8c094.51f29","name":"","group":"ed79067.a9fe4f8","order":0,"width":0,"height":0,"label":"chart","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"60","cutout":0,"colors":["#00ff00","#ff0000","#ff0000","#ff0000","#ff0000","#ff0000","#ff9896","#9467bd","#c5b0d5"],"x":620,"y":260,"wires":[[],[]]},{"id":"ec8f1d04.228b2","type":"inject","z":"c0a8c094.51f29","name":"Random","topic":"","payload":"","payloadType":"date","repeat":"1","crontab":"","once":true,"x":200,"y":260,"wires":[["8d445d81.01cec"]]},{"id":"8d445d81.01cec","type":"function","z":"c0a8c094.51f29","name":"Random Number","func":"msg.payload = Math.random(100);\nreturn msg;","outputs":1,"noerr":0,"x":430,"y":260,"wires":[["22b2f2da.3e7e9e"]]},{"id":"29895bac.575634","type":"ui_button","z":"c0a8c094.51f29","name":"","group":"ed79067.a9fe4f8","order":0,"width":0,"height":0,"label":"Clear Chart","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":210,"y":200,"wires":[["2e53212d.40ea2e"]]},{"id":"2e53212d.40ea2e","type":"function","z":"c0a8c094.51f29","name":"Clear Chart","func":"msg.topic = \"Clear\";\nmsg.payload = [];\nreturn msg;","outputs":1,"noerr":0,"x":410,"y":200,"wires":[["22b2f2da.3e7e9e"]]},{"id":"ed79067.a9fe4f8","type":"ui_group","z":"","name":"Group1","tab":"d212e8d1.29b388","disp":true,"width":"6"},{"id":"d212e8d1.29b388","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]

**Comment by Lroy** [comment]
This is perhaps a better illustration of the problem.

Press button to clear the bar and line chart.  The bar chart is having difficulty after the "clear".

[{"id":"c0a8c094.51f29","type":"tab","label":"Page 1"},{"id":"2581f40.66ae40c","type":"inject","z":"c0a8c094.51f29","name":"Random","topic":"","payload":"","payloadType":"date","repeat":"1","crontab":"","once":true,"x":160,"y":260,"wires":[["3119403.f46b5c","93435e28.a7602","a8940575.39e638"]]},{"id":"3119403.f46b5c","type":"function","z":"c0a8c094.51f29","name":"Random data","func":"msg.topic = \"Item1\";\nmsg.payload = Math.random();\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":260,"wires":[["1feee01b.f4a24","c284cd67.9c0be"]]},{"id":"1583e07.5af5a2","type":"function","z":"c0a8c094.51f29","name":"Clear","func":"msg.payload = [];\nreturn msg;","outputs":1,"noerr":0,"x":350,"y":180,"wires":[["1feee01b.f4a24","c284cd67.9c0be"]]},{"id":"164e01d6.7d495e","type":"ui_button","z":"c0a8c094.51f29","name":"","group":"6cdeec0b.cdb234","order":0,"width":0,"height":0,"label":"Clear Charts","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":170,"y":180,"wires":[["1583e07.5af5a2"]]},{"id":"1feee01b.f4a24","type":"ui_chart","z":"c0a8c094.51f29","name":"Bar chart","group":"6cdeec0b.cdb234","order":0,"width":0,"height":0,"label":"Bar Chart","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"No Data Available","ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"x":640,"y":300,"wires":[[],[]]},{"id":"c284cd67.9c0be","type":"ui_chart","z":"c0a8c094.51f29","name":"Line Chart","group":"6cdeec0b.cdb234","order":0,"width":0,"height":0,"label":"Line Chart","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"No Data Available","ymin":"","ymax":"","removeOlder":"20","removeOlderPoints":"","removeOlderUnit":"1","cutout":0,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"x":650,"y":220,"wires":[[],[]]},{"id":"a8940575.39e638","type":"function","z":"c0a8c094.51f29","name":"Random data","func":"msg.topic = \"Item3\";\nmsg.payload = Math.random();\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":340,"wires":[["1feee01b.f4a24","c284cd67.9c0be"]]},{"id":"93435e28.a7602","type":"function","z":"c0a8c094.51f29","name":"Random data","func":"msg.topic = \"Item2\";\nmsg.payload = Math.random();\nreturn msg;","outputs":1,"noerr":0,"x":380,"y":300,"wires":[["c284cd67.9c0be","1feee01b.f4a24"]]},{"id":"6cdeec0b.cdb234","type":"ui_group","z":"","name":"Default","tab":"d212e8d1.29b388","disp":true,"width":"6"},{"id":"d212e8d1.29b388","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]

**Comment by dceejay** [comment]
yup - got it. thanks
