### ISSUE TITLE
sending bellow data to a bar chart, crashes node-red

### ISSUE THREAD

**Issue by roadfox** [node-red/node-red-dashboard#218]
node-red is restarting constantly after i ran bellow flow

versions are:
node v6.10.2
npm 3.10.10
node-red v0.16.2
node-red-dashboard 2.3.9

error message is:
1 May 19:45:29 - [error] [ui_chart:2bedba92.62651e] TypeError: data[0].values.data[i].map is not a function
1 May 19:45:29 - [red] Uncaught Exception:
1 May 19:45:29 - TypeError: data[0].values.data[i].map is not a function
    at Object.convertBack (/usr/lib/node_modules/node-red-dashboard/nodes/ui_chart.js:48:64)
    at ChartNode.<anonymous> (/usr/lib/node_modules/node-red-dashboard/ui.js:172:35)
    at emitOne (events.js:96:13)
    at ChartNode.emit (events.js:188:7)
    at Timeout._onTimeout (/usr/lib/node_modules/node-red-dashboard/nodes/ui_chart.js:212:18)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

flow is:
[{"id":"d596bb7b.240ef","type":"debug","z":"34e52c17.913ca4","name":"","active":true,"console":"false","complete":"false","x":618,"y":500,"wires":[]},{"id":"a5a87050.0345a8","type":"function","z":"34e52c17.913ca4","name":"","func":"var chart=[\n  {\n    \"key\": \"Day Litres\",\n    \"values\": {\n      \"series\": [\n        \"2016/11/30\",\n        \"2016/12/01\",\n        \"2016/12/02\",\n        \"2016/12/03\",\n        \"2016/12/04\"\n      ],\n      \"data\": [\n        [\n          188.6,\n          296.3,\n          104.8,\n          321.9,\n          287.6\n        ]\n      ]\n    }\n  }\n];\nmsg.payload=chart;\nreturn msg;","outputs":1,"noerr":0,"x":282,"y":514,"wires":[["2bedba92.62651e"]]},{"id":"2bedba92.62651e","type":"ui_chart","z":"34e52c17.913ca4","name":"","group":"731256a6.696d18","order":0,"width":0,"height":0,"label":"chart2","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"x":433,"y":498,"wires":[["d596bb7b.240ef"],[]]},{"id":"731256a6.696d18","type":"ui_group","z":"","name":"Test Barchart","tab":"f288d2a9.62727","disp":true,"width":"6"},{"id":"f288d2a9.62727","type":"ui_tab","z":"","name":"Chart.js example","icon":"dashboard","order":2}]

**Comment by dceejay** [comment]
Thanks - yes - we shouldn't crash and burn on that bad data.
