### ISSUE TITLE
Dropdown: add input to set items dynamically

### ISSUE THREAD

**Issue by natcl** [node-red/node-red-dashboard#22]
The dropdown widget is really nice !  
I think it could be very useful if there was a way to dynamically set the elements of the dropdown by sending an object into the input of the dropdown.  This way we could create dynamic menus by querying a database for example.

**Comment by knolleary** [comment]
That is the plan... just a case of getting a stable release done first otherwise we'd never stop adding things

👍

**Comment by natcl** [comment]
Great :) Very nice work on dashboard lately looks good now !
