### ISSUE TITLE
Custom msg timestamp for chart

### ISSUE THREAD

**Issue by marciogranzotto** [node-red/node-red-dashboard#222]
Is it possible to set a custom timestamp on a msg that will be shown on the chart x-axis?
I've tried to set `msg.timestamp` but no success.

This would be highly appreciated since I'm trying to show a glucose chart with measures that need to be organized by their actual date, note the date that the msg was received by the `chart` node.

**Comment by dceejay** [comment]
Hi, in general we prefer things to be raised and discussed on the mailing list or Slack first - but seeing as you have already raised a PR I'm going to close this issue.
