### ISSUE TITLE
Upgrading: cannot remove node-red-contrib-ui

### ISSUE THREAD

**Issue by andig** [node-red/node-red-dashboard#228]
I've stopped nr, changed to the `~/node-red` folder and did:

	npm remove node-red-contrib-ui
	npm install node-red-dashboard

I've also done a 

    npm remove -g node-red-contrib-ui

for good measure. Now, starting nr I'm getting these errors:

	Welcome to Node-RED
	===================
	12 May 16:40:53 - [info] Node-RED version: v0.16.0
	12 May 16:40:53 - [info] Node.js  version: v4.4.7
	12 May 16:40:53 - [info] Linux 4.4.26-v7+ arm LE
	12 May 16:40:55 - [info] Loading palette nodes
	pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /usr/local/lib/node_modules/node-red/nodes/core/hardware/nrgpio.py info
	pam_unix(sudo:session): session opened for user root by (uid=0)
	pam_unix(sudo:session): session closed for user root
	12 May 16:41:01 - [info] Dashboard version 2.3.10 started at /ui
	12 May 16:41:02 - [info] UI started at /ui
	12 May 16:41:05 - [warn] ------------------------------------------------------
	12 May 16:41:05 - [warn] [sensehat] Error: Can't find Sense HAT python libraries. Run sudo apt-get install sense-hat
	12 May 16:41:05 - [warn] [ui_switch] Error: ui_switch already registered
	12 May 16:41:05 - [warn] [ui_slider] Error: ui_slider already registered
	12 May 16:41:05 - [warn] [ui_numeric] Error: ui_numeric already registered
	12 May 16:41:05 - [warn] [ui_text] Error: ui_text already registered
	12 May 16:41:05 - [warn] [ui_text_input] Error: ui_text_input already registered
	12 May 16:41:05 - [warn] [ui_gauge] Error: ui_gauge already registered
	12 May 16:41:05 - [warn] [ui_chart] Error: ui_chart already registered
	12 May 16:41:05 - [warn] [ui_toast] Error: ui_toast already registered
	12 May 16:41:05 - [warn] [ui_link] Error: ui_link already registered
	12 May 16:41:05 - [warn] [ui_template] Error: ui_template already registered
	12 May 16:41:05 - [warn] [ui_tab] Error: ui_tab already registered
	12 May 16:41:05 - [warn] [logentries] Error: Cannot find module 'logentries'
	12 May 16:41:05 - [warn] ------------------------------------------------------
	12 May 16:41:05 - [info] Settings file  : /home/pi/.node-red/settings.js
	12 May 16:41:05 - [info] User directory : /home/pi/.node-red
	12 May 16:41:05 - [info] Flows file     : /home/pi/.node-red/flows_heizung.json
	12 May 16:41:05 - [info] Server now running at http://127.0.0.1:1880/
	12 May 16:41:05 - [info] Waiting for missing types to be registered:
	12 May 16:41:05 - [info]  - ui_tab
	12 May 16:41:05 - [info]  - ui_toast
	12 May 16:41:05 - [info]  - ui_text
	12 May 16:41:05 - [info]  - ui_chart
	12 May 16:41:05 - [info]  - ui_gauge

Using "manage palette" inside nr it seems ui_tab from contrib-ui is still in use yet I can't find a node using it. I've also removed all ui nodes for now and they're all unused, except for the tab.

My questions: how can I properly kill contrib-ui and/or remove the phantom node? 

Imho the steps for upgrading from contrib-ui should be documented as well.

**Comment by dceejay** [comment]
normally we prefer how-to type questions on the mailing list or slack.
As usual it depends where you installed contrib-ui...
normally  it's the `~/.node-red`   directory with a .

**Comment by andig** [comment]
For sake of other readers: `npm list -g` showed me

    npm ERR! extraneous: node-red-contrib-ui@1.2.19 /usr/local/lib/node_modules/node-red/node_modules/node-red-contrib-ui

Nuking that folder and restarting fixed it.

**Comment by dceejay** [comment]
ah - yes if you install it globally - you must remove it globally.
