### ISSUE TITLE
Chart lose data when switching to a tab with an iframe.

### ISSUE THREAD

**Issue by pierosavi** [node-red/node-red-dashboard#232]
node-red-dashboard v 2.3.10.
node-red v 0.16.2

I have a chart with 4 lines, 1 day limit.
![before](https://cloud.githubusercontent.com/assets/15440183/26296475/257da098-3ecf-11e7-86e4-3b48b836a8aa.PNG)
if i switch to a tab with an iframe inside a template (in this case the worldmap node page) and return to the original tab the chart becomes blank.
![after](https://cloud.githubusercontent.com/assets/15440183/26296545/64696c06-3ecf-11e7-9e8f-ca1f0506ee4d.PNG)
Data returns when refreshing the page.

**Comment by dceejay** [comment]
Is this not the same as #226 ?

**Comment by pierosavi** [comment]
It is. I see it should be fixed in 2.3.11. Thanks.
