### ISSUE TITLE
Error when I install the last version with "node fixfa.js" ?

### ISSUE THREAD

**Issue by chameleonbr** [node-red/node-red-dashboard#233]
NPM error message below:

```npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-dashboard@2.3.11"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-red-dashboard@2.3.11 postinstall: `node fixfa.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-dashboard@2.3.11 postinstall script 'node fixfa.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fixfa.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
```

**Comment by knolleary** [comment]
The `fixfa.js` script assumes that the font-awesome module has been installed in the `node_modules` directory beneath the `node-red-dashboard` module. That's okay for npm 2.x, but as of 3.x, node modules get installed at the same level when possible, so this script won't work.

Looking at the script, it silently fails in this case, but does exit cleanly - so it's not immediately apparent why the script would ever exit with a bad status code.

@chameleonbr As it says in the last line of that output, please can you provide the `npm-debug.log` file as well?

**Comment by chameleonbr** [comment]
[npm-debug.txt](https://github.com/node-red/node-red-dashboard/files/1027362/npm-debug.txt)

**Comment by knolleary** [comment]
This might be a permissions issue on the file.

Can you try rerunning the install with the ` --unsafe-perm` argument:

    npm install  --unsafe-perm node-red-dashboard

**Comment by chameleonbr** [comment]
The package has now been installed correctly. Thanks.
