### ISSUE TITLE
Feature Request: allow dynamic defining of sector boundaries

### ISSUE THREAD

**Issue by TakahashiNZ** [node-red/node-red-dashboard#235]
Hi,
I'm looking for a way to update the sector boundaries dynamically.

I'm using the gauge to show a temperature, and I allow the end user to set a high and low limit via numeric input nodes. I want to use those high and low values as the sector boundaries. Is this possible at present? and if not could I please submit it as a feature request.

Thanks.

**Comment by dceejay** [comment]
Thank you. Normally we prefer ideas to be discussed on the mailing list or slack channels first in order for a wider audience to be able to join in, keeping the the issues list for actual code issues.

Currently it is not possible to set the limits dynamically, but could be considered in the future. One question would be, how would it work... if limits are set in the node... and a message arrives with new limits... change to the new limits ? - then the next message arrives without limits... do they revert to the original as set by the node - or stay on new limits ?  And id this just the min and max values - or all the sector boundaries as well ? (but as I say - we would prefer this sort of discussion on the other channels)
