### ISSUE TITLE
Compass Gauge broken after update to 2.3.11

### ISSUE THREAD

**Issue by DENightOne** [node-red/node-red-dashboard#237]
I have 2 servers with node red installed....updated both to 2.3.11 and the compass gauge no longer works on both...
![image](https://cloud.githubusercontent.com/assets/24840753/26690375/5b57787e-46f9-11e7-99d4-e265d72bf4e0.png)

**Comment by dceejay** [comment]
what sizes are they ? can you share the relevant part of the flow to help me recreate ? thanks

**Comment by DENightOne** [comment]
[{"id":"a77215ec.4b526","type":"ui_gauge","z":"61e22fa1.978f4","name":"","group":"dd440902.ab2298","order":20,"width":"3","height":"3","gtype":"compass","title":"Wind Direction","label":"","format":"{{value | number:0}}°","min":"0","max":"360","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":912,"y":607,"wires":[]},{"id":"dd440902.ab2298","type":"ui_group","z":"","name":"IOT Dashboard","tab":"7b0f4fd3.a98378","disp":false,"width":"27"},{"id":"7b0f4fd3.a98378","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]

**Comment by DENightOne** [comment]
Compass size is 3x3, theme is set to default dark... when I set it to light I get the same weird compass

**Comment by DENightOne** [comment]
Just to add another test.... completely fresh dashboard:

[{"id":"173ceb20.cde4f5","type":"random","z":"fbb90187.08fb78","name":"","low":"0","high":"360","inte":"true","x":581,"y":256,"wires":[["89f83926.0a5fb"]]},{"id":"a9420ddf.32db","type":"inject","z":"fbb90187.08fb78","name":"","topic":"","payload":"","payloadType":"date","repeat":"5","crontab":"","once":true,"x":328,"y":236,"wires":[["173ceb20.cde4f5"]]},{"id":"89f83926.0a5fb","type":"ui_gauge","z":"fbb90187.08fb78","name":"","group":"f7de359d.6bef5","order":0,"width":0,"height":0,"gtype":"compass","title":"Gauge","label":"units","format":"{{value}}","min":0,"max":"360","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":848,"y":260,"wires":[]},{"id":"f7de359d.6bef5","type":"ui_group","z":"","name":"Default","tab":"ce72ac1d.9ad67","disp":true,"width":"6"},{"id":"ce72ac1d.9ad67","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]

**Comment by DENightOne** [comment]
I get this:  

![image](https://cloud.githubusercontent.com/assets/24840753/26741292/1d518eee-47d9-11e7-9735-d5210ca4b748.png)

**Comment by dceejay** [comment]
What platform is this running on? And which browser ?

**Comment by DENightOne** [comment]
Windows 10  and Firefox 53.0.3 and Microsoft edge.... both have the same weird compass.. I have tried on 2 versions of windows 10...the first is the standard windows to with creators update, the second is windows 10 insider build (latest)..I have weird compass on both the same on both.

**Comment by dceejay** [comment]
most odd - I have now installed  2.3.11 on Windows 10 and yup.. it works fine :-(... Firefox 54, and latest Edge.  Maybe - in the theme section - can you try reseting the colour using the reset button 
![image](https://cloud.githubusercontent.com/assets/5375409/26742527/f1bcc1a2-47d5-11e7-8314-52afd1a4612e.png) and re-deploy.

**Comment by DENightOne** [comment]
Thanks dceejay.....resetting to colour worked..... Could have been one late night/early morning clicking stuff I know nothing about and deploying.  Thanks again for the help

**Comment by dceejay** [comment]
Phew !

**Comment by DENightOne** [comment]
Full disclosure: Just figured out what I did wrong.... I change the default background colour to the same as the DARK theme, so that I could "cheat" and make an md-icon appear without the icon background being blue..... have now change the md-icon in the template node to have (md-button style="background: #333333") as it should be
