### ISSUE TITLE
text-input node automatically sends msg when delay sets to 0

### ISSUE THREAD

**Issue by jmikerq** [node-red/node-red-dashboard#238]
When the delay field is set to 0, the text-input node still sends the msg when the text-input field is focused/unfocused in the dashboard without pressing the "enter" key.

**Comment by dceejay** [comment]
which version of dashboard ? do you have an example flow that shows the problem
(I think it has been fixed in latest... but)

**Comment by jmikerq** [comment]
I was testing that with both 2.3.6 and 2.3.11. It was just the text-input node simply connecting to a debug node.

I removed all the UI nodes (including the UI_base, UI_group and UI_tab node in the configuration nodes) to restart my flow from scratch, this issue doesn't seem to appear anymore (looks like restarting the node-red instance was not enough?) 

here is the flow
```
[{"id":"8938eb2.d49f518","type":"ui_text_input","z":"2c43bb05.1ee9d4","name":"","label":"","group":"aa1db3cf.320db","order":0,"width":0,"height":0,"passthru":true,"mode":"text","delay":"0","topic":"","x":372,"y":280,"wires":[["3423ca66.908166"]]},{"id":"3423ca66.908166","type":"debug","z":"2c43bb05.1ee9d4","name":"","active":true,"console":"false","complete":"false","x":554,"y":327,"wires":[]},{"id":"aa1db3cf.320db","type":"ui_group","z":"","name":"Default","tab":"da97da18.106ae8","disp":true,"width":"6"},{"id":"da97da18.106ae8","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]
```
