### ISSUE TITLE
Chart node: Date line not in line with hover info

### ISSUE THREAD

**Issue by roadfox** [node-red/node-red-dashboard#24]
My system where node-red runs and my client are set to UTC +2h Timezone. 
If i hover over a chart i see that the Date Line drawn is 2 hours offset from midnight compared to the tooltip times shown when hovering over the graph. The tooltip times seem correct, when i hover over the newest datapoint in the graph the time shown is current local time.

**Comment by dceejay** [comment]
will look at it - thanks.

**Comment by dceejay** [comment]
Charts now re-implemented using charts.js - so closing this issue
0fe76c294fe1c6894e3b8bc6ce4f8ccd6ed8d8ae
