### ISSUE TITLE
Configure message key of ui widget value & when to send msg

### ISSUE THREAD

**Issue by ds82** [node-red/node-red-dashboard#241]
I think it would simplify the use of dashboard widgets in flows a lot, if one could configure the key of the message object that holds the value of the ui widget and when the message is send.

To give you an example, lets look at the following flow:

![screen shot 2017-06-07 at 15 12 55](https://user-images.githubusercontent.com/332905/26880161-d73327e2-4b93-11e7-9d21-2644cff0dc45.png)

This flow does **not work** with the current dashboard text-input. But if I could configure the text-input to put its value into ``msg.input`` and only send this input when a message arrives, it would work. This change would enable more complex UIs with simpler flows, because I could easily chain these ui elements and even use them to aggregate different user inputs

![screen shot 2017-06-07 at 15 25 23](https://user-images.githubusercontent.com/332905/26880697-8d429b48-4b95-11e7-90df-1c14827698d8.png) 

If there are other ways to get this behaviour I would appreciate if you point me in the right direction (I'm quite new to node-red). If you think this is a good idea, I would be happy to help to implement this.

**Comment by dceejay** [comment]
Thanks - In general we prefer ideas to be aired on the mailing list or slack channel as per the contribution guidelines, so they can be more widely discussed, leaving the issue list for actual code bugs and work in progress.  So I'm going to close this as an Issue for now.

All nodes by default put their interesting data onto msg.payload and that is true across the core project as well.  the way you have drawn (fig 2) still wouldn't work as the timestamp would replace the text in input 1 - and then also input 2 and finally feed through to the function resulting in adding two timestamps... - to prevent that you would need the nodes also not to respond to payload coming in and be able to select that as well... again something not in our thinking.
