### ISSUE TITLE
Changing the default url access to the dashboard

### ISSUE THREAD

**Issue by mascapollo** [node-red/node-red-dashboard#242]
Hello there,

How do you change the default url dashborad access  http://localhost:1880/ui ?

Thanks

**Comment by knolleary** [comment]
Via your settings file. The default Node-RED settings file has a commented out section for the dashboard:

```
    // If you installed the optional node-red-dashboard you can set it's path
    // relative to httpRoot
    //ui: { path: "ui" },
```

@dceejay we should add that to the project readme - will leave this issue open to do that.

@mascapollo fyi, in general we prefer to handle this type.of question on the mailing list or slack team - both linked at the bottom of nodered.org

**Comment by mascapollo** [comment]
thanks a lot.

**Comment by bambulko** [comment]
hello,
how to remove "ui"? i want to address: http://localhost:1880 for ui and http://localhost:1880/admin (httpAdminRoot) for admin

thanks

**Comment by bambulko** [comment]
thx. i found it too ;)
