### ISSUE TITLE
Date Picker input date strings incorrectly parsed as UTC time

### ISSUE THREAD

**Issue by shrickus** [node-red/node-red-dashboard#245]
There is some unexpected behavior with the date picker -- when i pass `msg.payload` as "2017-03-01", it is interpreted as Zulu time, which is 5 hours ahead of me. so the date actually shown is Feb. 28th, 2017

The parsing is done in `ui-component-ctrl.js` here:
```
    case 'date-picker': {
        if (me.item.ddd !== undefined) {
            if (typeof me.item.ddd !== "object") {
                var b = me.item.ddd.split(/\D+/);
                me.item.ddd = new Date(Date.UTC(b[0], --b[1], b[2], b[3], b[4], b[5], b[6]));
            }
        }
    . . .
```
When the input payload typeof === "string", it seems like this could be changed to `me.item.ddd = new Date(me.item.ddd);` which assumes the local timezone (if none is specified).

If the input string ends with "Z" or contains a TZ offset like "-0500", it will be handled correctly according to that embedded timezone information.

Numeric input representing a javascript timestamp should always be considered as UTC.

I'm puzzled by the test for `typeof me.item.ddd !== "object"` -- does this mean that a date "object" structure is a valid form of input to the date picker? Is this documented somewhere?

**Comment by dceejay** [comment]
yeah - that's much better...
will patch it up
