### ISSUE TITLE
ui_switch resizing not working properly

### ISSUE THREAD

**Issue by Rawa** [node-red/node-red-dashboard#246]
The ui_switch does not resize properly in the dashboard when setting width to "auto".

How to reproduce bug:
1. Create ui_switch
2. Set size to 1x1
3. Deploy (Size in Dashboard is 1x1)
4. Set size to auto
5. Deploy (Size in Dashboard is still 1x1).

When setting auto to size in config width will be stored as "0", however initially width is stored as 0, thus it works the first time. However, other UI nodes seem to handle this and "0" is fine. The ui_switch, however are not able to handle it.

**Comment by dceejay** [comment]
Thanks - yes - bug
