### ISSUE TITLE
`Tabs & Links` height in FF in dashboard 2.4.0

### ISSUE THREAD

**Issue by codmpm** [node-red/node-red-dashboard#247]
The height of the control where you manage your Tabs & Links in the configure tab seems to small in Firefox (osx, V54).

![node-red-dashboard-2 4-config-tab](https://user-images.githubusercontent.com/9745239/27735447-db49e21c-5d9f-11e7-9c77-9ba39a85ff18.png)
(Chrome left, Firefox right)

**Comment by dceejay** [comment]
indeed - min-height should only be a guide - not to fix it... - will have a look ...
