### ISSUE TITLE
White space in drop-down

### ISSUE THREAD

**Issue by fab33** [node-red/node-red-dashboard#25]
When you have whitespace in dropdown item (height siez : 1), text is written on 2 lines and dropdown list is too large (even with small text inside). I made test with _ and it works fine.

**Comment by dceejay** [comment]
do you have a screenshot ? or flow (just the widget )  to show the problem ?

**Comment by fab33** [comment]
`[{"id":"788cadd6.e11b14","type":"ui_group","z":"4ed2e76b.278718","name":"OpenEVSE","order":"1","disp":true,"width":"6"},{"id":"508ea8e6.9630b8","type":"ui_tab","z":"4ed2e76b.278718","name":"LEAF","icon":"directions_car","order":"1"},{"id":"a3284778.5cd7b8","type":"mqtt-broker","broker":"localhost","port":"1883","clientid":""},{"id":"6bd7a55d.991ebc","type":"mqtt in","z":"4ed2e76b.278718","name":"","topic":"/openEVSE/state/current_capacity","broker":"a3284778.5cd7b8","x":234,"y":232,"wires":[[]]},{"id":"1bc4e5d2.5b949a","type":"mqtt in","z":"4ed2e76b.278718","name":"","topic":"/openEVSE/state/status","broker":"a3284778.5cd7b8","x":194,"y":84,"wires":[["3b95f7ad.10f4d8","4482ec93.2716c4"]]},{"id":"3b95f7ad.10f4d8","type":"ui_text","z":"4ed2e76b.278718","tab":"508ea8e6.9630b8","group":"788cadd6.e11b14","order":"1","width":"5","height":"","name":"","label":"Status du chargeur : ","format":"{{msg.payload}}","x":628,"y":86,"wires":[]},{"id":"c6552271.35979","type":"comment","z":"4ed2e76b.278718","name":"Voiture","info":"","x":147,"y":35,"wires":[]},{"id":"4482ec93.2716c4","type":"ui_switch","z":"4ed2e76b.278718","tab":"508ea8e6.9630b8","group":"788cadd6.e11b14","order":"2","width":"1","height":"","name":"","label":"","topic":"","onvalue":"true","onicon":"battery_charging_full","oncolor":"red","offvalue":"false","officon":"battery_full","offcolor":"black","x":581,"y":147,"wires":[[]]},{"id":"d72401a1.135cc","type":"ui_gauge","z":"4ed2e76b.278718","tab":"508ea8e6.9630b8","group":"788cadd6.e11b14","order":"3","width":"6","height":"","name":"Courant de Charge","title":"Courant de charge","label":"","format":"{{value}}","min":0,"max":"30","x":626,"y":231,"wires":[]},{"id":"b25749d5.21e018","type":"ui_dropdown","z":"4ed2e76b.278718","name":"","label":"Courant souhaité","tab":"508ea8e6.9630b8","group":"788cadd6.e11b14","order":1,"width":"6","height":"1","options":[{"label":"10A","value":"10"},{"label":"16A","value":"16"},{"label":"20A","value":"20"},{"label":"25A","value":"25"},{"label":"30A","value":"30"}],"payload":"","topic":"","x":187,"y":168,"wires":[["d72401a1.135cc"]]}]`

![Uploading evse.png…]()

**Comment by dceejay** [comment]
I see it.

**Comment by dceejay** [comment]
fixing... 
![image](https://cloud.githubusercontent.com/assets/5375409/16132728/55047ab8-340c-11e6-9efe-da7884915a2f.png)
