### ISSUE TITLE
Dashboard fails to open on Chrome (Android)

### ISSUE THREAD

**Issue by PKGeorgiev** [node-red/node-red-dashboard#250]
Recently I upgraded from 2.1.0 to 2.4.0. Since then the Dashboard will not open on my phone (Android, Chrome). Instead I see this:

![image](https://user-images.githubusercontent.com/9254467/27740591-76208016-5daa-11e7-8237-040391c0c774.png)
* The orange line shows only where the picture was cut by me to reduce its size

And the main menu item does not show:

![image](https://user-images.githubusercontent.com/9254467/27740760-e96dd0d2-5daa-11e7-9fef-0fae8dd202d4.png)

Additional info:

Running on RPi3
Linux 4.9.24-v7+ (raspbian)
node -v: v6.10.3
NodeRed 0.16
Dashboard v2.4
Tested on: Android / Chrome 58.0.30.29.83

**Comment by dceejay** [comment]
have you / can you - edit / update any of the widgets in the flow and then redeploy and then reload te dashboard page ?

**Comment by PKGeorgiev** [comment]
Hmm, I did clear the MAX values of all charts and then re-deployed. After this my dashboard seems to work on my mobile phone.

**Comment by dceejay** [comment]
yes - going from an "old" version to a newer one does sometimes need a redeploy to get to write / fill in some defaults for things it now expects... I thought most were caught ok... must have been something left somewhere.
OK to close ? (unless you have any logs that may help trace it ?)

**Comment by PKGeorgiev** [comment]
I tested dashboard on my mobile a few times - it works well. Please, close this issue.
