### ISSUE TITLE
Exception with Node-RED version: v0.15.3

### ISSUE THREAD

**Issue by yhan2678** [node-red/node-red-dashboard#251]
Hi 

Got an exception when loading a very simple dashboard, my flow is just an inject node linked directly to the graph node. 

I get this error : TypeError: Cannot call method 'emit' of undefined

2 Jul 16:44:49 - [info] Node-RED version: v0.15.3
2 Jul 16:44:49 - [info] Node.js  version: v0.10.29
2 Jul 16:44:49 - [info] Linux 4.4.34-v7+ arm LE

Dashboard : ### 2.4.1: Maintenance Release

Other strange symptom, when editing the graph node properties, I can't enter anything in the size field, same problem when editing the group node, the widht field is locked. I can provide screenshots if you need to. 

Thanks, 

Johan

**Comment by knolleary** [comment]
Can you provide some context to where/when you see that error message?

**Comment by yhan2678** [comment]
Sure, when I create a new flow, simple thing as i'm learning to use the dashboard. 

When I deploy the new flow, the node-red server gets this exception. 

I'm following that tutorial : http://developers.sensetecnic.com/article/a-node-red-dashboard-using-node-red-dashboard/

**Comment by dceejay** [comment]
looks to be an issue with a newer version of one of the dependancies that also upgraded. While I investigate you can install dashboard at a previous level

    cd ~/.node-red && npm i node-red-dashboard@2.3.11

then restart Node-RED

**Comment by yhan2678** [comment]
Thanks, 2.3.11 works as a charm. Let me know when you will fix the dependancie, so I could beta test for you. Nothing is in prod on my side, this is still a learning pod. 

Thanks 

Johan

**Comment by dceejay** [comment]
Hi - I have pushed a version 2.4.2 to master for you to test. You can install is using
    npm i node-red/node-red-dashboard

**Comment by yhan2678** [comment]
Hey Dave,

Thank you !

No problem detected, no errors.

So far, I have tested the sliders, gauges and charts.

Hope that help !

Johan
On Jul 4, 2017, at 7:08 AM, Dave Conway-Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi - I have pushed a version 2.4.2 to master for you to test. You can install is using
npm i node-red/node-red-dashboard

**Comment by dceejay** [comment]
released as 2.4.2
