### ISSUE TITLE
Feature request: Adding the possibility to have dot line chart

### ISSUE THREAD

**Issue by erfansheikhi** [node-red/node-red-dashboard#252]
**Update:** Sorry! I shouldn't have mentioned it in the issue list. Unfortunately, I am not able to delete it.

Hello,
Is it possible to add the possibility to have dot chart like the following image?
![image](https://user-images.githubusercontent.com/29888159/27827697-d6795698-60b8-11e7-95d1-898475ec31ac.png)
It is very useful when subsequent values are the same and the actual position of each value is not known unless the mouse is over that point.
Thank you in advance.

**Comment by dceejay** [comment]
added to 2.4.2

**Comment by erfansheikhi** [comment]
Great! Thank you.
