### ISSUE TITLE
Enhancement: Dynamic Icons with Buttons

### ISSUE THREAD

**Issue by MaxRei-dev** [node-red/node-red-dashboard#254]
I think it would be great to be able to set icons dynamic. 
So if your button is 1x1 you could make for example a mute toggle.
greets Max

**Comment by dceejay** [comment]
You mean a switch ?

**Comment by MaxRei-dev** [comment]
no. because a switch is limited to 2 states. an with a button we could make a 3,4 whatever state type...

**Comment by knolleary** [comment]
If a switch is a stateful button, then perhaps an option would be to allow the switch to have multiple states. Rather than duplicate statefulness in the button widget.

**Comment by dceejay** [comment]
Or use a template like Pete does - https://tech.scargill.net/more-node-red-dashboard-success/

**Comment by dceejay** [comment]
Or you can use the label which can already be dynamic and inject whatever html...

[{"id":"fb9f0ff8.738cf","type":"inject","z":"3ee56046.c933c","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"x":110,"y":760,"wires":[["81a8824e.e3916"]]},{"id":"8c893176.7dea9","type":"ui_button","z":"3ee56046.c933c","name":"","group":"ca294884.9f6a68","order":0,"width":"1","height":"1","passthru":false,"label":"{{msg.payload}}","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":470,"y":760,"wires":[[]]},{"id":"81a8824e.e3916","type":"function","z":"3ee56046.c933c","name":"","func":"msg.payload = '<i class=\"fa fa-camera-retro\"></i>';\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":760,"wires":[["8c893176.7dea9"]]},{"id":"ca294884.9f6a68","type":"ui_group","z":"3ee56046.c933c","name":"Click","tab":"513b7ff4.3de5d","order":1,"disp":true,"width":"5"},{"id":"513b7ff4.3de5d","type":"ui_tab","z":"3ee56046.c933c","name":"Home","icon":"link","order":1}]

**Comment by MaxRei-dev** [comment]
Hi there,
i love both ideas. The label function i did not think about it. Sorry an Thanks for that.
But the Idea a switch to have multible states would also be a good improvement.
Thanks for all.

**Comment by dceejay** [comment]
closed by release of 2.5.0
