### ISSUE TITLE
Switch widget only accepts boolean.

### ISSUE THREAD

**Issue by bartblommaerts** [node-red/node-red-dashboard#257]
When setting the Switch widget to something else then boolean (eg: numeric, on = 1, off = 0). The values revert to true and false automatically when clicking 'done'; type remains numeric and node is set to 'incorrectly configured'.

**Comment by dceejay** [comment]
Do you have any example / step to reproduce this - as it works fine for me...

**Comment by bartblommaerts** [comment]
I'm gonna call ghostbusters... now it works for me too.
Thanks for the fast response though!

**Comment by dceejay** [comment]
well - re-open if and when or maybe

Thanks

We ain't afraid of no ghosts
