### ISSUE TITLE
add custom url pages

### ISSUE THREAD

**Issue by francescoagati** [node-red/node-red-dashboard#258]
hi,
is possible add custom url pages for have in therory unlimited number of dashboard pages

**Comment by dceejay** [comment]
please note - we prefer use of the google mailing list of slack channel for general usage questions or discussion of new features, so that the wider community can help.
You can add links in the dashboard to any page you like.

**Comment by knolleary** [comment]
If you're asking if you can have more than one dashboard, then no, you can only have one dashboard in a node-red instance. A dashboard can have multiple tabs to provide different views, but they are part of a single dashboard.
