### ISSUE TITLE
Unable to update to latest version

### ISSUE THREAD

**Issue by swilson86** [node-red/node-red-dashboard#259]
I am running node-red on Windows 10 and have dashboard 2.3.11 running. I can see in the Pallet Manager that a newer version 2.4.3 is available, but it says it cannot upgrade and that I need so view your documentation. I am hesitant to uninstall the dashboard and reinstall as I have other nodes and goodies that I don't want to disturb. I have also tried **npm update node-red-dashboard** which says it updated to 2.4.3 but when I start node-red it still shows the old version. Here is what I see:

21 Jul 02:36:42 - [info] Node-RED version: v0.17.4
21 Jul 02:36:42 - [info] Node.js  version: v8.2.1
21 Jul 02:36:42 - [info] Windows_NT 10.0.15063 x64 LE
21 Jul 02:36:44 - [info] Loading palette nodes
21 Jul 02:36:45 - [info] Dashboard version 2.3.11 started at /ui

**Comment by dceejay** [comment]
Yes, currently you can't update a node that is in use by using the palette manager. So stop node-red. Go to your .node-red directory and run   npm i node-red-dashboard   then restart node-red

**Comment by swilson86** [comment]
Thanks. I tried that but it still will not upgrade. Here is what I have when stopping node-red, doing the install, and restarting:

C:\Users\Scott\.node-red>npm i node-red-dashboard

> node-red-dashboard@2.4.3 postinstall C:\Users\Scott\.node-red\node_modules\node-red-dashboard
> node fixfa.js

npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

+ node-red-dashboard@2.4.3
added 19 packages and updated 1 package in 7.562s

C:\Users\Scott\.node-red>node-red
22 Jul 02:53:25 - [info]

Welcome to Node-RED
===================

22 Jul 02:53:25 - [info] Node-RED version: v0.17.4
22 Jul 02:53:25 - [info] Node.js  version: v8.2.1
22 Jul 02:53:25 - [info] Windows_NT 10.0.15063 x64 LE
22 Jul 02:53:26 - [info] Loading palette nodes
22 Jul 02:53:27 - [info] Dashboard version 2.3.11 started at /ui

**Comment by dceejay** [comment]
About 3 lines further on it prints out your user directory.  That is where you need to be to run the npm i command.

**Comment by swilson86** [comment]
Something is strange, perhaps only in Windows 10. I tried the npm i node-red-dashboard command after deleting everything off my hard drive including node-red, node.js, the path, rebooting, reinstalling everything and npm i node-red-dashboard made a <JUNCTION> of the what was before <DIR>node-red-dashboard as follows:

----------Before:
07/22/2017  02:22 PM    <DIR>          negotiator
07/22/2017  02:29 PM    <DIR>          node-red-contrib-alexa-home-skill
07/22/2017  03:00 PM    <DIR>          node-red-dashboard
07/22/2017  02:22 PM    <DIR>          node-red-node-openweathermap
07/22/2017  02:22 PM    <DIR>          node-red-node-ping

---------After running npm i node-red-dashboard

C:\Users\Scott\.node-red\node_modules>dir n*
 Volume in drive C has no label.
 Volume Serial Number is 829C-C9D9

 Directory of C:\Users\Scott\.node-red\node_modules

07/22/2017  02:22 PM    <DIR>          negotiator
07/22/2017  02:29 PM    <DIR>          node-red-contrib-alexa-home-skill
07/22/2017  03:01 PM    <JUNCTION>     node-red-dashboard [C:\Users\Scott\.node-red\node_modules\node-red-dashboard]
07/22/2017  02:22 PM    <DIR>          node-red-node-openweathermap
07/22/2017  02:22 PM    <DIR>          node-red-node-ping

**Comment by dexterlabora** [comment]
I'm running into the same issue where I can't update a custom node. Installing via the command line isn't an option because it's a hosted solution (in Heroku). I was hoping the palette manager would have had support for this. Any plans to update this?


---
An update for this node is available, but it is not installed in a location that the palette manager can update.

Please refer to the documentation for how to update this node.
---

**Comment by dceejay** [comment]
as it says it's not installed in a place where the palette manager has access to... so you will have to do it manually. Eg if it's installed globally then we would need root access and that is bad security etc. - If it's installed via palette manager in first place (ie not as root and into ~/.node-red ) then it can be upgraded as long as it's not in use.

**Comment by dexterlabora** [comment]
Thanks. I think its the way the Heroku method stores the settings in an
attached database. Updating the package version manually in the settings
JSON worked.
I was able to update the node via palette in a local install, which
prompted me to restart Node-RED. Too bad that's not an option in the editor.


Cheers,
