### ISSUE TITLE
not in npm

### ISSUE THREAD

**Issue by stefanoco** [node-red/node-red-dashboard#26]
It seems to me that the package can't be installed with

```
cd ~/.node-red
npm install node-red-dashboard
```

because it's not in the npm repo

**Comment by knolleary** [comment]
Please see the first line of the readme.

We'll hopefully be publishing the first stable release next week.

**Comment by dceejay** [comment]
If you want to play with it you can install using

    npm i node-red/node-red-dashboard

**Comment by stefanoco** [comment]
Oh sorry didn't notice - I'll try manual install, hopefully this is a solution to the many demos we need to prepare using html / js. Thanks!

**Comment by stefanoco** [comment]
...yes! Successfully modified Dockerfile for node-red so that UI is included. Thanks a lot
