### ISSUE TITLE
Data pushed to invisible items

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red-dashboard#260]
Hi Dave,

Suppose you have a dashboard with two tabsheets: one with sensor graphs, and one with camera images.  Until now I thought that only data was being pushed to the widgets on the tab that is currently visible.

However, today I saw that the data of ALL widgets is being pushed to the browser (undependent if the widgets are visible or not).  For example when my sensor tab is active, my camera images are still being pushed every second:

![image](https://user-images.githubusercontent.com/14224149/28456604-3a0947e8-6e03-11e7-868c-4c6e17335530.png)

Since I have a rather limited connection to my smartphone, this is a major issue for me (since the camera images contain lots of data).  Until now I had a tab without data as default, and I only switched to the camera tab if I wanted to retrieve camera images.  However, my data limit was very fast exceeded ;-(

Is this a know issue already?  If you want me to analyze it in more detail, please let me know...  I had a simular issue some years ago, and I worked around by communicating tab switches to the server: the server needed to store the active tab name for each push connection.  Data was only being pushed to widgets on the visible tab sheet.  Don't know how this works in NodeJS/Angularjs.

Not an easy one, I suppose ...

Kind regards,
Bart

**Comment by knolleary** [comment]
That is how it works. If we stopped passed data to the dashboard for widgets that aren't on the active tab then, for example, charts would get gaps in their data.

You can use the ui_control node to know which tab is active at any time, and put a check into your data-intensive flows to only pass msgs to their dashboard widgets it the appropriate tab is active.

**Comment by bartbutenaers** [comment]
Hi Nick,

the gaps would indeed become an issue.  So instead of adding functionality to the dashboard nodes (to ignore messages arriving for invisible widgets), I have to add functionality to my flow (to only send data to dashboard nodes referring to visible nodes).  I'm afraid that the latter solution makes my flow a little bit harder to maintain: if I move a widget to another tab, I also have to update my flow logic to send data to the 'new' tab name if visible...  Or didn't I understand your solution correctly?

But for the time being, I created a simple test flow to determine which tab is active:
![image](https://user-images.githubusercontent.com/14224149/28459961-09483f62-6e10-11e7-8756-877037aadecb.png)
```
[{"id":"c42441d.3e505c","type":"ui_ui_control","z":"d0d4f76e.209b68","name":"ui control","x":300,"y":640,"wires":[["c3c22ca8.e923c"]]},{"id":"c3c22ca8.e923c","type":"debug","z":"d0d4f76e.209b68","name":"tab name","active":true,"console":"false","complete":"true","x":480,"y":640,"wires":[]}]
```
When I press the menu item (1) and I select another tab (2), **_no message_** (containing the tab name) arrives at the output of my ui_control node:
![image](https://user-images.githubusercontent.com/14224149/28460125-f4d4183e-6e10-11e7-8cbf-1986987ea32f.png)

I assume I will have to use it in another way?

P.S. If you prefer that I ask this question on the forum (and close this issue), please let me know ...

Thanks !!
Bart

**Comment by dceejay** [comment]
You should get a message like
![image](https://user-images.githubusercontent.com/5375409/28662909-ad49a496-72b3-11e7-8645-26293046460d.png)

**Comment by bartbutenaers** [comment]
Hi Dave,

I did an npm uninstall and a afterwards a new install of my dashboard, and now it indeeds sends the output message at a tabswitch.  

Thanks for your assistence !!

Bart
