### ISSUE TITLE
Gauge label not changing

### ISSUE THREAD

**Issue by jprovan** [node-red/node-red-dashboard#262]
I am working with the Gauge widget. I am sending a change to the topic with a value. If the value is the same as is currently displayed, the label will not change. If I change the value, I can change the label.  So, the value must be different in order for the label to be changeable.

**Comment by dceejay** [comment]
yes - currently we only send data if there is a change in value. Having only recently allowed labels to be changed at all - didn't expect them to change on their own. What is the use case where labels change more than data ?

**Comment by jprovan** [comment]
Actually, it's a demo for a convention....and I am learning the dashboard. I change the label whether an audio input is muted or not. It would be really great to be able to change the label based on condition to reflect what the gauge is showing.

**Comment by dceejay** [comment]
If it's muted can you not also set the value to 0 ? Or disable the whole widget ? 
But yes, hear you. Won't be an immediate fix.

**Comment by jprovan** [comment]
I will do some kind of workaround. I just thought that I would report what I had found.

**Comment by jprovan** [comment]
I was able to get it to do what I wanted it to by decrementing the value by 1...sending the message...waiting 1 millisecond...then sending the original message. At 1 millisecond, the UI doesn't even flicker. Thank you for your insight.

**Comment by dceejay** [comment]
Good shout. The trigger node could help do that

**Comment by jprovan** [comment]
I guess that I could have used the trigger. I went old school though.

function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}

function clone(obj) {
    if (null === obj || "object" != typeof obj) return obj;
    var copy = obj.constructor();
    for (var attr in obj) {
        if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
    }
    return copy;
}

var work;

msg.topic = msg.payload.heading;

try
{
    work = msg.payload.volume.$set.volume;
}
catch(Error)
{
    try
    {
        work = msg.payload.volume;
    }
    catch(Error)
    {
        work = 0;
    }
}

var msg1 = clone(msg);

msg1.payload = work - 1;
node.send(msg1);

sleep(1);
msg.payload =  work;

return msg;

**Comment by dceejay** [comment]
Well (now seriously off topic), if you are using a function to return two messages then no need for the delay. And can return them both in one go.

return [[{payload:0},msg]];

to return a 0 followed by the original msg

**Comment by jprovan** [comment]
That actually works better and I don't have to worry about blocking the whole system( even if it's only 1 millisecond). Thank you.
