### ISSUE TITLE
Enhancement: split ui to multiple users/pages...

### ISSUE THREAD

**Issue by gorec2005** [node-red/node-red-dashboard#263]
Hi!
first - thank you for good tool (i mean ui)!
may be possible split one ui between multiple user's ( with different auth credentials )?
and second thing:
if i use multiple chart's with a lot of point ui page load long time ( how load data in one/all chart's only by request?)

**Comment by dceejay** [comment]
Hi, please note that as per our contribution guidelines we prefer discussion of new features on the google mailing list, or slack channel before being made into an issue. 

1) Currently the ui does not support multiple users.
2) Chart performance is a known issue (#144) - but it can be improved by being aware and reducing the amount of data being sent - either by reducing the number of points - or limiting the time period. - Or you can preprocess the data up front to reduce it in some other way. (eg filtering / smoothing)

**Comment by gorec2005** [comment]
sorry...

**Comment by dceejay** [comment]
Not a problem. Just not an issue  :-)
