### ISSUE TITLE
UI group in layout 'Tabs & Links' is not consistent with  'Edit template node' Group

### ISSUE THREAD

**Issue by Dowster64** [node-red/node-red-dashboard#264]
Hi All,
With node-red V0.17.3 and dashboard v2.4.1 and with node-red v0.16.2 and dashboard 2.3.11 I have one 'lost' widget and others that do not show their actual group when the edit template node is opened.  (See screen shot).  The UI elements are in subgroups that have been created to make a larger UI 'superwidget' that we can reuse. 
Also the ui_groups like "0353" and "0364" are not available from the Group drop down selector in the node properties area. So I can't manually re-assign them.  I was able to drag and drop from the group 'Timmy' as a couple of other ui controls had ended up there but still the connction between the node properties and the layout area seems broken.

Note - thinking back - the original groups were created from the main flow. The nodes in those groups are now in subflows (as are some new nodes).  The UI nodes in the group 'Timmy' are on the main flow.  I had tried with an earlier release to use UI nodes in a subflow but it didn't work (or more truthfully - I couldn't get it to work).  My colleague did create  subflows with UI nodes a few months later with initially no problems.  Later he added the DL donut tab and group 'Timmy' to the main flow.

![image](https://user-images.githubusercontent.com/13059464/28858277-d2d4ea16-7792-11e7-8b70-ca0df4ef8bc0.png)

Thanks for any solutions ,
Steve
(P.S - Slightly embarrassed that our DLine Donut tab test group is called Timmy.  - At least it's called Dave on the v0.16.2 test install...)

**Comment by dceejay** [comment]
May be a duplicate / related to #66

**Comment by Dowster64** [comment]
Hi @dceejay ,
If this is related to #66 Can you explain where I can find how to ensure that the ui_group types and the tab are made global?  I have explored the 'show more' utility for the nodes and used the gear icon to go to the parent object (tab) but they change when clicked and then end up under the incorrect tab:
before click:
![image](https://user-images.githubusercontent.com/13059464/28948873-215c3062-78fc-11e7-8ed9-eb003c0129fa.png)
after click gear:
![image](https://user-images.githubusercontent.com/13059464/28948702-e3363072-78fa-11e7-83ee-6ddd260eaf50.png)
Thanks for your help,
Steve

**Comment by dceejay** [comment]
You can't. That is why it's an open issue and needs to be investigated.

**Comment by dceejay** [comment]
I believe this was fixed by 6c0efb942efa8091e872654fda4161fc416d81af
