### ISSUE TITLE
Keyboard / Numpad for Touchscreen input

### ISSUE THREAD

**Issue by BigBang0502** [node-red/node-red-dashboard#265]
Hello, 

one thing that I miss is an input for characters and numbers. 

I hope you can develop a new flow for this =) 

Thank you for the Dashboard projekt =)

**Comment by dceejay** [comment]
We prefer requests for new features to be raised and discussed on the mailing list or slack channel first leaving this for issues with existing code. 

We rely on the operating system to provide basic input types
