### ISSUE TITLE
Custom Favicon & Logo for Dashboard

### ISSUE THREAD

**Issue by ram1505** [node-red/node-red-dashboard#271]
How can I provide a custom favicon and a custom logo for my dashboard?

**Comment by dceejay** [comment]
we prefer generic how-to questions on the mailing list or slack channels (saw it there also - so no need to cross post)...

Right now the simplest way is to replace the icons in your ~/.node-red/node_modules/node-red-dashboard/dist directory… and then edit the dashboard.appcache to also point to the new files.
