### ISSUE TITLE
button passes null

### ISSUE THREAD

**Issue by dingausmwald** [node-red/node-red-dashboard#272]
Guess this is a bug. When payload is sent to a button, the output is null. When marked to pass through its input or not. Tried to send value to a button and release it only when pressing it. Acts weird. Seems like the button cant translate the payload that is send to it or im missing the setting/code for the payload field.

**Comment by dceejay** [comment]
How is the button configured ? It will output whatever it is configured to do so. It wil not output what it is sent. Do you have a small example flow that shows the problem?

**Comment by dingausmwald** [comment]
When it will not output what it is sent, what is the option "If msg arrives on input, pass through to output:" for? There the output is "null" too. When i send something to a text input for example, the option "If msg arrives on input, pass through to output:" passes the input directly to the output. For the button theres always null as payload, the topic and other options are ok.

got an example: `[{"id":"613f2bc.cc393d4","type":"ui_slider","z":"154ee435.3966ec","name":"","label":"slider","group":"d96b5dbc.03afb","order":0,"width":0,"height":0,"passthru":true,"topic":"","min":0,"max":10,"step":1,"x":306,"y":302.8000020980835,"wires":[["7310af0a.6f2a9"]]},{"id":"7310af0a.6f2a9","type":"ui_button","z":"154ee435.3966ec","name":"","group":"d96b5dbc.03afb","order":5,"width":"2","height":"1","passthru":true,"label":"Go","color":"","bgcolor":"","icon":"","payload":"","payloadType":"num","topic":"watt","x":515.0001010894775,"y":275.00001430511475,"wires":[["c68061d4.8ee64"]]},{"id":"c68061d4.8ee64","type":"debug","z":"154ee435.3966ec","name":"","active":true,"console":"false","complete":"true","x":704.4000091552734,"y":226,"wires":[]},{"id":"d96b5dbc.03afb","type":"ui_group","z":"","name":"Tank Steuerung","tab":"f568cb2e.c757e8","order":2,"disp":true,"width":"6"},{"id":"f568cb2e.c757e8","type":"ui_tab","z":"","name":"Tank Steuerung","icon":"home","order":"1"}]`

**Comment by dceejay** [comment]
The node sends whatever payload it is configured to do so (including in this case null as you have not configured anything in the button payload field). The pass though to output allows a flow to trigger the button as if it had been pressed...  by disabling that you can still feed it things like `msg.enabled` (= false) - and disable the button - but without triggering any output.

The behaviour you want can be created by saving the slider output in a flow variable using a change node - the setting the button to send that - as below

`[{"id":"75ba075.e5813f8","type":"ui_slider","z":"df030567.d1ff38","name":"","label":"slider","group":"b39382f0.89d3e","order":0,"width":0,"height":0,"passthru":true,"topic":"","min":0,"max":10,"step":1,"x":110,"y":500,"wires":[["a488b541.fea548"]]},{"id":"a488b541.fea548","type":"change","z":"df030567.d1ff38","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"slider","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":210.5,"y":561,"wires":[["39433376.16e8bc"]]},{"id":"39433376.16e8bc","type":"ui_button","z":"df030567.d1ff38","name":"","group":"b39382f0.89d3e","order":5,"width":"2","height":"1","passthru":false,"label":"Go","color":"","bgcolor":"","icon":"","payload":"slider","payloadType":"flow","topic":"watt","x":330,"y":620,"wires":[["a0ca761e.3278f8"]]},{"id":"a0ca761e.3278f8","type":"debug","z":"df030567.d1ff38","name":"","active":true,"console":"false","complete":"true","x":528.4000091552734,"y":643.1999979019165,"wires":[]},{"id":"b39382f0.89d3e","type":"ui_group","z":"","name":"Tank Steuerung","tab":"73a22eb.5b12cd","order":2,"disp":true,"width":"6"},{"id":"73a22eb.5b12cd","type":"ui_tab","z":"","name":"Tank Steuerung","icon":"home","order":"1"}]`
