### ISSUE TITLE
Reset theme to default

### ISSUE THREAD

**Issue by vallik800i** [node-red/node-red-dashboard#273]
If i want to change the theme I change the Colour of the light theme.
After deploying that, the Colour is changed and e.g. the title is changed, too.
But if I restart node-red or deploy the whole project, the theme and title etc. get resetted to default...

I am using a Raspberry Pi and node-red 0.17.5

Thanks in advance
Valentin

**Comment by dceejay** [comment]
We prefer general how-to questions to be raised in the google mailing list or on the slack channel so the widest audience can step in and help. Once you have deployed the flow the scheme should stay set. Which type of deploy did you do ? full ? or flow only ? or nodes only ?

**Comment by vallik800i** [comment]
If I do a flow only deploy, it runs. But if I do a full deploy it gets resetted to default

**Comment by knolleary** [comment]
One possible explanation is that you have multiple dashboard base config nodes. Long story short, open the configuration nodes sidebar in the editor and see if you have more than one dashboard base node listed. If you do, double click on each and delete it - leave just one.

**Comment by vallik800i** [comment]
Where do I find the configuration nodes sidebar?

**Comment by vallik800i** [comment]
Yes, that was the error.
Thanks!

**Comment by knolleary** [comment]
Great!

**Comment by T0T4R4** [comment]
Same problem on dashboard v2.17.1 running on NR 1.0.2 (even with 0.20.5)
I have only one ui_base, still that happens randomly.

**Comment by justinSCS** [comment]
I am as well.  I noticed the other cofig nodes can be found in the flow json file, however I can't find a "ui_base" node anywhere in the json.  Should there be one?

**Comment by dceejay** [comment]
yes - once deployed with some dashboard nodes the ui_base should be automatically generated and saved.

**Comment by justinSCS** [comment]
ok.  I have all of the "ui_group" and "ui_tab" nodes in the json flow, but no ui_base.  The settings hold for a deploy or 2 but then it's like the cache is cleared and it goes back to the default scheme/title.  I went on Node-Red's forum to see if some other people who posted their flows had a ui_base node in the flow when it came to regarding the dashboard, and I don't see any ui base nodes in those posts that I could find. (Although I do know sometimes they are very stringent on what they post). Should I raise an issue or would you be willing to reopen this one?

**Comment by dceejay** [comment]
Are you sure this is the complete flow file you are looking at and not just an export of that tab or set of nodes ? Are you able to share the actual file with us ? or you can dm me at dceejay  at gmail
