### ISSUE TITLE
Setting button color/bgcolor via msg not working?

### ISSUE THREAD

**Issue by cakefornoreason** [node-red/node-red-dashboard#275]
In the Sept 3 commit, I was excited to see the ability to set the the button color and background color via msg, but I can't seem to get it working.

It's clear that you can pass variables that way, as setting the button label works for me, but color and background don't appear to work. I'm sending the color as a "#000000" text string defined as msg.color by the function node before the button in my flow, and I've set {{msg.color}} in the color field of the button node itself, but no luck.

Am I using the using the feature incorrectly or is something actually not working?

Glad to provide a flow sample if needed. Thanks!

**Comment by Paul-Reed** [comment]
I posted this in Slack about 10 minutes ago complete with an example flow...

**Comment by cakefornoreason** [comment]
I was actually just about to join the Slack group myself. I'll check it out. Thanks!

**Comment by dceejay** [comment]
working example

[{"id":"bf0c0177.5793c","type":"inject","z":"df030567.d1ff38","name":"","topic":"","payload":"go","payloadType":"str","repeat":"","crontab":"","once":false,"x":110,"y":1220,"wires":[["b948c437.9ff538"]]},{"id":"b948c437.9ff538","type":"trigger","z":"df030567.d1ff38","op1":"red","op2":"green","op1type":"str","op2type":"str","duration":"5","extend":false,"units":"s","reset":"","bytopic":"all","name":"","x":380,"y":1160,"wires":[["af6dbe20.78564"]]},{"id":"af6dbe20.78564","type":"change","z":"df030567.d1ff38","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"colour","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":1260,"wires":[["1dd1eaa.3dddf15","917d8db7.df7e7"]]},{"id":"1dd1eaa.3dddf15","type":"ui_button","z":"df030567.d1ff38","name":"","group":"4e7edda4.417004","order":0,"width":"2","height":"2","passthru":false,"label":"","color":"{{msg.colour}}","bgcolor":"#525252","icon":"fa-shower fa-4x","payload":"a","payloadType":"str","topic":"","x":210,"y":1160,"wires":[["b948c437.9ff538"]]},{"id":"917d8db7.df7e7","type":"debug","z":"df030567.d1ff38","name":"","active":true,"console":"false","complete":"true","x":490,"y":1220,"wires":[]},{"id":"4e7edda4.417004","type":"ui_group","z":"","name":"Group 3","tab":"d7901f40.2659d","order":3,"disp":false,"width":"6"},{"id":"d7901f40.2659d","type":"ui_tab","z":"","name":"Charts","icon":"dashboard","order":2}]

**Comment by cakefornoreason** [comment]
I just tried the example flow you used above, but it still isn't working for me. I tried it on both Safari and Chrome on my Mac and neither showed the programmed color change. What browser were you using?

**Comment by Paul-Reed** [comment]
Let's stick to one channel!
I see you've also posted is Slack....
I'll reply in Slack.
