### ISSUE TITLE
Connection Lost message not disappearing

### ISSUE THREAD

**Issue by colinl** [node-red/node-red-dashboard#278]
Running 2.4.3 with node-red 0.17.5 and node 6.11.3 if the dashboard loses the connection then a Connection Lost message is displayed in the browser. When the connection is restored the message remains. The dashboard items work correctly once the connection is restored but the message remains.

I believe this started after a recent upgrade, but not certain.

**Comment by dceejay** [comment]
Hi - can you try the latest 2.5.0 version of the dashboard please... While nothing specifically has been addressed in that area during the upgrade we haven't seen that issue locally. If it's still a problem - what platform(s) OS are you running on ? Is this all local on one machine ? Is there a firewall in the way ? etc ?

**Comment by colinl** [comment]
Hi, no change with dashboard 2.5.0.
I am seeing it on Firefox on a PC (Ubuntu) and on Android. This is all on my local network with no additional firewalls.
The fact that only I am seeing it suggests it is something to do with my flow or setup. I only have one machine running the dashboard at the moment, and it is in 'production' use so I can't mess with it too much. I will try to get another one setup and see if I can replicate it.
I do see a number of messages of this type in the browser console, I don't know whether they are significant:
Error in parsing value for 'color'.  Declaration dropped.
Error in parsing value for 'background-image'.  Declaration dropped.
When I disconnect the network I see
The connection to ws://xxx.local:1880/ui/socket.io/?EIO=3&transport=websocket&sid=rIRenAJGUSatNcWVAAAN was interrupted while the page was loading.  socket.io.js:3:1012
I don't see a re-connection message in the log when it reconnects. The dashboard panel flashes as it refreshes and then it starts working, but the red connection lost message stays on screen.
In the browser on the PC the message appears in the top right hand corner over the blue bar, is that where it should be?

**Comment by colinl** [comment]
I can confirm it is something specific about the setup on the pi that exhibits it, I have setup another system with the same s/w versions and it is ok. I suppose I shall have to find time to put, as far as possible, the same flows on that one and see what happens then.

**Comment by dceejay** [comment]
closing as not a general probem - but happy to re-open if anything specific can be identified.

**Comment by colinl** [comment]
I have done some debugging and this is what I am seeing:
I am running the browser client on one machine and the node-red server on another.
I start node-red and open the dashboard ui on the client.
When I disconnect the network connection then main.js events.on('disconnect'..) is called and the connection lost message is shown.
However few seconds later events.connect(..) is called even though the network is not yet reconnected. This calls finishLoading but does not pass down the path that clears the message.
When I then reconnect the network cable the ui starts working but events.connect is not called again so the message is not cleared.
I am a bit stumped as to where to go next.

**Comment by colinl** [comment]
I now understand more about what was happening in my previous post, I was being stupid as I had the wifi switched on so as soon as it disconnected it reconnected via the wifi, so that explains the reconnection. I have started again with the wifi off and this is what happens.
On removing the network connection events.on('disconnect'..) is called and the message is shown.
On reconnect events.connect(..) is called via the if (!inNan(prevTabIndex))..) route
In finishLoading main.selectedTab is an object but typeof(main.selectedTab.theme is undefined so $mdToast.hide is not called.
I am wondering whether hide should actually be outside the if statements.

**Comment by dceejay** [comment]
well - does it work "correctly" if moved outside the if ?

**Comment by colinl** [comment]
Yes it does work if outside the tests. Any idea why I seem to be the only one seeing it (or at least reporting it)? I don't know what the tests are doing so don't know why my system is different.
I presume you don't need me to do a PR for this as it is trivial. I will if you prefer.

**Comment by nielsnl68** [comment]
You are not the only one seeing this. I just not bother to say it, earlier.

**Comment by dceejay** [comment]
Indeed. No idea.  But yes already patched in my version
