### ISSUE TITLE
Lost ui-switch and ui-button nodes functionality on partial deploy

### ISSUE THREAD

**Issue by zapicoj** [node-red/node-red-dashboard#279]
I'm running node-red 0.17.5 and dashboard 2.4.3 on a RPi3. I have 3 flows getting mqtt data from devices and sending commands from button and switch nodes. The web page is working fine, but sometimes I lost buttons and switches functionality (they stay on the page but don't work correctly, I connected a debugger at the nodes output and they produce no output when clicked). They stop working, but the rest of the page  still works (I can receive new data from mqtt and visualise it on the gauges and charts). The only way I found to revive those input nodes is killing the node-red process and restarting it again. After some minutes I lost again the buttons and switches functionality. (:
I have tried of reducing number of ui nodes (have around 15 switches and 6 buttons) just in case, I also changed the RPi3 but no way.
Switches are used displaying the input state (coming from mqtt), the output send a payload = "1" to a specific topic when clicked. The remote device send a feedback to turn On the switch state (when it works).
I have no idea what kind of issue could cause this rare dashboard behaviour.

Does anyone have any idea or recommendation where to start looking for the problem ?
Appreciate your support.
JZ

**Comment by dceejay** [comment]
Hi - can you try the latest 2.5.0 version of dashboard. If it still fails can you share some of the flow with us ?  When you say sometimes.... how often ? What provokes it ?

**Comment by zapicoj** [comment]
Hi Dave, thank you for your response.
I tried with the last dashboard upgrade 2.5 and I got the same issue. 

The good news is that I could isolate and reproduce the problem.
I am attaching one simple flow: two switches and one chart node. The steps to reproduce the issue are the following:
1. go to web page and verify that the switches state change when clicked.
2. go to the editor and open the chart node window, change the label field to whatever word or character you want
3. close the chart window and now go to deployment menu and select “Modified Nodes”
4. apply the deploy
5. go to the web page and click the switches. (in my case they don’t change the state. They don’t work)
6. Now, go to the editor and change the label again.
7. if now you deploy it with “Modify Nodes” nothing happens in the switches ( they don’t work). So go to the deploy menu and change to “Full”
8. Now do the deployment
9. go to the web page and click on the switches (in my case they work again).
Try to reproduce this on your side.
I did the tests in two different raspberry and the behavior is the same.

Thank you
JZs

the flow:
[{"id":"52cb81c4.60934","type":"ui_switch","z":"49316ea3.45ba5","name":"","label":"switch 1","group":"287fc64a.a1490a","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":598.333333333333,"y":486.6666666666664,"wires":[[]]},{"id":"c92b26ba.1e99e8","type":"ui_switch","z":"49316ea3.45ba5","name":"","label":"switch 2","group":"287fc64a.a1490a","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":600,"y":640,"wires":[[]]},{"id":"15506b6b.1fc8c5","type":"ui_chart","z":"49316ea3.45ba5","name":"","group":"287fc64a.a1490a","order":0,"width":0,"height":0,"label":"bien","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":1191.666666666666,"y":563.333333333333,"wires":[[],[]]},{"id":"287fc64a.a1490a","type":"ui_group","z":"","name":"Relays","tab":"a96a64c9.616d48","order":4,"disp":true,"width":"3"},{"id":"a96a64c9.616d48","type":"ui_tab","z":"","name":"General","icon":"dashboard","order":1}]

**Comment by dceejay** [comment]
aha - yes can reproduce that. thanks.

**Comment by waqaslam** [comment]
The same issue is discussed here too:
https://groups.google.com/forum/#!topic/node-red/JP6ZmsGql2M

**Comment by dceejay** [comment]
OK - found it - actually it is/was a bug in the chart node that was causing the others widgets to fail...
so thanks for spotting it.
