### ISSUE TITLE
Values shown when navigating the UI

### ISSUE THREAD

**Issue by stefanoco** [node-red/node-red-dashboard#28]
I didn't find an obvious solution to this: when navigating the UI, the panel is built according to the flow but the values shown inside each widget are coming up only as soon as messages reach them (according to the wiring etc). I would find it useful some async event reacting to "someone is loading the page". Not sure if this would mess everything but think of some value coming from MQTT each hour, would be nice to have "last known good value" shown. Having that event I could save useful values and trigger sending them to the UI when the page gets loaded.

**Comment by dceejay** [comment]
currently the chart widget has a second output that sends a message "restore" when the connection to the backed is restored so the values can be resent - this can be used to drive other widgets if you like.
But yes - more generally it would make sense (in case you don't have a gauge on the page...)

**Comment by stefanoco** [comment]
...back on this after so much time, I'm finding that "restore" seems not be working. I get a message only while saving a new flow, not while navigating the UI, is this the intended behaviour?

**Comment by dceejay** [comment]
Hi,
the existing behaviour is (has always been) that restore is only sent at startup (or redeploy). And as such is an event from the server to itself.
I want to move this out from this node anyway (probably to the ui_control node) - as I think it makes sense across the whole dashboard... - but yes open to ideas what the desired behaviour should be.

**Comment by dceejay** [comment]
commit eccd70a52f46ef3aa89ecbaddd966551f7fe1149 
The ui_control node now emits connect and lost messages for every client connection that can be used to trigger anything else needed on load of a page by a client.
