### ISSUE TITLE
Node-Red Crashs after Switching with this issue after the updating on Version: 2.5.0

### ISSUE THREAD

**Issue by heydemar** [node-red/node-red-dashboard#280]
If i switch, Node-Red Crash with this issue. I must reboot Node-Red!!!

20 Sep 08:10:16 - [error] [link in:17e3e3ee.592d94] RangeError: Maximum call stack size exceeded
20 Sep 08:10:16 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:16 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:16 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:16 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:16 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:17 - [error] [link out:e0263b6f.e1cbd] RangeError: Maximum call stack size exceeded
20 Sep 08:10:17 - [error] [template:Relais 1 (Pin5) An] Maximum call stack size exceeded
20 Sep 08:10:17 - [error] [template:Relais 1 (Pin5) An] RangeError: Maximum call stack size exceeded
20 Sep 08:10:19 - [error] [ui_switch:e17ad07a.d64748] RangeError: Maximum call stack size exceeded

**Comment by dceejay** [comment]
After switching what ? It looks like you have a loop. Is the output fed back to the input ? Can we see part of the flow ?

**Comment by heydemar** [comment]
This is my flow, i switch a 433Mhz Device, an if i Switch with 1 or 0 the Node-Red Crash. 
If i delete the wiring to the Dashboard-Switch everything is ok. 
![2017-09-20_09-20-58](https://user-images.githubusercontent.com/5207948/30631619-1c88d654-9de5-11e7-8938-fc9824a6ecbb.jpg)

**Comment by dceejay** [comment]
do you have the passthru unticked ? That stops feedback loops
![image](https://user-images.githubusercontent.com/5375409/30634502-3dcc8930-9de7-11e7-9456-65cd525b440e.png)

**Comment by dceejay** [comment]
any update on this ?
