### ISSUE TITLE
Inject node "at specific time", time box behaves incorrect.

### ISSUE THREAD

**Issue by MatsKarlsson** [node-red/node-red-dashboard#282]
NR 0.17.5 (and previous versions also) recently updated.

- Add a `inject node`
- Edit node, set `Repeat` to `at a specific time`
- Click the up/down arrows on time-text box. 
- Set focus to the textbox press up/down arrow on keyboard.

always subtracts 1h and moves 1 min in the right direction (+ or -) 

How I would like it: up/down arrow (keyboard) moves Hour or Minute depending on where the caret is.
clicking up/down arrows should perhaps add/remove 10min?

**Comment by knolleary** [comment]
Hi @matskarlsson 

This repo is for node-red-dashboard. The Inject node is a core node in the main project repo: https://github.com/node-red/node-red

Please reopen over there. Thanks!
