### ISSUE TITLE
Chart node (v.2.5.0) Series legend

### ISSUE THREAD

**Issue by zapicoj** [node-red/node-red-dashboard#283]
Hi Dave,
Legend of series in 2.5.0 version is showed on the left side of the chart, which in some cases takes an important area for drawing graphics. Is there any way to get the legend on top as in 2.4.3 ?
 
Additional comment (for your consideration): the coloured rectangles in the legend, in my opinion, could be smaller (as in the dynamical legend when mouse is over the chart with multilines), that way we would have more space for texts.

thank you,
JZ

**Comment by dceejay** [comment]
Good spot  - didn't realise it had moved... 
and will have a go at shrinking rectangles.
will push fix to master soon (but not npm)
