### ISSUE TITLE
Filling chart with stored data

### ISSUE THREAD

**Issue by DJWassink** [node-red/node-red-dashboard#284]
I tried to following the instructions from the guide in: https://github.com/node-red/node-red-dashboard/blob/master/Charts.md#stored-data

However if I try a chart with the data snippet:
```js
[{
"series": ["A", "B", "C"],
"data": [
    [{ "x": 1504029632890, "y": 5 },
     { "x": 1504029636001, "y": 4 },
     { "x": 1504029638656, "y": 2 }
    ],
    [{ "x": 154029633514, "y": 6 },
     { "x": 1504029636622, "y": 7 },
     { "x": 1504029639539, "y": 6 }
    ],
    [{ "x": 1504029634400, "y": 7 },
     { "x": 1504029637959, "y": 7 },
     { "x": 1504029640317, "y": 7 }
    ]
],
"labels": [""]
}]
```

I get the error: 
```
TypeError: Cannot read property 'data' of undefined
    at app.min.js:1077
    at m.$digest (app.min.js:167)
    at m.$apply (app.min.js:170)
    at app.min.js:183
    at f (app.min.js:68)
    at app.min.js:71
```

This issue is actually pretty easy to reproduce by checking the example on the same page: https://github.com/node-red/node-red-dashboard/blob/master/Charts.md#example

If you import that flow and click on the `TIME LINE 1` button you will get exactly the same error.

Has the API been changed in the meantime or is this a bug?
I am using node-red v0.17.5 and node-red-dashboard@2.5.0

**Comment by Paul-Reed** [comment]
The format has changed, see
https://github.com/node-red/node-red-dashboard/blob/master/Charts.md
In the 'chart' node, there is an option to select the previous way of
formatting data, but probably a good time to embrace the new format.

**Comment by DJWassink** [comment]
Ahh right I get it now, in the example flow the chart had the `use deprecated` data format selected. Unchecking this made the chart work at once!

Thanks a ton!

**Comment by dceejay** [comment]
thanks for noting it - will try to catch that a bit better.
