### ISSUE TITLE
Template node outputs incoming msg?

### ISSUE THREAD

**Issue by clickworkorange** [node-red/node-red-dashboard#285]
I have a template node that displays the payload of incoming messages (a base64 encoded image). I want to add a button to this template which sends a message to trigger an update of the image. This works, but once the output of the template node is connected to something, every incoming message is repeated on the output - including the images themselves.

```
<img src="data:image/jpg;base64,{{msg.payload}}" style="display: block; width: 296px; height: 222px;" />
<button class="md-raised md-button" type="button" ng-click="send({payload:0})" style="position: absolute;">
	<ng-md-icon icon="refresh"></ng-md-icon>
</button>
```
How do I get the template node to only send messages when asked to?

**Comment by dceejay** [comment]
In general as per the participation guidelines, we prefer "how-to" type question on the google mailing list or slack channel so the widest audience can help, leaving the issues list for things that are potentially broken.

maybe the node edit config can help ?
![image](https://user-images.githubusercontent.com/5375409/30781857-a623115e-a11e-11e7-986f-bee3a6a89ccd.png)

**Comment by clickworkorange** [comment]
Ooops.
