### ISSUE TITLE
Audio out: TTS voice is different on different OS.

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#293]
Hi! I noticed that the available voices change on different systems resulting in different languages. For example, if someone with a windows PC connects to my dahsboard he will hear English accent, if on Mac, he will hear a english spoken with a spanish accent.

**Comment by dceejay** [comment]
The voices are what are built in by the various browser vendors and outside of my control. Unless they all decide to co-operate I'm not sure what I could do about it.

**Comment by dceejay** [comment]
Actually - I have a cunning plan...
