### ISSUE TITLE
ui_gauge: dynamically set min/max values

### ISSUE THREAD

**Issue by larkolab** [node-red/node-red-dashboard#295]
Hello,

How difficult would it be to be able to dynamically configure the gauge node from the flow for its min and max values, through the input message?
That would be useful to report a status for datat which can have different range at a point of time.

I'm not a javascript programmer, I've looked into the code, but seemed not obvious to me how to add it.

Anyone could help me, if you think it is not too complicated to add, and useful?

Thanks and regards,
Michael

**Comment by larkolab** [comment]
It seems that it has been discussed already, sorry for the duplicate, I close it, and I'll try to follow the progress on this.

Thanks!

**Comment by dceejay** [comment]
Already in master as 2.6.0-beta
