### ISSUE TITLE
Chart colours don't show as specified in Series Colours 

### ISSUE THREAD

**Issue by paloknapo** [node-red/node-red-dashboard#296]
Pie chart ignores specified colours and always shows default colours.

Bar chart goes for a random selection on each deploy or tab reload which is quite amusing but not really desired behaviour. 

Versions:
NodeRED v0.17.5
node-red-dashboard 2.5.1
NodeJS v6.11.5

I tried my flow on different computer, even reinstalled NodeRED and dashboards too but still can't fix this. I ran out of ideas, please help.

![image](https://user-images.githubusercontent.com/760452/32100673-9037b59a-bb0c-11e7-9f11-979fbacd076a.png)

`[{"id":"6b97b7db.2599f8","type":"tab","label":"Bug Report","disabled":false,"info":""},{"id":"14c78eeb.863c21","type":"function","z":"6b97b7db.2599f8","name":"open issues - assigned & priority","func":"var assigned = flow.get(\"assigned\");\nvar priority = flow.get(\"priority\");\nvar priorityLabel = flow.get(\"priorityLabel\");\nvar counter = {};\nvar counter2 = {};\n\nfor(var i=0; i<assigned.length; i++){\n    for(var j=0; j<priority.length; j++){\n        var property = String(priorityLabel[j] + \"_\" + assigned[i]);\n        counter[property] = 0;\n    }\n}\n\nfor(var i=0; i<msg.payload.length; i++ ){\n    if(msg.payload[i].status != \"closed\"){\n        for(var j=0; j<assigned.length; j++){\n            for(var k=0; k<priority.length; k++){\n                if(msg.payload[i].assigned_roles[0] == undefined){\n                    msg.payload[i].assigned_roles[0] = \"unassigned\";\n                }\n                if(msg.payload[i].assigned_roles[0] == assigned[j] && msg.payload[i].priority == priority[k]){\n                    var property = String(priorityLabel[k] + \"_\" + assigned[j]);\n                    var property2 = priorityLabel[k];\n                    counter[property] += 1;\n                    counter2[property2] = counter2[property2] || 0;\n                    counter2[property2] += 1;\n                }\n            }\n        }\n    }\n}\n\nreturn [{payload: counter},{payload:counter2}];","outputs":"2","noerr":0,"x":361.4409484863281,"y":100.00248146057129,"wires":[["5f488a4a.79c4e4"],["2575ba4d.d57026"]]},{"id":"5f488a4a.79c4e4","type":"function","z":"6b97b7db.2599f8","name":"sort & format","func":"var keys = Object.keys(msg.payload);\nvar assigned = flow.get(\"assigned\");\nvar m = {};\nvar data = [];\nvar dataFormated = [];\nvar priority = flow.get(\"priority\");\n\nkeys.sort();\n\nfor(var i in keys){\n    data.push(msg.payload[keys[i]])\n}\n\nfor(var i=0; i<data.length; i+=assigned.length){\n    dataFormated.push(data.slice(i,i+assigned.length));\n}\n    \nm.labels = assigned;\nm.series = priority;\nm.data = dataFormated;\nreturn {payload:[m]};","outputs":1,"noerr":0,"x":630.3123321533203,"y":90.13473701477051,"wires":[["6732d1f2.d7bd2"]]},{"id":"2575ba4d.d57026","type":"function","z":"6b97b7db.2599f8","name":"sort & format","func":"var keys = Object.keys(msg.payload);\nvar m = {};\nvar priority = flow.get(\"priority\");\nvar data = [];\n\nkeys.sort();\n\nfor(var i in keys){\n    data.push(msg.payload[keys[i]])\n}\n\nm.labels = priority;\nm.data = [data];\nm.series = [\"A\"];\nreturn {payload:[m]};","outputs":1,"noerr":0,"x":632.7938995361328,"y":135.5516529083252,"wires":[["6f893976.bdff38"]]},{"id":"13c756ce.0db749","type":"inject","z":"6b97b7db.2599f8","name":"","topic":"","payload":"[{\"_id\":\"04135790-76c9-11e7-9943-d7eda6ab34fd\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"low\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"in progress\",\"owner\":\"Fred\",\"created\":1501599138700,\"number\":17,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":2,\"status_last_changed\":1505753698586,\"assigned_roles\":[\"CCC\"],\"viewCount\":289,\"commentCount\":2,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/04135790-76c9-11e7-9943-d7eda6ab34fd/thumbnail.png\",\"norm\":[0.15452040505554673,-0.18427174345118644,0.9706530631419911],\"position\":[8745888.432839515,6269.045687757359,-1897622.797898335],\"viewpoint\":{\"unityHeight\":1.7232716272624293,\"fov\":1.4224211726539802,\"aspect_ratio\":0.589186004971447,\"far\":135124.26457821095,\"near\":13.512426457809898,\"guid\":\"2c33eab7-c984-4349-8d71-ab06ce46843d\",\"_id\":\"598095a262558c20488f79aa\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/04135790-76c9-11e7-9943-d7eda6ab34fd/viewpoints/2c33eab7-c984-4349-8d71-ab06ce46843d/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":7500.75,\"normal\":[0,-1,0]}],\"right\":[0.6908095738623125,-2.7755575615628926e-17,-0.7230367436445885],\"view_dir\":[-0.6077765980403512,-0.5416737464449332,-0.5806867996491805],\"look_at\":[-1267.5488855198728,-1129.6880397097239,-1211.051738590555],\"position\":[8747152.272269867,7482.020719243653,-1896436.2854839335],\"up\":[-0.39165002174730895,0.8405888129236019,-0.37419340995402656],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/04135790-76c9-11e7-9943-d7eda6ab34fd/viewpoints/2c33eab7-c984-4349-8d71-ab06ce46843d/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"06232d20-76bb-11e7-bc95-dd430c81fea8\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"none\",\"desc\":\"clash with slab?\",\"topic_type\":\"for_information\",\"status\":\"closed\",\"owner\":\"Fred\",\"created\":1501593129206,\"number\":7,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":2,\"status_last_changed\":1501594018216,\"assigned_roles\":[\"CCC\"],\"viewCount\":0,\"commentCount\":2,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/06232d20-76bb-11e7-bc95-dd430c81fea8/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.4727589925585391,\"fov\":1.2694536907417024,\"aspect_ratio\":0.5258248140027569,\"far\":138767.24234806353,\"near\":13.876724234810254,\"guid\":\"3ac04efe-cad4-4f1f-81f4-3390eb487841\",\"_id\":\"59807e29b71dd42054a8d864\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/06232d20-76bb-11e7-bc95-dd430c81fea8/viewpoints/3ac04efe-cad4-4f1f-81f4-3390eb487841/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":5900.59,\"normal\":[0,-1,0]}],\"right\":[0.13322317129493058,-0.01888308883542061,0.9909061588193685],\"view_dir\":[0.4883897175722602,-0.8687438278088023,-0.0822170627898983],\"look_at\":[1463.1871807638454,-2602.705967144944,-246.31753697074237],\"position\":[8746202.384140596,7705.429730620488,-1891762.9662595426],\"up\":[0.862396121512504,0.49490159688582913,-0.10651450136036274],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/06232d20-76bb-11e7-bc95-dd430c81fea8/viewpoints/3ac04efe-cad4-4f1f-81f4-3390eb487841/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"1572e430-76c7-11e7-9943-d7eda6ab34fd\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"medium\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"open\",\"owner\":\"Fred\",\"created\":1501598308859,\"number\":13,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":1,\"priority_last_changed\":1501598313316,\"assigned_roles\":[\"CCC\"],\"viewCount\":285,\"commentCount\":1,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1572e430-76c7-11e7-9943-d7eda6ab34fd/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.7232716272624293,\"fov\":1.4224211726539802,\"aspect_ratio\":0.589186004971447,\"far\":145408.01966030893,\"near\":14.540801966034984,\"guid\":\"e3217343-52eb-4cd9-8dd4-7467dd1d112b\",\"_id\":\"5980926462558c20488f796f\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1572e430-76c7-11e7-9943-d7eda6ab34fd/viewpoints/e3217343-52eb-4cd9-8dd4-7467dd1d112b/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":94009.4,\"normal\":[0,-1,0]}],\"right\":[0.7047886554025918,0,0.7094173321929812],\"view_dir\":[0.680958418050189,-0.28039706294176553,-0.6765154247910509],\"look_at\":[7839.48911516331,-3228.052792342074,-7788.339446739374],\"position\":[8736809.998418966,95020.36178729012,-1875295.133718098],\"up\":[0.19891853634689477,0.9598841008651158,-0.19762066896956287],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1572e430-76c7-11e7-9943-d7eda6ab34fd/viewpoints/e3217343-52eb-4cd9-8dd4-7467dd1d112b/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"1cb3b7f0-96d5-11e7-af55-17ddd64f7440\",\"creator_role\":\"DDD\",\"scale\":1,\"priority\":\"high\",\"desc\":\"Updated concrete setting out drawings showing BWH.\",\"topic_type\":\"for_information\",\"status\":\"open\",\"owner\":\"Sally\",\"created\":1505122771236,\"number\":34,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":2,\"assigned_roles\":[\"AAA\"],\"viewCount\":286,\"commentCount\":2,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1cb3b7f0-96d5-11e7-af55-17ddd64f7440/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.486523095292731,\"fov\":1.2783490641393787,\"aspect_ratio\":0.5295093974550176,\"far\":131415.94310636574,\"near\":13.14159431062568,\"guid\":\"b16ab087-06d3-454b-a118-13f93f2cba9d\",\"_id\":\"59b659d3da781d4ca2c8b4a8\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1cb3b7f0-96d5-11e7-af55-17ddd64f7440/viewpoints/b16ab087-06d3-454b-a118-13f93f2cba9d/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":3900.39,\"normal\":[0,-1,0]}],\"right\":[0.3832436508111383,0,-0.9236472833895797],\"view_dir\":[-0.6103441808141503,-0.7505638824494253,-0.25324659782265474],\"look_at\":[-12725.743376504033,-15649.339595542646,-5280.219450220591],\"position\":[8752874.255590342,15687.913536897257,-1873843.4463733512],\"up\":[-0.6932562910347473,0.6607978952466825,-0.28764884247689965],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1cb3b7f0-96d5-11e7-af55-17ddd64f7440/viewpoints/b16ab087-06d3-454b-a118-13f93f2cba9d/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"1d54a410-9c81-11e7-b79e-f998f956d81d\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"none\",\"desc\":\"Pipework and clearance +headroom for stairs to be checked\",\"topic_type\":\"for_information\",\"status\":\"open\",\"owner\":\"Fred\",\"created\":1505746401548,\"number\":41,\"rev_id\":\"68fbae3a-7e01-42a3-8435-940bad37b300\",\"__v\":1,\"assigned_roles\":[\"AAA\"],\"viewCount\":286,\"commentCount\":1,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1d54a410-9c81-11e7-b79e-f998f956d81d/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.5686190453286215,\"fov\":1.330200168667416,\"aspect_ratio\":0.5509868232115751,\"far\":167419.42468795984,\"near\":16.74194246878211,\"guid\":\"a36fe78f-6275-4bf7-aa19-4f2903287f12\",\"_id\":\"59bfdde18256f91978959e7f\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1d54a410-9c81-11e7-b79e-f998f956d81d/viewpoints/a36fe78f-6275-4bf7-aa19-4f2903287f12/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":8750885.61001134,\"normal\":[-1,0,0]}],\"right\":[0.03497841657530493,0,-0.9993880679565293],\"view_dir\":[-0.9974647728103133,0.062010015239792354,-0.03491110156427106],\"look_at\":[4438.286109899811,46383.711977826504,3294.7646450721877],\"position\":[8762690.734718233,6117.145609382376,-1887231.1562972507],\"up\":[0.06197206932445102,0.9980755272072154,0.002169012144898464],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/1d54a410-9c81-11e7-b79e-f998f956d81d/viewpoints/a36fe78f-6275-4bf7-aa19-4f2903287f12/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"2f6ab480-87fc-11e7-bf69-473692af4596\",\"creator_role\":\"BBB\",\"scale\":1,\"priority\":\"none\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"closed\",\"owner\":\"Duncan\",\"created\":1503490285801,\"number\":29,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":1,\"status_last_changed\":1508398002304,\"assigned_roles\":[\"CCC\"],\"viewCount\":146,\"commentCount\":1,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/2f6ab480-87fc-11e7-bf69-473692af4596/thumbnail.png\",\"norm\":[-0.077561937808067,-0.023817855639191723,0.996702992649369],\"position\":[8747451.54239532,5217.782063186979,-1893189.347449396],\"viewpoint\":{\"unityHeight\":1.633038718648072,\"fov\":1.369465739775116,\"aspect_ratio\":0.5672511515403659,\"far\":141916.3493132653,\"near\":14.191634931330519,\"guid\":\"25f4e7c2-109b-4ff1-b010-b38fa51011e3\",\"_id\":\"599d70eda22c42049bd960d9\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/2f6ab480-87fc-11e7-bf69-473692af4596/viewpoints/25f4e7c2-109b-4ff1-b010-b38fa51011e3/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":-1893359.0746348605,\"normal\":[0,0,-1]}],\"right\":[0.9999986015515945,0,0.0016723919563041935],\"view_dir\":[0.001672336348803626,0.008154719745081803,-0.9999653513182423],\"look_at\":[-1594.84854245731,630.2702104663786,-2998.908363730792],\"position\":[8747208.297636485,5144.013548903461,-1890046.3381159066],\"up\":[-0.000013637887707589794,0.9999667497201492,0.00815470834112698],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/2f6ab480-87fc-11e7-bf69-473692af4596/viewpoints/25f4e7c2-109b-4ff1-b010-b38fa51011e3/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"32a8e3d0-76ca-11e7-9943-d7eda6ab34fd\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"low\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"in progress\",\"owner\":\"Fred\",\"created\":1501599646353,\"number\":20,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":2,\"status_last_changed\":1505753424980,\"assigned_roles\":[\"CCC\"],\"viewCount\":285,\"commentCount\":2,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/32a8e3d0-76ca-11e7-9943-d7eda6ab34fd/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.7232716272624293,\"fov\":1.4224211726539802,\"aspect_ratio\":0.589186004971447,\"far\":121418.46653449944,\"near\":12.141846653453358,\"guid\":\"72e61f1c-04c9-4adc-9ea1-9d49b2302f4c\",\"_id\":\"5980979e62558c20488f7ab1\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/32a8e3d0-76ca-11e7-9943-d7eda6ab34fd/viewpoints/72e61f1c-04c9-4adc-9ea1-9d49b2302f4c/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":11501.15,\"normal\":[0,-1,0]}],\"right\":[0.5111613341659264,0,0.8594847819791285],\"view_dir\":[0.596030559690193,-0.720481417151397,-0.3544772199379108],\"look_at\":[4668.276693115781,-5643.010333663327,-2776.363924924859],\"position\":[8739834.286251264,16150.37621447103,-1883813.89134799],\"up\":[0.6192428137403821,0.6934742443231144,-0.3682822424328655],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/32a8e3d0-76ca-11e7-9943-d7eda6ab34fd/viewpoints/72e61f1c-04c9-4adc-9ea1-9d49b2302f4c/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"3667e720-97c5-11e7-a791-0df14120e1d0\",\"creator_role\":\"CCC\",\"scale\":1,\"priority\":\"high\",\"desc\":\"Update BW for electrical as CCC drawing\",\"topic_type\":\"for_information\",\"status\":\"open\",\"owner\":\"Harry\",\"created\":1505225893529,\"number\":40,\"rev_id\":\"a4b374ed-d6bc-44b7-b9f7-80537692c75b\",\"__v\":1,\"assigned_roles\":[\"DDD\"],\"viewCount\":295,\"commentCount\":1,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3667e720-97c5-11e7-a791-0df14120e1d0/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.4539119853411537,\"fov\":1.257178187303059,\"aspect_ratio\":0.5207401351684754,\"far\":156348.5526991992,\"near\":15.634855269924318,\"guid\":\"ec1f214f-6e8d-4139-8c79-664030bc4341\",\"_id\":\"59b7eca5e7ee114caee6cafb\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3667e720-97c5-11e7-a791-0df14120e1d0/viewpoints/ec1f214f-6e8d-4139-8c79-664030bc4341/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":94509.45,\"normal\":[0,-1,0]}],\"right\":[0.5295648552669147,-2.7755575615628914e-17,-0.8482694525126622],\"view_dir\":[-0.7141534256953468,-0.5396420788297493,-0.44583776345651494],\"look_at\":[-5490.763005574641,-4149.033885547455,-3427.8201433979593],\"position\":[8751062.54746914,98330.25013040662,-1885858.1369294384],\"up\":[-0.45776189076170626,0.8418945461020083,-0.2857754793714132],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3667e720-97c5-11e7-a791-0df14120e1d0/viewpoints/ec1f214f-6e8d-4139-8c79-664030bc4341/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"3952f340-76c2-11e7-bc95-dd430c81fea8\",\"creator_role\":\"AAA\",\"scale\":1,\"priority\":\"medium\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"open\",\"owner\":\"Fred\",\"created\":1501596221561,\"number\":11,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":0,\"assigned_roles\":[\"CCC\"],\"viewCount\":286,\"commentCount\":0,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3952f340-76c2-11e7-bc95-dd430c81fea8/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.4727589925585391,\"fov\":1.2694536907417024,\"aspect_ratio\":0.5258248140027569,\"far\":130052.49836913643,\"near\":13.005249836917299,\"guid\":\"9813c283-f2bb-4e48-95f6-c909d05ed878\",\"_id\":\"59808a3db71dd42054a8d9a6\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3952f340-76c2-11e7-bc95-dd430c81fea8/viewpoints/9813c283-f2bb-4e48-95f6-c909d05ed878/screenshot.png\",\"clippingPlanes\":[{\"clipDirection\":-1,\"distance\":-1892656.811625001,\"normal\":[0,0,-1]}],\"right\":[0.8861149594374312,0,-0.46346550967811995],\"view_dir\":[-0.4609442986909212,0.104164431454526,-0.8812945731842958],\"look_at\":[-1908.0573348378966,-43883.040725970226,-4395.324471177326],\"position\":[8748193.376815412,73319.97838008452,-1888217.0134796107],\"up\":[0.0482766213144035,0.9945600892956421,0.09230166095315041],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3952f340-76c2-11e7-bc95-dd430c81fea8/viewpoints/9813c283-f2bb-4e48-95f6-c909d05ed878/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"},{\"_id\":\"3a802440-76a4-11e7-bad8-43e576e1f4de\",\"creator_role\":\"G3_FED.collaborator\",\"scale\":1,\"priority\":\"medium\",\"desc\":\"(No Description)\",\"topic_type\":\"for_information\",\"status\":\"closed\",\"owner\":\"BBB\",\"created\":1501583338658,\"number\":2,\"rev_id\":\"2244dd89-de67-4c4b-958c-582ea61140b7\",\"__v\":10,\"status_last_changed\":1501591650563,\"assigned_roles\":[\"CCC\"],\"viewCount\":0,\"commentCount\":10,\"thumbnail\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3a802440-76a4-11e7-bad8-43e576e1f4de/thumbnail.png\",\"norm\":[],\"position\":[],\"viewpoint\":{\"unityHeight\":1.685382476252421,\"fov\":1.4004712366808738,\"aspect_ratio\":0.5800940458991255,\"far\":121342.56094839444,\"near\":12.134256094829388,\"guid\":\"df5f27e6-89ea-47e7-81de-5763de7020f0\",\"_id\":\"598057ea1cf338204eea631a\",\"type\":\"perspective\",\"screenshot\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3a802440-76a4-11e7-bad8-43e576e1f4de/viewpoints/df5f27e6-89ea-47e7-81de-5763de7020f0/screenshot.png\",\"clippingPlanes\":[],\"right\":[0.8675433214485639,0,0.4973616243841033],\"view_dir\":[0.4973489484087473,0.007139483387026901,-0.8675212108609678],\"look_at\":[3207.519308528528,46.04419269423124,-5594.846522340937],\"position\":[8731654.319373177,17376.45412065473,-1886760.5412472638],\"up\":[-0.0035509050546350183,0.9999745135637039,0.00619381113100816],\"screenshotSmall\":\"BBB/570018ce-6724-4555-8a7e-a19d943bec71/issues/3a802440-76a4-11e7-bad8-43e576e1f4de/viewpoints/df5f27e6-89ea-47e7-81de-5763de7020f0/screenshotSmall.png\"},\"typePrefix\":\"\",\"modelCode\":\"\",\"account\":\"BBB\",\"model\":\"570018ce-6724-4555-8a7e-a19d943bec71\"}]","payloadType":"json","repeat":"","crontab":"","once":true,"x":111.51785659790039,"y":100.7638931274414,"wires":[["14c78eeb.863c21","250e5bbc.9baa54"]]},{"id":"250e5bbc.9baa54","type":"function","z":"6b97b7db.2599f8","name":"flow variables","func":"var owners = [];\nvar assigned = [];\npriority = [\"none\",\"low\",\"medium\",\"high\"];\npriorityLabel = [\"0_N\",\"1_L\",\"2_M\",\"3_H\"];\nstatus = [\"open\",\"in progress\",\"for approval\",\"closed\"];\nstatusLabel = [\"0_O\",\"1_IP\",\"2_FA\",\"3_C\"];\n\nfor (var i=0; i<msg.payload.length; i++){\n    owners.push(msg.payload[i].owner);\n    if(msg.payload[i].assigned_roles[0] != null){\n        assigned.push(msg.payload[i].assigned_roles[0]);\n    }\n}\n\nvar ownersSet = new Set(owners);\nowners = Array.from(ownersSet);\n\nvar assignedSet = new Set(assigned);\nassigned = Array.from(assignedSet);\nassigned.unshift(\"unassigned\");\nassigned.sort();\n\nflow.set(\"owners\",owners);\nflow.set(\"assigned\",assigned);\nflow.set(\"priority\",priority);\nflow.set(\"priorityLabel\",priorityLabel);\nflow.set(\"status\",status);\nflow.set(\"statusLabel\",statusLabel);\n\nreturn {payload:[owners,assigned]};","outputs":1,"noerr":0,"x":325.7266845703125,"y":195.71676635742188,"wires":[[]]},{"id":"6732d1f2.d7bd2","type":"ui_chart","z":"6b97b7db.2599f8","name":"","group":"9c3ad063.5d398","order":0,"width":0,"height":0,"label":"chart","chartType":"bar","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":831.5228385925293,"y":96.64932250976562,"wires":[[],[]]},{"id":"6f893976.bdff38","type":"ui_chart","z":"6b97b7db.2599f8","name":"","group":"9c3ad063.5d398","order":0,"width":0,"height":0,"label":"chart","chartType":"pie","legend":"true","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":"50","useOneColor":false,"colors":["#80ffff","#80ff00","#ffff00","#ff0080","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"x":831.5228385925293,"y":148.07540893554688,"wires":[[],[]]},{"id":"9c3ad063.5d398","type":"ui_group","z":"","name":"Group 2","tab":"2f1b1588.3a1a8a","order":2,"disp":true,"width":"12"},{"id":"2f1b1588.3a1a8a","type":"ui_tab","z":"","name":"test","icon":"dashboard","order":3}]`

**Comment by dceejay** [comment]
can you retry with latest from master 

    cd ~/.node-red
    npm i node-red/node-red-dashboard

![image](https://user-images.githubusercontent.com/5375409/32103232-6646054c-bb17-11e7-9071-262f459fbdde.png)

**Comment by paloknapo** [comment]
Thanks dceejay. That fixed the random colours problem. 

The bar chart still doesn't show the series colours right. I followed examples and I'm 99% I formatted my data correctly. This is what I want to achieve:

![image](https://user-images.githubusercontent.com/760452/32109050-7b20a4b8-bb2b-11e7-9fb0-9c308510e131.png)

**Comment by paloknapo** [comment]
Also, I have multiple flows with multiple dashboards organised in a few tabs. When I switch between tabs colours of charts changes.

**Comment by dceejay** [comment]
that bar chart comes from this data - what does yours look like

```var m={};
m.labels = [10,20,30,40,50,60,70];
m.series = ['Series A', 'Series B', 'Series C', 'Series D'];
m.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90],
    [38, 28, 20, 49, 45, 60, 20],
    [58, 18, 40, 29, 15, 30, 60]
  ];
return {payload:[m]};
var m={};
m.labels = [10,20,30,40,50,60,70];
m.series = ['Series A', 'Series B', 'Series C', 'Series D'];
m.data = [
    [65, 59, 80, 81, 56, 55, 40],
    [28, 48, 40, 19, 86, 27, 90],
    [38, 28, 20, 49, 45, 60, 20],
    [58, 18, 40, 29, 15, 30, 60]
  ];
return {payload:[m]};
```

do you have a simple example that shows the colors changing when you change tabs ?

**Comment by paloknapo** [comment]
This is the object I feed into the chart
`[
    {
        "labels": ["AAA","CCC","DDD","unassigned"],
        "series": ["none","low","medium","high"],
        "data": [
            [1,0,0,0],
            [0,2,0,0],
            [0,2,0,0],
            [1,0,1,0]
        ]
    }
]`
When it comes to colours changing when switching tabs, I couldn't replicate it on a simple example. Do I need to delete dashboard 2.5.1 nodes from my flows and replace them with new ones?
