### ISSUE TITLE
Dynamic color controls

### ISSUE THREAD

**Issue by smadds** [node-red/node-red-dashboard#299]
Feature request:
Would you consider an option to make the color wheel & slider dynamic so that they output changes immediately (i.e. not just when receiving an onmouseup event)? This would bring functionality in line with the slider control and make it easier to set the color of lights by eye.

**Comment by dceejay** [comment]
Yes. Feel free to raise a pull request

**Comment by Arial7** [comment]
But we would probably need *some* sort of delay, as sending 1000 mqtt events when changing a color probably is not *that* great of an idea

**Comment by dceejay** [comment]
there is already code in https://github.com/node-red/node-red-dashboard/blob/master/src/components/ui-component/ui-component-ctrl.js#L214
to do that so it can be re-used.
