### ISSUE TITLE
Switch fails to store properties properly when switched from 'false' to '0'

### ISSUE THREAD

**Issue by JoeStrout** [node-red/node-red-dashboard#300]
Steps:

1. Add a Switch to a flow.  Open its properties; note that the on message is boolean (true), and the off message is boolean (false).
2. Change the on message to numeric (100), and the off message to numeric (0).  Close the switch properties.
3. Attempt to deploy.  Get a warning that the switch is misconfigured.
4. Check the switch properties.  Note that the off message is now numeric (false).  Say "WTF?!"
5. Change the value to 0.  Go to step 3.

The work-around is to change the value to something other than zero, e.g. 1, close the properties, and then open them back up again and change to 0.  It appears that somewhere in the pipeline, "0" is being considered the same as "false" and so it's not bothering to save the zero.

**Comment by dceejay** [comment]
which version of node.js and dashboard are you using ? And what platform / OS ?

**Comment by JoeStrout** [comment]
Sorry, I  didn't see your question.  I'm not sure what versions of those things (or how to find out), but it was all downloaded within the last week.  Running on Raspberry Pi (Raspbian).

**Comment by dceejay** [comment]
when you start node-red from a console  (eg using node-red-start ) then it will print out the versions of node.js, node-red and the dashboard during the startup.

**Comment by JoeStrout** [comment]
So it does!  Node-RED v0.17.5; Node.js v6.11.5; and for completeness, Linux 4.9.59-v7+ arm LE.

This is reproducible every time for me.  Is it not happening for you?

**Comment by dceejay** [comment]
Yes - I have pushed a fix to master (not published to npm yet) will be 2.6.2
(you can get it early by `cd ~/.node-red && npm i node-red/node-red/dashboard`
