### ISSUE TITLE
Dashboard: Button does send variable name instead of variable content

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red-dashboard#301]
Dasboad button: I've configured the "when clicked send: Payload" field as: msg.payload

Now, the button sends "payload" as payload and not the payload value he received before.

linux: 4.4.0 
nr v: 0.17.5
db v: 2.6.1

**Comment by dceejay** [comment]
hmm - good spot - the option makes no sense as the node does not hold any state (context) - so there is no previous value to send anyway. the `msg.` option should be removed

**Comment by M0ebiu5** [comment]
I would need a possibility to dynamically configure the payload.
How else can i do it?

**Comment by dceejay** [comment]
save it in one of the contexts... either `flow.` or `global.`

**Comment by M0ebiu5** [comment]
no, i'm old school and try to avoid any "globals".
Looks like i have to stick with ui-template then... :(

**Comment by dceejay** [comment]
use flow. then... it's not as global as global :-)

**Comment by M0ebiu5** [comment]
*g*
i will wait and hope for a solution...cause if label, colors, etc are reconfigurable - one day the payload will follow (it's just logical).
