### ISSUE TITLE
Dashboard widget notification does not parse html tags

### ISSUE THREAD

**Issue by M0ebiu5** [node-red/node-red-dashboard#303]
For a label, this works :
msg.label  = "<font color="red">ON</font>"

but a notification shows only the whole string.

**Comment by dceejay** [comment]
Can you provide an example flow that shows this ? Thanks

**Comment by M0ebiu5** [comment]
Oh, the github editor swallowed a part of the message - it was:
`msg.label  = "<font color="red">ON</font>"`

My use case is, that i have some already prepared messages (events, warnings, errors) floating on the mqtt bus. Now, it is easy to show them anywhere - but on the notification toast, it does not work properly.

Here is the example:

`[{"id":"c141e95.c28af18","type":"ui_toast","z":"96082429.7476f8","position":"top right","displayTime":"10","highlight":"gold","outputs":0,"ok":"OK","cancel":"","topic":"","name":"","x":912,"y":1805,"wires":[]},{"id":"e6db5a14.b147c8","type":"inject","z":"96082429.7476f8","name":"","topic":"","payload":"Tomorrow:<font color='orange';> Trash can! </font>","payloadType":"str","repeat":"","crontab":"","once":false,"x":600,"y":1794,"wires":[["c141e95.c28af18","f4a8766e.9d0718","f7145bbc.b84bb8"]]},{"id":"f4a8766e.9d0718","type":"ui_text","z":"96082429.7476f8","group":"7d105c7b.563384","order":0,"width":0,"height":0,"name":"","label":"Event:","format":"{{msg.payload}}","layout":"row-spread","x":895,"y":1740,"wires":[]},{"id":"f7145bbc.b84bb8","type":"ui_button","z":"96082429.7476f8","name":"","group":"7d105c7b.563384","order":0,"width":0,"height":0,"passthru":false,"label":"{{msg.payload}}","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":936,"y":1669,"wires":[[]]},{"id":"7d105c7b.563384","type":"ui_group","z":"","name":"Data new","tab":"631762ac.ba822c","order":2,"disp":false,"width":"10"},{"id":"631762ac.ba822c","type":"ui_tab","z":"","name":"Greenhouse","icon":"dashboard","order":8}]`

**Comment by dceejay** [comment]
well it currently does work properly... as designed... 
It may not do as you want - but that is something else :-)

**Comment by M0ebiu5** [comment]
ok, i thought that all labels should accept html tags.
Thanks!

**Comment by dceejay** [comment]
so like this then ?
![image](https://user-images.githubusercontent.com/5375409/32461450-bfb632a0-c32d-11e7-944b-3c32d3e90a39.png)

**Comment by M0ebiu5** [comment]
yeah - great!
