### ISSUE TITLE
Error while installing node-red-dashboard, version: 2.6.1

### ISSUE THREAD

**Issue by VladoRaj** [node-red/node-red-dashboard#304]
8 Nov 21:52:04 - [info] Node-RED version: v0.17.5
8 Nov 21:52:04 - [info] Node.js  version: v6.12.0
8 Nov 21:52:04 - [info] Linux 4.9.59-v7+ arm LE
8 Nov 21:52:05 - [info] Loading palette nodes
8 Nov 21:52:09 - [info] Settings file  : /root/.node-red/settings.js
8 Nov 21:52:09 - [info] User directory : /root/.node-red
8 Nov 21:52:09 - [info] Flows file     : /root/.node-red/flows_raspberrypi.json
8 Nov 21:52:09 - [info] Server now running at http://127.0.0.1:1880/
8 Nov 21:52:09 - [info] Starting flows
8 Nov 21:52:09 - [info] Started flows
8 Nov 21:55:01 - [info] Installing module: node-red-contrib-netatmo-dashboard, version: 0.2.3
8 Nov 21:55:34 - [info] Installed module: node-red-contrib-netatmo-dashboard
8 Nov 21:55:35 - [info] Added node types:
8 Nov 21:55:35 - [info]  - node-red-contrib-netatmo-dashboard:netatmo-dashboard
8 Nov 21:55:35 - [info]  - node-red-contrib-netatmo-dashboard:netatmo-config-node
8 Nov 21:56:38 - [info] Installing module: node-red-dashboard, version: 2.6.1
8 Nov 21:57:06 - [warn] Installation of module node-red-dashboard failed:
8 Nov 21:57:06 - [warn] ------------------------------------------
8 Nov 21:57:06 - [warn] Error: Command failed: npm install --save --save-prefix="~" --production node-red-dashboard@2.6.1
module.js:471
    throw err;
    ^
Error: Cannot find module '/root/.node-red/node_modules/node-red-dashboard/fixfa.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "--save-prefix=\"~\"" "--production" "node-red-dashboard@2.6.1"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-red-dashboard@2.6.1 postinstall: `node fixfa.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-dashboard@2.6.1 postinstall script 'node fixfa.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fixfa.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
[npm-debug.log](https://github.com/node-red/node-red-dashboard/files/1455445/npm-debug.log)

**Comment by dceejay** [comment]
What platform is this on ? Is there any reason you are needing to run this as root ?

**Comment by VladoRaj** [comment]
Hi,
No there was no reason to run node-red as root. I try run it now not as a root and installation of node-red-dashboard was successful. Thanks for advice. Before I opened this issue I was trying install other dashboard as root and there was no problem.
In case that you are still interested I put here info about platform.

**Raspberry Pi 3 model B**

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**Comment by dceejay** [comment]
there "should" be no problem running as root - just it's not generally advised unless you really need to, and certainly mixing installing some parts as root and others as non-root often leads to errors as a) files are where they are expected and b) permissions of files will be incompatible.

OK to close ?

**Comment by VladoRaj** [comment]
Yes for me it is solved, thanks.

**Comment by dceejay** [comment]
Thanks
