### ISSUE TITLE
Text input not sending text on tab key when delay is set to 0

### ISSUE THREAD

**Issue by vguarna** [node-red/node-red-dashboard#307]
Created a tab for a new flow and dragged in a single text input node connected to a debug node. Set the delay to 0 ms. Input typed in the text input control correctly buffers without sending and hitting ENTER does cause the msg payload to propagate. However, hitting the Tab key causes the cursor to move out of the box but does not cause the buffered text to propagate. If I am understanding the Info tab correctly, the TAB key should also send the the text payload.

Environment:
iMac
High Sierra OS
Safari, Firefox, and Chrome browsers
nodejs version 6.11.4
node-red version 0.17.5
dashboard version 2.6.2

**Comment by dceejay** [comment]
good spot... could swear that used to work... but def broken now... will see what's up.
