### ISSUE TITLE
Dashboard 2.6.2 color picker bug

### ISSUE THREAD

**Issue by Toshibass** [node-red/node-red-dashboard#308]
Dashboard 2.6.2 does not pass through input to output correctly on color picker node, now it adds an extra # to output.

Capture2.5.1 attached shows output of following flow on Dashboard 2.5.1
Capture2.6.2 attached shows output of same flow on Dashboard 2.6.2

![capture2 5 1](https://user-images.githubusercontent.com/6310911/32884504-84f2d114-cab2-11e7-8a9e-79d3dc151552.JPG)

![capture2 6 2](https://user-images.githubusercontent.com/6310911/32884503-84de5608-cab2-11e7-8ce8-325be73cfba1.JPG)

[{"id":"a4bb944c.6ccb48","type":"function","z":"7f0e2398.c642fc","name":"","func":"msg.topic='cmnd';\nnode.status({text:msg.topic+" "+msg.payload});\nreturn msg;","outputs":1,"noerr":0,"x":420,"y":1390,"wires":[["8d16d89b.f19e98","67cbae63.afcc2"]]},{"id":"7fe2e8d3.8208e8","type":"inject","z":"7f0e2398.c642fc","name":"","topic":"","payload":"#ff0000","payloadType":"str","repeat":"","crontab":"","once":false,"x":272.8571319580078,"y":1415.7143087387085,"wires":[["a4bb944c.6ccb48"]]},{"id":"8d16d89b.f19e98","type":"ui_colour_picker","z":"7f0e2398.c642fc","name":"","label":"","group":"3e148784.a62a88","format":"hex","outformat":"string","showSwatch":true,"showPicker":false,"showValue":false,"showAlpha":false,"showLightness":true,"order":0,"width":0,"height":0,"passthru":true,"topic":"Through Color Picker","x":597.1427879333496,"y":1390.0001230239868,"wires":[["b8d15654.ad06a8"]]},{"id":"b8d15654.ad06a8","type":"debug","z":"7f0e2398.c642fc","name":"","active":true,"console":"false","complete":"payload","x":795.7142208644323,"y":1390.0001464571271,"wires":[]},{"id":"67cbae63.afcc2","type":"debug","z":"7f0e2398.c642fc","name":"","active":true,"console":"false","complete":"false","x":605.7143440246582,"y":1344.2858724594116,"wires":[]},{"id":"3c784b0e.f7cfb4","type":"inject","z":"7f0e2398.c642fc","name":"","topic":"","payload":"#0000ff","payloadType":"str","repeat":"","crontab":"","once":false,"x":273.57139587402344,"y":1370.000075340271,"wires":[["a4bb944c.6ccb48"]]},{"id":"3e148784.a62a88","type":"ui_group","z":"","name":"ui 239 raspberrypi4 Living room","tab":"ae7c3b1a.ad5458","order":1,"disp":true,"width":"6"},{"id":"ae7c3b1a.ad5458","type":"ui_tab","z":"","name":"Setup","icon":"dashboard","order":1}]

**Comment by dceejay** [comment]
@Toshibass  Thanks for reporting it
