### ISSUE TITLE
private ui-controls, etc.

### ISSUE THREAD

**Issue by pelis** [node-red/node-red-dashboard#31]
This may not be the right place to drop this issue but there is no dedicated group yet and I just want to know whether the following is something which is considered for the future or not. Is there a good place to drop contribution suggestions or feature requests?
I have implement some test cases which required me to modify some of the base elements such as ui.js, events.js, ui-component-ctrl.js, …

Some of the issues I have implement are:
-   ui-controls that are private to a given client -
  I have added a post at: node-red https://groups.google.com/forum/#!topic/node-red/I6ojoN9ne4Q
-   simple things like text-input -> emit data when user hits enter rather than via delay
-   fill dropdown dynamically based on input node (current dropdown has no input channel; I have added one) – I have seen this request is an issue here already
-   mechanism to override control type, mechanism to inject control properties

Is this something you consider for your next releases?
Would be helpful to know where node-red-dashboard is heading, I assume that there is a backlog or list of issues for next releases?
Thanks an cheers - Peter

**Comment by dceejay** [comment]
This is as good a place as any. We are trying to get he base release out as soon as possible with the functionality as-is before we start considering enhancements. Most of the final work is around the configuration of the widgets, and the right hand menu panel. 

Several of your suggestions above look very useful. We need to think more carefully about the "meOnly" flag and how that is exposed in a sensible manner, and what use-cases that both enables and breaks.

**Comment by pelis** [comment]
OK, thanks - looking forward to your release...

**Comment by dceejay** [comment]
in meantime - happy to consider a PR for items 2 and 3, (subject to CLA), if you like. (to the 0.14.0 branch)

**Comment by pelis** [comment]
Sounds very good! 
Thanks...

**Comment by dceejay** [comment]
Hi - we have now released to npm. Do we want to re-visit this ?

**Comment by pelis** [comment]
Is there something I could do in that regard?
For #1 I have put my code changes on gist - I have done some minor changes in the meantime, however, did not check against current branch/release

**Comment by dceejay** [comment]
Hi, certainly a PR (or pref separate ones) for item 2 and 3 would be quick wins.

**Comment by pelis** [comment]
OK, I have created a pull request for the "Enter" for text-input (issue 2).
I have included the code in the base files, so no injection is necessary.

I will do the same modifications for the drop down control - so there is some re-coding that I have to do

I hope the PR has "arrived" properly...
Tell me, if you want me to do it differently

**Comment by madeddie** [comment]
This is regarding PR #40

**Comment by dceejay** [comment]
@pelis - almost there - will continue each discussion in their respective PR threads.

**Comment by dceejay** [comment]
Added ui-control as part of e70788eebc0cdfd887deceaac0229d588cfe2037

**Comment by dceejay** [comment]
commit eccd70a 
The ui_control node now emits connect and lost messages for every client connection that can be used to trigger things on load of a page by a client. Also each widget emits a msg.socketid property that can be used to identify where an event has come from...

Going to close this as we have implemented as far as we are going to go .... for now...
can re-open a new one to handle any extras.

**Comment by pelis** [comment]
Thanks - will have a look at it...

**Comment by dceejay** [comment]
Hi @pelis - note, it doesn't go as far as you did :-)
