### ISSUE TITLE
Widget of Text node fails to resize to multiline content

### ISSUE THREAD

**Issue by gustavovelascoh** [node-red/node-red-dashboard#311]
I have found that text widget (from text node) fails at resize with multiline content. I'm passing this payload:
`"1 sica<br>2 wifi<br>3 actuador<br>4 temperatura<br>5 on-off<br>6 pulso<br>"` 
and this is the output:

![screenshot from 2017-11-22 10-40-50](https://user-images.githubusercontent.com/2431850/33136009-1608e8aa-cf72-11e7-8fa6-d2a789f6231a.png)

I'm running nodered using docker in an Amazon instance.

**Flow info:**
[{"id":"f461dc43.73f9b","type":"ui_text","z":"eba2c5d8.a05c58","group":"ba914212.a562c","order":0,"width":0,"height":0,"name":"tipos_texto","label":"Tipos","format":"{{msg.payload}}","layout":"col-center","x":1044,"y":617,"wires":[]},{"id":"ba914212.a562c","type":"ui_group","z":"","name":"Crear Dispositivo","tab":"6800edca.15f5d4","disp":true,"width":"6"},{"id":"6800edca.15f5d4","type":"ui_tab","z":"","name":"Gestión Dispositivos","icon":"dashboard"}]

**My setup:**
Dashboard: 2.6.2
Node-RED: 0.17.5
Node.js: 6.12.0

**Comment by dceejay** [comment]
The text node was never conceived as a multi-line widget - the ui-template is probably more appropriate for this task.

**Comment by jjssoftware** [comment]
I'm not entirely clear on what "fails at resize with multiline content" means wrt the text node. In my experience when testing with the text `"1 sica<br>2 wifi<br>3 actuador<br>4 temperatura<br>5 on-off<br>6 pulso<br>"` split onto multiple lines with the `<br/>` element, it appears to be working as it should. Reducing the width of the group that the text node appears within or reducing the width of the text node itself, forces the text to resize.

Perhaps it doesn't actually "fail to resize" but it just doesn't resize exactly in the way you want it to resize?

Here's a suggestion (based on very little to go on) - if you want to render a numbered list of items, use markup that naturally does that for you i.e. `<ol><li>sica</li><li>wifi</li><li>actuador</li><li>temperatura</li><li>on-off</li><li>pulso</li></ol>`

**Comment by dceejay** [comment]
Actually yes - having now looked at it again... it's not actually too bad... the fact that it doesn't auto scale to fit some unknown height of data is hardly a show-stopper. Manually setting the height is generally a good idea in order to stop all the other elements being "responsive" and moving when you don't want them to.
