### ISSUE TITLE
The "new" Angular

### ISSUE THREAD

**Issue by xeor** [node-red/node-red-dashboard#313]
Angularjs become "angular" when version 2 got released. Everything changed! A complete rewrite, a  new framework. They are now at `angular 5` (following semver, therefor the high number).

But is there a plan for the `node-red-dashboard`? Have it been discussed (cant find any discussions)?

The `angular` version of the dashboard should be it's own project. Eg `node-red-dashboard-2` (angular is a "new" framework).. Is it in the plans?

**Comment by dceejay** [comment]
Hi,

generally we prefer discussions like this on the mailing list or slack channels first so everyone can join in... but seeing as we are here.

As you point out Angular 2 -> 5 are a complete rewrite and would also entail a massive re-write of Dashboard. We have no current plans to do so as our focus has always been on the core of Node-RED. We do want to keep enhancing the Dashboard, but a complete re-write is not on the cards. We are happy for others to produce other dashboards based on whatever libraries are in vogue at the time, and as you know there are many others to choose from, some of which may be a better choice for an extensible user defined set of widgets based UI.

**Comment by dceejay** [comment]
Closing as we have no intention of re-writing.

**Comment by xeor** [comment]
Not even using something similar like vue? Long term

**Comment by dceejay** [comment]
when they invent 28 hour days.
yes Vue would be a possibility... but it would be a new Dashboard not an Issue for this one.

**Comment by xeor** [comment]
Thats cool.. I've btw started doing some development in vue. And it just feels right.. angular 1 done without many of its problem, but not as big and chunky as angular 2+.

.vue files looks perfect for an extensible dashboard

**Comment by xeor** [comment]
Did this discussion die out?
Been using vue a lot since last time. And it seams to be a perfect fit for this dashboard...
