### ISSUE TITLE
Add switch status to nodes

### ISSUE THREAD

**Issue by ulab** [node-red/node-red-dashboard#314]
It would be nice to see the current state of a switch in the Node-RED flow editor similar to MQTT nodes showing their connection status.

<img width="131" alt="screen shot 2017-12-08 at 00 36 00" src="https://user-images.githubusercontent.com/504616/33744087-cf726ea8-dbaf-11e7-95bc-c8c39e958cb5.png">

**Comment by dceejay** [comment]
The editor is not a dashboard !

**Comment by ulab** [comment]
It would help to see if an input changes the state of a switch while editing a flow. Or when I use a switch to change the state of another node ("Big Timer") it'd be nice to see why the timer is in "auto" or "manual" while working in the editor.

Injecting messages, debugging outputs, etc. are not "editing" features either, but interactions with the user.

**Comment by dceejay** [comment]
hmm definite maybe

**Comment by dceejay** [comment]
sort of like 
![image](https://user-images.githubusercontent.com/5375409/33795096-14ea2e30-dcd2-11e7-9b67-cd6ed28988c3.png)

**Comment by dceejay** [comment]
now in master (not yet on npm)

**Comment by ulab** [comment]
Thanks for adding this so fast.
