### ISSUE TITLE
ui_switch: RangeError: Maximum call stack size exceeded when adding to a Sonoff component.

### ISSUE THREAD

**Issue by GAZ082** [node-red/node-red-dashboard#316]
Hi there. When I add a switch ui component breaks havok in my flow with the error of the subject. I dont have to actuate the switch, just by adding it and deploying makes my Sonoff swich to halt with the error displayed

![image](https://user-images.githubusercontent.com/100194/33897418-2a908940-df44-11e7-955c-fb67b59c323c.png)

`12 Dec 13:53:51 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:51 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:51 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:52 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:52 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:52 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:53 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:53 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:53 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:53 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:54 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:54 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:55 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:55 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:55 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:55 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:56 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:56 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:56 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:56 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:57 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:57 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:58 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:53:58 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:53:58 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:54:01 - [error] [ui_switch:5b6a51aa.1fb23] RangeError: Maximum call stack size exceeded
12 Dec 13:54:01 - [error] [Sonoff device:switch00] RangeError: Maximum call stack size exceeded
12 Dec 13:54:02 - [info] [mqtt-broker:45ca83b7.55511c] Disconnected from broker: mqtt://192.168.1.2:51883
12 Dec 13:54:17 - [info] [mqtt-broker:45ca83b7.55511c] Connected to broker: mqtt://192.168.1.2:51883
`

**Comment by dceejay** [comment]
In general we prefer general ho-to type questions via the mailing list or slack channel as per out contribution guidelines - so that the widest possible community can help.

I suspect you haven't selected - "don't pass input through to output" in the switch node - so you basically have a massive feedback loop...

**Comment by GAZ082** [comment]
@dceejay hi! unckecked the box and now it works flawlessly (it says the same thing you mentioned but the opposite).

Will keep your suggestion for any other future inquiry. Thanks!
