### ISSUE TITLE
Installed on Mac High Sierra - no ui displayed

### ISSUE THREAD

**Issue by nospam2k** [node-red/node-red-dashboard#329]
I installed node-red-dashboard using npm i node-red/node-red-dashboard and then started node using node-red. I get an error Cannot GET /ui. I'm assuming something needs to be to node-red sh file?

**Comment by knolleary** [comment]
What directory did you run the install in?

Did the NR log mention the dashboard on startup?

**Comment by nospam2k** [comment]
Wow superfast response! I reread the info and found I was not in the user dir. Resolved.
