### ISSUE TITLE
node-red-dashboard is not published on npmjs

### ISSUE THREAD

**Issue by jpwsutton** [node-red/node-red-dashboard#33]
Following the instructions in the readme currently don't work because node-red-dashboard is not published on npmjs: https://www.npmjs.com/package/node-red-dashboard (404)

Is this because it's not considered ready for the general community to use? If so, maybe a note on the readme might be quite useful.

**Comment by knolleary** [comment]
Please see the very first line of the readme

**Comment by jpwsutton** [comment]
Apologies, Looks like I need some coffee!
