### ISSUE TITLE
Switch state updating issue

### ISSUE THREAD

**Issue by teddybee** [node-red/node-red-dashboard#330]
I would like to put on a switch that updates its state as well if something changes in an mqtt subject, also it can control that value as well. 
If I connect the switch's input to the mqtt in and as well the output to mqtt out, it will turn into infinite loop. (maybe this is normal)
But if I don't bind it's input it doesn't update its state. 

I am new in node-red, maybe there is a workaround for this, but it would be simpler if there will be some option to do this without a flood.

NodeJS 6.11.0
Node-RED 0.17.5
node-red-dashboard 2.7.0

**Comment by knolleary** [comment]
By default, the Switch will pass through anything to receives to its output. This causes the loops you see.

But you can turn off this behaviour by unticking the option in the node's edit dialog:

<img alt="cursor_and_node-red" src="https://user-images.githubusercontent.com/51083/34276379-12585590-e699-11e7-965f-63e035bfd4ab.png">

**Comment by dceejay** [comment]
as per contribution guidelines please use the mailing list or slack channel for how-to type questions.

in the meantime - just untick 
![image](https://user-images.githubusercontent.com/5375409/34276406-309ea46e-e699-11e7-9a9a-e6ab02b0c45c.png)

**Comment by teddybee** [comment]
Ahh sorry, I see now, too litle texts... :) Thank you for the help.
