### ISSUE TITLE
switch node.status() with "state of the input"

### ISSUE THREAD

**Issue by openSoftMan** [node-red/node-red-dashboard#335]
Node-RED version: v0.17.5
Node.js  version: v6.11.0
Dashboard version 2.7.0 started at /ui

The switch node.status() is not set correctly when using "Switch icon shows the state on the input".
An easy way to replicate:
1) Add a switch to palette and connect nothing to it.
2) Deploy.
3) Go to dashboard, click on the switch. It won't change, as expected, but you'll get this in the editor:
![state](https://user-images.githubusercontent.com/10749849/34423796-947f6de4-ebec-11e7-8424-3be7bc308f0d.png)

I often use "state of the input" with pass through disabled as it provides an "ACK" via mqtt on the input. 

I do like the node.status() added to the editor [or admin "dashboard" :-)]

Many thanks for the team's work.

Here's a simple test flow:
`[{"id":"43ac403f.70aee8","type":"ui_switch","z":"8148b300.043618","name":"state of the input","label":"test","group":"3c304387.072db4","order":29,"width":"5","height":"1","passthru":false,"decouple":"true","topic":"","style":"","onvalue":"1","onvalueType":"num","onicon":"","oncolor":"","offvalue":"0","offvalueType":"num","officon":"","offcolor":"","x":890,"y":320,"wires":[[]]},{"id":"8e5efc02.add43","type":"inject","z":"8148b300.043618","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"x":710,"y":300,"wires":[["43ac403f.70aee8"]]},{"id":"c000353f.55417","type":"inject","z":"8148b300.043618","name":"","topic":"","payload":"0","payloadType":"num","repeat":"","crontab":"","once":false,"x":710,"y":340,"wires":[["43ac403f.70aee8"]]},{"id":"3c304387.072db4","type":"ui_group","z":"","name":"dG homeMation","tab":"80814172.931bd","order":1,"disp":false,"width":"6"},{"id":"80814172.931bd","type":"ui_tab","z":"","name":"Control","icon":"wb_incandescent","order":1}]`

**Comment by dceejay** [comment]
that's because the status is showing the status of the output and not the input - ie the last message it sent.

**Comment by openSoftMan** [comment]
Probably should have brought this up in groups, but here we are.
The feature request [here](https://github.com/node-red/node-red-dashboard/issues/314)  mentions inputs changes.  I understand that node.status({}) is updated on output.  But I think the intentions of the feature were to show the status of the input.

if checked, code would remain the same.
![checked](https://user-images.githubusercontent.com/10749849/34425888-c6aad0c6-ebfe-11e7-81bb-9637277f485c.png)

else
![unchecked](https://user-images.githubusercontent.com/10749849/34425857-58c1b9e4-ebfe-11e7-90c0-5c50fc349e61.png)
node.status would show input.

I'm now using dashboard to troubleshoot the editor.  I wouldn't be opposed to reverting this change all together.
-Thanks for your time.

**Comment by dceejay** [comment]
The request says "to show the state of the switch" which is the output state, not the state of the icon.

**Comment by openSoftMan** [comment]
I understand your thoughts on this.  Maybe disable node.status() if pass through is disabled on the switch when the state of the input is selected?

In this unique situation where the state of the switch is the input, it should show that.  The input does change the state of the switch,  just not node.status().  The icon is the state of the switch.

I also notice, for the other nodes, where this feature was added, that the behavior is the same.  I have an mqtt retained message to populate the fields at startup and never again.

In this simple flow, the node status shows the "state of what was entered in the dashboard".

`[{"id":"acd3ca41.672de8","type":"inject","z":"a5704b4f.6b2168","name":"","topic":"","payload":"5","payloadType":"num","repeat":"","crontab":"","once":false,"x":130,"y":2600,"wires":[["54e96c76.8d5f34"]]},{"id":"1633b355.009515","type":"inject","z":"a5704b4f.6b2168","name":"","topic":"","payload":"9","payloadType":"num","repeat":"","crontab":"","once":false,"x":130,"y":2640,"wires":[["54e96c76.8d5f34"]]},{"id":"54e96c76.8d5f34","type":"ui_numeric","z":"a5704b4f.6b2168","name":"","label":"numeric","group":"9e19efea.c5c488","order":0,"width":0,"height":0,"passthru":false,"topic":"","format":"{{value}}","min":0,"max":10,"step":1,"x":280,"y":2620,"wires":[[]]},{"id":"9e19efea.c5c488","type":"ui_group","z":"","name":"Sunset","tab":"ea27cc67.376e7","order":1,"disp":false,"width":"6"},{"id":"ea27cc67.376e7","type":"ui_tab","z":"","name":"Timers","icon":"hourglass_empty","order":12}]`

The problem lies with pass through.  I've also noticed today that dashboard values go blank in the nodes where status is not shown with pass through disabled.  I can't replicate this right now, but I've never had an issue until now.

There are many nodes to debug issues.  Please consider reverting this change.

Thanks.

**Comment by dceejay** [comment]
OK - let's try and break this down a bit.

The switch is a bit of a special case as - as well as passthru or not - you can also set it to folow the input or the output. So yes there is a case to be made for the switch showing more status - maybe something like
![image](https://user-images.githubusercontent.com/5375409/34455770-06bb2db6-ed7e-11e7-90e7-4bdb4dc92954.png)
This would only need to apply to not passthru mode of course...
where the blob reflects the indicated value of the switch (as seen in UI) - and the left word is the last state of the input and the right the last state of the output... but the colour of the blob will track the dashboard indication. The Caps indicates which one the blob is tracking.



Not sure what you mean by "There are many nodes to debug issues. Please consider reverting this change."  - Reverting this would just mean removing all status messages, as it was just the indicators that were added, no other logic change.

**Comment by openSoftMan** [comment]
Happy New Year! ...took a few days off for the holiday.

This looks good.

What help me a lot, I went through all dashboard nodes and added a superscript ¹ to all dash nodes with  passthru enabled.

I meant by "There are many nodes to debug issues".  An "advanced" user, could show input/output on their own.  And for "Please consider reverting this change", I meant removing all node status on dashboards nodes.

I will certainly test an npm release or from another git branch.

Thanks again.

**Comment by dceejay** [comment]
Hi - pushed to master (not npm).

The basic feature won't be reverted. You can of course turn off all status indicators using menu - settings.

**Comment by openSoftMan** [comment]
Just installed via my dashboard_git_install.sh  I haven't used that script in "forever".  It still works, I created it early on.

At startup, via a retained mqtt msg:
![startup](https://user-images.githubusercontent.com/10749849/34507392-78b7e2f6-f003-11e7-8f3f-940b84e4907b.png)

After startup, where the state of the input is selected and with passthru disabled, sending mqtt msg from another app:
![state_of_input](https://user-images.githubusercontent.com/10749849/34507459-0ed944dc-f004-11e7-9133-e13e06d407d7.png)

Thanks for working through this.  I will further test the other nodes and report back.

**Comment by openSoftMan** [comment]
As OP, resolved.
