### ISSUE TITLE
Cannot find a way to only display groups vertically regardless of browser window

### ISSUE THREAD

**Issue by nospam2k** [node-red/node-red-dashboard#337]
Is there a way to force all groups only in one column regardless of whether the group width and browser width allow for multicolumn?

**Comment by dceejay** [comment]
Hi 

As per the contribution guidelines in general we prefer general questions like this in either the slack channel or the google mailing list.

(but to answer you question - yes you can use a ui_template to set the container css width to whatever you wish. eg

[{"id":"3538f7d2.59fd78","type":"ui_template","z":"7ad2df3.90a8a2","group":"8918a0a9.e593f","name":"","order":0,"width":0,"height":0,"format":"<style>\n    .masonry-container {\n        max-width: 1024px;\n        width : 1024px;\n    }\n</style>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"global","x":200,"y":960,"wires":[[]]},{"id":"8918a0a9.e593f","type":"ui_group","z":0,"name":"demo","tab":"1529594.75e03a7","order":2,"disp":true,"width":"6"},{"id":"1529594.75e03a7","type":"ui_tab","z":"7ad2df3.90a8a2","name":"demo","icon":"wi-wu-cloudy","order":2}]
