### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by IowaR8** [node-red/node-red-dashboard#338]
Newly updated Raspi 3, tried to install through terminal npm install command or through the palette install in the node-red browser window, I get the same error result, see below.
Other installs have worked.
I don't know what to try next. Thanks for any help.

pi@raspberrypi:~/.node-red $ npm install node-red-dashboard
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! path /home/pi/.node-red/node_modules/meshblu/node_modules/ansi-styles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/pi/.node-red/node_modules/meshblu/node_modules/ansi-styles' -> '/home/pi/.node-red/node_modules/meshblu/node_modules/.ansi-styles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-01-09T03_07_29_328Z-debug.log

**Comment by dceejay** [comment]
Which version of node.js ? Why is it referring to meshblu ? That is not one of our nodes ?

**Comment by IowaR8** [comment]
node.js was updated as part of the update of node-Red. I don't know how to find out the version. I updated yesterday.
The meshblu folder was created by ?. I updated node-red and installed a few extra nodes (mostly Rpi GPIO). I don't know what it is or where it came from exactly.
Inside the meshblu folder are 'node modules', 'src' and 'test' folders, a few files.
The read me file is included here. This seems to be the source of the trouble indeed.
[README.txt](https://github.com/node-red/node-red-dashboard/files/1616182/README.txt)

**Comment by dceejay** [comment]
I suspect you have a few extra nodes installed... normally in your ~/.node-red/node_modules directory

Depends how much you want them - you can delete them and re-install - or you could try going into that directory and typing
    npm rebuild
    npm update

**Comment by IowaR8** [comment]
Tried rebuild-update. Still get error.
I will try deinstalling nodes.

**Comment by dceejay** [comment]
ah - do you have node-red-contrib-gpio ?

**Comment by IowaR8** [comment]
Yes
