### ISSUE TITLE
Devices created & listed on dashboard disappear when modification/deploy is made in editor

### ISSUE THREAD

**Issue by hovig** [node-red/node-red-dashboard#340]
Devices are disappearing from the list in the node-red dashboard after a deploy (no major code change, sometimes no code change) is made in the editor.
Created devices:
![image](https://user-images.githubusercontent.com/5958327/34884175-8fd1122a-f781-11e7-969f-45bec0cc43a9.png)
After the deploy in the editor ![image](https://user-images.githubusercontent.com/5958327/34884753-52ce7190-f783-11e7-82f1-884f0c83c6e1.png), the devices are gone (refreshed the page and still not shown):
![image](https://user-images.githubusercontent.com/5958327/34884294-ec993a3c-f781-11e7-8e96-5961888d53eb.png)

**Comment by knolleary** [comment]
That table must be a custom ui_template widget, rather than a core widget supplied with the dashboard. So any problem will be with that custom code and how the ui_template node is configured. Check you have the `Add output messages to stored state.` option ticked in the template node.

**Comment by dceejay** [comment]
closing - no response
