### ISSUE TITLE
node config options missing

### ISSUE THREAD

**Issue by goofballtech** [node-red/node-red-dashboard#343]
I am migrating node-red over from one rasPi3 to another and trying to get my dashboard up and running again. The original was running the full Rasbian and now i am running light so i had to manually install Node-Red. I used the nodered.org page for guidance int he install. 

My issue, as illustrated in the below screen shots, is that the node properties aren't what i expect them to be. I don't know how to properly configure a node in the dashboard without having the config options that are present in the 'old-node' graphic. 

I'm pretty sure i am doing something wrong. At one time I also installed one of the 'ui' nodes as well and have since removed it again. Please let me know if i can provide anything else that would narrow down the source of the change. 

Both are running node-red 0.17.5. Both are running 2.7.0 of the dashboard. 

*note - i have upgraded the new pi to 2.8.0 of dashboard in troubleshooting but the issue is present with both versions. 

![old-node](https://user-images.githubusercontent.com/8220165/35025213-ca2dd10c-fb09-11e7-827c-d06f0105e316.JPG)
![new-node](https://user-images.githubusercontent.com/8220165/35025214-ca3c621c-fb09-11e7-8f72-17354733974b.JPG)

**Comment by dceejay** [comment]
Hi,
as per our contribution guidelines we prefer general help and how-to type topics to be raised via the mailing list or slack channel where more people can see them and help get it resolved, leaving the issues list for actual software bugs.
Yes it looks like you have some old contrib-ui nodes still installed, they need to be removed and the node-red-dashboard re-installed. They can probably be found in ~/.node-red/node-modules directory somewhere.
