### ISSUE TITLE
ui_numeric node: Pressing down keeps repeating

### ISSUE THREAD

**Issue by HarmOtten** [node-red/node-red-dashboard#344]
When I use a numeric node on my dashboard and press the down arrow, sometimes it does not only go down one step, but keeps counting down until it's configured min. Until now, this only happens sometimes, and only when I use the dashboard on my iPhone.

Used flow:`[{"id":"cc599bc6.8f9978","type":"inject","z":"79976831.5ca708","name":"","topic":"","payload":"10","payloadType":"num","repeat":"","crontab":"","once":false,"x":90,"y":740,"wires":[["4bcb44b7.bb7a1c"]]},{"id":"4bcb44b7.bb7a1c","type":"ui_numeric","z":"79976831.5ca708","name":"","label":"numeric","group":"11eec0f.f02133f","order":0,"width":0,"height":0,"passthru":false,"topic":"","format":"{{value}}","min":0,"max":10,"step":".5","x":280,"y":740,"wires":[["8b051b71.805848"]]},{"id":"8b051b71.805848","type":"function","z":"79976831.5ca708","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"x":440,"y":740,"wires":[[]]},{"id":"11eec0f.f02133f","type":"ui_group","z":"","name":"Test","tab":"a91b0aeb.f9a628","order":1,"disp":true,"width":"6"},{"id":"a91b0aeb.f9a628","type":"ui_tab","name":"Tab 2","icon":"dashboard","order":2}]`

Node-RED v0.17.5
node-red-dashboard v2.7.0
node.js v6.12.3
Browser: Google Chrome iOS v 60.0.3112.72
iOS v11.2.2

**Comment by dceejay** [comment]
Thanks for reporting.
Is this only on down ? 
Is it to do with the 0.5 increments changing the width, moving the button ?

**Comment by HarmOtten** [comment]
I did a little more research.
Until now it only happens when pressing down, in combination with the length of the number getting longer! So for instance when it changes from 8 to 7.5, or from 9 to 8.9. In those cases, the down arrow moves a little bit to the left.
When it happens, and I let it count down all the way, in the end it looks like this:
![numeric](https://user-images.githubusercontent.com/10838083/35419851-9e236ec2-023a-11e8-8398-8d9220f51c36.png)
It looks like an imaginary finger is still pressing the down arrow.
Sometimes I even can not stop the down-counting by pressing up again. Then I have to reset the page to get it back to normal again.

**Comment by dceejay** [comment]
Did you get a chance to try the/a fix (on master) - not npm ?

    cd ~/.node-red && npm i node-red/node-red-dashboard

**Comment by HarmOtten** [comment]
Not yet. I am currently setting up a new test environment. As it is not in npm yet, what command do I need to use to get the improved version of Node-RED Dashboard?

**Comment by Paul-Reed** [comment]
npm i node-red/node-red-dashboard

**Comment by HarmOtten** [comment]
Yes, I saw that command, but I don't understand. He said the change is not in npm yet, but still I can install it using the npm command?

**Comment by dceejay** [comment]
yes - as per command above - it is smart enough to recognise the node-red/ bit and guess that it may be on github.

**Comment by dceejay** [comment]
PS - now released on npm as 2.8.1

**Comment by HarmOtten** [comment]
I created a separate test environment with the latest Node-RED v0.18.3 and node-red-dashboard v2.8.1, and tested the issue.
Result: When counting down from 8 to 7.5 the issue is indeed solved, but the space used is wider then necessary and when using bigger numbers (like 2000.5), the issue still exists.
So if the length of "˅ nnn.n ˄" does not change, it works, but the solution should (in my opinion) be a bit better then just setting a minimum length.
Solution hint: take the highest possible number that can be selected in this numeric node, and include the decimal places. Then calculate the total length by filling every digit with for instance a "2" (at least not a "1"!), and use that length as the minimum length.
Please let me know if you need more info.

**Comment by dceejay** [comment]
Happy to consider a PR or code to do that

**Comment by HarmOtten** [comment]
I assume you are asking me. Is there some documentation of the dashboard-code, or can you point me in the right direction where this should be coded? Then I am happy to program it.

**Comment by dceejay** [comment]
Hi - the place to look will be around src/components/ui-component/templates/numeric.html line 12 and   src/components/ui-component/templates/numeric.css - but probably want to do the maxWidth calculation in src/components/ui-component/ui-component-ctrl.js line 50.

**Comment by HarmOtten** [comment]
This is my sugestion.
src/components/ui-component/ui-component-ctrl.js line 50:
```
case 'numeric': {
var intLength = me.item.min.toFixed().length>me.item.max.toFixed().length ? me.item.min.toFixed().length : me.item.max.toFixed().length;
var dec = Math.round((me.item.step - Math.round(me.item.step))*10000)/10000;
var decLength = dec>0 ? dec.toString().length-2 : 0;
var minWidth = Math.round(intLength*9.2 + (dec>0?4.36:0) + decLength*9.2 + 0.4);  // [px]
...
```
Then minWidth should be used as minimum width for the numeric value, in:
src/components/ui-component/templates/numeric.css
or
src/components/ui-component/templates/numeric.html

Different fonts might need some extra adjustments in the above factors.
Please tell me what you think about it.

**Comment by dceejay** [comment]
Yes. Not sure it needs to be quite that precise given different fonts, and yes I did forget to take min value into account. So def better than mine.

**Comment by HarmOtten** [comment]
I might have a better and more simple solution. Instead of calculating the maximum width, it is also possible to make sure that the width does not change at all, by showing the 0-decimals!
The function .toFixed(number_of_decimals) is perfect for that. The only difference is, that the result is a string instead of a number. So when reading the numeric value, a Number(value) might be necessary.
What do you think of this?

**Comment by dceejay** [comment]
Certainly worth considering

**Comment by dceejay** [comment]
though given the fact that it's the change of width that causes the issue... then fixing it woudl probably be best.. I'm currently think something simple like this would do for the majority of cases.

    var mnw = (me.item.min + me.item.step).toString().length * 10;
    var mxw = (me.item.max + me.item.step).toString().length * 10;
    me.item.minWidth = mnw > mxw ? mnw : mxw;

**Comment by HarmOtten** [comment]
Although it would be nice to solve the real problem (no repeating, even when the button moves), I think your proposal would be a nice workaround.
By the way, do not forget the take the [Value Format] into account. It could contain extra characters, for instance, "{{value}}**°C**".

**Comment by dceejay** [comment]
good spot - how about

    var regex = /({{([^}}]+)}})/ig
    var fl = me.item.format.replace(regex, "").length * 7;
    var mnw = (me.item.min + me.item.step).toString().length * 10;
    var mxw = (me.item.max + me.item.step).toString().length * 10;
     me.item.minWidth = (mnw > mxw ? mnw : mxw) + fl;

**Comment by HarmOtten** [comment]
Looks good!
Just one thing. I would both 7 and 10 replace with 9.5, that should be wide enough.
Do you agree?

**Comment by dceejay** [comment]
let's go with that for now.

**Comment by HarmOtten** [comment]
Ok, let me know when it can be tested.
