### ISSUE TITLE
Round/Square indicators?

### ISSUE THREAD

**Issue by Jasurf** [node-red/node-red-dashboard#345]
Hi,
I would love to see and indicator that can change colors based on a boolean state.
be able to choose either round or square, then change color based off a on/off state.
Any change this can be added to the Dashboard?

**Comment by dceejay** [comment]
Hi, as per the contribution guidelines we prefer general how-to type questions and ideas to be rasied via the google group mailing list or slack channel first.
This already be accomplished in several ways..
1) use a switch node as an indicator - you can select both the on and off icons and colors,
2) use a text node and either send it html - or provide it a template - for example

  
  [{"id":"40799c16.9074e4","type":"ui_switch","z":"3ee56046.c933c","name":"","label":"switch1","group":"ca294884.9f6a68","order":6,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":490,"y":304,"wires":[["98cb3fdd.b62cc"]]},{"id":"98cb3fdd.b62cc","type":"ui_text","z":"3ee56046.c933c","group":"ca294884.9f6a68","order":4,"width":"1","height":"1","name":"on/off","label":"","format":"<font color={{(msg.payload?\"yellow\":\"grey\")}}><i class=\"fa fa-lightbulb-o fa-2x\"></i></font><br/><font size=\"-2\">World</font>","layout":"row-center","x":650,"y":304,"wires":[]},{"id":"ca294884.9f6a68","type":"ui_group","z":"3ee56046.c933c","name":"Click","tab":"513b7ff4.3de5d","order":1,"disp":true,"width":"5"},{"id":"513b7ff4.3de5d","type":"ui_tab","z":"3ee56046.c933c","name":"Home","icon":"link","order":1}]

**Comment by Jasurf** [comment]
Hi Dave,
Will you please re-copy me the example you pasted below?
I am unable to import this into node-red on the clipboard, the import button just stays disabled after I paste it.

Thank you so much!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dceejay** [comment]
Apologies

[{
		"id": "40799c16.9074e4",
		"type": "ui_switch",
		"z": "3ee56046.c933c",
		"name": "",
		"label": "switch1",
		"group": "ca294884.9f6a68",
		"order": 6,
		"width": 0,
		"height": 0,
		"passthru": true,
		"decouple": "false",
		"topic": "",
		"style": "",
		"onvalue": "true",
		"onvalueType": "bool",
		"onicon": "",
		"oncolor": "",
		"offvalue": "false",
		"offvalueType": "bool",
		"officon": "",
		"offcolor": "",
		"x": 490,
		"y": 304,
		"wires": [
			["98cb3fdd.b62cc"]
		]
	}, {
		"id": "98cb3fdd.b62cc",
		"type": "ui_text",
		"z": "3ee56046.c933c",
		"group": "ca294884.9f6a68",
		"order": 4,
		"width": "1",
		"height": "1",
		"name": "on/off",
		"label": "",
		"format": "<font color={{(msg.payload?\"yellow\":\"grey\")}}><i class=\"fa fa-lightbulb-o fa-2x\"><font size=\"-2\">World",
		"layout": "row-center",
		"x": 650,
		"y": 304,
		"wires": []
	}, {
		"id": "ca294884.9f6a68",
		"type": "ui_group",
		"z": "3ee56046.c933c",
		"name": "Click",
		"tab": "513b7ff4.3de5d",
		"order": 1,
		"disp": true,
		"width": "5"
	},
	{
		"id": "513b7ff4.3de5d",
		"type": "ui_tab",
		"z": "3ee56046.c933c",
		"name": "Home",
		"icon": "link",
		"order": 1
	}
]

**Comment by Jasurf** [comment]
Ugh!  So sorry, it still will not work when pasting it into the clipboard.
Maybe put it in a text file and email it??

Again so sorry and thank you for your help Dave,

D. Jason Hone
d.jason.hone@outlook.com
801-361-4153

**Comment by dceejay** [comment]
Hi...

OK - well - let's try this... It was just a switch and a text node...  
![image](https://user-images.githubusercontent.com/5375409/35668977-7e51a5be-072b-11e8-8646-d04285720d91.png)
with the switch set to send true/false (default) and the text node set with value format like this

    <font color={{(msg.payload?"yellow":"grey")}}><i class="fa fa-lightbulb-o fa-2x"></i></font><br/><font size="-2">World</font>

**Comment by Jasurf** [comment]
Ok, that was super helpful!
Where can I see and choose from possible icons I can use besides the light bulb?
Thank you so much again for your help,

Jason Hone

**Comment by dceejay** [comment]
https://fontawesome.com/v4.7.0/icons/
