### ISSUE TITLE
scope.send within UI_Template triggers endless loop

### ISSUE THREAD

**Issue by fahrvergnuugen** [node-red/node-red-dashboard#346]
I believe this is a bug. 

I'm trying to create and send a message from a UI_Template, but in doing so the flow enters an endless loop.

Here is a simple flow that will illustrate it:
`[{"id":"995deb31.9c80a8","type":"ui_template","z":"5e6c4198.9d6f18","group":"64704468.613964","name":"","order":0,"width":0,"height":0,"format":"<script>\n(function(scope){\n    scope.$watch('msg', function(msg) {\n        console.log(\"Msg sent\")\n         scope.send({payload: \"something\"});\n    });\n})(scope);\n</script>\n\n\n{{msg}}\n","storeOutMessages":true,"fwdInMessages":false,"templateScope":"local","x":520,"y":1060,"wires":[[]]},{"id":"f4e693f3.9d2778","type":"inject","z":"5e6c4198.9d6f18","name":"","topic":"Test","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":340,"y":1060,"wires":[["995deb31.9c80a8"]]},{"id":"64704468.613964","type":"ui_group","z":"","name":"Default Group","tab":"ef22f042.de6a1","disp":true,"width":"16"},{"id":"ef22f042.de6a1","type":"ui_tab","z":"","name":"Home Tab","icon":"dashboard"}]`

Deploy this flow, then open the Dashboard and check the browser's console. You will see `Msg sent` repeating endlessly.

**Comment by Hugobox** [comment]
This is expected behavior as you have ticked the box "Add output messages to stored state." which changes the scope.msg on every scope.send which triggers the scope.$watch which triggers the scope.send...

**Comment by dceejay** [comment]
Closing thanks to @hugobox pointing out the obvious :-)
