### ISSUE TITLE
Gauge of type "level" is too big

### ISSUE THREAD

**Issue by theminor** [node-red/node-red-dashboard#347]
The circular gauges of type "level" are too big. The gauge covers up the label. The circle probably ought to be the same size as the "donut" type gauge.

Here is what they look like side-by-side:

![untitled](https://user-images.githubusercontent.com/6283823/35588005-6497833c-05cd-11e8-9a1e-522b3167bfa5.png)

**Comment by dceejay** [comment]
Hi thanks - we prefer general comments and how to questions via the google group or via he slack channel.
It is "as designed" - so not about to change, but thank you for the feedback.
