### ISSUE TITLE
Layout options enhancement

### ISSUE THREAD

**Issue by i8beef** [node-red/node-red-dashboard#348]
This is an enhancement thought. The problem I'd like to solve is a desire for some more manual positioning of elements in the dashboard. While I recognize that's probably a full rewrite of the positioning approach, and is not feasible, what about allowing for a maximum column width on a tab? This would allow one to constrain the main container to a smaller size on larger resolution screens, and thus have just a tiny bit more control over how things align.

The main thing I'm looking to do a little better is not having a single line of 4 groups on a tab, but being able to constrain it a bit so they end up stacking as 2 lines of 2 groups.

Alternatively, being able to place groups inside of groups could work as well, as groups have column constraints... in fact that might be even more flexible in the long run in allowing people to group things and align them in a much more controlled manner...

**Comment by dceejay** [comment]
Hi thanks for the suggestion, we prefer general how-to questions via the google group or via the slack channel. You are right, we aren't about the re-write the dashboard any time soon... hapy for oother to have a go if they like.

You can constrain the max-width as per this post https://groups.google.com/forum/#!searchin/node-red/max-width%7Csort:date/node-red/ka9z9TdJcro/CXtOig54CQAJ

basically create a ui_template as per
![image](https://user-images.githubusercontent.com/5375409/35591610-7f911808-0602-11e8-8d15-3c8ff6d4e349.png)
