### ISSUE TITLE
Invisible Graph Plots

### ISSUE THREAD

**Issue by DeanCording** [node-red/node-red-dashboard#349]
I'm having a problem with data plots turning invisible on graphs over time.
![invisible](https://user-images.githubusercontent.com/251170/35594764-0bf320cc-0660-11e8-9353-01ff0696b637.png)

On this graph, there is a plot which shows data points when you mouse over them but the line does not show.  This graph was displaying a data plot last night but it had vanished this morning.  I've had this occur often.

**Comment by dceejay** [comment]
how many points do you have and how far apart are they ? looks like a very short timescale... Not sure how chart.js handles this when multiple points are co-located and the line length maybe less than one display pixel worth.

**Comment by DeanCording** [comment]
Lots - a point every 4 seconds over a 24 hour period.  That's probably the cause - the horizontal distance would be less than 1 pixel.  Interesting it doesn't show the vertical.

**Comment by dceejay** [comment]
oh - it's supposed to fill the screen ? (I thought this was related to your other issue with old data)
hmm - that is odd...
Did you try either/both of the enlarge points option or the different interpolation options ?

**Comment by DeanCording** [comment]
Yes, it is supposed to fill the entire screen.  Interesting that it is a 1 day graph but stopped working before the full day's worth of data was received.  I'd suggest your right about it being due to too many data points - there would be 15,000 on the example graph.

I haven't tried fiddling with any settings.

**Comment by DeanCording** [comment]
I've got another graph where only one data channel has gone invisible and it is the high data rate channel as well - the lower data rate channels show up fine.

**Comment by dceejay** [comment]
so you are fitting 15000 data points across about 300 screen pixels... methinks some data reduction/aggregation maybe in order...

**Comment by DeanCording** [comment]
But I like my data to look like a smear across the screen :-)
