### ISSUE TITLE
dashboard takes significant CPU resource

### ISSUE THREAD

**Issue by kusumy** [node-red/node-red-dashboard#352]
Why  dashboard take a lot CPU resource? In my laptop it can take 60% CPU, in other computer can take nearly 90%. Is it normal?

**Comment by dceejay** [comment]
Hi, in general we prefer question via the mailing list or slack channel so the widest possible audience can get to see and help answer them.

Short answer is it can do... but usually only if you have a very busy UI with lots of gauges and charts updating rapidly. If you only have a few updating then it should be ok. Also for charts you must remember to limit the amount of data shown (either by time or number of readings shown) or there will be a lot of data being moved around on every update.
