### ISSUE TITLE
Dynamic max / min in a gauge

### ISSUE THREAD

**Issue by Silvia-t** [node-red/node-red-dashboard#355]
Hi all,

I'm trying to dynamically configure the max / min in a gauge.

I've been reading this: https://github.com/node-red/node-red-dashboard/blob/master/config-fields.md so it seems like it's possible to do, but it doesn't work.

As recommended in the link, I'm setting a max and a min trough the editor (10 and 0 to be used as defaults). On top of this, I'm sending a msg to the gauge like this:

```
msg.ui_gauge = {"max": 15, "min": 5};
return msg;
```

But it doesn't change the max / min values.

I've also tried sending `msg.payload = {"max": 15, "min": 5};`, 

and `msg.payload.ui_gauge = {"max": 15, "min": 5};` and even doing 

```msg.ui_gauge = {};
msg.ui_gauge.max = 15;
return msg;
```
but no luck.

I'm using
- node v6.12.3
- node-Red v0.17.5
- node-red-dashboard v2.8.1

Any thoughts? Thanks.

EDIT: I've just seen the ui control node, but still can't figure it out. I'd appreciate if someone could point me in the right direction. Thanks again! :)

**Comment by knolleary** [comment]
You should set `msg.ui_control`:

```
msg.ui_control = {"min":5,"max":15}
return msg;
```

**Comment by Silvia-t** [comment]
Thanks so much @knolleary :+1: 

The changes only take effect after a page refresh though, is this what's meant to happen? Cheers!! :D

**Comment by knolleary** [comment]
@Silvia-t no, they should take affect immediately - that is the behaviour I see.

**Comment by Silvia-t** [comment]
Working now, I've rebooted! :) Thanks again!!
