### ISSUE TITLE
x-axis sets to zero

### ISSUE THREAD

**Issue by vkiselyov** [node-red/node-red-dashboard#356]
Hi. I have some problem with chart.
I build this Flow
![image](https://user-images.githubusercontent.com/35599680/36529790-6d353110-17ca-11e8-9566-0ba3dd7d653d.png)

After deploy i see this picture
![image](https://user-images.githubusercontent.com/35599680/36530711-df995a18-17cc-11e8-832e-782b1295e6f6.png)
Chart contain more than one value;
But shown only one line and x-axis is ZERO.
Whats wrong?

**Comment by dceejay** [comment]
as per contribution guidelines we prefer general how-to type questions via the mailing list (Google group) or slack channel. 

You  don't actually say or show what data you are sending or in what format. They chart just expects a number.

**Comment by vkiselyov** [comment]
Hi. Thanks for you attention.
From mqtt topic i receive integer value from -20000 to 20000

**Comment by dceejay** [comment]
please show the output of one of the debug nodes - and the actual config of the chart node.
Which version of dashboard are you using (printed in console.log at startup)

**Comment by vkiselyov** [comment]
Sometimes chart show normal.
Node-RED version: v0.17.5
23 Mar 15:51:47 - [info] Node.js  version: v9.2.0
Dashboard version 2.6.2 started at /ui
![image](https://user-images.githubusercontent.com/35599680/36531972-8a482b1c-17d0-11e8-9611-206bda8cfe7f.png)

![image](https://user-images.githubusercontent.com/35599680/36531986-94c1abcc-17d0-11e8-9849-f59efa5e28da.png)

**Comment by dceejay** [comment]
which version of dashboard are you using ?
(You also have some bad string data in there - but we should be ignoring that)

**Comment by vkiselyov** [comment]
Dashboard version 2.6.2

**Comment by dceejay** [comment]
Can you please trying upgrading to latest version 2.8.1 and retest ? Thanks

**Comment by vkiselyov** [comment]
Hi. I update version of dashboard it doesn't help.

**Comment by dceejay** [comment]
what platform are you running on ? Is the hardware clock OK ?
(Some embedded platform don't have a realtime clock and so always start at 00:00 unless they sync up to a time server first).

**Comment by echtelerp** [comment]
i Seem to have the exact same issue. 
I have 5 Raspberries running almost the same Dashboards. 
only one of them has now the same issue with the x Axis time thing. 

If i type Date uns command line, it gives me the right time.

**Comment by echtelerp** [comment]
Any news on the Issue? 
some more infos I can provide: 
I have the issue on all of them, if they are not synchronized with a time Server. 
so it seems, that the local Time of the displaying device causes the problem as they are too far of from each other... 
I don't Know if that can be solved within nodeRed Dashboard. maybe by setting the Time from the device that NodeRed is running from?

**Comment by dceejay** [comment]
setting the time via ntp is not a Node-RED issue - but should be sorted.
If the devices have access to the internet they can be set to sync from pool.ntp.org
or if there is no internet available it is also possible to point to a local source - such as a laptop configured to run ntpd, or a device with a GPS. Configuring all those is beyond the scope of this.
