### ISSUE TITLE
Add autofocus to input node property

### ISSUE THREAD

**Issue by erwrow** [node-red/node-red-dashboard#359]
as the title says, can you add that property? it's really messy to implement it using ui_template.

**Comment by dceejay** [comment]
Which input ? What happens when you have more than one ? Each node is independant so won't know of any others or which is top left for example.

**Comment by erwrow** [comment]
Sorry, i'm referring to the text input. I understand, the user could enable that property to all text inputs on the same tab. Although it would be nice to have the option.

**Comment by dceejay** [comment]
Is adding a template containing (below) overly complex ?

    <script>
        $("input:text:visible:first").focus();
    </script>

Adding tick boxes all over the place to let the user select autofocus is (IMHO) a bad idea as the browser behaviour when you have multiple selected by mistake is undefined (or is up to the browser implementation), as then the user then has to look through every node to untick all the "wrong" ones.

**Comment by erwrow** [comment]
the solution that was reached in the node-red google groups (https://groups.google.com/forum/#!topic/node-red/Ip6bAnh01t0) was a little more complex. Thanks a lot for this way simpler solution

**Comment by Silvia-t** [comment]
Hi, thanks for this great solution :)

I know this is closed but does anyone know how to have the focus on one textbox, and when 'enter' is pressed move the focus to another? Thanks!

**Comment by dceejay** [comment]
the nodes don't know about each other so not possible to do simply - maybe use tab instead of enter ?

**Comment by Silvia-t** [comment]
I want to use this with a barcode scanner so it will send enter after scanning. If not I guess using a form might be easier.

**Comment by khangvan** [comment]
Could you find alternative solution to autofocus at one textbox? It’s happy to have this property!
