### ISSUE TITLE
Template node not properly configured

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#363]
When setting a template node to type "added to site &lt;head&gt; section" it creates a "not properly configured" popup and has the red triangle as long as the hidden group selector is on "default [unassigned]". Workaround possible through switching to type "Widget in Group", choosing a valid group and switching back to "added to site &lt;head&gt; section". 
Testet with node-red-dashboard@2.8.2 and node-red@0.18.4

**Comment by dceejay** [comment]
Hi - can you describe in more detail how to re-create this ?
I started with a blank project - added a blank ui-template node - set it to add to head - then done and deploy - no red triangle/no warnings.

**Comment by hobbyquaker** [comment]
Just tried to reproduce with a fresh installed node-red - and yes, you're right, it does not occur. When I do the same on my "production" node-red instance I can reproduce it. Difference is: on my "production" instance the Group dropdown is preselected with `Default [unassigned]`, on the fresh installed one it is `Add new ui_group...`. Perhaps some leftovers from playing around with node-red-dashboard in previous versions or smth... 
Ok for me to close the issue as it seams to occur only under uncommon conditions and can be resolved by workaround.

**Comment by dceejay** [comment]
Ok thanks - will keep an eye out for it again. but will close for now.

**Comment by ajitam** [comment]
This "bug" is back (0.18.7)

**Comment by knolleary** [comment]
@ajitam 0.18.7 is the Node-RED version. What version of Node-RED Dashboard are you using?

**Comment by ajitam** [comment]
Yes, sorry about that.

Last entry in CHANGELOG is

```
### 2.9.6: Maintenance Release
```
