### ISSUE TITLE
Error: node-red-dashboard@2.8.2 postinstall: `node fixfa.js`

### ISSUE THREAD

**Issue by net2action** [node-red/node-red-dashboard#364]
Hi i try to install on Ubuntu 16.4 LTS + xUbuntu

Welcome to Node-RED
===================

13 Mar 08:16:08 - [info] Node-RED version: v0.18.4
13 Mar 08:16:08 - [info] Node.js  version: v4.2.6
13 Mar 08:16:08 - [info] Linux 4.4.0-116-generic x64 LE
13 Mar 08:16:08 - [info] Loading palette nodes
13 Mar 08:16:09 - [warn] ------------------------------------------------------
13 Mar 08:16:09 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
13 Mar 08:16:09 - [warn] ------------------------------------------------------
13 Mar 08:16:09 - [info] Settings file  : /root/.node-red/settings.js
13 Mar 08:16:09 - [info] User directory : /root/.node-red
13 Mar 08:16:09 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
13 Mar 08:16:09 - [info] Flows file     : /root/.node-red/flows_ubuntu.json

when i try to install from Node-Red Settings\ pallete i recieved following error:

> node-red-dashboard@2.8.2 postinstall /root/.node-red/node_modules/node-red-dashboard
> node fixfa.js

module.js:328
    throw err;
    ^

Error: Cannot find module '/root/.node-red/node_modules/node-red-dashboard/fixfa.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "--save-prefix=\"~\"" "--production" "node-red-dashboard@2.8.2"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-red-dashboard@2.8.2 postinstall: `node fixfa.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-dashboard@2.8.2 postinstall script 'node fixfa.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node fixfa.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log

[npm-debug.log](https://github.com/node-red/node-red-dashboard/files/1807839/npm-debug.log)

**Comment by dceejay** [comment]
when running as root (which we don't recommend) you will need to use

    npm i --unsafe-perm node-red-dashboard
