### ISSUE TITLE
Gauge does not support html entities like &deg;

### ISSUE THREAD

**Issue by tbowmo** [node-red/node-red-dashboard#366]
While setting up a basic dashboard, representing temperatures, I discovered that the Gauge node does not support for example &amp;deg; in Value / Labels,

The Numeric node does, so figure that it's a small bug

**Comment by dceejay** [comment]
not that small - the gauge strips out any html (or rather just renders it as text)... but is will accept the degrees character just fine - °
![image](https://user-images.githubusercontent.com/5375409/37533735-a1fd505e-293a-11e8-8d0f-e6d9d0589779.png)
