### ISSUE TITLE
Require tinycolor minimized

### ISSUE THREAD

**Issue by cinhcet** [node-red/node-red-dashboard#367]
If deleting the dist folder, the color picker node does not work anymore, since the minimized version
require('../dist/js/tinycolor-min'); 
in the ui_colour_picker.js file is imported?

Is this intended?

dashboard version 2.8.2
node-red 0.18.4
node 8.10.0

**Comment by knolleary** [comment]
Not sure I follow... if you delete files used by the node, then the node doesn't work properly. Why would this be an issue?

**Comment by cinhcet** [comment]
as per readme:
> The plugin uses the dist folder if it exists. Make sure it has been deleted if you want to use the non-minified version while developing.
I think the node should still work even without the distribution files?
Like using
require('tinycolor2');
instead.

**Comment by knolleary** [comment]
Ah right, that puts it into context. Thanks.
