### ISSUE TITLE
UI_Form Expose Step and/or Min attributes for Numeric Input Field

### ISSUE THREAD

**Issue by scottrcarlson** [node-red/node-red-dashboard#368]
Requesting a Step and Min field for Numeric type input fields inside of UI_Form.

Chrome defaults to step="1" which limits the input to integer only. Setting to step="any" would be ideal to allow all floating point values, but may not work inside of a form.

Suggesting step="0.001" to account for "reasonable" range.

Thanks for the great work!

**Comment by dceejay** [comment]
Actually step="any" does seem to give best of both worlds... - up/down step still is 1 - but allows you to enter floating point...  Thanks.
