### ISSUE TITLE
Ghost nodes

### ISSUE THREAD

**Issue by PerMalmberg** [node-red/node-red-dashboard#37]
Hi,

Node version: 0.10.29
Node-RED Dashboard version: 2.0.1
Node-Red version: 0.14.5
Running on Raspberry Pi, Raspian (Jessie)

I've got an issue with NR Dashboard (2.0.1) in that it seems to create ghost groups. When I press deploy, I get the popup telling me that 

> You have some unused configuration nodes. Click here to see them

And yes, it does show such a node, "Spots [unassigned]". The global one doesn't seem to affect anything, but I didn't create that one afaik.
![config](https://cloud.githubusercontent.com/assets/2729388/17270690/8aeb0f14-5669-11e6-8c4d-24cdcbb125ef.PNG)

and double-clicking it to show the config for it, shows this:
![is_unassigned](https://cloud.githubusercontent.com/assets/2729388/17270691/a9bd5050-5669-11e6-9b78-0c204c54faaa.PNG)

I do have created a node with the name "Spots", but it is properly configured, as shown by these two images:
![tabs](https://cloud.githubusercontent.com/assets/2729388/17270703/dda0bbd2-5669-11e6-8e92-e88305fd2c2e.PNG)

![but does have a tab](https://cloud.githubusercontent.com/assets/2729388/17270706/e7c2506c-5669-11e6-89fa-8d456d338095.PNG)

Am I doing something wrong?

I've attached my flows, if that helps:
[flows_central.zip](https://github.com/node-red/node-red-dashboard/files/391895/flows_central.zip)

**Comment by knolleary** [comment]
You have two groups called 'spots' - the empty one is not assigned to a tab so doesn't show up in the dashboard sidebar... this is an edge case we need to handle - to make it more obvious you have a group (which may have widgets in), that isn't on a tab so won't be visible.

**Comment by PerMalmberg** [comment]
Hm, ok. I don't remember creating the second one, but what you say does make sense.

**Comment by dceejay** [comment]
Is this still a problem ? can we close ?

**Comment by knolleary** [comment]
No we cannot close - need to understand the routes that lead to this happening and figure out how to help the user avoid them.

**Comment by Paul-Reed** [comment]
Issue https://github.com/node-red/node-red-dashboard/issues/39 created a number of ghost nodes for me. I selected and deleted them earlier so unfortunately can't provide screenshots etc.

Paul

**Comment by dceejay** [comment]
Now addressed by fix a5991a512327fb8c5bbf947e05b95df1322cccbb
