### ISSUE TITLE
Show a decimal with two decimal places without rounding

### ISSUE THREAD

**Issue by NintendoPlayer** [node-red/node-red-dashboard#371]
Hi!

New to the node-red world, sorry if it's something stupid.  I've seen from the main page how to get 1 decimal place with rounding.  But I have a pretty large float number, and I don't want to round it, just show two decimal places, how can this be done?

Thank you!

**Comment by dceejay** [comment]
As per the contribution guidelines - we much prefer general how-to type questions via the mailing list or slack channel so the widest possible community can help.
The widgets use the angular number filter - https://docs.angularjs.org/api/ng/filter/number which can round to a specified number of places.
Other than that you would need to add your own pre-processor function to just trim them if required.
