### ISSUE TITLE
Switching to an empty tab via URL throws uncaught exception and crashes Node-RED 

### ISSUE THREAD

**Issue by tedhuang** [node-red/node-red-dashboard#375]
Empty UI tabs are hidden by default in the dashboard sidebar but they can still be access via the URL using "/ui/#/<TAB_NUMBER>". When this happens the dashboard node throws an exception and Node-RED crashes. If the empty tabs are hidden is it possible to just not allow them to be access via URL as well?

**To reproduce:**
1. Create a new tab, leave it empty
2. Access the tab via the #/[tab-number] in the URL
3. Node-RED crashes with error:

```
2 Apr 13:40:40 - TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Socket.<anonymous> (/home/sts-develop/.node-red/node_modules/node-red-dashboard/ui.js:350:37)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /home/sts-develop/.node-red/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by tedhuang** [comment]
Thanks for the quick fix @dceejay. 

I found that it wasn't the empty tab that was causing the crash. Even if you created just one tab with content at `/ui/#/0`, trying to access `/ui/#/1` will cause the crash. In fact accessing the UI tab url at exactly `current number of tabs + 1` will throw the error. There might be a +/-1 bug somewhere when the ui tab endpoints are created?

I wanted to bring this up in case the fix is masking another issue.

**Comment by dceejay** [comment]
Good shout... and yes also an off by one error...
belt and braces now in place.
