### ISSUE TITLE
UI_Chart Feature Request (Set Interpolation to None per Series)

### ISSUE THREAD

**Issue by scottrcarlson** [node-red/node-red-dashboard#377]
Request UI_Chart Interpolation = "None" per series. That can be set via msg.ui_control.

Example: 
Series 1: Scatter Plot Raw Data points with no lines
Series 2: Plot Best Fit Curve with Linear Interpolation.

Is this a tricky request? 

Thanks in Advance for the great work.

**Comment by dceejay** [comment]
Hi   in general we prefer feature requests and how-to via the mailing list or slack channel so the widest possible community can discuss etc...

As it happens - charts.js (the underlying library) does not provide a way to turn off interpolation, and we don't support the bubble chart format - and even if we did you couldn't mix that with lines easily....

However... there is a workaround...  if you set the chart to enlarge points - and then send a `msg.payload = null;` after each point - it will be plotted on it's own.
