### ISSUE TITLE
AngularJS Material style issues

### ISSUE THREAD

**Issue by kodaniel** [node-red/node-red-dashboard#379]
Hi!

I tried to use the dashboard's Template node with the angular material design according to the documentation ([link](https://material.angularjs.org/latest/demo/list)), but in the most cases the style is buggy.

How it looks:
![dashboard](https://user-images.githubusercontent.com/24585704/38497167-7b8ba762-3c00-11e8-8c10-64193aad2947.png)

And how should it looks:
![image](https://user-images.githubusercontent.com/24585704/38497248-c9110ebe-3c00-11e8-86b1-dc033578ec64.png)

![image](https://user-images.githubusercontent.com/24585704/38497262-d342e77c-3c00-11e8-84b8-a91ee3068528.png)

Is it a bug, or I just do something wrong?

Node-Red-Dashboard version: v2.8.2
Node-Red version: v0.18.4
NodeJs version: v8.10.0

Sample nodes [here](https://pastebin.com/rQyRrHKJ)

**Comment by cinhcet** [comment]
the css of the dashboard
https://github.com/node-red/node-red-dashboard/blob/master/src/theme.less#L76
sets the background color for md-button

**Comment by kodaniel** [comment]
How could I do this in the node-red editor?

**Comment by kodaniel** [comment]
The widget background changes the widget's background. But how does it solve the problem?
Where can I find the edit config?

**Comment by kodaniel** [comment]
Then I think you didn't really understand the problem.

The Dashboard uses the [https://material.angularjs.org/](https://material.angularjs.org/) UI framework which has several components like lists, dialogs, inputs, progress bars, etc... I want to use these components in the Template node, but I can't because the UI elements look bad (see the pictures above).
I think it is not only a "how-to".

**Comment by cinhcet** [comment]
in the css file https://github.com/node-red/node-red-dashboard/blob/master/src/theme.less#L225
(sorry, I clicked on the wrong line in the post above, is edited) you see that the background of md-button and other things are set. A hacky way to get the default behavior would be to comment out line 224-240 in this file. (you need to install the dasboard from git and run gulp, of course).

Acutally, the problem you describe was the reason I started https://github.com/cinhcet/node-red-contrib-component-dashboard because I wanted to use angularjs elements in the template which was not possible without hacks. Another workaround would be to set those properties in a style tag inside the template

**Comment by dceejay** [comment]
OK - getting there...  I think that CSS should only affect buttons in the template so they default to being like other buttons...  so other items ought to be ok ?
And indeed you should be able to override it in the template as inline  style should take priority.

**Comment by dceejay** [comment]
hmm - is there a way I could use less to optionally not add any style ? - (based on a "not yet implemented" flag in ui-template config)

**Comment by cinhcet** [comment]
I can remember roughly that there are so called "guarded mixins" (but I am not a less expert)

**Comment by dceejay** [comment]
top tip - thanks - looks like the thing we need... will have a play.

**Comment by dceejay** [comment]
Have pushed a possible way out to master for you to try... give feedback. I have now added an option to the Dashboard Site global options to remove the styling from ui_template nodes. So you can take control if you turn this off..

![image](https://user-images.githubusercontent.com/5375409/38606978-70dd80b8-3d6f-11e8-8a30-91048accccc7.png)

**Comment by dceejay** [comment]
cd ~/.node-red
npm i node-red/node-red-dashboard

**Comment by knolleary** [comment]
Worth pointing out, as @kodaniel is new to the nodejs world, running `npm i node-red/node-red-dashboard` will cause npm to install the code from this git repository rather than using the published release from the main npm repository. This is a way to install the latest code, albeit code that has not been formally released yet.

**Comment by kodaniel** [comment]
Works fine, thank you for everybody!

![image](https://user-images.githubusercontent.com/24585704/38666190-a3541d02-3e3e-11e8-958b-bdf559fd0de0.png)

**Comment by dceejay** [comment]
I didn't try all the "lists, dialogs, inputs, progress bars, etc..." that you mentioned, so please do so and let us know :-) 
And indeed if they work a simple test page with them on would be a good thing to add to http://flows.nodered.org - Thanks

**Comment by kodaniel** [comment]
Ok, I tested all components which does not require additional angularjs code. Everything looks good, I just found a little bug at the [Tabs](https://material.angularjs.org/latest/demo/tabs). The content inherits the theme base color instead of black.

![image](https://user-images.githubusercontent.com/24585704/38674436-be009a48-3e54-11e8-99d5-9ae7a2b6cd5f.png)

**Comment by dceejay** [comment]
can you share that part of the flow ? thanks

**Comment by kodaniel** [comment]
[AngularMaterialThemeDemo.zip](https://github.com/node-red/node-red-dashboard/files/1902968/AngularMaterialThemeDemo.zip)

**Comment by dceejay** [comment]
Hi - grab it again - and give it a whirl...

**Comment by dceejay** [comment]
closed by b369e2bec25c9169cd7a8a8f79c25a277519a1e5
