### ISSUE TITLE
Gauges showing null value

### ISSUE THREAD

**Issue by swilson86** [node-red/node-red-dashboard#385]
A minor bug in the gauges. They will display a {} if a value is passed to them as a string. They no longer use parseInt to set the value to be numeric in dashboard 2.9 and 2.9.1 beta. Quick patch is to write a two line function just before the gauge containing:

msg.payload = parseInt(msg.payload);
return msg;

**Comment by dceejay** [comment]
Hi do you have a simple example ? Thanks

**Comment by dceejay** [comment]
Hi,
have pushed a possible fix to master... (not on npm yet)... which should fix most of this issue - but as I'm not sure of your exact circumstance I can't be sure yet.

**Comment by swilson86** [comment]
Thanks dceejay. Here is an example and clarification of a 12km/h wind gust coming from MQTT as a string...

4/22/2018, 12:23:16 PMnode: Wind gusts
WindGusts : msg.payload : buffer[8]
[ 49, 50, 0, 0, 0, 0, 0, 0 ]

Feeding that string directly into a gauge (like I used to) now causes the gauge error. I must now build the 2 line function that I mentioned (containing the parseInt line) between the MQTT output and the gauge.

In a ui_chart you say "Each input msg.payload value will be converted to a number. If the conversion fails, the message is ignored." In ui_gauge you say "The msg.payload is searched for a numeric value and is formatted in accordance with the defined Value Format, which can then be formatted using Angular filters."

The ui_gauge is missing the conversion to a number.

**Comment by dceejay** [comment]
great - is sorted in master

**Comment by dceejay** [comment]
published to npm as 2.9.1

**Comment by swilson86** [comment]
That fixed it!! Thanks.
