### ISSUE TITLE
No pass throught in text input

### ISSUE THREAD

**Issue by shajek** [node-red/node-red-dashboard#388]
Hello,
i have little issue with pass throught of my payload. I have query from mysql and then parsed with function node to correct way and format to input text, and from input text back to mysql and update query and another function. But when i do query, text input fill correct but no output from even i have chcecked pass throught. This is little snippet with injection instead of mysql:

`[{"id":"f151d1ae.2ba4b","type":"ui_text_input","z":"c8a505c5.789d18","name":"Minimum % na zavlahu","label":"Minimum % na zavlahu","group":"712beadb.0648f4","order":1,"width":0,"height":0,"passthru":true,"mode":"text","delay":"500","topic":"minimum_zavlaha","x":910,"y":1040,"wires":[["c02cec30.a25ad","5c798665.667ac8"]]},{"id":"b55c05fe.6d2748","type":"ui_text_input","z":"c8a505c5.789d18","name":"Maximum % na zavlahu","label":"Maximum % na zavlahu","group":"712beadb.0648f4","order":2,"width":0,"height":0,"passthru":true,"mode":"text","delay":"500","topic":"maximum_zavlaha","x":910,"y":1080,"wires":[["c02cec30.a25ad"]]},{"id":"c54261b5.51bfa","type":"function","z":"c8a505c5.789d18","name":"parse min/max_zavlaha","func":"var str = msg.payload;\nvar premenna;\n\nif (str[0]['minimum_zavlaha']) {\npremenna = str[0]['minimum_zavlaha'];\nmsg.payload = premenna.toString();\nmsg.topic = \"minimum_zavlaha\";\nreturn msg;    \n}\n\nif (str[0]['maximum_zavlaha']) {\npremenna = str[0]['maximum_zavlaha'];\nmsg.payload = premenna.toString();\nmsg.topic = \"maximum_zavlaha\";\nreturn msg;    \n}","outputs":1,"noerr":0,"x":530,"y":1060,"wires":[["5fdd07f1.742cd8"]]},{"id":"5fdd07f1.742cd8","type":"switch","z":"c8a505c5.789d18","name":"","property":"topic","propertyType":"msg","rules":[{"t":"eq","v":"minimum_zavlaha","vt":"str"},{"t":"eq","v":"maximum_zavlaha","vt":"str"}],"checkall":"true","outputs":2,"x":709,"y":1059,"wires":[["f151d1ae.2ba4b"],["b55c05fe.6d2748"]]},{"id":"1cc519c0.3f6e26","type":"inject","z":"c8a505c5.789d18","name":"","topic":"minimum_zavlaha","payload":"80","payloadType":"str","repeat":"","crontab":"","once":false,"x":558,"y":998,"wires":[["f151d1ae.2ba4b"]]},{"id":"5c798665.667ac8","type":"debug","z":"c8a505c5.789d18","name":"","active":true,"console":"false","complete":"true","x":1122,"y":1014,"wires":[]},{"id":"712beadb.0648f4","type":"ui_group","z":"","name":"poda","tab":"bfe11959.12dfc8","order":2,"disp":false,"width":"6"},{"id":"bfe11959.12dfc8","type":"ui_tab","z":"","name":"ESP na stole","icon":"dashboard","order":10}]`

i cannot get output from text node without typing to it .... and that is .. little issue for me ... thank you

**Comment by dceejay** [comment]
If I reduce it further to the flow below - it works for me...

![image](https://user-images.githubusercontent.com/5375409/39552485-5b45b768-4e61-11e8-8ad2-5357fad5519c.png)

the nodes only pass on data if it changes - so you need to send a different value for it to be passed through...

[{"id":"6556bc5b.6f1eb4","type":"inject","z":"2792579f.43e958","name":"","topic":"minimum_zavlaha","payload":"70","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":160,"y":500,"wires":[["c3f76c46.83f8d"]]},{"id":"c3f76c46.83f8d","type":"ui_text_input","z":"2792579f.43e958","name":"Minimum % na zavlahu","label":"Minimum % na zavlahu","group":"985ffee7.542bf","order":1,"width":0,"height":0,"passthru":true,"mode":"text","delay":"500","topic":"minimum_zavlaha","x":450,"y":540,"wires":[["2e2c168f.155cca"]]},{"id":"2e2c168f.155cca","type":"debug","z":"2792579f.43e958","name":"","active":true,"console":"false","complete":"true","x":670,"y":540,"wires":[]},{"id":"84bc59d5.5e70c8","type":"inject","z":"2792579f.43e958","name":"","topic":"minimum_zavlaha","payload":"80","payloadType":"str","repeat":"","crontab":"","once":false,"x":158,"y":538,"wires":[["c3f76c46.83f8d"]]},{"id":"985ffee7.542bf","type":"ui_group","z":"","name":"poda","tab":"8535d2aa.4df84","order":2,"disp":false,"width":"6"},{"id":"8535d2aa.4df84","type":"ui_tab","z":"","name":"ESP na stole","icon":"dashboard","order":10}]

**Comment by shajek** [comment]
Yes, if i change value it works. Thank you. But i read (nearly) whole internet about passthrougt-ing messages but actually I can not find anything and anything about  change of value .... specially when Node-RED say  

> If msg arrives on input, pass through to output

is this feature or bug ?

**Comment by dceejay** [comment]
It's a feature to reduce traffic going from server to client when nothing has changed.

**Comment by kucik** [comment]
One thing is that it does not pass through message. The other thing is it does not show value in dashboard until it is changed.
Test:
![Screenshot_2022-12-19_13-34-55](https://user-images.githubusercontent.com/6491536/208427765-db2b68d7-fbaa-47b4-b6b4-95190f3453d7.png)

Using Text Input node in Time picker mode.
Change the value of TextInput by sending message to it with msg.payload equivalent of 06:00 PM (miliseconds from midnight). Now I can see the value 06:00 PM.
Now I can see value in dashboard.
Reload dashboard page in web browser. Value int Text Input node shows --:-- --.
![Screenshot_2022-12-19_13-35-25](https://user-images.githubusercontent.com/6491536/208427675-dc919ccd-dcac-4499-bd2e-9be0b63abf14.png)

Value in Text input is not known until I change value from 06:00 PM to different value.

**Comment by dceejay** [comment]
Correct - this is working as designed. We don't resend data if it hasn't changed.

**Comment by kucik** [comment]
Sorry I probably haven't made myself clear. I understand TextInput does not resend data if it hasn't changed. I'm OK with that.
But in Time picker mode it does not even **show** current value until it is changed again. Even though for example Number Input node works differently.

My use case:
![Screenshot_2022-12-20_13-00-37](https://user-images.githubusercontent.com/6491536/208662566-21cd2eb2-163b-4ec6-9009-5e220bcc6e47.png)
I'm using this form to program schedule for some devices. When I open the dashboard to see/change schedule I don't  see values which were previously filled and passed through. But that wouldn't be the trouble.
When I change the device I want see/update, the schedule of that device is loaded into these fields.
But if new value in TimePicker is equal to previous value I cannot see what the value is. (Value was not resent too, but that is not problem.)
![Screenshot_2022-12-20_13-31-55](https://user-images.githubusercontent.com/6491536/208668071-1eac6b8d-da07-4409-9449-8ad1708654aa.png)
To workaround this behaviour I would have to change the value of TimePicker at least twice to make sure that value was changed and will be visible even if original and final value might be equal.
