### ISSUE TITLE
Group no longer retain the collapse / un-collapse state

### ISSUE THREAD

**Issue by Toshibass** [node-red/node-red-dashboard#389]
Reference - Ensure groups are restored rather than completely disappeared on refresh. Issue #386 (2.9.0)

Unfortunately I have to report Dashboard 2.9.2 is only a partial fix .. whilst the groups no longer disappear, every time the the browser is refreshed the group does not retain the collapse / un-collapse state, so if you close the browser with the group collapsed when you refresh the browser the group is un-collapsed ... prior to the 2.9.0 update the state was retained, so if you collapsed the group at stayed collapsed for ever, or until you un-collapsed it.

**Comment by dceejay** [comment]
@Toshibass  Does 2.9.3 fix this for you ?

**Comment by Toshibass** [comment]
YES 2.9.3 fixes the issue, thank you very much 🥇
