### ISSUE TITLE
Losing tab setting after updating icon

### ISSUE THREAD

**Issue by Paul-Reed** [node-red/node-red-dashboard#39]
Noticed that groups lose their tab setting when their respective Tab node icon is updated.

![1](https://cloud.githubusercontent.com/assets/973580/17346027/d2999670-5900-11e6-8877-2721191f03ef.png)

If the 'Test' tab node icon is updated to say 'school' from 'github-circle', update & deploy, all of the flows contained within the 'Examples' group are orphaned from the 'Test' tab.

![2](https://cloud.githubusercontent.com/assets/973580/17346312/ef3b860c-5901-11e6-962a-3fb327018bb8.png)

Now if the 'Examples' group is examined, it shows that it has changed tab from 'Test' to 'Power'

![3](https://cloud.githubusercontent.com/assets/973580/17346460/b4fdcdc8-5902-11e6-8343-c0969eb6cee5.png)

To restore things back to normal, it's necessary to revert the 'Examples' group's tab back to 'Test' from 'Power'. 

Paul

**Comment by dceejay** [comment]
Hopefully this is now also fixed as part of the tab/group/widget update fixes now in place...

**Comment by Paul-Reed** [comment]
Have these changes found their way to npm yet? If so I'll retest.

Paul

**Comment by knolleary** [comment]
@Paul-Reed no, will be released later this week and announced on the mailing list.

**Comment by Paul-Reed** [comment]
Will check tonight.

**Comment by Paul-Reed** [comment]
Error still persists using dashboard 2.0.2.

Example, I have 2 groups - 'Current Conditions' & 'Forecast' sitting under a tab - 'weather', and the dashboard looks like this;
![dash1](https://cloud.githubusercontent.com/assets/973580/19126338/68c12bdc-8b32-11e6-8282-fd600e023dbb.PNG)

Now if I edit the 'weather' dashboard tab, changing the tab icon from 'wb_sunny' to 'wb_cloudy', update and deploy, my dashboard looks like;
![dash2](https://cloud.githubusercontent.com/assets/973580/19126437/d946a1ca-8b32-11e6-89ab-7a6e6d8a9e0e.PNG)

Now only the 'Current Conditions' group is displayed, and 'Forecast' has disappeared.
If I look at any of the dashboard nodes which comprise in the 'Forecast' group, I can see that they are now detached from the 'weather' tab.
![node](https://cloud.githubusercontent.com/assets/973580/19126688/d212c518-8b33-11e6-8eb5-dda0c3f53680.png)

I can re-attach the groups back to 'weather' by;

- Edit the 'Forecast' dashboard group node
- It currently shows that 'weather' is selected in the dropdown tab field
- re-select 'weather' in the dropdown tab field
- select update & deploy
Now the forecast nodes and the 'forecast group node' have returned back under the weather tab, and all is well.

I've run through this 3 times now, and same result each time.

Paul

**Comment by dceejay** [comment]
I'm failing to re-create this using the 2.2.0-beta version - so I'm going to close this for now.
