### ISSUE TITLE
Installation of module node-red-dashboard failed

### ISSUE THREAD

**Issue by kasparjj** [node-red/node-red-dashboard#393]
Hi 
I'm only a beginner using Node-RED and I can't understand why the node-red-dashboard palette continuously fails to install. Even if i just med a new blank application from Bluemix.

Here is the error I get:
`npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has 1 low vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] parsejson has 1 high vulnerability. Go here for more details: https://nodesecurity.io/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURI...`

What am I supposed to do? I haven't yet had any experience with Node.js and CLI for Cloud Foundry.
<img width="1440" alt="screen shot 2018-05-10 at 00 35 42" src="https://user-images.githubusercontent.com/32299432/39843160-21302264-53ea-11e8-97a3-cdc4c8a08bde.png">

**Comment by knolleary** [comment]
The fixed version of npm _should_ be released on Thursday 10th May - I'll update here once I confirm it is available.

**Comment by knolleary** [comment]
I can confirm that with npm 6.0.1 published this issue is fixed for new installs of the boilerplate.

To fix an existing version, please follow the instructions above to set the `NPM_CONFIG_AUDIT` environment variable.
