### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by chrisegge** [node-red/node-red-dashboard#395]
I get an error everytime I try to install the newest dashboard. My Rpi 3B+ is fresh. Just reinstalled raspian for the second time thinking I did something wrong there. But It wont install the package.

**Comment by knolleary** [comment]
Can you share the error you are hitting? Can't do much without the details.

**Comment by chrisegge** [comment]
I honestly cannot remember what it was that fixed it. It was something to do with the package-lock. Somehow it had two conflicting packages with different information so I had to delete that package lock and download it and then run sudo npm install node-red-dashboard and I'm not sure why but it wouldn't let me install without sudo

**Comment by chrisegge** [comment]
I had to go to git hub and download it and unzip and install from the directory. Maybe that's how I was supposed to do it from the beginning but I'm new to all this and learning so I'm probably not even making sense
