### ISSUE TITLE
UI nodes disappear/not shown on mobile devices

### ISSUE THREAD

**Issue by craxdm** [node-red/node-red-dashboard#398]
I am fairly new to using dashboard, but I have run into a problem where some or all of my UI does not display correctly on mobile devices. It works fine when I make it, but then some time later (lets say 30 min) it is not longer showing my mobile devices (android). The UI is still showing and working just fine on my computers. To get it working again I need to delete entire group and all the nodes. The new group also needs to have a new name.

Is this a know issue, or has anyone seen this before?

**Comment by dceejay** [comment]
Hi
not heard of this before. Any idea how we could try to recreate this ?
What sort of widgets are you using ?
What sort of Android device is it on?
What sort of browser is it using ?

**Comment by craxdm** [comment]
Hi,
I have tested some more and it seems to me that this is the same issues, or at least somewhat related, as reported on #66, #264, #369.
I have also manged to get the issue on the computers as well now so it does not seem to be just mobile devices. Simply appeared there earlier than on the normal PC.

I am only using some buttons and sliders, nothing fancy.

The mobile devices are Samsung S7 and Huawei P20 Lite.

Browsers are chrome and samsung internett on the mobile devices and chrome and microsoft edge on the computers.

The issue itself seems to be related some widgets while cached not being displayed. So as a temporary workaround I can get everything to appear as it should using incognito mode in the browser. This works on both the mobile devices and the computers.

**Comment by dceejay** [comment]
Are you using subflows ? 
This first issue you refer to is about that - and the fact that the ui on the right of the editor can't visualise ui elements in multiple copies of a subflow - workaround is not to use ui elements in subflows.
The second is related to the ordering they appear on the screen vs in the editor sometimes getting out of sync - but that won't cause them to disappear.
The last could be a cacheing issue - but in your case if they were in the cache they won't suddenly disappear - that is the point of the cache after all...
Are there multiple tabs (/pages) involved also ?

**Comment by craxdm** [comment]
I am at work atm so I am unable to provide any screenshots.
But how do you define a sub flow?
I am using multiple flows with the same node red flow tab. Should I only have one flow with a UI element pr node red flow tab? (I have tested a lot of different setups, but not this).
I currently have more 2 tab pages, but the issue was there with only one page.

**Comment by dceejay** [comment]
No - subflows are a group of nodes that you collapse into a single "node" and can re-use elsewhere in a flow... (under menu -  subflows) - if you haven't done that then don't start now :-)
Multiple flows across a page and multiple ui elements is business as usual.

**Comment by craxdm** [comment]
Sorry for the late response. Been working 12 hour shifts every day. Attached is my flow that has issues. It is no longer as simple as it was at the start. The issue is a lot easier to reproduce on a mobile device than a comptuer.

![belysning](https://user-images.githubusercontent.com/8851956/40590434-15663bb2-61ff-11e8-9b52-4a9dd58f9a8d.PNG)

[tradfri.txt](https://github.com/node-red/node-red-dashboard/files/2042988/tradfri.txt)

**Comment by dceejay** [comment]
no further info/progress - closing
