### ISSUE TITLE
The text color of angular  material dialog  widget is  blue not white when used in dashboard template 

### ISSUE THREAD

**Issue by chaim1986** [node-red/node-red-dashboard#400]
### What are the steps to reproduce?

use a  dialog component  in  dashboard template
(from https://material.angularjs.org/latest/demo/dialog) 

I find  this bug is very similar to  https://github.com/node-red/node-red-dashboard/issues/379

### What happens?

the text color of the widget is blue 

### What do you expect to happen?

the text color of the widget would  be  **white** 

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
2.9.4 .  and  set the dashboard  **No theme  in ui-template**
- [ ] Node-RED version:
0.18.6
- [ ] node.js version:
- [ ] npm version:

     node -v 
             v8.11.2
     npm -v 
             5.6.0
- [ ] Platform/OS:
ubuntu 
- [ ] Browser:
chrome

- [ ] Flow
`
[{"id":"303985e3.a3079a","type":"ui_template","z":"c2d4615f.12c53","group":"86b7421a.3676e","name":"dialog","order":0,"width":0,"height":0,"format":"<div class=\"md-padding\" id=\"popupContainer\" ng-cloak>\n  <p class=\"inset\">\n    Open a dialog over the app's content. Press escape or click outside to close the dialog and\n    send focus back to the triggering button.\n  </p>\n\n  <div class=\"dialog-demo-content\" layout=\"row\" layout-wrap layout-margin layout-align=\"center\">\n    <md-button class=\"md-primary md-raised\" ng-click=\"showAlert($event)\"   >\n      Alert Dialog\n    </md-button>\n    <md-button class=\"md-primary md-raised\" ng-click=\"showConfirm($event)\" >\n      Confirm Dialog\n    </md-button>\n    <md-button class=\"md-primary md-raised\" ng-click=\"showPrompt($event)\"  >\n      Prompt Dialog\n    </md-button>\n    <md-button class=\"md-primary md-raised\" ng-click=\"showAdvanced($event)\">\n      Custom Dialog\n    </md-button>\n    <md-button class=\"md-primary md-raised\" ng-click=\"showTabDialog($event)\" >\n      Tab Dialog\n    </md-button>\n    <md-button class=\"md-primary md-raised\" ng-if=\"listPrerenderedButton\" ng-click=\"showPrerenderedDialog($event)\">\n      Pre-Rendered Dialog\n    </md-button>\n  </div>\n  <p class=\"footer\">Note: The <b>Confirm</b> dialog does not use <code>$mdDialog.clickOutsideToClose(true)</code>.</p>\n\n  <div ng-if=\"status\" id=\"status\">\n    <b layout=\"row\" layout-align=\"center center\" class=\"md-padding\">\n      {{status}}\n    </b>\n  </div>\n\n  <div class=\"dialog-demo-prerendered\">\n    <md-checkbox ng-model=\"listPrerenderedButton\">Show Pre-Rendered Dialog</md-checkbox>\n    <p class=\"md-caption\">Sometimes you may not want to compile the dialogs template on each opening.</p>\n    <md-checkbox ng-model=\"customFullscreen\" aria-label=\"Fullscreen custom dialog\">Use full screen mode for custom dialog</md-checkbox>\n    <p class=\"md-caption\">Allows the dialog to consume all available space on small devices</p>\n  </div>\n\n  <div style=\"visibility: hidden\">\n    <div class=\"md-dialog-container\" id=\"myDialog\">\n      <md-dialog layout-padding>\n        <h2>Pre-Rendered Dialog</h2>\n        <p>\n          This is a pre-rendered dialog, which means that <code>$mdDialog</code> doesn't compile its\n          template on each opening.\n          <br/><br/>\n          The Dialog Element is a static element in the DOM, which is just visually hidden.<br/>\n          Once the dialog opens, we just fetch the element from the DOM into our dialog and upon close\n          we restore the element back into its old DOM position.\n        </p>\n      </md-dialog>\n    </div>\n  </div>\n\n</div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":516.5,"y":533,"wires":[[]]},{"id":"86b7421a.3676e","type":"ui_group","z":"","name":"group4","tab":"30e26a88.e54bd6","disp":true,"width":"6","collapse":false},{"id":"30e26a88.e54bd6","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]`

**Comment by dceejay** [comment]
Hi - thanks for raising this - I have pushed what I think is a fix to the master branch as 2.9.5-beta
  
    cd ~/.node-red && npm i node-red/node-red-dashboard

should install it. Can you give it a try ? Thanks

**Comment by dceejay** [comment]
Any response ? Did you try the fix ?

**Comment by dceejay** [comment]
closing due to lack of response to fix.
