### ISSUE TITLE
Failed to load 'node-red-dashboard/ui_base'

### ISSUE THREAD

**Issue by mlewis26201** [node-red/node-red-dashboard#402]
I have had this happen on two fairly new installs on Rasbian Stretch, so I am not sure if it is a bug or something I am breaking.

Node-Red itself seems to be working fine, but after some period of time after rebooting, I lose the dashboard tab on the right next to "debug". I also get a warning at the top of the browser on initial load that says:
"Failed to load 'node-red-dashboard/ui_base'"
"TypeError: $.widget is not a function"

I tried so many combinations of npm install/reinstall, with and without -g with no change in the problem.

node.js version: v8.11.2

Problem occurs with both Chrome and IE.

I did find a ui_base,js and ui_base.html:
pi@hahub:~/.node-red/node_modules/node-red-dashboard/nodes $ ls -l ui_base*
-rw-r--r-- 1 pi pi 115540 May 23 21:18 ui_base.html
-rw-r--r-- 1 pi pi   3736 May 18 07:57 ui_base.js

No idea what I am looking at, but also found this:
pi@hahub:~/.node-red/node_modules/node-red-dashboard/nodes $ grep $.widget ui_base*
ui_base.html:    $.widget("nodereddashboard.elementSizerByNum", {
ui_base.html:    $.widget( "nodereddashboard.elementSizer", {

Any ideas on what is happening or what I am doing to break it? And, how to fix?

**Comment by dceejay** [comment]
not seen that here (yet). Is the browser running on the Pi ? I assume not as you also mention IE.

**Comment by mustafasei** [comment]
May be your issue same mine. I cannot see the dashboard /ui after finishing the project even I can see the dashboard items on the left side

**Comment by battika** [comment]
Same issue here on the latest version of Raspian Stretch.

**Comment by dceejay** [comment]
Any more reports of this ? anyone able to recreate this ?

**Comment by Roger53** [comment]
Love your work 👍

Not sure it is the same, but certainly a look-a-like :-)

For me it went wrong between 2.9.6 and 2.9.7, and as you dont have dates in your changelog I dont know if it fits above complaint ( Dates would be handy ).

I am using a docker image on Orange Pi One with latest armbian and a self build image, based on : arm32v7/node:10.9.0-slim which is based on debian:jessie-slim

I upgraded a few days ago to Dashboard version 2.9.7 and lost the ui in Windows10 Internet Explorer 11, while FF and Edge on same machine worked fine.
All works fine, except the ui : Screen is white and empty ( normally it starts with a black background )

I made a second docker image where I forced  a downgrade to Dashboard version 2.9.6 and the ui worked again for IE11

I also got today a Dashboard version 2.9.8, same problem.

There is some caching going on, that confuses things, so close/open explorer and paste basic url (.../ui for every test ! refresh is not enough) 
I see many warnings / errors for both versions, except this one in IE (F12)  : 

Creating AppCache with manifest: 'http://192.168.X.X:1880/ui/dashboard.appcache'.
TypeError: Object doesn't support property or method 'assign'
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: {
               [functions]: ,
               __proto__: null
            },
            message: "",
            name: "Error"
         },
         message: "",
         name: "TypeError"
      },
      description: "Object doesn't support property or method 'assign'",
      message: "Object doesn't support property or method 'assign'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'assign'
   at f.defaults (http://192.168.X.X:1880/ui/js/app.min.js:503:14084)
   at f.copyOptions (http://192.168.X.X:1880/ui/js/app.min.js:503:13393)
   at g (http://192.168.X.X:1880/ui/js/app.min.js:501:12658)
   at i (http://192.168.X.X:1880/ui/js/app.min.js:499:10133)
   at Anonymous function (http://192.168.X.X:1880/ui/js/app.min.js:499:10352)
   at f (http://192.168.X.X:1880/ui/js/app.min.js:504:24853)
   at dfunction (http://192.168.X.X:1880/ui/js/app.min.js:504:25631)
   at d (http://192.168.X.X:1880/ui/js/app.min.js:504:393)"
   }

Hope this helps repairing ?
Until then I am using 2.9.6, no problem, but updates updates updates.....

**Comment by dceejay** [comment]
Looks like this http://techcater.com/object-doesnt-support-property-or-method-assign/
You may be able to try that in a ui_template to test it. I’ll try a fix over the weekend.

**Comment by Roger53** [comment]
Hi,
Well no idea where to change that, but as said, no hurry
Let me know when you fixed it, I will test it.

**Comment by dceejay** [comment]
![image](https://user-images.githubusercontent.com/5375409/45253026-078d6100-b358-11e8-8152-b91686b0dda3.png)
![image](https://user-images.githubusercontent.com/5375409/45253030-1b38c780-b358-11e8-8e1a-52769295b7f3.png)

**Comment by Roger53** [comment]
I appreciate that you try to solve asap, but as said, 2.9.6 works, so take your time, no problem. Have a nice trip

But I am always willing to test for you, no problem, the least I can do ;)

OK, so I did understand you correctly, but that does not work
It shows a red cross in editor in the margin, "Expected Tag name. Got something else instead"
But I can click done and deploy anyway without a warning

at this line :      for (var index = 1; index < arguments.length; index++) {

**Comment by dceejay** [comment]
Hi - OK - have pushed a test fix to master... you can install it by

    cd ~/.node-red
    npm i node-red/node-red-dashboard

fingers crossed

**Comment by Roger53** [comment]
Hi,
So  build a new docker container, with node-red-dashboard": "*", which normally would give the latest version.

Sorry to ask, but are you sure you did the push ? I still get Dashboard version 2.9.8 started at /ui , same as Sept 4, but I expected 2.9.9 or so ?

Anyway my new container with 2.9.8, has the same "assign" problem : is not solved.

**Comment by dceejay** [comment]
no - it's in master not on npm so in package.json you need

     "node-red-dashboard": "node-red/node-red-dashboard",

it's still 2.9.8 - and you will need to flush your browser cache - ctrl-r to reload a couple of times.

**Comment by Roger53** [comment]
all new to me, OK, 
Build is ok, I see again "2.9.8"

But I see no difference, still white screen and error on IE, works fine on Edge / FF.
I assume that your fix should make the ui template not needed anymore, right ?

TypeError: Object doesn't support property or method 'assign'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'assign'",
      message: "Object doesn't support property or method 'assign'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'assign'
   at f.defaults (http://192.168.X.X:1880/ui/js/app.min.js:503:14084)
   at f.copyOptions (http://192.168.X.X:1880/ui/js/app.min.js:503:13393)
   at g (http://192.168.X.X:1880/ui/js/app.min.js:501:12658)
   at i (http://192.168.X.X:1880/ui/js/app.min.js:499:10133)
   at Anonymous function (http://192.168.X.X:1880/ui/js/app.min.js:499:10352)
   at f (http://192.168.X.X:1880/ui/js/app.min.js:504:24853)
   at Anonymous function (http://192.168.X.X:1880/ui/js/app.min.js:504:25631)

   at d (http://192.168.X.X:1880/ui/js/app.min.js:504:393)"
   }

![image](https://user-images.githubusercontent.com/19274367/45429404-8a3d5580-b6a3-11e8-98ef-5f8646d8786f.png)

**Comment by Roger53** [comment]
I got another IE problem : sizing of a bar chart after opening, Ill put it in a new thread, ok?

**Comment by Roger53** [comment]
Yes flushed, also via the menu's,

Not using IE ? Yes sure, but I use Firefox for internet, with adblock clear history, block / delete cookies etc, etc, making it slower and forgetfull.

My IE has no internet access (ZoneAlarm) also no additions mentioned above, making it work very fast and remembers some stuff.

Isn't everybody doing that than, to have some protection :-) ? Should !

Ok, so can we try something else ?

What did you change between 2.9.6 and 2.9.7 that could cause this, because that is where the problem started ?

**Comment by dceejay** [comment]
I believe it is now fixed - and is in github as per above. I'm not sure why you can't get it to refresh properly. It will be released to npm as part of 2.9.9 as and when.
I guess one of the other dependencies started to use Object.assign and when it got upgraded it broke.

**Comment by dceejay** [comment]
pushed a version 2.9.9-beta to master 
maybe that will load correctly for you.

**Comment by Roger53** [comment]
Good news : 

I now see "Dashboard version 2.9.9-beta started at /ui" and IE now works !!!

Coming days I will upgrade all my node-reds and see if they all work.

I hope that the other guys above can also confirm that their problems are solved.

**Comment by dceejay** [comment]
will push out 2.9.9 to npm probably later this week - so everyone can get more easily.

**Comment by Roger53** [comment]
Yes, I had to add git,  64 libs and 50MB to my image :-)

**Comment by dceejay** [comment]
errrr - hmm - apologies for that ... maybe leave the others if you can wait.

**Comment by Roger53** [comment]
Tested all dashboard variants I use (not all node-reds machines yet, but all remaing have the same dashboard code), all look fine.
