### ISSUE TITLE
manage default value 

### ISSUE THREAD

**Issue by Summer88** [node-red/node-red-dashboard#404]
I've an input node that will send this to a gauge:

msg : string[26]
"Error stopping node: Error"
19/6/2018, 08:41:00node: 7bee95a8.84438c

How can let the gauge know that this is an error, stop display last value and show a default value i.e. 0?

19 Jun 09:08:00 - [info] Node-RED version: v0.17.5
19 Jun 09:08:00 - [info] Node.js  version: v8.11.2
19 Jun 09:08:00 - [info] Linux 4.15.0-2-amd64 x64 LE
19 Jun 09:08:00 - [info] Loading palette nodes
19 Jun 09:08:01 - [info] Dashboard version 2.6.2 started at /ui

**Comment by dceejay** [comment]
In general we prefer how to and operational type questions via either the slack channel or discourse forum. 
In this case this was fixed in a more recent dashboard update. Please upgrade.

**Comment by Summer88** [comment]
Thanks for your answer, I've updated dashboard: [info] Dashboard version 2.9.5-beta started at /ui, I've read also this:
https://github.com/node-red/node-red-dashboard/blob/master/config-fields.md
but can't see the default value field in the editor and the dashboard seems to work exactly as in previous version.

**Comment by dceejay** [comment]
Can you share a small example of the failing flow. It should put the text as text and remove the pointer

**Comment by Summer88** [comment]
`[{"id":"196e2a1.0396dd6","type":"inject","z":"32dcbe6f.eacc02","name":"DATA","topic":"","payload":"","payloadType":"str","repeat":"30","crontab":"","once":true,"x":180,"y":100,"wires":[["2f065515.4e83aa","2b15be6d.68cb22","b691fb6c.5a26a8","ccd12c32.470dc","72e20f5.cb501f","43e23b4e.d71734","7e4a02b1.0e858c","93f3687b.5922c8","16caaf66.567b31","45fd4ccf.11a254","a6ca5a58.111c88","e18ec15d.785b4","8b944f2d.7db1a","6eb4686a.65ae78","24a1a91a.c80096","2ba9c58a.e3e03a","f472d5a9.8c7f78","f12f5e66.67676","5bdbc1c0.c8fa","906acc88.88f02","1210fe91.1dd6a1","eff9c0ea.6e82a","7df1ad8c.4f8824","ed2215a2.10bba8","244e87c3.3bc078","6c18722a.6b02ec","a4f4586.ca046a8","c86949b.16df3b8","c9fb35f7.de9fc8","a32ac3d3.86ba1","af8f7fda.4b7a4","e9132caa.eef56","ecd8542d.baaa08","5b3735a5.d8974c","f8ccd664.0be478","bcb65d1d.3883b","a1f21849.aaa908","8fcb8a60.597dc8","73f4f9ab.c93958","b5d2f077.b819e","1e497553.e59f3b","7dd9ddf7.19c594"]]},{"id":"ef4bd32c.0714","type":"ui_switch","z":"32dcbe6f.eacc02","name":"","label":"","group":"5753451.15d99bc","order":0,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"1","onvalueType":"num","onicon":"","oncolor":"","offvalue":"0","offvalueType":"num","officon":"","offcolor":"","x":550,"y":220,"wires":[[]]},{"id":"5b3735a5.d8974c","type":"OpcUa-Item","z":"32dcbe6f.eacc02","item":"ns=2;s=data.data.data","datatype":"Boolean","value":"","name":"","x":380,"y":220,"wires":[["ef4bd32c.0714"]]},{"id":"469da6a0.401838","type":"OpcUa-Client","z":"32dcbe6f.eacc02","endpoint":"db075043.cec69","action":"read","time":10,"timeUnit":"s","name":"","x":1220,"y":160,"wires":[[]]},{"id":"2f065515.4e83aa","type":"function","z":"32dcbe6f.eacc02","name":"","func":"msg.topic = 'ns=2;s=data.data.data';\nreturn msg;","outputs":1,"noerr":0,"x":1050,"y":160,"wires":[["469da6a0.401838"]]},{"id":"5753451.15d99bc","type":"ui_group","z":"","name":"STATI","tab":"66c9612f.0422b","order":1,"disp":true,"width":"4"},{"id":"db075043.cec69","type":"OpcUa-Endpoint","z":"","endpoint":"opc.tcp://myopc:62841/ciccio/bello","secpol":"None","secmode":"NONE","login":false},{"id":"66c9612f.0422b","type":"ui_tab","z":"","name":"PROVA","icon":"dashboard"}]`


If the client is connected  the data is show on the switch, it goes to on state, if it receive an error it stay on.
Is there a way to make it off or change it's color to red?

**Comment by dceejay** [comment]
Sorry - this flow has nothing to do with a gauge so I guess this is a different problem.
If so please raise it via either the slack channel or discourse forum.
