### ISSUE TITLE
Ui_dropdown dont show value in list

### ISSUE THREAD

**Issue by Brian5600** [node-red/node-red-dashboard#405]
From ui_dropdown.html, Line 51
var valueField = $('<input/>',{class:"node-input-option-value",type:"text",style:"margin-left:7px; width:calc(50% - 32px);", placeholder: 'Value',value:option.value}).appendTo(row).typedInput({default:option.type||'str',types:['str','num','bool']});

I Think the property “width” should be “min-width” like in line 52 with Label.
I have tried to edit the file manually with succes.

### What are the steps to reproduce?
Try to edit or add new option to dropdown box.
### What happens?
You Can not edit or see value-field, or choose value-type.
### What do you expect to happen?
I would like the field with value to show in edit-mode.
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.9.4, i Think newest of June, 21 2018
- [ ] Node-RED version: 17.5
- [ ] node.js version: 6.9
- [ ] npm version: ?
- [ ] Platform/OS: Rpi
- [ ] Browser: Chromium

**Comment by dceejay** [comment]
do you have an example flow you can share that shows the problem ? thanks

**Comment by Brian5600** [comment]
I Can not verify, that the solution with min-width is working. It was a bit lave, so maybee it was manual editing, that did it.. By manual edit in css, se picture, the width on Claus red-ui-typedInput-container is changed from 2px to 200px. But the button for str, num or boel, is also not showing correct.
Before edit of CSS
![e0658c99-1d46-45d7-81b2-9f2331c119f6](https://user-images.githubusercontent.com/30555220/41791877-5d7c4c0e-7657-11e8-9a1e-f89943a8a265.jpeg)

After edit of CSS
![95a6da1e-21bf-4829-b68f-0e8a671c368d](https://user-images.githubusercontent.com/30555220/41791940-95530c1c-7657-11e8-8d5a-497ed7042655.jpeg)


Flow

[{"id":"e288e553.41f1f8","type":"ui_dropdown","z":"d110aaf4.303858","name":"","label":"Dropdown test","place":"Select option","group":"291792d5.7846d2","order":0,"width":0,"height":0,"passthru":true,"options":[{"label":"Label 1","value":"","type":"str"},{"label":"Label 2","value":"","type":"str"}],"payload":"","topic":"","x":262,"y":118,"wires":[["97972964.f17b48"]]},{"id":"97972964.f17b48","type":"debug","z":"d110aaf4.303858","name":"","active":true,"console":"false","complete":"true","x":495,"y":97,"wires":[]},{"id":"291792d5.7846d2","type":"ui_group","z":"","name":"dropdown","tab":"294d2b20.07ba54","disp":true,"width":"10","collapse":false},{"id":"294d2b20.07ba54","type":"ui_tab","z":"","name":"Dropdown Error #405","icon":"dashboard","order":5}]

When it was user first time in frontend, the backend showet an error obout returning an object. Proberly because, there are 2 items with same value “label”.

**Comment by Brian5600** [comment]
I have tried to install 2.9.5beta. But it does not solve the problem.

I have investetegated further. The width value from the line adding var value to the container goes to the class “red-ui-typedInput-container”, when it load the side. This is not changing afterwards, even if I change the width of the Edit dropdown node. This means that if the line with “var value” has “width:150px” in style, it will be the size of the class “red-ui-typedInput-container”. 
The text-field for the value can resize, but if the size become bigger, than the container-width, it will not be visible. The next field with label, stays next to the class “red-ui-typedInput-container”.

It might be something with CSS “calc(50% - 32px)”, that does not calc well in the line var value....

Even if I comment out the width /*width:150px;*/ it goes to the class “red-ui-typedInput-container”.

This problem shows on iPad, Chrome and Rpi, chromium.

**Comment by dceejay** [comment]
Which browser are you using ? On which os is the browser running ? Struggling to recreate the problem here. 
I’m going to suggest updating Node-RED to latest 0.18 version

**Comment by Brian5600** [comment]
Hello

In the buttom I wrote, it is iPad, Chrome latest version. And Raspberry pi, with updated Rpi-os, and cromium.

For now I have made an workaround, by putting in width:150px; in the line with var value...

It is running in an semi-production environment, so the next step will be upgrading node-red, node.js and npm. I will try in a test-environment first.

Best regards
