### ISSUE TITLE
Numeric input field too small

### ISSUE THREAD

**Issue by olivalle** [node-red/node-red-dashboard#407]
### What are the steps to reproduce?
Use the numeric widget
### What happens?
Numeric field is to small with more than 2 digits
### What do you expect to happen?
It was working fine with Node-RED-Dashboard version: 2.7
### Please tell us about your environment:
Node-RED version: 

- [ ] Node-RED-Dashboard version: 2.9.4
- [ ] Node-RED version: v0.18.6
- [ ] node.js version: v8.11.2
- [ ] npm version: 6.1.0
- [ ] Platform/OS: Raspberry PI 3 Rasbian 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
- [ ] Browser: Firefox ESR 52.8.1

**Comment by dceejay** [comment]
can you provide an example flow to show the problem ?
How is the numeric node configured ? min / max etc

**Comment by dceejay** [comment]
no response
