### ISSUE TITLE
There is no way to change the Submit/Cancel text on a ui-form without editing code

### ISSUE THREAD

**Issue by juggledad** [node-red/node-red-dashboard#408]
There is no way to change the Submit/Cancel text on a ui-form without editing the code in
 .node-red/node_modules/node-red-dashboard/dist/js/app.min.js
and searching for 
<md-button type="submit" class="md-raised nr-dashboard-form-button">submit</md-button>
and then you can change it.

### What are the steps to reproduce?
There aren't any steps to reproduce, just add a form and look at it. this is 'missing functionalty'??

### What happens?
The Submit/Cancel text is embedded in:
 .node-red/node_modules/node-red-dashboard/dist/js/app.min.js so it always displays

### What do you expect to happen?
It would be nice to have an option in the ui-form node to allow the user to enter what they want for the words 'Submit' and 'Cancel'

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.9.4
- [ ] Node-RED version: 0.18.7
- [ ] node.js version: 8.9.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: osx
- [ ] Browser: Any

**Comment by juggledad** [comment]
works like a charm!

**Comment by dceejay** [comment]
what check box ?

**Comment by juggledad** [comment]
oh wait...that is just an icon that looks like a check box...hmmm might want to use a different one.

**Comment by dceejay** [comment]
ah - was just trying to find one that looks like a button 

![image](https://user-images.githubusercontent.com/5375409/41810775-c5cd5830-76fb-11e8-8b74-449e6f714b83.png)

**Comment by juggledad** [comment]
Yeah I get that now, but I thought that was aa option to turn on/off the option

**Comment by dceejay** [comment]
better suggestions from fa-icons 4.7 welcome !

**Comment by juggledad** [comment]
pencil-square?? and I have to go out to rescue my daughter-in-law...(sigh I just got home)

**Comment by juggledad** [comment]
I think the 'square' instead of the 'square-o' would be better, at least it diesn't look like a check box.

None of the other fa-icon's reaches out to me to represent a button.
