### ISSUE TITLE
Denial of service warnings on install

### ISSUE THREAD

**Issue by sspence65** [node-red/node-red-dashboard#411]
C:\Users\sspence\.node-red>npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > engine.io > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-adapter > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-client > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-client >
                  engine.io-client > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-adapter >
                  socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-client >
                  socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Patched in      >= 2.6.9 < 3.0.0 || >= 3.1.0

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-parser > debug

  More info       https://nodesecurity.io/advisories/534

  High            Regular Expression Denial of Service

  Package         parsejson

  Patched in      No patch available

  Dependency of   node-red-dashboard

  Path            node-red-dashboard > socket.io > socket.io-client >
                  engine.io-client > parsejson

  More info       https://nodesecurity.io/advisories/528

found 9 vulnerabilities (8 low, 1 high) in 192 scanned packages
  9 vulnerabilities require manual review. See the full report for details.

The parsejson package has not been functionally updated since it was initially released.

Additionally, it provides functionality which is natively included in Node.js, and therefore the native JSON.parse() should be used, for both performance and security reasons.

**Comment by knolleary** [comment]
For security related items, please consider contacting the maintainers privately in the first instance rather than make a public disclosure. Thanks.
