### ISSUE TITLE
Scroll Bar present on form nodes

### ISSUE THREAD

**Issue by JamiePhonic** [node-red/node-red-dashboard#416]
I have added a form node to a flow to allow users to enter data into a flow, however when viewed on the dashboard, a scroll bar is shown, but only for the form element. (see image below)

#### Environment information:
Node-RED-Dashboard version: 2.9.6
Node-RED version: 0.18.7
node.js version: 8.11.3
npm version: 6.3.0
Platform/OS: Ubuntu Server 16.04.3
Browser: Firefox & Chrome on Linux mint 19 and windows 10 1803

[![Selection_001.png](https://s8.postimg.cc/lwqvzdd8l/Selection_001.png)](https://postimg.cc/image/rkx6q9hkx/)

**Comment by dceejay** [comment]
Hi - sorry for delay (been on vacation) - can you share the flow you have that shows this. thanks

**Comment by JamiePhonic** [comment]
This issue is present on any and all flows i create, even a simple "form --> debug" flow.
I can post the flow anyway, however I'll need some time to sanitize it first.

**Comment by dceejay** [comment]
OK just create a simple one then ;-)

**Comment by dceejay** [comment]
hmm - odd - not seeing that here - How do you have the Dashboard Site settings?
![image](https://user-images.githubusercontent.com/5375409/44006604-0535ce30-9e7f-11e8-86ed-35da134f8402.png)

![image](https://user-images.githubusercontent.com/5375409/44006597-e0426764-9e7e-11e8-8b5c-f8eef1e611ce.png)

**Comment by JamiePhonic** [comment]
That seems to be the issue.
I have my 1x1 widget size set to 40 to give me a tighter grouping on some guages i have on another flow. setting it back to 48 gets rid of the scroll bar on the form widget

![2018-08-13 08_33_01-node-red _ node-red jamiephonic tk](https://user-images.githubusercontent.com/4817698/44018575-20964bdc-9ed4-11e8-8c49-c78341b9d0e7.png)

**Comment by dceejay** [comment]
Aha - ok will have a look to see if we can improve that.
