### ISSUE TITLE
Saving and loading custom profile themes doesn't work properly

### ISSUE THREAD

**Issue by K-RAD** [node-red/node-red-dashboard#419]
Saving and loading custom profile themes doesn't work. Tried a lot of times to save a profile, didn't work until I restarted the server. I changed something, now I try to load the saved profile and it will not do it.

  Node-RED-Dashboard version: 2.9.6
  Node-RED version: 0.18.7
  node.js version: 8.11.3
  npm version: 5.6.0
  Platform/OS: Windows
  Browser: Chrome

**Comment by K-RAD** [comment]
Turns out the colors do load up on the actual dashboard, but they don't show up/change in the theme settings colors

**Comment by dceejay** [comment]
odd - don't have windows to hand - but is working on chrome on mac - soon as you select theme and say OK - the colours in the editor sidebar change... then deploy and thy appear on dashboard.

**Comment by Paul-Reed** [comment]
Working here on -
Node-RED-Dashboard version: 2.9.7 beta
Node-RED version: 0.19.1
node.js version: 8.11.3
npm version: 5.10.0
Platform/OS: Windows 10
Browser: Chrome

Can you try updating @K-RAD and try again?

![theme](https://user-images.githubusercontent.com/973580/44287430-be6c5480-a264-11e8-9784-5fef689f2b61.gif)
