### ISSUE TITLE
Objects Hidden on Screen Resize

### ISSUE THREAD

**Issue by 9H5G** [node-red/node-red-dashboard#42]
I have some objects as shown here:
![triplecol](https://cloud.githubusercontent.com/assets/13579277/17476428/4b16805a-5d60-11e6-9847-43f5d5275ab5.png)

If I reduce the Window width, then one object (Freezer Temperature) disappears.
![doublecol](https://cloud.githubusercontent.com/assets/13579277/17476430/4b1d4bb0-5d60-11e6-8c71-00ae458a5355.png)

In a single column, then all is well.
![singlecol](https://cloud.githubusercontent.com/assets/13579277/17476429/4b189f34-5d60-11e6-833d-3666c3008b89.png)

I have noticed this behaviour on Windows Chrome and also, iOS Safari where the Temperature graph is always hidden. I have also seen instances where, when I take the window from a 2 column width to 3 column width, the hidden object will not reappear even in a new tab.

All objects are auto sized.

**Comment by dceejay** [comment]
Yes - basically the layout algorithm fails is the first column is shorter than the second - (That 3rd column should move fully to the left but doesn't..)  For workaround now - re-arrange columns so larger on left.

**Comment by 9H5G** [comment]
Cheers Dave :)

Kind Regards
John

**Comment by dceejay** [comment]
Going to close this for now as the fix seems to work so far....
