### ISSUE TITLE
ui control issues, not syncing between devices

### ISSUE THREAD

**Issue by K-RAD** [node-red/node-red-dashboard#422]
I am using a switch+ui control to switch between 2 dashboards. It does work properly on the device where I am pressing the switch, for example on the PC. However, if I press the switch on the mobile, then on the PC the switch will do change, but the UI will actually not. So it becomes unsynced.

Node-RED-Dashboard version: 2.9.6
Node-RED version: 0.18.7
node.js version: 8.11.3
npm version: 5.6.0
Platform/OS: Windows
Browser: Chrome

**Comment by dceejay** [comment]
In general we prefer How-to queries via the discourse forum to start with so th ewidest audience can help to address them.

For your use case you may need the switch configured like this
![image](https://user-images.githubusercontent.com/5375409/43895691-0fd3d944-9bce-11e8-9680-83137136906f.png)

Or am I not understanding the issue ?

**Comment by dceejay** [comment]
Or do you mean you feed the input to a ui_control to switch tabs ? In which case you may need to delete `msg.socketid` so that it knows to send to all rather than just back to that socket.

**Comment by K-RAD** [comment]
I feed the output of the switch to a ui_control to switch tabs. Here's a snippet.

`[{"id":"ff61318c.61156","type":"ui_switch","z":"ef4b69dc.27e518","name":"switch","label":" ","group":"a82fe683.b9b578","order":5,"width":"5","height":"1","passthru":false,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":170,"y":180,"wires":[["5df51bb6.1f2514"]]},{"id":"5df51bb6.1f2514","type":"function","z":"ef4b69dc.27e518","name":"Show/Hide Dashboards","func":"if (msg.payload) {\n    msg.payload = {\"group\":{\"hide\":[\"K-Home_Time\",\"K-Home_Weather\"],\"show\":[\"K-Home_SonosDisplay\",\"K-Home_SonosControls\"]}};\n}\nelse {\n    msg.payload = {\"group\":{\"hide\":[\"K-Home_SonosDisplay\",\"K-Home_SonosControls\"],\"show\":[\"K-Home_Time\",\"K-Home_Weather\"]}};\n}\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":180,"wires":[["a5372c64.d8cb4"]]},{"id":"a5372c64.d8cb4","type":"ui_ui_control","z":"ef4b69dc.27e518","name":"","x":580,"y":180,"wires":[[]]},{"id":"a82fe683.b9b578","type":"ui_group","z":"","name":"Everything Off","tab":"251a1d35.745dc2","order":5,"disp":false,"width":"5","collapse":false},{"id":"251a1d35.745dc2","type":"ui_tab","z":"","name":"K-Home","icon":"dashboard","order":1}]`

**Comment by dceejay** [comment]
Yes - so in your function 
     
    delete msg.socketid;

**Comment by K-RAD** [comment]
Awesome, that solved it, thanks. Guess it wasn't an issue with ui_control
