### ISSUE TITLE
Add Data Labels/Legends Button option to the node-red-dashboard Node for Charts (Bar,Line and Pie Charts)

### ISSUE THREAD

**Issue by M-M-Labhe** [node-red/node-red-dashboard#423]
### What are the steps to reproduce?
Normal Node-RED Dashboard Chart
Please add an option to the Bar,Line as well as Pie Charts to display the data labels so that inference can be drawn easily out of the charts. 

### What happens?

No Option to Add Data Labels.

### What do you expect to happen?

When we see the Charts generated on the Dashboard we should also be able to see the Data Labels specifying the Data above the respective Bar in the Bar Graph or Point in the Line Graph etc.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [x] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Was about to close these issue as it provides no details or context, but then saw it was raised following this thread in the forum: https://discourse.nodered.org/t/how-to-display-legends-in-bar-charts/2205

**Comment by dceejay** [comment]
The datapoints for individual points are visible on hover over - but the overall legend option is not selectable for bar charts. I initially thought this is a bug - but on looking at it now - it would only repeat the labels that are under the bars anyway... so is it really necessary ?

![image](https://user-images.githubusercontent.com/5375409/43966753-9f5f020e-9cba-11e8-8894-77409ec54b8b.png)

**Comment by M-M-Labhe** [comment]
I think yes, because at the first glance itself we will be able to percieve all the data without individual hover over , which maybe a tire some task if the bars are large in number.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dceejay** [comment]
sorry - I don't have access ton Android for a while - can you post a screenshot ?

**Comment by dceejay** [comment]
Is this the sort of thing ?
![image](https://user-images.githubusercontent.com/5375409/43981828-5b0ff10e-9ceb-11e8-825b-814370ad5b59.png)

**Comment by M-M-Labhe** [comment]
Yes, correct.

When the bars are more then, hover over is a tiresome some.If data labels are present on the bars , then and there problem resolves because at a glance we are able to properly understand the data and the meaning behind the data that too at actual numbers.


________________________________

**Comment by dceejay** [comment]
Ok - added a fix to 2.9.7-beta in master on github

**Comment by henriquefchaves** [comment]
> Is this the sort of thing ?
> ![image](https://user-images.githubusercontent.com/5375409/43981828-5b0ff10e-9ceb-11e8-825b-814370ad5b59.png)

Heyyy, can you help me making something like you?
Or can you import to me your flow?
