### ISSUE TITLE
Dashboard nodes not showing when starting node-red with root privileges

### ISSUE THREAD

**Issue by alberto2000** [node-red/node-red-dashboard#424]
I'm on a Raspberry Pi 3 Model B v1.2 and I need to run node-red with `sudo` as I need access to the GPIO pins of the Raspi for control of some LEDs.
When node-red is run with `sudo` the Dashboard nodes do not show up. They do show up normally when node-red is run without `sudo`. Is this by design or is it a bug?

**Comment by dceejay** [comment]
by design  - when you run as sudo you are using the root user's working directory  `/root/.node-red`  and not the default pi user's - `/home/pi/.node-red`   so you need to specify the user directory you want to use on the command line `-u ...` parameter
