### ISSUE TITLE
ui_numeric ignores angular filter

### ISSUE THREAD

**Issue by ZaragonArt** [node-red/node-red-dashboard#428]
The current version ui_numeric widget does appears to ignore angular filters in the value format field. This worked successfully in an earlier dashboard version.

```
[

    {
        "id": "a3de2378.76249",
        "type": "ui_numeric",
        "z": "4ec1a628.644cf8",
        "name": "doorbell start",
        "label": "Start",
        "group": "23178b5.3febc74",
        "order": 1,
        "width": "3",
        "height": "1",
        "passthru": true,
        "topic": "",
        "format": "{{value * 1000*60|date:\"HH:mm\"}}",
        "min": "0",
        "max": "1435",
        "step": "5",
        "x": 730,
        "y": 900,
        "wires": [
            [
                "f121f476.600fd8",
                "69e94e12.7c757"
            ]
        ]
    },
    {
        "id": "23178b5.3febc74",
        "type": "ui_group",
        "z": "",
        "name": "Doorbell configuration",
        "tab": "c19f1ea3.33fe4",
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "c19f1ea3.33fe4",
        "type": "ui_tab",
        "z": "",
        "name": "Doorbell configuration",
        "icon": "dashboard",
        "order": 2
    }
]
```

I expect this to display the value as a time formatted value eg 14:55 but it just displays the value number. Any form of scaling also is ignored eg {{value * 1000}} only displays the value.
It displayed as expected in dashboard version 2.8.2.
 

### What are the steps to reproduce? 
Create an ui_numeric widget and add angular to value format

### What happens? 
Only the value is displayed angular manipulation is ignored

### What do you expect to happen? 
With the example `{{value * 1000 * 60:date:"HH:mm"}}` I expect a clock like display eg 11:45

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.9.7
- [ ] Node-RED version: 0.19.2
- [ ] node.js version: 8.11.4
- [ ] npm version: 5.6.0
- [ ] Platform/OS: Ubuntu 18.04
- [ ] Browser: IE and Edge

**Comment by ZaragonArt** [comment]
The change appears to have occurred between version 2.9.0 and 2.9.1 when testing with just default node-red, npm and node.js installation. 2.9.0 works, 2.9.1 ignores angular

**Comment by ZaragonArt** [comment]
This change does not fix the issue. Tested with a completely brand new installation of Ubuntu 18, NodeJS, npm and Node-Red with 2.9.8 dashboard. Numeric control still only displays value.

**Comment by dceejay** [comment]
Have you flushed your browser cache/ forced a reload ? The example you gave above is now working fine for me. Or have you changed the example?

**Comment by ZaragonArt** [comment]
My apologies, because I built a brand new environment to test that was the bit I forgot to do. You are of course correct it is working with the browser cache clean. Thank you for the quick fix.
