### ISSUE TITLE
Angular Material ng-click changes background

### ISSUE THREAD

**Issue by Drinkler** [node-red/node-red-dashboard#433]
### What are the steps to reproduce?
`<md-content>
<md-list>
<md-list-item ng-repeat="item in msg.payload"
    ng-click="send({payload:item.sap_description})">
        <div class="md-list-item-text">
            <p>{{item.sap_description}}</p>
        </div>
</md-list-item>
</md-list>
</md-content>`

That's the code from a template in node red. 

### What happens?

If I add  ng-click, the background changes and I can't change it back.

![unbenannt](https://user-images.githubusercontent.com/17321535/46137389-cf3bbd00-c249-11e8-867e-195a1b070026.PNG)

### What do you expect to happen?

I just wanted the material design but with the normal background.

I already tried npm i install node-red/node-red-dashboard but it's just loading.

Should look kinda like this:

![unbenanntsd](https://user-images.githubusercontent.com/17321535/46137761-951eeb00-c24a-11e8-8c22-a81ce52b69e8.PNG)

Thats without ng-click, but well, I can't press it anymore.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.9.8
- [ ] Node-RED version: 0.19.3
- [ ] node.js version: 8.11.1
- [ ] Platform/OS: Raspberry Pi
- [ ] Browser: Google Chrome

**Comment by dceejay** [comment]
Hi - do you have the rest of the flow to inject test data please ?

**Comment by dceejay** [comment]
Hi, I have pushed a fix to master - please give a try and see if it works for you ?

We believe it is related to this upstream issue - https://github.com/angular/material/issues/7525
