### ISSUE TITLE
Gauge shows value but draws no indication

### ISSUE THREAD

**Issue by McGr3g0r** [node-red/node-red-dashboard#441]
The gauge shows value but the indication pointer is always to the minimal value.
When the value is set for example from timestamp trigger it works, but when from msg.payload from sql response it displays only value.

![gauge](https://user-images.githubusercontent.com/3796827/47521044-3329c380-d892-11e8-9020-0a9c2c4aa83e.png)

Node-RED-Dashboard version: 2.10.0
Node-RED version: 0.19.4
node.js version: v6.14.4
npm version: 3.10.10
Platform/OS: Linux
Browser: Chrome (69.0.3497.100) on PC, Chromium on Android Phone

**Comment by McGr3g0r** [comment]
It has something to do with data formating

Does work:
`{{ msg.payload['temp01'].temp }}`

Does not work:
`{{ msg.payload['temp01'].temp | number:2 }}`

**Comment by dceejay** [comment]
Pushed a fix to master - not yet on npm
