### ISSUE TITLE
Radar chart | Labels are not following the theme

### ISSUE THREAD

**Issue by robbbsen** [node-red/node-red-dashboard#443]
### What are the steps to reproduce?

1. Set the theme to dark
2. Insert a chart node
3. Set it to Radar chart

### What happens?

The Y-axis labels are displayed with a white background and dark foreground. (against the theme).

### What do you expect to happen?

Having labels with a back-/ and foreground set to the current theme (dark).
_Nice to have: Option to disable the labels at all (i dont need them, just want the overview)_

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.10.0
- [ ] Node-RED version: 0.19.4
- [ ] node.js version: 8.11.3
- [ ] npm version: 6.4.1
- [ ] Platform/OS: Windows 10 Pro x64
- [ ] Browser: Firefox xx

### Screenshot

![screen_chart](https://user-images.githubusercontent.com/44235470/47607365-4d44dc80-da1f-11e8-8ab7-857154ea344a.png)

**Comment by dceejay** [comment]
Pushed a fix to master (not yet npm)
![image](https://user-images.githubusercontent.com/5375409/47615921-f2a69180-daad-11e8-98bd-3e9840b0764a.png)

**Comment by robbbsen** [comment]
That was fast! Thank you very much!

**Comment by jchen5057** [comment]
how  do I format dataset for radar chart?

**Comment by knolleary** [comment]
@jchen5057 please don't use issues that have been closed over a year to ask questions. You can use discourse.nodered.org for questions.
