### ISSUE TITLE
Latest Dashboard 2.10.1 has issue with the template widget, showing the text background color is different color with background.

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#444]
Latest Dashboard 2.10.1 has issue with the template widget, it is showing a square over the text with different color with background.

### What are the steps to reproduce?
 try this in template widget: 
![image](https://user-images.githubusercontent.com/36041520/47950933-766bec80-df8c-11e8-9110-cf9d9fb321d1.png)

screen shot the issue with Template Widget on ver2.10.1:
![image](https://user-images.githubusercontent.com/36041520/47950847-19bc0200-df8b-11e8-8329-85b1a36c26ac.png)

it shoule be like this screenshot:
![image](https://user-images.githubusercontent.com/36041520/47950878-aa92dd80-df8b-11e8-998e-02ba2aaa162a.png)

### Please tell us about your environment: Node-red-dashboard on Pi 3B+

- [ ] Node-RED-Dashboard version: 2.10.1
- [ ] Node-RED version: v0.19.2
- [ ] node.js version: v8.12.0
- [ ] npm version: 6.2.0
- [ ] Platform/OS: Raspbian
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
can you share your template so we can re-create ?
have you tried turning off our template overrides in the SIte settings tab ? 
![image](https://user-images.githubusercontent.com/5375409/47950936-d7c29a00-df51-11e8-93d8-85c1db79361c.png)
