### ISSUE TITLE
 .nr-dashboard-theme .nr-dashboard-template path ruin the template

### ISSUE THREAD

**Issue by SergiuToporjinschi** [node-red/node-red-dashboard#447]
Hi, I have highChart in a template and unfortunately, after update the chart is ruined;
I've done some investigations and it seems this css is faulting; because the charts are displayed with paths is putting the blue color (default one) over the graphics.
  `  .nr-dashboard-theme .nr-dashboard-template path {
        fill: @widgetBackgroundColor;
    }`
I tried adding a new value for (.nr-dashboard-theme .nr-dashboard-template path) and unfortunately, setting fill as none became transparent, which resolves the lines in chart but labels are messing, because are transparent.
 
![image](https://user-images.githubusercontent.com/9376439/48406247-a067a080-e73c-11e8-9d38-2546a7295ce9.png)

**Comment by dceejay** [comment]
Did you try turning off the theme in the template ? 

![image](https://user-images.githubusercontent.com/5375409/48413837-dad33c80-e740-11e8-9ee2-d37c66a9db24.png)

**Comment by SergiuToporjinschi** [comment]
Hi @dceejay, Thank you for the tip. Is working with "Angular theme everywhere"
