### ISSUE TITLE
Bluemix node red integration

### ISSUE THREAD

**Issue by ratihS** [node-red/node-red-dashboard#45]
Hi,

May I know how to integrate this to bluemix platform please? I'm fairly new in bluemix development so it would be helpful to have a guide for that if possible.

Thank you kindly

**Comment by knolleary** [comment]
Hi, for general questions please use the mailing list linked from nodered.org

In this instance, the landing page of your node-red app on bluemix includes instructions for adding additional nodes to your app. That's all you need to do here - add node-red-dashboard to your apps dependencies in package.json.

**Comment by dceejay** [comment]
or you can use my quickstart button - 
https://github.com/dceejay/node-red-bluemix-starter
that already includes it
(or clone that project and fully customise to suit yourself)

**Comment by ratihS** [comment]
Thank you kindly sir :)
