### ISSUE TITLE
Is it me or when I updated to 2.11.0 Dashboard and node-red 19.5 the tab names no longer appear in the title bar?

### ISSUE THREAD

**Issue by marksmanaz** [node-red/node-red-dashboard#453]
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by dceejay** [comment]
ooops... will be back imminently...

**Comment by marksmanaz** [comment]
Sorry to say but that put the tab name in the title bar along with the title. From what I remember Tabs had their own bar secondary under the title bar.

**Comment by marksmanaz** [comment]
![capture](https://user-images.githubusercontent.com/29682799/49572486-28366a00-f8f9-11e8-991e-194cf0bda2bb.PNG)

**Comment by marksmanaz** [comment]
I guess this would be fine if you could make the Tab name come after the Tile name and have a space between them

**Comment by dceejay** [comment]
Ok - now aiming for this

![image](https://user-images.githubusercontent.com/5375409/49598489-aab13f00-f976-11e8-8434-deccbb64afef.png)

**Comment by marksmanaz** [comment]
Sounds good to me, thank you
