### ISSUE TITLE
TypedInputs for ui_button changed, now missing flow and global

### ISSUE THREAD

**Issue by danlorek** [node-red/node-red-dashboard#455]
Hi,
I had to rebuild a Pi with my dashboard today and when restoring the flow from the clipboard it no longer worked. 

After some troubleshooting I noticed that the button node no longer had the "flow." and "global." typed inputs for the payload which I as using. This is for the latest version: 2.12.1

Reverting back to 2.9.7 of node-red-dashboard fixed this. Is this change expected?
You can see the change for ui_button.html here that removed the typedInputs:
https://github.com/node-red/node-red-dashboard/commit/6f7c920ed8832612d2d8009cb8b4fc828a8e1815#diff-ca15fd43dfaeb80eb8c125735e0479b0

Thanks,
Daniel

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
0.19.5: Maintenance Release

- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by dceejay** [comment]
hmm yeah - I now have no idea what the thinking was there...  will revert in master right away... 
(not yet to npm)
