### ISSUE TITLE
Audio-out node, "error: not-allowed"

### ISSUE THREAD

**Issue by LeonardAB** [node-red/node-red-dashboard#458]
### What are the steps to reproduce?
1. Run a node-red instance in Ubuntu VM on azure.
2. create a simple inject that goes to an audio-out node on that instance

### What happens?
When injected, the node has "error: not-allowed" mark
![image](https://user-images.githubusercontent.com/14308605/49857348-a8972680-fe35-11e8-8016-bc5b1eea89d1.png)
When accessing `http://<my_ip>:1880/ui` , no audio was heard

### What do you expect to happen?
audio could be heard from  `http://<my_ip>:1880/ui` after injecting the node 

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.12.2
- [x] Node-RED version: 0.19.5
- [x] node.js version: 8.14.0
- [x] npm version: 6.4.1
- [x] Platform/OS: Ubuntu 18.04 on Azure VM
- [x] Browser: Chrome 71.0.3578.80 

Thanks!

**Comment by dceejay** [comment]
Hi - in general we prefer questions via the discourse forum or slack channel so the widest possible audience can help.

This is an error from your browser for some reason... the error is actually coming from here

https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionError/error

So something in your browser is blocking it. I know they were stopping auto play of music etc - so maybe it's related. - eg see here https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/WsnBm53M4Pc

**Comment by LeonardAB** [comment]
Hi, thanks for the reply. 
Then my guess it that chrome blocks sound automatically if the sound comes from an HTTP (not HTTPS) site.
As a workaround, on Chrome I changed the site setting so that it allows sound (click the "Not secure" mark on the left side of the address). I guess there is nothing we can do on the server side, maybe changing it to HTTPS will work (I haven't tried it though)

Once again, thanks for giving a hint!
