### ISSUE TITLE
ui.js beforeSend()

### ISSUE THREAD

**Issue by pelis** [node-red/node-red-dashboard#46]
Suggestion: I think ui.js beforeSend should be revised:

```
        if (opt.forwardInputMessages && opt.node._wireCount) {
            //forward to output
            msg.payload = opt.convertBack(newValue);
            msg = opt.beforeSend(msg) || msg;
            opt.beforeSend(msg);
            opt.node.send(msg);
        }
```

beforeSend(msg) is called twice?
msg = opt.beforeSend(msg) || msg;
opt.beforeSend(msg);

since the default beforeSend(msg) in ui.js returns nothing (undefined) I would probably kill 
 msg = opt.beforeSend(msg) || msg;

ui.js handler passes two arguments to beforeSend()

```
   var toSend = {payload: converted};
   toSend = opt.beforeSend(toSend, msg) || toSend;
```

revising this could be a bit painfull as most controls could be affected...
e.g. ui_dropdown.js beforeSend(msg) takes one argument

Maybe there are some good reasons for this...

**Comment by dceejay** [comment]
Hi - yes I spotted that a few days ago... not sure it makes sense to me either... needs digging into.

**Comment by dceejay** [comment]
commented out the second with no ill effects.. and been running in master like that for weeks - no reports of any issues, and now part of 2.2.0 release.
so going to close this for now.
