### ISSUE TITLE
Security issues with Angular 1.5.11

### ISSUE THREAD

**Issue by JacobTheEvans** [node-red/node-red-dashboard#462]
First off thanks to everyone who contributes to this project. We use these nodes all the time!

### Issue
This project currently uses Angular 1.5.11 as a dependency. See below
package.json
```json
"angular": "~1.5.11",
```
package.json.lock
```json
        "angular": {
            "version": "1.5.11",
            "resolved": "https://registry.npmjs.org/angular/-/angular-1.5.11.tgz",
            "integrity": "sha1-jFunOG8VllyazzQp9ogVU6raMNY=",
            "dev": true
        },
```
This is an outdated version of angular and has some known vulnerabilities. See here
https://snyk.io/test/npm/angular/1.5.11

### Recommended Solution:
Update to angularJS version 1.7.5

### Environment:

- [ ] Node-RED-Dashboard version: 2.13.0

**Comment by dceejay** [comment]
hmm - doesn't show up in `npm audit`.  Tried simply upgrading to that level and it breaks the dashboard so not going to rush this in.
