### ISSUE TITLE
 base color fill all path elements

### ISSUE THREAD

**Issue by Liddll** [node-red/node-red-dashboard#463]
the base color is inherited to all **path** fill elements

`.nr-dashboard-theme .nr-dashboard-template path {
	fill: #097479;
}`

this is impractical if thermometers, gauges, charts (e.g. fusionscharts or google charts) are used
![grafik](https://user-images.githubusercontent.com/30312707/50742552-04728680-120d-11e9-878c-f898b7820169.png)

![grafik](https://user-images.githubusercontent.com/30312707/50742560-20762800-120d-11e9-9c14-7a719a35db7a.png)

**Comment by dceejay** [comment]
Did you try turning off the theme in the template using the Dashboard - Site settings tab -
![image](https://user-images.githubusercontent.com/5375409/50771067-68cf2d80-1281-11e9-9244-b01aff713c3f.png)

**Comment by DDDanny** [comment]
I have (had) this issue too and can confirm that choosing this options solved it!
My styles included in header for later SVG's are no more overwritten with later inline fill css declarations
*voting for "OK to close"*

PS: Now some of my nasty CSS aligns looks very crappy but this is not your topic dev ;)

**Comment by dceejay** [comment]
Thanks
