### ISSUE TITLE
ui_text_input - Date Picker - no Date on Mobiles

### ISSUE THREAD

**Issue by Damontir** [node-red/node-red-dashboard#467]
### What happens?
"ui_text_input" in Mode "Time Picker" doesnt display the actual Time(HH:mm) on Mobilephones. Tested with iOS12.1.2
On Windows 10 + Chrome i can see the actual HH:mm on Dashboard, everything perfect

### What do you expect to happen?
display the HH:mm on Android/iOS

### Please tell us about your environment:

- [ X ] Node-RED-Dashboard version: 2.13.0
- [ X ] Node-RED version: 0.19.5
- [ X ] node.js version: 10.15.0
- [ X ] npm version: 6.4.1
- [ X ] Platform/OS: Raspbian Stretch
- [ X ] Browser: Chrome 71.0.3578.98

**Comment by dceejay** [comment]
The various modes of the ui_text node are set by the html5 tags. How those are presented to the user depends on how your device browser chooses to support them. Not much we can do about that.
