### ISSUE TITLE
[minor] reoccurence of solved error: SideNav 'left' is not available!

### ISSUE THREAD

**Issue by DDDanny** [node-red/node-red-dashboard#470]
Hi folks, 
also not a hard error from my POV -> as I see no general misbehaviour - I guess the dashboard restarts itseld due to the error, as I see 2 times "Less has finished."

I removed all my startups scripts inheader, but maybe someone can shortly verify that this occurs for him also:
_Reproduce_: Open NR Dashboard initial (new tab or new browser session) (does not occur on reload page)
_Error_: Console shows: (error) SideNav 'left' is not available! Did you use md-component-id='left'? app.min.js:148:278

_version infos_
server (raspberry pi): node js v8.15.0 + NR 6.7.0 + NR dashboard 2.13.1
client (Windows 10 1803): firefox 64.0.2 (64-Bit)

Full firefox console snippet:

```
Rendered http://<host>:1880/ui/css/app.min.less successfully. app.min.js:514:12823
CSS for http://<host>:1880/ui/css/app.min.less generated in 140ms app.min.js:514:12823
Less has finished. CSS generated in 140ms app.min.js:514:12823
You are using the ngTouch module. 
AngularJS Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with AngularJS Material! app.min.js:148:278

SideNav 'left' is not available! Did you use md-component-id='left'? app.min.js:148:278

e/<
http://<host>:1880/ui/js/app.min.js:148:278
find
http://<host>:1880/ui/js/app.min.js:469:179845
e/<
http://<host>:1880/ui/js/app.min.js:469:179974
this.select
http://<host>:1880/ui/js/app.min.js:568:3439
this.open
http://<host>:1880/ui/js/app.min.js:568:3534
<anonym>
http://<host>:1880/ui/js/app.min.js:568:6360
f/r<
http://<host>:1880/ui/js/app.min.js:190:308
Tg/this.completeTask
http://<host>:1880/ui/js/app.min.js:187:15
Ag/h.defer/d<
http://<host>:1880/ui/js/app.min.js:73:1
Rendered http://<host>:1880/ui/css/app.min.less successfully. app.min.js:514:12823
CSS for http://<host>:1880/ui/css/app.min.less generated in 109ms app.min.js:514:12823
Less has finished. CSS generated in 109ms app.min.js:514:12823
```

It seems that this issue was already fixed within
2.1.0: Milestone Release
[...] Fix missing sidenav "left" item on initial page load

Thank you soo much for providing this great frontend!
Danny

**Comment by dceejay** [comment]
closed by 248ae4059785e87dba39363831bfb27940618660
