### ISSUE TITLE
Stored Cross Site Scripting (XSS)

### ISSUE THREAD

**Issue by thelostsaint** [node-red/node-red-dashboard#473]
We   observed that the web application is vulnerable to cross-site scripting (XSS)   attack due to inappropriate filtering of input variables. Application is   accepting special characters as user input. Browsers are capable of   displaying HTML page and executing javaScript. If the application does not   escape special characters in the input/output and reflects user input as is   back to the browser, an adversary may be able to launch a Cross-Site   Scripting attack successfully. It was also observed the vulnerability in the   parameters mentioned. However, the vulnerability might be available in the   entire application, and all other parameters, functions and pages needs to be   checked for the same.

Stored XSS:
Step 1: Browse the URL and insert the Javascript payload as shown in the image below.
![image](https://user-images.githubusercontent.com/6994778/52058538-adeb3480-258d-11e9-93e6-0b9ee797daf8.png)
Step 2: The above image confirms that the application is vulnerable to Stored XSS.

**Comment by royaldevbrat** [comment]
> I have identified the issue in the node-red-dashboard module. This is not a core node-red issue. I will move this issue over to the appropriate repository.

But I am not using node-red-dashboard.

**Comment by knolleary** [comment]
Can you share precise steps to reproduce then? What node are you editing to insert the script?

**Comment by knolleary** [comment]
@royaldevbrat in my original reply to you I asked if you could recreate this with any non-dashboard node, and to provide details if that is the case.

Right now, the *only* issue we are aware of is specific to the node-red dashboard sidebar.

Please can you confirm exactly what you are doing to reproduce this.

**Comment by dceejay** [comment]
I have pushed a commit to replace as many .html( tags as possible with .text( . This should clean up the examples so far given. Please let us know of any more you can find. Thanks

to try it  install the master version in your node-red user directory

    npm i node-red/node-red-dashboard

**Comment by royaldevbrat** [comment]
> @royaldevbrat in my original reply to you I asked if you could recreate this with any non-dashboard node, and to provide details if that is the case.
> 
> Right now, the _only_ issue we are aware of is specific to the node-red dashboard sidebar.
> 
> Please can you confirm exactly what you are doing to reproduce this.

I am using Twitter Node(some other node also has this issue)and adding some script in edit the node
![capture2](https://user-images.githubusercontent.com/3677263/52390222-4cf7bb00-2abd-11e9-8d06-7d1c35e7fbfe.PNG)

Then after deploy, I am getting that alert
![capture1](https://user-images.githubusercontent.com/3677263/52390263-71539780-2abd-11e9-9fe9-80a4dc466bf6.PNG)

Please check once whether it is Node-RED or Pallete issue.  Let me how to mitigate this. Thanks in advance

**Comment by knolleary** [comment]
@royaldevbrat thanks for that - your description has helped to identify the extra step you were taking to hit this compared to the original report. Specifically, it was the warning dialog when trying deploy a misconfigured node. Have pushed a fix to node-red - will be in 0.20.

**Comment by royaldevbrat** [comment]
I am also developing some nodes for my company. So can you please tell me
how to fix these issue?

This will be a great help for me.

Thanks,
Devbrat

**Comment by knolleary** [comment]
@royaldevbrat the fix was in the core of Node-RED. There's nothing to change in your node for this.

The main thing to do is never display any node property without sanitising any html content.

**Comment by knolleary** [comment]
You can see the specific fix we applied for the instance you reported here: https://github.com/node-red/node-red/commit/724acff59179a50dcce3f1c4fcc16215f5c73fb9

**Comment by royaldevbrat** [comment]
Thanks for your reply.

**Comment by dceejay** [comment]
so are we good to close this now - or ... ?

**Comment by dceejay** [comment]
closing as I believe this is now fixed as per issue above. No further feedback.

**Comment by saurabhcnigam** [comment]
This XSS issue in nodes has been fixed. But XSS can still occur in other places on dashboard. Actually at any place where user input is accepted by application and is not sanitized. 

![image](https://user-images.githubusercontent.com/20120534/54263688-6ba71100-4597-11e9-8f7b-8732724718ff.png)

I would recommend to try using x-xss-protection HTTP response header in every response which would enable XSS filters built-in browsers. It may solve all the XSS possibilities. At same time, sanitizing all user inputs would be the best practice.

**Comment by dceejay** [comment]
Hopefully this fix in the core will mop up most of those  - 1d7be6457ffa42247d9a02c8a5b630e4e33acf31
