### ISSUE TITLE
Updated Dashboard broken

### ISSUE THREAD

**Issue by sithembisoa** [node-red/node-red-dashboard#477]
17 Nov 18:24:12 - [warn] [node-red-node-serialport/serialport] Error: Module version mismatch. Expected 46, got 57.
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_base] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_button] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_dropdown] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_switch] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_slider] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_numeric] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_text_input] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_date_picker] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_colour_picker] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_form] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_text] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_gauge] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_chart] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_audio] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_toast] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_ui_control] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_template] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_link] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
17 Nov 18:24:12 - [warn] [node-red-dashboard/ui_spacer] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### What are the steps to reproduce?
- Install nodered dashboard

### What happens?
[node-red-dashboard/ui_base] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

- [ 2.13.2 ] Node-RED-Dashboard version:
- [ 0.19.4 ] Node-RED version:
- [ v8.11.1 ] node.js version:
- [ 2.14.7 ] npm version:
- [ Raspberrypi 3] Platform/OS:
- [Chrome ] Browser:

**Comment by dceejay** [comment]
Please can you also paste the top part of the console log when you run `node-red-start`.
This looks like you have an old version of node.js running yet you say you have 8.11.1

**Comment by sithembisoa** [comment]
17 Nov 19:45:01 - [info]

Welcome to Node-RED
===================

17 Nov 19:45:01 - [info] Node-RED version: v0.19.4
17 Nov 19:45:01 - [info] Node.js  version: v4.2.1
17 Nov 19:45:01 - [info] Linux 4.14.98-v7+ arm LE
17 Nov 19:45:02 - [info] Loading palette nodes
17 Nov 19:45:07 - [warn] ------------------------------------------------------

**Comment by knolleary** [comment]
Your version of node.js is too old. It is using 4.2.1 - not 8.11 your initial report states

**Comment by sithembisoa** [comment]
I ran nodejs -v instead of node -v.

 sudo apt-get install node
Reading package lists... Done
Building dependency tree
Reading state information... Done
node is already the newest version (4.2.1-1).
The following packages were automatically installed and are no longer required:
  vlc-plugin-notify vlc-plugin-samba vlc-plugin-video-splitter vlc-plugin-visualization
Use 'sudo apt autoremove' to remove them.

**Comment by dceejay** [comment]
If this is on a Pi you should use our Install/upgrade instructions as per our documentation
