### ISSUE TITLE
Dashboard 2.13.2 crashes in Chrome 72.0.3626.119

### ISSUE THREAD

**Issue by A-Epp** [node-red/node-red-dashboard#478]
### What are the steps to reproduce?
Open the Dashboard in Chrome 72.0.3626.119

### What happens?
The Dashboard works for a few seconds and then it produces the error:
`index.js:83 WebSocket connection to 'wss://192.168.80.60/api/ui/socket.io/?EIO=3&transport=websocket&sid=YWJbOQdSgxDRC4WiAAAK' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID`

This "infects" the Node-RED Editor if it is open in a second tab and it also fails. I have a webpage which is hosted from the same node.js instance and it also goes down with said error on each request.
If I only open my webpage and the Node-RED Editor everything is fine

### What do you expect to happen?
Before the Chrome update to Version 72.0.3626.119 everything worked fine.

### Please tell us about your environment:
Node-RED is embedded in my node.js application. The Connection to Node-RED goes through a proxy (Nginx). This issue does not occur for the Node-RED editor, or the website from my node.js application (experss webserver).

- [ ] Node-RED-Dashboard version: 2.13.2
- [ ] Node-RED version: 0.18.7
- [ ] node.js version: v11.6.0
- [ ] npm version: 6.5.0-next.0
- [ ] Platform/OS: 
  Windows 10 1809 Build 10.0.17763.316
  Debian 9, Kernel 4.9.0-7-amd64
- [ ] Browser: Chrome 72.0.3626.119

**Comment by dceejay** [comment]
Do you have a self-signed cert ? Does this give any clues
https://stackoverflow.com/questions/23404160/why-does-my-wss-websockets-over-ssl-tls-connection-immediately-disconnect-w

The dashboard uses socket.io which tries a variety of connection types to create its "websocket" connection, so it may be triggering a failure for some reason.

**Comment by A-Epp** [comment]
Hey, thanks for the reply.
Yes I am using a self signed certificate. Unfortunately the link you provided does not help in my case as I can not alter the Sourcecode of the dashboard (I'd like to stay compatible with updates)

The connection to the dashboard is routet through a proxy and is encryptet (https).
Is it possible to deactivate the secure websocket of the dashborad for a normal websocket and still be encryptet because of the the proxy which encrypts all traffic anyway?

**Comment by dceejay** [comment]
I think it matches the web socket security to the http security level so if you use http it should use ws, and if https then wss is used.

**Comment by A-Epp** [comment]
I see. I think I will use Firefox until this is fixed by Google or maybe the Dashboard team.
Out of curiosity: where you able to reproduce this behaviour?
I found several cases of users of different programms with browser clients which had problems with the new Chrome update but not a single one with the Dashboard.

**Comment by dceejay** [comment]
I don't use nginx so can't easily replicate this.
Also note we prefer the LTS versions of node.js (so 8.x or 10.x) and I think we did update ws library in the underlying Node-RED 0.19.x so maybe worth up/down-grading.

**Comment by A-Epp** [comment]
I have now upgraded Node-RED to 0.19.6, still the same result.
Could you try it without a proxy and chrome? I am really interested to see if someone else has the same issue. I will now try to downgrade my node.js to 10.x and report back

**Comment by A-Epp** [comment]
Unfortunately I can not downgrade the node.js version as my team depends on it. I am switching to Firefox for now, and keep an eye on chrome, maybe this will sort itself out.
Thanks anyways.
