### ISSUE TITLE
ui_dropdown not always displaying options passed to it via msg.options

### ISSUE THREAD

**Issue by jphillips-bp3** [node-red/node-red-dashboard#479]
### What happens?
I have an issue with the `ui_dropdown` not always showing the data passed to it via `msg.options`. I say not always because this seems to be sporadic. However, if I hit the refresh button on the browser the items always appear.

I have other drop downs with the values configured directly in the component and never get this problem.

So whilst I cannot replicate it every time, I wondered if this was a known issue and what the fix might be?

### What are the steps to reproduce?
I cannot share the flow because it is for a client and is confidential, and I have tried replicating in a basic flow but cannot (typical!). But essentially I am creating a `msg.options` object from a function node and passing in the data to the `ui_dropdown` node. I have checked when it does happen that I have actually passed in the options and I can see the data being passed through.

This also only seems to happen on Chrome, and not Firefox or Safari.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.13.2
- [ ] Node-RED version: v0.19.5
- [ ] node.js version: v6.16.0
- [ ] npm version: 3.10.10
- [ ] Platform/OS: Mac OS, with NR running inside Docker built from image `nodered/node-red-docker` 
- [ ] Browser: Chrome v72.0.3626.121

**Comment by dceejay** [comment]
Going to be tricky to fix if we can't recreate. So will leave it here and hope someone else a) reports the same and b) has a reliable way to re-create.

**Comment by jphillips-bp3** [comment]
@dceejay Sure and that was the answer I expected!

**Comment by fhoner** [comment]
I'm having the same issue, as well as for the form node.  I will try to provide a sample flow to reproduce this.

**Comment by DoctorU** [comment]
Here's full steps to recreate this issue.
Sorry for not exporting the Dashboard: 1) I don't know how to, and 2) there's things on other UI tabs I don't want to share!

PREREQUISITE
* Create two tabs in the dashboard UI, 'Demo UI Tab 1', 'Demo UI Tab 2'
* Put dropdown on 'Demo UI Tab 2'. Anything on 'Demo UI Tab 1'.
* The dropdown's `msg.option`s are populated in a flow started by an interval trigger, e.g., 2 seconds after deployment.
* Deploy the flows/ui once.

STEPS TO REPRODUCE
* Before re-deploy, view 'Demo UI Tab 1'.
* Deploy all flows.
* Wait for interval (in example below, 1 second) to "populate" the dropdown on tab 2.
* View 'Demo UI Tab 2'.

ACTUAL OUTCOME
* Dropdown options are empty.

EXPECTED OUTCOME
* Dropdown options are populated with values.


EXAMPLE FLOW
```
[
    {
        "id": "cca8d493.5a61e8",
        "type": "tab",
        "label": "Flow 4",
        "disabled": false,
        "info": ""
    },
    {
        "id": "9e697b90.51e418",
        "type": "ui_dropdown",
        "z": "cca8d493.5a61e8",
        "name": "",
        "label": "",
        "tooltip": "",
        "place": "Select option",
        "group": "5f032b51.37b174",
        "order": 2,
        "width": 0,
        "height": 0,
        "passthru": true,
        "multiple": false,
        "options": [
            {
                "label": "",
                "value": "",
                "type": "str"
            }
        ],
        "payload": "",
        "topic": "",
        "x": 830,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "63961c63.4b9e54",
        "type": "inject",
        "z": "cca8d493.5a61e8",
        "name": "",
        "props": [],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": "1",
        "topic": "",
        "x": 300,
        "y": 200,
        "wires": [
            [
                "ce8be060.0944c"
            ]
        ]
    },
    {
        "id": "ce8be060.0944c",
        "type": "change",
        "z": "cca8d493.5a61e8",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "options",
                "pt": "msg",
                "to": "['one','two','three']",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 610,
        "y": 200,
        "wires": [
            [
                "9e697b90.51e418"
            ]
        ]
    },
    {
        "id": "5f032b51.37b174",
        "type": "ui_group",
        "name": "Demo UI Group",
        "tab": "efb50e58.599cf",
        "order": 5,
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "efb50e58.599cf",
        "type": "ui_tab",
        "name": "Demo UI Tab 2",
        "icon": "dashboard",
        "order": 3,
        "disabled": false,
        "hidden": false
    }
]
```

**Comment by DoctorU** [comment]
Sorry, missed out this additional info:
* Node-RED-Dashboard version: 2.25.0
* Node-RED version: v1.2.6
* node.js version: v10.23.0
* npm version: Unknown
* Platform/OS: Raspberry pi 4+ running docker-compose'd using nodered/node-red-docker
* Browser: Chrome Version 87.0.4280.88 (Official Build) (64-bit) on Windows

**Comment by fhoner** [comment]
Thanks @dceejay for the fix, works fine on the dropdown. However the same problem still persists on the form node. The reproduction should be exactly the same as described above. If you need another example flow please let me know.

**Comment by dceejay** [comment]
yes please - much easier if I see the same code as you are reporting on. thanks
