### ISSUE TITLE
Template node code window not sized correctly

### ISSUE THREAD

**Issue by TotallyInformation** [node-red/node-red-dashboard#48]
The template node's code window does not vertically size to the browser window. On my large monitor only 13 and a bit lines are actually visible though there is room for well over twice that number.

**Comment by dceejay** [comment]
Yup - got it. Fix in place but looking also looking at dynamic resize of content issue (the widget end) for your cat videos :-)

**Comment by TotallyInformation** [comment]
Thanks Dave - gotta have those cat vids properly shown ;-)

**Comment by dceejay** [comment]
Having now tried dynamic re-size of window when template content changes... - I'm not going to put it in. As it's not easy to tell the content requires a screen size change or not then assuming a redraw for every content change then has to try to resize everything to fit - which is really bad redraw time wise and is just awful... Fine if the content is actually static and doing clever stuff with sockets etc - but hopeless if you just inject new payloads with new values to display - which I think would be the more common behaviour for most people.

So for now a manual reload of the page (ctrl-R etc) will refit the template to the contents (unless you specify a fixed size of course).
