### ISSUE TITLE
Remove AppCache

### ISSUE THREAD

**Issue by gfcittolin** [node-red/node-red-dashboard#480]
We use Node-RED and Dashboard here through HTTPS with self-signed certificates, and we've been experiencing random connectivity issues with it. After digging around a bit, we've found the main culprit to be the interaction usage/application of Dashboard's AppCache by the browser.

Mainly what happens is, on first time the dashboard is loaded, the user accepts the usage of the self-signed certificate, the dashboard loads, and the AppCache definition is downloaded.  By the next time the dashboard is loaded, the resources are loaded from the AppCache, but then the WebSocket connection is not allowed to be done because of invalid certificates. In this case, no certificate confirmation is done.
Here's how it usually looks like when the problem happens

As far as I could see (and please correct me if I'm wrong), the AppCache definition is used solely for caching purposes, and the browser itself is already able to cache resources without using it. I'd like to propose therefore the removal of the AppCache usage by the dashboard.

Here are some links that recommends *against* the usage of AppCache
 - [MDN deprecation note](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache)
 - [Google's Lighthouse Best Practices](https://developers.google.com/web/tools/lighthouse/audits/appcache)
 - [Removal from Web specifications](https://html.spec.whatwg.org/multipage/offline.html#offline)

I'll be happy to provide a PR for this if you guys agree with it :)

### What are the steps to reproduce?

Configure your Node-RED instance to use HTTPS with a self-signed certificate and:
 - Access the dashboard multiple times from Safari or Chrome;
 - or (iOS only) create a shortcut to the dashboard on iPhone's home screen, and then access it multiple times

### What happens?

After loading the dashboard and all the resources have been successfully cached inside AppCache...
![load02](https://user-images.githubusercontent.com/2856088/54561595-c2e81f80-49a3-11e9-9765-1ba3cc556f7f.png)
... the dashboard fails to load and keeps dropping the socket connection on subsequent loads
![load03](https://user-images.githubusercontent.com/2856088/54561621-d3989580-49a3-11e9-8535-428b6619319a.png)

This has been successfully fixed by removind the `dashboard.appcache` file and manually removing the cache from Chrome by using chrome://appcache-internals.

### What do you expect to happen?

The Dashboard should work properly despite the usage of self-signed certificates

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: `2.8.2`
- [ ] Node-RED version: `0.17.5` (same behavior on `v0.20.2`)
- [ ] node.js version:` v8.15.1`
- [ ] npm version: `6.4.1`
- [ ] Platform/OS: Running on Linux/AMv7, accessing from Linux/Windws/iOS
- [ ] Browser: Safari / iOS(WebKit) / Chrome

**Comment by dceejay** [comment]
While deprecated it is still fully supported by all browsers. What isn't fully supported is the use of self-signed certificates with appcache as it can cause security issues. In fact Chromes non-handling of it is an accidental issue that happens to help prevent this security exposure... and so (as appcache is being deprecated) they are in no rush to fix it :-)

Take your point about browsers caching things anyway - will need to do some testing to check load times, and if Ok will remove it. No need for a PR, would be an easy update.

**Comment by dceejay** [comment]
pushed a version 2.15.0-beta to master to test - please provide feedback re both functionality AND load performance. Thanks

**Comment by Paul-Reed** [comment]
Didn't the absence of the AppCache create auth problems, ie repeated requests for logins?

**Comment by dceejay** [comment]
well as pointed out modern browser should handle caches locally better anyway ... but we shall see - hence why only a beta/test at the moment... please feel free to try and comment.

**Comment by Paul-Reed** [comment]
`npm i node-red-dashboard@2.15.0-beta` - is that correct?

Result;
`silly fetchPackageMetaData error for node-red-dashboard@2.15.0-beta No matching version found for node-red-dashboard@2.15.0-beta`

**Comment by dceejay** [comment]
sorry - to pull direct from github you need

    npm i node-red/node-red-dashboard@2.15.0-beta

**Comment by Paul-Reed** [comment]
Yep, tried that too;
`Could not install from "node-red/node-red-dashboard@2.15.0-beta" as it does not contain a package.json file.
`

**Comment by dceejay** [comment]
doh - to rushed  

    npm i node-red/node-red-dashboard

**Comment by gfcittolin** [comment]
I've done some simple tests locally on Gogle Chrome with the help of Developer Console, and here are some of my conclusions:

 - The removal of AppCache does not impact the load speed on local/intranet installations (pretty obvious, but even though)
 - The download size on subsequent page loads increases by approx 3x without AppCache, although still very small (a few kBs, like from 2.3KB to 6.2KB)
 - The load times on simulated slow and fast 3G connections increase by 1s (from `1.5s` to `2.5s`) and 4s (from `4.4s` to `8.4s`) without AppCache, respectively
   - This seems to be mainly due to the network delay to get the 304 response from the server that the file hasn't changed, and the cached version can be used
 - Disabling/clearing the cache or hard reloading a page have no effect for the resources cached by AppCache

The test data and results can be found here: [tests_appcache.tar.gz](https://github.com/node-red/node-red-dashboard/files/2984365/tests_appcache.tar.gz)

So there's a small penalty on removing AppCache, that may be significant for users accessing the dashboard over networks with a very high latency.

If you find out that the removal is not worthy due to increased load times, there maybe a mid-term we can try: to cache all resources with AppCache, except the main page itself. I'll try to do some tests later and check if it's worthy or not.

**Comment by dceejay** [comment]
Interesting. Good results. 
The appcache file should not have had index.html in it anyway (line 40 of the gulpfile.js that builds it). so errr.. not sure what is going on there then. Though I did read somewhere that he page that references the cache may be automatically cached anyway... but I don't know for sure.

**Comment by gfcittolin** [comment]
> Though I did read somewhere that he page that references the cache may be automatically cached anyway... but I don't know for sure.
Looks like that the case. As far as I could see, the html file where the AppCache manifest is defined is *always* cached, it's even listed as "Master" by the browser... what I was trying out is a "hack" that seems to be common when using AppCache to avoid exactly this problem. 
The trick is to have an iframe that loads an empty page, just with the manifest file itself. So the iframe's page get cached, but the main one no. But I'm still missing something here, as I've not been able to make it work :/

**Comment by Paul-Reed** [comment]
Now getting continual requests for auth.

After switching to this version, I cleared my Windows laptop 'chrome' browser & app-cache-manifest, but found that I've had to log in 4 times today for the same browser (most times that I've visited).

In Android mobile browser, again deleted browser cache, and have needed to log in 3 times today. On occasions that I've not needed to auth there is probably a 3-4 second delay before the dashboard is rendered, which did not occur previously.

**Comment by gfcittolin** [comment]
What auth scheme are you using? So that I can try to simulate the issue here

**Comment by Paul-Reed** [comment]
Just the basic `httpNodeAuth` node authentication.
https://nodered.org/docs/security#http-node-security

**Comment by gfcittolin** [comment]
I haven't been able to simulate the basic authentication issue with the current version. Tried multiple times with/without caching with Firefox and Chrome. Do you have any other custom setting that could influence this?

**Comment by Paul-Reed** [comment]
It's a vanilla node-RED installation, being served via https using Cloudflare.
I've now reverted back to v2.14.0 due to repeated auth requests.

**Comment by knolleary** [comment]
@Paul-Reed using what browser on what platform?

**Comment by Paul-Reed** [comment]
On Windows 10 Home - Chrome browser Version 73.0.3683.86 (Official Build) (64-bit)
On Android mobile v9 - Version 73.0.3683.90
Node-RED version 0.20.3 installed on Raspberry Pi under Raspbian Stretch.

Since moving back to Dashboard v2.14.0 the dashboard loads quicker, and the repeated auth requests have stopped.

I'm sure that you will already know anyway, but this is the list of cached files in my browser manifest;
```
CACHE MANIFEST

CACHE:
i18n.js
icon120x120.png
icon192x192.png
icon64x64.png
css/app.min.css
css/app.min.less
css/index.html
js/app.min.js
js/tinycolor-min.js
socket.io/socket.io.js
font-awesome/fonts/fontawesome-webfont.woff
font-awesome/fonts/fontawesome-webfont.woff2
weather-icons-lite/fonts/weather-icons-lite.woff
weather-icons-lite/fonts/weather-icons-lite.woff2
```

**Comment by dceejay** [comment]
For now I'm going to revert this change and restore the appcache as I want to get some other changes released.and don't want to just do this while the logging in multiple times vs self signed certs is still unresolved. (It's a one line change to the index.html to not invoke the appcache so easy to patch manually for now.)

**Comment by gfcittolin** [comment]
That's fine. I haven't had the time to investigate it further/deeper. For now we'll just manually delete the manifest file, having the same result as removing it from the the index.html.
I'll let you know if I find out anything new about it.

**Comment by Rotzbua** [comment]
The appcache is removed from most browsers. Just apple is remaining.
https://caniuse.com/offline-apps

Service works are the replacement which is supported by all common browsers.
https://caniuse.com/serviceworkers

A good framework to implement offline function by service workers is `workbox`.
https://developers.google.com/web/tools/workbox

**Comment by dceejay** [comment]
Yes - but it's still used by some older browsers and tablets...
eg see this thread for a request to run "old code" to support old browsers - https://discourse.nodered.org/t/updating-old-kit/52041/2
I don't think it causes a serious issue for new browsers if left in place.
