### ISSUE TITLE
Chart restarting

### ISSUE THREAD

**Issue by Nedopetaski** [node-red/node-red-dashboard#486]
Hi.. 

I'm new to Node-Red, and I am using the Node-Red-Dashboard to show some data in line charts. 

It was everything ok, but since two days ago the charts started reseting everyday, and loose all the data of the day before. 

Did someone have any ideia of how to solve this problem?

The image show my flow.
![logica nr](https://user-images.githubusercontent.com/49526037/55964318-e6bd1f00-5c4a-11e9-8efe-ad7495593f31.png)

**Comment by dceejay** [comment]
Hi,

generally we prefer how-to type questions on the discourse forum or slack channel so the widest possible audience can try to help you. As we don't know what you have changed in the last few days it's hard to say without guessing. Generally charts are set ot display only a certain amount of data (either points or time) so as not to take up too much memory, and any newly arriving data may cause old data to scroll off the left hand side.

**Comment by Nedopetaski** [comment]
Sorry for posting in the wrong place.

I use two tabs: one to show the data of the day, and the other to show the mean value of each day for one month. 

The charts that show data of the day receive one value each half hour, so it is 48 values per day.

The charts taht show data of the month receive only one value per day.

But everyday the two kinds of chart are reseting. So I don't think it is too much memory in the charts.

**Comment by dceejay** [comment]
no further info or follow up
