### ISSUE TITLE
ui_template produces random height

### ISSUE THREAD

**Issue by nospam2k** [node-red/node-red-dashboard#489]
### What are the steps to reproduce?
Using this flow, when the page first loads, it's fine. Refresh and "bottom line" height changes between 25px(?) and the passed 100px from the msg.payload in the function.

```
[{"id":"92b6f0d9.127df8","type":"ui_template","z":"a47b7c22.4362f8","group":"987f770.d9f8e08","name":"","order":3,"width":0,"height":0,"format":"<div ng-style=\"{'height': '100px'}\">{{msg.payload.top}}</div>","storeOutMessages":true,"fwdInMessages":false,"templateScope":"local","x":660,"y":200,"wires":[[]]},{"id":"aa4cbce0.1f9f","type":"ui_template","z":"a47b7c22.4362f8","group":"987f770.d9f8e08","name":"","order":5,"width":0,"height":0,"format":"<div ng-style=\"{'height': msg.payload.height}\">{{msg.payload.bottom}}</div>","storeOutMessages":false,"fwdInMessages":false,"templateScope":"local","x":660,"y":240,"wires":[[]]},{"id":"f7989716.27bf68","type":"function","z":"a47b7c22.4362f8","name":"Test","func":"var topLine = 'Top line';\nvar bottomLine = 'Bottom line';\nvar payload = {top: topLine, bottom: bottomLine, height: '100px'};\nreturn {payload : payload};","outputs":1,"noerr":0,"x":510,"y":220,"wires":[["92b6f0d9.127df8","aa4cbce0.1f9f"]]},{"id":"835b6c82.58b058","type":"inject","z":"a47b7c22.4362f8","name":"OneTime","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":360,"y":220,"wires":[["f7989716.27bf68"]]},{"id":"987f770.d9f8e08","type":"ui_group","z":"","name":"Test Group","tab":"f320b5e6.9c06b","order":1,"disp":false,"width":"6","collapse":false},{"id":"f320b5e6.9c06b","type":"ui_tab","z":"","name":"Testing","icon":"dashboard","order":5}]
```

### What happens?
Div height randomly changes

### What do you expect to happen?
Div height to remain the same

### Please tell us about your environment:
Running on a fully updated Raspberry Pi.

- [] Node-RED version: 0.19.4
- [] node.js version: 10.15.0
- [] npm version: 6.7.0
- [] Platform/OS: Raspberry Pi - Debian Stretch
- [] Browser: Firefox, Safari

**Comment by nospam2k** [comment]
Thanks, your link took me back to the same place.

**Comment by dceejay** [comment]
The basic functionality is working as designed... in that the template height is calculated at deploy time so that the overall layout of the groups can be determined. If the height changed dynamically whenever new content appeared then the overall layout could "bounce" around all over as it redrew itself.

There is a problem however when you use the ng-style to set the height in that doesn't seem to always get calculated in time for the layout calculation. This time can be extended, to allow more likely completion.

pushed to master here for you to try.

**Comment by nospam2k** [comment]
The refresh seems ok (not sure if that was just the add messages to stored state), but the initial deployment still creates the 2nd div short. Thanks for the work so far!

**Comment by dceejay** [comment]
The card size calculations are done in src/components/ui-card-panel/ui-card-panel-ctrl.js
which is the file I modified withe the above change. More than happy to consider a pull request if your investigations pan out well.

**Comment by nospam2k** [comment]
I'm assuming that ui-card-panel-ctrl.js is min'd somewhere? Changes I'm making don't seem to reflect. I even renamed it and didn't get an error starting node-red.

**Comment by dceejay** [comment]
yes the gulp build step minifies it all. Also you need to flush your browser side cache - or open the browser dev tools and in the network section turn off cache.
![image](https://user-images.githubusercontent.com/5375409/56468253-ab2c0d00-6421-11e9-8dd3-cdb7cc2333e1.png)

**Comment by nospam2k** [comment]
After playing with this for a while, I decided to just use an http request/response and use the normal template node. It was getting too much like work ;)

It would be nice to have a ui_template node option that just displays raw html wysiwyg style. Maybe add this as a feature request?

**Comment by dceejay** [comment]
It already does.  What you see IS what you get. :-)
I guess you mean something else. ;-)

**Comment by nospam2k** [comment]
dceejay, with all do respect, all card sizes are pre-calculated so auto longer means auto. It means the size determined according to predicted layout. Although I agree with the premise that you don't want the cards bouncing around, but that, by definition is no longer wysiwyg. It's what you see is what we think looks good. I'm not disagreeing with this premise, but it renders designing a dynamic interface using ui-template unattainable. I think my simple example demonstrates this.

In order to work around this, I had to write code to iterate through all ui-cards below the ui-template card and modify the top attribute to increase or decrease the space accordingly and fix the height attribute on the ui-template. It's works but it's definitely ugly code.

My specific "wish list" would be for dashboard to have an option to not use calculated height or top attributes. (Personally, The web based ui's I have designed have never used top and have rarely used height.)

**Comment by dceejay** [comment]
OK - auto means the size is pre-calculated at load time based on information it has available at that time. (and not based on data that arrives later), and what you see (at load time) is what you are getting. 

If you do get time to work it out I'd be happy to consider a PR as long as it was optional and didn't break existing users.

There is also the ui-builder project that is more bare bones but lets you bring any framework you like to  help build the UI and is thus a lot more flexible and supports more endpoints and other goodness, but you have to managed the widgets yourself.

**Comment by nospam2k** [comment]
I'm interested in more info on the ui-builder. I've not heard of it.

As I said, the Dashboard code itself is hard for me to follow not being (back end code level) familiar with node-red or Dashboard. My ugly hack seems to be working to modify the data after it arrives and it's only for my Smart Home console.

**Comment by dceejay** [comment]
The ui-builder project can be found here - https://www.npmjs.com/package/node-red-contrib-uibuilder
Lots of good info and examples using different frameworks on the wiki here - https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki

**Comment by nospam2k** [comment]
Wow. I didn't know about this. I'll look into this. Thx!
