### ISSUE TITLE
Odd versioning issue

### ISSUE THREAD

**Issue by hammoaj** [node-red/node-red-dashboard#49]
I'm using Node-RED and dashboard on Bluemix. I'm trying to use the text-input node, with the delay set to 0 in order to wait for return, however it doesn't seem to exist in what I've pulled.

The package.json for my app has: `"node-red-dashboard":"2.x",` and when I examine the modules it pulls on deployment, it certainly looks like it has 2.0.1, however when I examine the html and js files for the text-input node, it doesn't appear to have the code to interpret the `time delay<=0` case which I can clearly see in the repository. Is it me? Or am I somehow pulling an earlier version of the code?

**Comment by knolleary** [comment]
The master version of code is newer than the current stable 2.0.1 release. We'll do a 2.0.2 in the near future to roll up the various fixes that have gone in since 2.0.1
