### ISSUE TITLE
Slider not following Output setting

### ISSUE THREAD

**Issue by SleepyPrince** [node-red/node-red-dashboard#490]
### What are the steps to reproduce?
1. Create a slider with 'Output' set to 'only on release' and connect to debug
2. Deploy flow
3. Drag slider (from a position other than original) to new position then release

### What happens?
2 outputs were triggered, one on first click and one on release.

### What do you expect to happen?
Only the output when released should be sent.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.14.0
- [x] Node-RED version: 0.20.5
- [x] node.js version: 10.15.3
- [x] npm version: 6.9
- [x] Platform/OS: raspbian-stretch
- [x] Browser: firefox 67.0b15, Chrome 73.0.3683.103

**Comment by dceejay** [comment]
Hi, I'm not able to reproduce this. Can you share your exact flow... maybe there is some other setting I am missing.

**Comment by SleepyPrince** [comment]
[{"id":"bc02d91c.33e1d","type":"debug","z":"833327bf.de3128","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":60,"wires":[]},{"id":"58b0eeff.7a2f1","type":"ui_slider","z":"833327bf.de3128","name":"","label":"slider","tooltip":"","group":"5ab67d72.4be854","order":0,"width":0,"height":0,"passthru":true,"outs":"end","topic":"","min":0,"max":"100","step":1,"x":110,"y":60,"wires":[["bc02d91c.33e1d"]]},{"id":"5ab67d72.4be854","type":"ui_group","z":"","name":"Default","tab":"fd2750fc.fe536","disp":true,"width":"6","collapse":false},{"id":"fd2750fc.fe536","type":"ui_tab","z":"","name":"Test","icon":"dashboard","disabled":false,"hidden":false}]

Just a simple slider will do, probably a slider with a larger value will cause it easier to trigger since your first click will probably miss the original value.

**Comment by SleepyPrince** [comment]
I have uploaded a short video
https://www.dropbox.com/s/oj8zg2e34u51zhk/2019-05-02 22-12-35.mkv?dl=0

initial value should be around 50, I click and hold at 39 then drag to 13. Expected output should only show 13, but 39 is triggered as well.
2nd click and drag was right on 13 then released on 44, 13 did not trigger. (correct behavior)
3rd click and drag was on the dot but slightly offset, causing it to trigger at 42 (incorrect). Release on 15 is triggered as it should be.
The rest is similar.
