### ISSUE TITLE
How to fix, chart refresh

### ISSUE THREAD

**Issue by avato92** [node-red/node-red-dashboard#491]
### What happens?

Hello, my mistake is that when I use the dashboard chart, the reading and drawing of the data do it correctly, but if I refresh the page, the line of the chart remains vertical.

![image](https://user-images.githubusercontent.com/44777468/57070441-b875b100-6cd7-11e9-9dc0-36b3909328ef.png)

The previous image is when everything happens correctly, and the next is when I refresh the page.

![image](https://user-images.githubusercontent.com/44777468/57070491-e6f38c00-6cd7-11e9-9089-7ed6097d1feb.png)

- [2.14.0 ] Node-RED-Dashboard version:
- [ v.0.20.5] Node-RED version:
- [ v10.15.3] node.js version:
- [ 6.9.0] npm version:
- [Ubuntu 19.04 ] Platform/OS:
- [ Google Chrome] Browser:

Code:

![image](https://user-images.githubusercontent.com/44777468/57070583-3afe7080-6cd8-11e9-9788-c70f7e262163.png)

the inject is to be able to reset the HTML view and the graph to appear correctly again.

**Comment by avato92** [comment]
I have been debugging and I have seen that during the data collection, all the necessary information comes out, the thing is that when I refresh the page there is a small second that the value is undefined and I think that is what causes the error, it is not how to solve this small fault, I have tried to save the last value collected in a global variable and inject it again but the error continues

![image](https://user-images.githubusercontent.com/44777468/57083124-55484680-6cf8-11e9-8b53-7807bc5a1e0b.png)


moment when you stay undefined

![image](https://user-images.githubusercontent.com/44777468/57083178-6d1fca80-6cf8-11e9-811a-828b8e855eea.png)


during the execution process

**Comment by dceejay** [comment]
Hi, when does the data arrive ? Is this at the same time that the chart is being created ?
What is your debug showing ? where is that data from at those points in time - what does it equate to in terms of the flow you have shown above ?

**Comment by avato92** [comment]
Hi @dceejay, thanks for answering, I'm going step by step:

when does the data arrive?
- when the application starts, it starts reading data from a file

Is this at the same time that the chart is being created?

- Yes, the graph is generated as you read the data in the file.

What is your debug showing?

- I have debugged the scope that the chart receives, position 2 equals the Y axis, position 3, equals the X axis, position 4 is the topic

where is that data from at those points in time - what does it equate to in terms of the flow you have shown above?

- Equivalent to a saved file which stores information collected with an opc-ua function

I do not know if this is enough or you need the flow, anyway the "only" viable solution that I have found so far, is to put a button to show the graph and when you press the graph restarts and with a delay I sent the information with 1 second delay

**Comment by dceejay** [comment]
If it is possible to share the flow and an example data file that would be very helpful. Thanks

**Comment by avato92** [comment]
This is the new code that I have put as a momentary solution, anyway if you refresh the page once you are reading data, the same thing happens again.


`[{"id":"d6dfe512.b42968","type":"tab","label":"Dashboard","disabled":false,"info":""},{"id":"a5ab784c.45ab38","type":"file in","z":"d6dfe512.b42968","name":"","filename":"/home/tacome/.node-red/projects/Node-red_IoT/data/data.json","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":636.01171875,"y":237.6328239440918,"wires":[["d3336b05.1bbac8"]]},{"id":"d3336b05.1bbac8","type":"function","z":"d6dfe512.b42968","name":"","func":"let arrData = msg.payload.split('\\n');\n\narrData.map( data => {\n    try{\n        let dataParse = JSON.parse(data);\n            if(dataParse.variable == \"ns=3;s=\\\"Pantalla\\\".\\\"Totalizador metros\\\"\"){\n                let object = {};\n                object.payload = dataParse.value;\n                object.timestamp = new Date(dataParse.sourceTimestamp).getTime();\n                object.topic = dataParse.variable;\n                node.send(object)\n            }\n    }catch(e){\n        //node.warn(e);\n    }\n});","outputs":1,"noerr":0,"x":948.0117301940918,"y":239.03908157348633,"wires":[["f8472177.f5a18"]]},{"id":"8fea88e5.5ecfe8","type":"inject","z":"d6dfe512.b42968","name":"","topic":"","payload":"[]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1216.0098037719727,"y":1080.982459783554,"wires":[["b838a9b2.27fe78","549c1af9.3e07a4","c4fc54f6.4f2498"]]},{"id":"cb9cdad5.917418","type":"link in","z":"d6dfe512.b42968","name":"","links":["9431afff.954b7"],"x":112.00780868530273,"y":796.9493103027344,"wires":[["71ca2bd0.20f044"]]},{"id":"71ca2bd0.20f044","type":"function","z":"d6dfe512.b42968","name":"","func":"let backup = {};\nbackup.payload = parseFloat(msg.payload.value).toFixed(2);\nbackup.topic = msg.payload.variable;\nbackup.timestamp = msg.payload.sourceTimestamp;\nreturn backup;","outputs":1,"noerr":0,"x":300.0058841705322,"y":798.5371556282043,"wires":[["c360dd79.13169"]]},{"id":"f8472177.f5a18","type":"ui_chart","z":"d6dfe512.b42968","name":"","group":"59196dff.3bdc74","order":2,"width":"12","height":"12","label":"Total metros","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"1","removeOlderPoints":"1000","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":1181.00980758667,"y":340.0371389389038,"wires":[[]]},{"id":"c360dd79.13169","type":"switch","z":"d6dfe512.b42968","name":"","property":"topic","propertyType":"msg","rules":[{"t":"eq","v":"ns=3;s=\"Pantalla\".\"Totalizador metros\"","vt":"str"},{"t":"eq","v":"ns=3;s=\"Pantalla\".\"Concentracion de ozono\"","vt":"str"},{"t":"eq","v":"ns=3;s=\"Pantalla\".\"SetPoint concentracion ozono\"","vt":"str"},{"t":"eq","v":"ns=3;s=\"Pantalla\".\"Sel velocidad maquina\"","vt":"str"}],"checkall":"false","repair":false,"outputs":4,"x":529.0136756896973,"y":798.5938415527344,"wires":[["4a236159.4f48e"],["d5fe1a75.81b3f8"],["fa647c43.f73e2"],["6cb68b6a.00acb4"]]},{"id":"b838a9b2.27fe78","type":"ui_chart","z":"d6dfe512.b42968","name":"","group":"f3bf8cba.e32da","order":2,"width":"8","height":"8","label":"Concentración Ozono","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"10","removeOlderPoints":"","removeOlderUnit":"1","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":1645.0097465515137,"y":937.0039508342743,"wires":[[]]},{"id":"549c1af9.3e07a4","type":"ui_chart","z":"d6dfe512.b42968","name":"","group":"f3bf8cba.e32da","order":2,"width":"8","height":"8","label":"Velocidad máquina","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"10","removeOlderPoints":"","removeOlderUnit":"1","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":1671.0097770690918,"y":1002.0039441585541,"wires":[[]]},{"id":"c4fc54f6.4f2498","type":"ui_gauge","z":"d6dfe512.b42968","name":"","group":"f3bf8cba.e32da","order":3,"width":0,"height":0,"gtype":"gage","title":"Velocidad máquina","label":"units","format":"{{value}}","min":0,"max":"25000","colors":["#00b500","#e6e600","#ca3838"],"seg1":"10000","seg2":"17500","x":1679.0078239440918,"y":1066.279334783554,"wires":[]},{"id":"54a26870.47aeb8","type":"ui_template","z":"d6dfe512.b42968","group":"f3bf8cba.e32da","name":"Debugger","order":4,"width":"6","height":"6","format":"<h3>Testing dynamic scripts with Dashboard 2.0</h3>\n{{msg.payload}}\n<script>\n    (function(scope) {\n        console.log('Position 1');\n        console.dir(scope);\n        scope.$watch('msg.payload', function(data) {\n            console.log('Position 2');\n            console.dir(data);\n        });\n        scope.$watch('msg.timestamp', function(data) {\n            console.log('Position 3');\n            console.dir(data);\n        })\n        scope.$watch('msg.topic', function(data) {\n            console.log('Position 4');\n            console.dir(data);\n        })\n    })(scope);\n</script>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":217.00786972045898,"y":139.2265338897705,"wires":[[]]},{"id":"6dce36da.8a20b8","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"f3bf8cba.e32da","order":5,"width":"2","height":"2","passthru":false,"label":"Ver datos metros","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":610.0078430175781,"y":1115.369158744812,"wires":[[]]},{"id":"a5a4875.ee39a78","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"455b5bf3.4acba4","order":0,"width":0,"height":0,"passthru":false,"label":"Ver gráfico metros","tooltip":"","color":"","bgcolor":"","icon":"","payload":"{\"group\":{\"show\":[\"Grafico_1_Prueba\"]}}","payloadType":"json","topic":"","x":611.0119323730469,"y":1047.1152801513672,"wires":[[]]},{"id":"4b595c02.23e174","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"455b5bf3.4acba4","order":1,"width":0,"height":0,"passthru":false,"label":"Ver grafico concentracion ozono","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":168.0078125,"y":471.1191701889038,"wires":[["46f1cb50.3ce4e4"]]},{"id":"46f1cb50.3ce4e4","type":"ui_ui_control","z":"d6dfe512.b42968","name":"","x":748.0097312927246,"y":530.2246236801147,"wires":[[]]},{"id":"133a5.1e727c5be","type":"inject","z":"d6dfe512.b42968","name":"","topic":"","payload":"{\"group\":{\"hide\":[\"Dashboard_Read_Data\", \"Dashboard_Graphs\"],\"show\":[\"Dashboard_Menu\"]}}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":104.01368522644043,"y":572.9785070419312,"wires":[["46f1cb50.3ce4e4"]]},{"id":"4a236159.4f48e","type":"ui_template","z":"d6dfe512.b42968","group":"eff10fcd.dcd32","name":"","order":1,"width":"6","height":"3","format":"<div>\n    <h3>Total metros:</h3><br />\n    <p class=\"caja\"><strong>{{msg.payload}}</strong> m</p>\n</div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":763.0098495483398,"y":712.2208127975464,"wires":[[]]},{"id":"d5fe1a75.81b3f8","type":"ui_template","z":"d6dfe512.b42968","group":"eff10fcd.dcd32","name":"","order":1,"width":"6","height":"3","format":"<div>\n    <h3>Conc. ozono:</h3><br />\n    <p class=\"caja\"><strong>{{msg.payload}}</strong> gr/Nm&sup3;</p>\n</div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":764.009838104248,"y":771.0039825439453,"wires":[[]]},{"id":"fa647c43.f73e2","type":"ui_template","z":"d6dfe512.b42968","group":"eff10fcd.dcd32","name":"","order":1,"width":"6","height":"3","format":"<div>\n    <h3>Setpoint ozono:</h3><br />\n    <p class=\"caja\"><strong>{{msg.payload}}</strong> gr/Nm&sup3;</p>\n</div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":766.0099258422852,"y":830.0039978027344,"wires":[[]]},{"id":"f5385b81.07bd58","type":"ui_template","z":"d6dfe512.b42968","group":"eff10fcd.dcd32","name":"CSS","order":4,"width":0,"height":0,"format":"<style>\n    .caja { \nfont-family: Century Gothic,CenturyGothic,AppleGothic,sans-serif; \ncolor: #ffffff; \nfont-size: 18px; \nfont-weight: 400; \ntext-align: center; \nbackground: #889ccf; \nmargin: 0 0 25px; \noverflow: hidden; \npadding: 20px; \nborder-radius: 35px 0px 35px 0px; \n-moz-border-radius: 35px 0px 35px 0px; \n-webkit-border-radius: 35px 0px 35px 0px; \nborder: 2px solid #5878ca;}\n</style>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":383.00782585144043,"y":135.21679496765137,"wires":[[]]},{"id":"6cb68b6a.00acb4","type":"ui_template","z":"d6dfe512.b42968","group":"eff10fcd.dcd32","name":"","order":1,"width":"6","height":"3","format":"<div>\n    <h3>Velocidad máquina:</h3><br />\n    <p class=\"caja\"><strong>{{msg.payload}}</strong> m/h</p>\n</div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":769.0098361968994,"y":883.0040740966797,"wires":[[]]},{"id":"80b794f6.633f78","type":"delay","z":"d6dfe512.b42968","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":308.01170349121094,"y":236.76953506469727,"wires":[["a5ab784c.45ab38"]]},{"id":"32b582a6.062b1e","type":"function","z":"d6dfe512.b42968","name":"","func":"msg.payload = [];\nreturn msg;","outputs":1,"noerr":0,"x":391.0097846984863,"y":334.78906059265137,"wires":[["f8472177.f5a18"]]},{"id":"205a6020.00c2a","type":"ui_template","z":"d6dfe512.b42968","group":"f3bf8cba.e32da","name":"","order":5,"width":0,"height":0,"format":"<div ng-bind-html=\"msg.payload\"></div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":797.0097694396973,"y":1091.2227630615234,"wires":[[]]},{"id":"19db975f.c7a589","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"6acb1e4b.1cec4","order":0,"width":0,"height":0,"passthru":false,"label":"Read Data","tooltip":"","color":"","bgcolor":"","icon":"","payload":"{\"group\":{\"hide\":[\"Dashboard_Menu\", \"Dashboard_Graphs\"],\"show\":[\"Dashboard_Read_Data\"]}}","payloadType":"json","topic":"","x":107.00600814819336,"y":679.3810272216797,"wires":[["46f1cb50.3ce4e4"]]},{"id":"6dc94f40.2a38","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"6acb1e4b.1cec4","order":0,"width":0,"height":0,"passthru":false,"label":"View graphs","tooltip":"","color":"","bgcolor":"","icon":"","payload":"{\"group\":{\"hide\":[\"Dashboard_Menu\", \"Dashboard_Read_Data\"],\"show\":[\"Dashboard_Graphs\"]}}","payloadType":"json","topic":"","x":119.00982666015625,"y":335.00398349761963,"wires":[["46f1cb50.3ce4e4","32b582a6.062b1e","80b794f6.633f78"]]},{"id":"2af8d67e.aa1a2a","type":"ui_button","z":"d6dfe512.b42968","name":"","group":"6acb1e4b.1cec4","order":0,"width":0,"height":0,"passthru":false,"label":"Subs/Unsubs","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":979.0099334716797,"y":1078.0039978027344,"wires":[[]]},{"id":"59196dff.3bdc74","type":"ui_group","z":"","name":"Graphs","tab":"a6a31337.5f3a7","disp":true,"width":"18","collapse":false},{"id":"f3bf8cba.e32da","type":"ui_group","z":"","name":"Data","tab":"5a500584.91ce8c","disp":true,"width":"25","collapse":true},{"id":"455b5bf3.4acba4","type":"ui_group","z":"","name":"Menu","tab":"895bfc86.927c9","disp":true,"width":"14","collapse":false},{"id":"eff10fcd.dcd32","type":"ui_group","z":"","name":"Read Data","tab":"a6a31337.5f3a7","disp":true,"width":"12","collapse":false},{"id":"6acb1e4b.1cec4","type":"ui_group","z":"","name":"Menu","tab":"a6a31337.5f3a7","disp":true,"width":"6","collapse":false},{"id":"a6a31337.5f3a7","type":"ui_tab","z":"","name":"Dashboard","icon":"dashboard","disabled":false,"hidden":false},{"id":"5a500584.91ce8c","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false},{"id":"895bfc86.927c9","type":"ui_tab","z":"","name":"Grafico 1","icon":"dashboard","disabled":false,"hidden":false}]`

[data.txt](https://github.com/node-red/node-red-dashboard/files/3152422/data.txt)

you should rename the file to .json, if I did not put it as .txt it would not let me upload the file

**Comment by dceejay** [comment]
ah right, yes...  you are resending all the individual points. This makes the graph think it is running in real time and so keep the right hand edge to the current time and inserts all the "old" points before now...  which given that your data is from 2013 results in a near vertical line.. 

To display just old data then you need to send the whole graph in one chunk  using and array as described in the docs - here is a simple version adapted from your code... (It could be cleaner but hopefully you can work out what I have done in the function instead...)

```
[{"id":"7fe8e210.0b960c","type":"inject","z":"64492048.abbe4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":true,"onceDelay":"1","x":150,"y":240,"wires":[["9de58fe9.0d083"]]},{"id":"9de58fe9.0d083","type":"file in","z":"64492048.abbe4","name":"","filename":"/tmp/data.json","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":380,"y":240,"wires":[["11fc7354.e5f33d"]]},{"id":"11fc7354.e5f33d","type":"function","z":"64492048.abbe4","name":"","func":"let arrData = msg.payload.split('\\n');\nvar graph = [];\nvar ser = \"\"\narrData.map( data => {\n try{\n     let dataParse = JSON.parse(data);\n     if(dataParse.variable == \"ns=3;s=\\\"Pantalla\\\".\\\"Totalizador metros\\\"\"){\n         let object = {};\n         object.y = dataParse.value;\n         object.x = new Date(dataParse.sourceTimestamp).getTime();\n         ser = dataParse.variable;\n         graph.push(object);\n     }\n }\n catch(e){\n //node.warn(e);\n }\n});\n\nmsg.payload = [{\n\"series\": [ ser ],\n\"data\": [ graph ],\n\"labels\": [\"\"]\n}];\nreturn msg;","outputs":1,"noerr":0,"x":550,"y":240,"wires":[["69422965.b06728"]]},{"id":"69422965.b06728","type":"ui_chart","z":"64492048.abbe4","name":"","group":"4924a383.1b58fc","order":1,"width":"12","height":"12","label":"Total metros","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"1","removeOlderPoints":"1000","removeOlderUnit":"86400","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":730,"y":240,"wires":[[]]},{"id":"4924a383.1b58fc","type":"ui_group","z":"","name":"Graphs","tab":"ca1cdcfa.7ed5d","disp":true,"width":"18","collapse":false},{"id":"ca1cdcfa.7ed5d","type":"ui_tab","z":"","name":"Dashboard","icon":"dashboard","disabled":false,"hidden":false}]
```
