### ISSUE TITLE
Cannot "hide" tab across all browsers (clients)

### ISSUE THREAD

**Issue by daveHounds** [node-red/node-red-dashboard#493]
Problem:  Control of tab visibility, cannot get hide/show 'tabs' to work across SOME browser (client) types.  Specifically there is no change to the tab pulldown select list when "hide" is sent to ui_control node per https://github.com/node-red/node-red-dashboard  .  

This issue also applies equally to 'tabs' enable/disable.

Works correctly with: Firefox (win10 and ubuntu), Chrome (macOS Mojave)  and iPhone 6S;
Cannot get to work correctly with: MS Edge (win10), Safari (macOS Mojave) or iPad.

Note: iPhone and iPad and Safari are all at latest (same) revision level, yet it only works with the iPhone.

Note: Worked with @shrickus on this issue in Slack.  He recommended to open repo issue.

Background:  I do have all other aspects of dynamic control of my Dashboard successfully working across all my open browser (client) windows (up to 7 tested).  1) sync'd changes between tabs; 2) hide/show of groups; 3) changes to UI widget settings.  I can restrict changes to local browser only, or reflected across all open browsers (using msg.socketid).

### Please tell us about your environment:
Server - Lenovo with win10;  browser - Firefox Version 66.0.4 (64-bit), up to date.

C:\Users\dave>node-red
6 May 09:12:50 - [info]

Welcome to Node-RED
===================

6 May 09:12:50 - [info] Node-RED version: v0.19.5
6 May 09:12:50 - [info] Node.js  version: v10.15.1
6 May 09:12:50 - [info] Windows_NT 10.0.17763 x64 LE
6 May 09:12:51 - [info] Loading palette nodes
6 May 09:12:53 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
6 May 09:12:54 - [info] Dashboard version 2.14.0 started at /red/ui
6 May 09:12:54 - [warn] ------------------------------------------------------
6 May 09:12:54 - [warn] [node-red/tail] Not currently supported on Windows.
6 May 09:12:54 - [warn] ------------------------------------------------------
6 May 09:12:54 - [info] Settings file  : \Users\dave\.node-red\settings.js
6 May 09:12:54 - [info] HTTP Static    : C:\Users\dave\.node-red
6 May 09:12:54 - [info] Context store  : 'default' [module=memory]
6 May 09:12:54 - [info] User directory : \Users\dave\.node-red
6 May 09:12:54 - [info] Server now running at http://127.0.0.1:1880/red/
6 May 09:12:54 - [info] Active project : Group_Hide_Template
6 May 09:12:54 - [info] Flows file     : \Users\dave\.node-red\projects\Group_Hide_Template\flow.json
6 May 09:12:54 - [info] Starting flows
6 May 09:12:55 - [info] Started flows
6

**Comment by dceejay** [comment]
Hi, have just tried your simple example on Safari (Mojave) and Edge (windows 10) - a simple inject of the hide message does as it should. The Tab is hidden from the left menu.
If you have a more complex example that does fail please can you share it here ?

**Comment by daveHounds** [comment]
@dceejay thanks for the help.
Have you heard of the professor syndrome?  Its when your project will not work, you call over the professor and by magic it starts to work.  In this case you are the professor and you got it only partially working.
The MS Edge is now working.  I have changed nothing except switch between node red projects.  But Safari and iPad are still not working (but iPhone is).

Still learning node-red's environment.  How do I paste the code here?

**Comment by dceejay** [comment]
:-) select all the nodes you wan to export - Ctrl-E or Cmd-E (export) - copy to clipboard. then paste here between two sets of three backticks  \`\`\`        \`\`\`

**Comment by daveHounds** [comment]
```[{"id":"b6be9ead.91c218","type":"ui_dropdown","z":"2f899e1b.b32082","name":"","label":"Timeline Tabs 1","tooltip":"","place":"Select option","group":"87a70558.d7eb48","order":3,"width":"5","height":"1","passthru":true,"options":[{"label":"Enable Tab 2","value":"Enable","type":"str"},{"label":"Disable Tab 2","value":"Disable","type":"str"},{"label":"Show Tab 2","value":"Show","type":"str"},{"label":"Hide Tab 2","value":"Hide","type":"str"}],"payload":"","topic":"","x":504,"y":632,"wires":[["2901ee97.7b95c2","93d8c879.d0b6f"]]},{"id":"2901ee97.7b95c2","type":"function","z":"2f899e1b.b32082","name":"Define Tab visibility; Across all browsers","func":"/* See theory about local vs. global UI \nbrowser/client control. */\n\n\n// Set flow variable based on payload input received.\n\n// Analyze payload message.\nif (msg.payload == \"Enable\") {\n  msg = {payload: {\"tabs\":{\"enable\":[\"Tab 2\"]}}};\n}\nelse if (msg.payload == \"Disable\") {\n  msg = {payload: {\"tabs\":{\"disable\":[\"Tab 2\"]}}};\n}\nelse if (msg.payload == \"Show\") {\n  msg = {payload: {\"tabs\":{\"show\":[\"Tab 2\"]}}};\n}\nelse {\n  msg = {payload: {\"tabs\":{\"hide\":[\"Tab 2\"]}}};\n}\n\n// Send current debugAid result as new payload message.\nreturn msg;\n\n","outputs":1,"noerr":0,"x":790,"y":632,"wires":[["c7b56392.049698","e239f993.20169"]]},{"id":"c7b56392.049698","type":"debug","z":"2f899e1b.b32082","name":"Selector results","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":881,"y":752,"wires":[]},{"id":"e239f993.20169","type":"ui_ui_control","z":"2f899e1b.b32082","name":"Hide/Show Tabs / Groups","x":1173,"y":741,"wires":[["c9a2a332.1fa21"]]},{"id":"641d7f63.1e202","type":"inject","z":"2f899e1b.b32082","name":"Show tab at launch","topic":"","payload":"Show","payloadType":"str","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":265,"y":632,"wires":[["b6be9ead.91c218"]]},{"id":"c9a2a332.1fa21","type":"debug","z":"2f899e1b.b32082","name":"Tab / Group changes","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1420,"y":741,"wires":[]},{"id":"d46af9e5.4ae0e","type":"comment","z":"2f899e1b.b32082","name":"Includes Hide/Show AND Disble/Enable of tabs","info":"","x":548,"y":680,"wires":[]},{"id":"93d8c879.d0b6f","type":"function","z":"2f899e1b.b32082","name":"Define Tab visibility; Local browser cntl only","func":"/* See theory about local vs. global UI \nbrowser/client control. */\n\n\n// Set flow variable based on payload input received.\n\n// Analyze payload message.\nif (msg.payload == \"Enable\") {\n  msg.payload = {\"tabs\":{\"enable\":[\"Tab 2\"]}};\n}\nelse if (msg.payload == \"Disable\") {\n  msg.payload = {\"tabs\":{\"disable\":[\"Tab 2\"]}};\n}\nelse if (msg.payload == \"Show\") {\n  msg.payload = {\"tabs\":{\"show\":[\"Tab 2\"]}};\n}\nelse {\n  msg.payload = {\"tabs\":{\"hide\":[\"Tab 2\"]}};\n}\n\n// Send current debugAid result as new payload message.\nreturn msg;\n\n","outputs":1,"noerr":0,"x":801,"y":600,"wires":[[]]},{"id":"f63f807c.81f53","type":"inject","z":"2f899e1b.b32082","name":"{\"tabs\":{\"hide\":[\"Tab 2\"]}}","topic":"","payload":"{\"tabs\":{\"hide\":[\"Tab 2\"]}}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":878,"y":496,"wires":[["e239f993.20169"]]},{"id":"a1b65817.9e996","type":"comment","z":"2f899e1b.b32082","name":"Code Purpose: Hide/Show/Disable/Enable Tabs","info":"","x":276,"y":488,"wires":[]},{"id":"6de85009.183aa","type":"comment","z":"2f899e1b.b32082","name":"direct global test case","info":"","x":881,"y":464,"wires":[]},{"id":"ea319a04.f1ba","type":"comment","z":"2f899e1b.b32082","name":"Note: Local vs. global UI control","info":"We can either wire for local or global UI\nbrowser/client control. Difference is the msg\nstructure.  See theory (why) for details.\n\nFor local setup only the payload is\nredefined/re-equated.  Other msg-keys pass-thru.\nIncluding the socketid.\n\nFor ALL browers (global) the entire \"msg\" is\nredefined or re-equated.  Others msg-keys are stopped.\nIncluding the socketid.\n\nLocal = socketid passes thru.\nGlobal = no socketid.\n","x":1218,"y":584,"wires":[]},{"id":"76ff2c73.c17bec","type":"comment","z":"2f899e1b.b32082","name":"Alternate method below.","info":"","x":1188,"y":648,"wires":[]},{"id":"9050cade.f46898","type":"comment","z":"2f899e1b.b32082","name":"Use fct node to redefine/cntl 'msg.socketid'","info":"","x":1248,"y":616,"wires":[]},{"id":"52d59105.ca30b","type":"ui_dropdown","z":"2f899e1b.b32082","name":"","label":"Timeline Tabs 2","tooltip":"","place":"Select option","group":"89249ca6.709d7","order":3,"width":"5","height":"1","passthru":true,"options":[{"label":"Enable Tab","value":"Enable","type":"str"},{"label":"Disable Tab","value":"Disable","type":"str"},{"label":"Show Tab","value":"Show","type":"str"},{"label":"Hide Tab","value":"Hide","type":"str"}],"payload":"","topic":"","x":504,"y":880,"wires":[[]]},{"id":"1fcab0cd.958eaf","type":"ui_dropdown","z":"2f899e1b.b32082","name":"","label":"Timeline Tabs 3","tooltip":"","place":"Select option","group":"c49b59f7.c04e","order":3,"width":"5","height":"1","passthru":true,"options":[{"label":"Enable Tab","value":"Enable","type":"str"},{"label":"Disable Tab","value":"Disable","type":"str"},{"label":"Show Tab","value":"Show","type":"str"},{"label":"Hide Tab","value":"Hide","type":"str"}],"payload":"","topic":"","x":504,"y":960,"wires":[[]]},{"id":"4798547d.bbbf24","type":"comment","z":"2f899e1b.b32082","name":"For tab 2","info":"","x":492,"y":848,"wires":[]},{"id":"e286add6.32874","type":"comment","z":"2f899e1b.b32082","name":"For tab 3","info":"","x":500,"y":928,"wires":[]},{"id":"853561c2.e4f118","type":"comment","z":"2f899e1b.b32082","name":"Theory / Notes: Hiding Groups","info":"\"Visibility of individual groups of widgets can\ncontrolled by a payload like\n{\"group\":{\"hide\":[\"tab_name_group_name_with_underscores\"], \"show\":[\"reveal_another_group\"], \"focus\":true}}\nwhere focus is optional and will cause the screen\nto scroll to show that group if required. The\ngroup names are the IDs of the groups and are\ntypically formed from the tab name plus group name\njoined with underscores replacing all spaces.\"","x":264,"y":336,"wires":[]},{"id":"3b6e9ad2.e49286","type":"comment","z":"2f899e1b.b32082","name":"IMPORTANT THEORY 1: Global vs Local control of tab/group hide and show","info":"Assuming this issue (capability) applies to all\nui_widegets.  Proven against Pulldown and button\nui's only as of this writing.\n-------------------------\n\nWhen tab or group commands are sent to ui_control\nnode directly from ui_widgets, the command is\nexecuted against the \"local\" browser ONLY from\nwhich the action event was initiated.\n\nTo have the tab/group command executed against ALL\nopen browsers, command msg from ui_widgets must be\nstopped and the command defined within a new msg.\n\nSpecifically, the socketID.  All ui_widgets send\nthe socketip of the browser it is associated with.\nThis seems to tell the ui_control to execute the\ngiven command against the local browser only.\n\nCommands issued from other nodes directly (e.g.,\ninject nodes, function nodes, etc.) cause the\nui_control to execute the given command against\nALL open browsers, because we have not issued any\nsocketid info.; or we stop upstream UI socketid\nfrom passing through.\n\nI speculate that if we sent a list of socketids as\npart of the command it would execute the command\nagainst that list.\n\nConclusion:\nUsing the socketid we can control which browsers\ntag/group commands control.","x":414,"y":272,"wires":[]},{"id":"572bdab3.43d45c","type":"comment","z":"2f899e1b.b32082","name":"SocketIPs, socketIDs, tag/names/numbers, group names important in control across browsers","info":"","x":464,"y":304,"wires":[]},{"id":"34e3214f.21c34e","type":"comment","z":"2f899e1b.b32082","name":"IDs vs. IPs; ui_widgets give socketid, ui_control give socketip and the ID","info":"","x":642,"y":336,"wires":[]},{"id":"26a4ac4e.2af18c","type":"comment","z":"2f899e1b.b32082","name":"Theory2: Client browser UI control; local vs. global","info":"The `socketid` is used to route a UI msg from the\nserver to only one of the client dashboards.\n \nWithout the `socketid` property the msg will affect\nall connected clients.\n\nE.g., controls from the ui have a socketid\nproperty attached and if present, responses will\ngo back to that socket only. \n(If not present they go to all)\n \n`socketid` an internal property. The default\ndashboard behavior is that a ui msg initiated from\ndashboard 1 should not affect dashboards 2-n.\n\nExample:  it's pretty common for that event\n(e.g. a button press) to modify some backend flow\nsetting -- which in turn may update some ui\nwidget's value. in that case, only those\ndashboards showing the affected widget would\nupdate (as long as the socketid is removed\nsomewhere in the feedback loop.)\n\nFrom node-red-dashboard theory:\nMultiple Users\nThis Dashboard does NOT support multiple individual\nusers. It is a view of the status of the underlying\nNode-RED flow, which itself is single user. If the\nstate of the flow changes then all clients will get\nnotified of that change.\nMessages coming from the dashboard do have a\nmsg.socketid, and updates like change of tab,\nnotifications, and audio alerts will be directed\nonly to that session. Delete the msg.socketid to\nsend to all sessions.\n\n","x":878,"y":272,"wires":[]},{"id":"87a70558.d7eb48","type":"ui_group","name":"Group 1","tab":"71cd046f.dbebb4","order":1,"disp":true,"width":6},{"id":"89249ca6.709d7","type":"ui_group","name":"Group 1","tab":"63df2ccd.68724c","order":1,"disp":true,"width":6},{"id":"c49b59f7.c04e","type":"ui_group","name":"Group 1","tab":"17be50c6.0609af","order":1,"disp":true,"width":6},{"id":"71cd046f.dbebb4","type":"ui_tab","name":"Tab 1","icon":"dashboard","order":1},{"id":"63df2ccd.68724c","type":"ui_tab","name":"Tab 2","icon":"dashboard","order":2},{"id":"17be50c6.0609af","type":"ui_tab","name":"Tab 3","icon":"dashboard","order":3}]```

**Comment by dceejay** [comment]
Hmm - again that is all working good for me on Windows 10 Edge and Safari (and Firefox and Chrome.)
Have you refreshed the browse to empty any cacheing ?

**Comment by daveHounds** [comment]
@dceejay All fixed.  Thank you.  It was the cacheing.  Even got the iPad working after doing "advanced website management."   This is the second time in one year that clearing cache solved a node-red problem. Cannot even remember the specific problem, but it also had to do with browsers, that's why I am at the moment using Firefox.  Clearing cache fixed the problem with the previous browser, but I never switched back.  So is the answer when Dashboard does not work as advertised - clear cache before contacting you guys?  Ha ha!  :)  Thank you Dave.

**Comment by daveHounds** [comment]
Do I close the issue or do you do that?
