### ISSUE TITLE
Legend is shown even if Legend Option set to "None"

### ISSUE THREAD

**Issue by Harpau** [node-red/node-red-dashboard#494]
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
- [ ] Node-RED version:
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by Harpau** [comment]
In the new version 2.5.1 the Legend is shown even if the Legend Option is set to "None".
I am using Node Red 0.20.5 one a Homematic CCU3 (RedMatic).

**Comment by swilson86** [comment]
It happens also in 2.15.0-beta of Dashboard. The little colored rectangle above the chart always shows even though Legend option is set to None.

**Comment by Harpau** [comment]
This problem occurs only if the Dashboard is displayed on desktops. On mobile devices the behavior is correct.

**Comment by Harpau** [comment]
With version 2.15.2 I have the same problem as before.
