### ISSUE TITLE
ui_text_input with TimePicker initialised input payload output as a NaN

### ISSUE THREAD

**Issue by WombatHollow** [node-red/node-red-dashboard#495]
WHilst trying to workout hoe the TIme Picker works (found little documentation, I found that if you send a initiasation value to the node in msg.payload and passthrough is ticked, it reports a payload of NaN.  This occurs whether the input is a text string ("16:00") or a number representing a time (360000).   The ui does display a number, usually, OK but reports NaN.  If you then change the time using the Time Picker ui, the correct time is reported.

THere has also been instances where a number id passed out!, and also instances when the time reported out includes a date element.  I have not sused out why it sometimes does that, nor been able to build a flow that does this repeatedly.

here is my flow
`[{"id":"2d3b21bf.30ca0e","type":"tab","label":"Bug Report Example","disabled":false,"info":""},{"id":"6260b9b2.79bc18","type":"ui_button","z":"2d3b21bf.30ca0e","name":"","group":"e73eee5.474051","order":0,"width":0,"height":0,"passthru":false,"label":"Load Text","tooltip":"","color":"","bgcolor":"","icon":"","payload":"16:00","payloadType":"str","topic":"Text","x":558,"y":157,"wires":[["55402ab7.ef2884"]]},{"id":"e97e16d9.1c4788","type":"change","z":"2d3b21bf.30ca0e","name":"Temp Store","rules":[{"t":"set","p":"DailyStart","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":991,"y":139,"wires":[[]]},{"id":"55402ab7.ef2884","type":"ui_text_input","z":"2d3b21bf.30ca0e","name":"DailyStart","label":"{{topic}}","tooltip":"00:00 to 23:59","group":"e73eee5.474051","order":4,"width":0,"height":0,"passthru":true,"mode":"time","delay":300,"topic":"","x":772,"y":198,"wires":[["e97e16d9.1c4788","7e3c32c3.02b1ec","bb7e18ca.40f948"]]},{"id":"d3314ac4.52ef88","type":"ui_button","z":"2d3b21bf.30ca0e","name":"","group":"e73eee5.474051","order":0,"width":0,"height":0,"passthru":false,"label":"Load Date Number","tooltip":"","color":"","bgcolor":"","icon":"","payload":"3660000","payloadType":"num","topic":"Number","x":538,"y":230,"wires":[["55402ab7.ef2884"]]},{"id":"7e3c32c3.02b1ec","type":"ui_text","z":"2d3b21bf.30ca0e","group":"e73eee5.474051","order":3,"width":0,"height":0,"name":"","label":"Result","format":"{{msg.payload}}","layout":"row-spread","x":965,"y":231,"wires":[]},{"id":"bb7e18ca.40f948","type":"debug","z":"2d3b21bf.30ca0e","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":962,"y":186,"wires":[]},{"id":"e73eee5.474051","type":"ui_group","name":"Group 1","tab":"b61413e9.3c55b","order":1,"disp":true,"width":6},{"id":"b61413e9.3c55b","type":"ui_tab","z":"","name":"Bug","icon":"dashboard","order":5,"disabled":false,"hidden":false}]`

My desired behavior is that when a Time is sent to the ui in text or number form with pass through set, that the resultant displayed time in the ui is immediately sent out (in number format, aka the text is converted to a number without any date element) 

Ta

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.14.0
- [ ] Node-RED version: 0.20.3
- [ ] node.js version: 11.12.0
- [ ] npm version:
- [ ] Platform/OS: W10
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Yup, slight wrinkle there.... 
It does/will expect an input to be a number of milliseconds since midnight - but yes it should not return NaN, and should passthrough ok. Will fix

**Comment by dceejay** [comment]
close by release 2.15.2
