### ISSUE TITLE
Legend is shown even if Legend Option set to "None"

### ISSUE THREAD

**Issue by Harpau** [node-red/node-red-dashboard#496]
With version 2.15.2 I have the same problem as before.

_Originally posted by @Harpau in https://github.com/node-red/node-red-dashboard/issues/494#issuecomment-492748957_

**Comment by dceejay** [comment]
Hopefully you have flushed your browser cache after loading the latest version.
please provide an example flow that shows the problem.

**Comment by Harpau** [comment]
Thank you for your support

Node configuration:
`[{"id":"435748da.c9a998","type":"ui_chart","z":"5e9450f9.0b095","name":"","group":"8ddb0632.c2851","order":5,"width":0,"height":0,"label":"Energiebilanz - 1 Stunde","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"1","removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"colors":["#2ca02c","#d62728","#1f77b4","#ff7f0e","#98df8a","#aec7e8","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":590,"y":300,"wires":[[]]},{"id":"8ddb0632.c2851","type":"ui_group","z":"","name":"Solaranlage","tab":"b6fb2189.fb3b1","disp":false,"width":"6","collapse":false},{"id":"b6fb2189.fb3b1","type":"ui_tab","z":"","name":"Solaranlage","icon":"dashboard","order":2,"disabled":false,"hidden":false}]`

Result on MacBook Pro:
![Screenshot 2019-05-15 19 48 58](https://user-images.githubusercontent.com/47887931/57797357-8e49d780-774a-11e9-8121-223f57029050.png)

Result on iPhone:
![IMG_0662](https://user-images.githubusercontent.com/47887931/57797256-4d51c300-774a-11e9-9416-5ee60683b026.PNG)

**Comment by dceejay** [comment]
looks fine for me on Mac/Chrome... are you sure you reloaded the page / flushed the cache properly... ? ?
![image](https://user-images.githubusercontent.com/5375409/57797552-9bfb5f00-7742-11e9-81f3-9713b16d41b2.png)

**Comment by Harpau** [comment]
Thank you again for your support. After having deleted all website data it works correctly now.
