### ISSUE TITLE
Tab "text" in sidebar is hidden when it is selected

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#500]
### What are the steps to reproduce?
- use Dashboard style is Light(default)
- Select the tab in sidebar
- Tab text in sidebar is hidden when the mouse is pointed to.

update: this issue has just happen after i upgraded dashboard from version 2.14.0 to 2.15.2.

### What do you expect to happen?
It should display even the tab is pointed by mouse.

### Please tell us about your environment:
- [x] Node-RED-Dashboard version: 2.15.2
- [x] Node-RED version: 0.19.5
- [x] node.js version: v8.12.0
- [x] npm version: 6.9.0
- [x] Platform/OS: Raspberry Pi 3B+ / Raspbian Stretch
- [x] Browser: MS Edge, Google Chrome

### Screen shot:
![image](https://user-images.githubusercontent.com/36041520/58066763-f10cfa00-7bb4-11e9-8b84-9a17d1150c3c.png)

**Comment by dceejay** [comment]
closed by 4480afde2bb9d3f885e08668738ffbc3a1280705

**Comment by wongnam** [comment]
Thanks.
It is required to clear the browser cache to work as expected.
