### ISSUE TITLE
Color picker cursor does not display in the correct position

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#502]
### What are the steps to reproduce?
Sorry, I update again. Color picker cursor does not display in the correct position where i pointed to.

ignore this -> Color picker cannot chose the color in inner of color circle.

### What do you expect to happen?
It display in the correct position where i pointed to.

### Please tell us about your environment:
 - [x] Node-RED-Dashboard version: 2.15.2
 - [x] Node-RED version: 0.20.4
 - [x] node.js version: v8.12.0
 - [x] npm version: 6.9.0
 - [x] Platform/OS: Raspberry Pi 3B+ / Raspbian Stretch
 - [x] Browser: MS Edge, Google Chrome

### Screen shot:
![image](https://user-images.githubusercontent.com/36041520/58143886-858b6100-7c76-11e9-98e4-04751b094f17.png)

**Comment by dceejay** [comment]
the value you get is where you clicked - it's just the cursor shown position that is wrong. We did patch the picker for some reason I can no longer recall... 
I will revert it for now... pending memory recall why it was changed.... (Indeed was something to do with LED lights but....
In meantime I have also added the square version of the widget which makes things like greyscale easier to create.

**Comment by dceejay** [comment]
My current thinking is to try to replace the rgb wheel with a version that is white in centre and dark at the edges - so full colour would be 50% in from edge - that way we can get from white to black and full colours...

**Comment by wongnam** [comment]
Yes, when it is selected, it will still be valid. It's just a pointer that isn't in the right place.
The way the current color picker works is fine, but it is nice to have a square picker. The best is to have 2 types of pickers, to have an option for the user.

**Comment by wongnam** [comment]
when moved the lightness slider to different level that the cursor does not move to the corresponding position on the color wheel.
