### ISSUE TITLE
Slider has UI issue when in "on release only" mode

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#503]
### Symptom:
 There are 3 issues.
1. The dot disappear. Please refer to pic#1
2. Slider horizontal line is broken. refer to pic#2 (I do not know what the horizontal line is called)
3. the number that it does not hide itself for a while and It is overridden on other widgets. refer to pic#3 

### What are the steps to reproduce?
 Select slider in "on release only" mode
 1. For the 1st issue,  the dot is disappear.
    - In dashboard, tap on the slider, and don't touch another place anymore
    - click another website tab in browser and go back to dashboard tab. -> You will notice the dot disappear.
 2. for the 2nd issue, horizontal line is broken
    - You just need to click on the slider to see the horizontal line is broken.
 3. for the 3rd issue
    - You just need to click on the slider to see the number is display very big that it will overlaps anther widget. -> it should auto hide for awhile.
    
### Please tell us about your environment:
  - [x] Node-RED-Dashboard version: 2.15.2
  - [x] Node-RED version: 0.20.4
  - [x] node.js version: v8.12.0
  - [x] npm version: 6.9.0
  - [x] Platform/OS: Raspberry Pi 3B+ / Raspbian Stretch
  - [x] Browser: MS Edge, Google Chrome

### Screen shot:
 - Pic#1: the dot is disappear.
![missing](https://user-images.githubusercontent.com/36041520/58168327-3403c600-7cb8-11e9-9af0-716432565dbe.png)

 - Pic#2:  Dash lines.
![dash](https://user-images.githubusercontent.com/36041520/58168377-51d12b00-7cb8-11e9-917c-fa518788ac9f.png)

 - Pic#3: 
![Normal](https://user-images.githubusercontent.com/36041520/58168429-6f05f980-7cb8-11e9-97b9-8823084c191c.png)

**Comment by dceejay** [comment]
1) Are you using latest version from master ? For me it doesn't disappear when using Chrome.
2) That is the md-discrete style - will make sure they match theme colour.
3) shifted down when in on release mode.

**Comment by wongnam** [comment]
I am using the latest Github version 2.15.2.

**Comment by dceejay** [comment]
Ah when you said tab I thought you meant dashboard tab.. got it

**Comment by wongnam** [comment]
The slider md-discrete style is still appear many dash-bar with widget color(annoying) when i pointed to it. It should have a grey scale color(more nature)

![image](https://user-images.githubusercontent.com/36041520/58270123-457dc880-7db3-11e9-9d41-ea44245173cf.png)

**Comment by dceejay** [comment]
for me it is OK
![image](https://user-images.githubusercontent.com/5375409/58270481-ddfb5500-7d81-11e9-9758-24972bc4b68a.png)

**Comment by wongnam** [comment]
the "continuously while sliding" mode does not have this issue.

**Comment by dceejay** [comment]
I am happy with it as it is. It is not an issue.

**Comment by wongnam** [comment]
for me it's not a issue too, but it's not consistent with the "continuously while sliding" mode.

**Comment by dceejay** [comment]
Ok - it's closed then.

**Comment by wongnam** [comment]
Thank you so far.

**Comment by dceejay** [comment]
If anyone is really concerned then can either override the css locally or raise a PR.

**Comment by wongnam** [comment]
@dceejay after update 2.15.3beta that It seems to have broken the fa icon everywhere in the dashboard.

**Comment by dceejay** [comment]
have made tick transparent so now consistent. - icons work fine here
![image](https://user-images.githubusercontent.com/5375409/58311588-3a518980-7e01-11e9-8db8-deb42cf15149.png)

**Comment by wongnam** [comment]
- Yes, it's more consistently and very nice now, the line is still a little bit thicker than the "continuously while sliding" mode if zoomed in to see it, but it wasn't a big deal. Thanks.
![image](https://user-images.githubusercontent.com/36041520/58314498-d13a3800-7e39-11e9-8ac0-5859f9b288cf.png)
- FA icon is still disappear even after i flushed cache fully. It only works normally when I return it to 2.14.0. Maybe I'll wait for the final release version to try again.

**Comment by wongnam** [comment]
@dceejay I correct the comment below because it is not a thicker issue with this line. Sorry about that. Thank you. 

> the line is still a little bit thicker than the "continuously while sliding" mode if zoomed in to see it, but it wasn't a big deal. Thanks.

**Comment by wongnam** [comment]
update. the FA Icon display already after reset my internet connection(i don't know it related or not). 

Thank you very much.
