### ISSUE TITLE
The color of the button is temporarily changed abnormally.

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#504]
### The Issue:
 The color of the button is temporarily changed/fade-out abnormally.

### What are the steps to reproduce?
 - In dashboard, click on the button and don't touch any where.
 - click another website tab in browser and go back to dashboard tab. -> You will notice the button color is temporarily changed.

### What do you expect to happen?
It display in the correct color as design.

### Please tell us about your environment:
 - [x] Node-RED-Dashboard version: 2.15.2
 - [x] Node-RED version: 0.20.4
 - [x] node.js version: v8.12.0
 - [x] npm version: 6.9.0
 - [x] Platform/OS: Raspberry Pi 3B+ / Raspbian Stretch
 - [x] Browser: MS Edge, Google Chrome\

### Screen shot:
![image](https://user-images.githubusercontent.com/36041520/58180930-142ecb00-7cd5-11e9-8097-9d07ddc867b9.png)

**Comment by wongnam** [comment]
Thanks.
when i can try this latest version from github.?
As i try to install by npm i node-red/node-red-dashboard that It is not effective yet.

**Comment by dceejay** [comment]
when I fix the colour wheel

**Comment by wongnam** [comment]
the return color is a slightly different to the widget original color.

![image](https://user-images.githubusercontent.com/36041520/58270781-c9848000-7db4-11e9-9f5e-604396120f4a.png)

**Comment by wongnam** [comment]
The experience on pc is very good, but on the phone its color does not return to the original color.

**Comment by dceejay** [comment]
If you can tell me the css required I will fix. otherwise will have to wait.

**Comment by wongnam** [comment]
It is simple to reproduce it.

![image](https://user-images.githubusercontent.com/36041520/58311194-98e32b80-7e32-11e9-8203-e838983318b3.png)

**Comment by dceejay** [comment]
All good here - have you flushed cache fully ?
![image](https://user-images.githubusercontent.com/5375409/58311466-f65e8480-7e00-11e9-9893-13f98bfc0579.png)

**Comment by wongnam** [comment]
> All good here - have you flushed cache fully ?
> ![image](https://user-images.githubusercontent.com/5375409/58311466-f65e8480-7e00-11e9-9893-13f98bfc0579.png)
> Though this is not a button issue - and you mentioned it on #503 - which is slider.

Sorry, i comment it on wrong topic.
Ok let me flushed the cache again.
