### ISSUE TITLE
Chart "Legend" capability to disable channels resets itself back to enable after a short period of time. 

### ISSUE THREAD

**Issue by ExperimentalZeros** [node-red/node-red-dashboard#507]
### What are the steps to reproduce?
- Create a chart with "Legend" selected, and trace length of 30 seconds.
1.- Add more than one channel to it dumping samples at a rate of 1 second each...(I currently use 18 channels under those conditions)
2.- Once the dashboard is displayed on the browser, click on one of the squares within the chart's "Legend" to disable a channel.
3.-  wait.

### What happens?
1.- Channel that was disabled is re-enabled automatically (meaning, without users input)

### What do you expect to happen?
1.- Channel to remain disabled indefinetly.

### Please tell us about your environment:
- [ ] Node-RED-Dashboard version: 2.15.4 (all environments)
- [ ] Node-RED version: v0.20.5 (all environments)
- [ ] node.js version: v10.16 (all environments)
- [ ] npm version:
- [ ] Platform/OS: OSX v10.14.5, Linux v18.04 (AWS and Local), and Windows (I have no clue about its version but it is the latest)
- [ ] Browser: Google Chrome(OSX & MS), MS Edge, Firefox (linux)

**Comment by dceejay** [comment]
Interesting. For me it seems that they get re-enabled whenever new data arrives...
As the legend enable/disable is built in functionality of chart.js, it will need to be investigated as to what is triggering the re-enable - or not saving the state... or whatever....
