### ISSUE TITLE
Numeric node: can't change value by keyboard

### ISSUE THREAD

**Issue by laquesisa** [node-red/node-red-dashboard#509]
When I use the node-red-dashboard numeric node, I can't change the value manually with the keyboard. I can only use the up and down arrows to change the value. That could take a long time, if you want to change the value between 0 and 1000. 
It worked with a previous version to change the value manually. But it isn't working in the newer versions of node-red-dashboard.

That's how it worked before:
![image](https://user-images.githubusercontent.com/31890886/60020133-b143a180-968f-11e9-925c-bb46bd2ae20d.png)

Now there is no input anymore.

**Environment**
It worked with:
- node-red-dashboard: 2.9.4
- node-red: 0.20.6

and it worked with:
- node-red-dashboard: 2.9.8
- node-red: 0.19.6
________________________________________________
It didn't work with:
- node-red-dashboard: 2.9.8
- node-red: 0.20.6

also did not work with all the versions higher than 2.9.8
- node-red-dashboard: 2.15.4
- node-red: 0.20.6

___________________
**other environment-variables didn't change**
- npm version: 6.9.0
- OS: Windows
- Browser: Chrome

**Comment by dceejay** [comment]
set the input Value Format to be {{msg.payload}} instead of {{value}} and it will work.
I have updated the info for next release to say

"Setting the Value Format field to {{msg.payload}} will make the input field editable so you can type in a number."

**Comment by laquesisa** [comment]
Thank you for your help!

**Comment by pomplesiegel** [comment]
This was extremely helpful. I've written about it here as well: https://discourse.nodered.org/t/numeric-text-input-and-slider-questions-ideas/12832/8
