### ISSUE TITLE
Must incoming messages be outputed directly?

### ISSUE THREAD

**Issue by codmpm** [node-red/node-red-dashboard#51]
Maybe the topic is not very well choosen, so for example: 

I have a dimmer which is controlled via mqtt. The dimmer is shown as a slider on the dashboard with values from 0-100. There is a topic for setting the value and one where the current brightness is stored, like this:
![bildschirmfoto 2016-09-02 um 20 41 36](https://cloud.githubusercontent.com/assets/9745239/18214525/b2a4b95c-714d-11e6-87f0-37631e20d3c2.png)

The problem now is, that the value of the current brightness gets updated with a bit of lag on setting the dimmer via the dashboard. Naturally I'll get a race condition and the slider jumps from left to right. I can handle this by limiting the messages from the incoming topic.

But is it necessary to let the dashboard element output the incoming value immediately? Maybe it should be switchable that only on changing values on the dashboard element itself generate an output and an input is only used to display the value?

Maybe I've just thinking the wrong direction and you could just point me out. And also I hope you've could get what I mean ;-)

I love node-red-dashboard and hope that this project get's the attention it deserves. Meanwhile my whole home automation is running on node-red and node-red-dashboard.

Cheers,
Patrik

**Comment by dceejay** [comment]
Hi, yes I can see the problem. It occurs when the widget outputs more than one value within the time it takes for the feedback to occur...
Yes - optionally disconnecting the input from passing through may be the simple fix... but need to think through if there are any other consequences.

**Comment by openSoftMan** [comment]
I had this issue early on too and figured out how to just update the switch with no payload output(or race condition).
In between the subscribe and switch, I set msg.topic = null in a function node and just pass the msg.payload to the switch.

**Comment by codmpm** [comment]
This is a marvelous idea. Never thought of that...

But I think it would be great to slightly optionally disconnect the input from the output. As @dceejay said, it should the thought through.

Thanks @openSoftMan!

**Comment by dceejay** [comment]
OK - have caved :-).... and added the option to disable pass-through of messages if you so wish - on both this and the toggle switch widgets.
Now in the github master branch.
