### ISSUE TITLE
Toolbar Enable

### ISSUE THREAD

**Issue by robertowiest** [node-red/node-red-dashboard#510]
Hello, in my node-red application, the side-bar toolbar menu is not being displayed. Some solution for such a probe

**Comment by knolleary** [comment]
Please use the template you were given when opening issue to provide the required information. Thanks!

**Comment by robertowiest** [comment]
### What are the steps to play?
When trying to access a simple page.
### What happens?
Sidebar or Sidemenu on the left side is not displayed
### What do you expect to happen?
Have the Sidebar or Sidemenu appear
### Please tell us about your environment:

- [] Node-RED-Dashboard version: 2.15.5
- [] Node-RED version: v0.20.6
- [] node.js version: 10.16
- [] npm version: 9.9.0
- [] Platform / OS: Raspberry pi 3
- [] Browser: Chromium 72.0.36

**Comment by dceejay** [comment]
If you only have widgets set on one page then there is no sidebar to display. It only appears if it needs to. If you do have more that one tab created then either the (hamburger) menu icon top left
![image](https://user-images.githubusercontent.com/5375409/60176599-b844ee00-980e-11e9-8eee-c739423cd5a0.png)
will show it - or in the dashboard site settings you can set it to be there all the time or not,
![image](https://user-images.githubusercontent.com/5375409/60176647-dc083400-980e-11e9-9d39-36caaf024970.png)
![image](https://user-images.githubusercontent.com/5375409/60176674-ec201380-980e-11e9-8016-e81733603f37.png)

**Comment by dceejay** [comment]
closing
