### ISSUE TITLE
ui_control only triggers the UI tab after some element of the UI lose focus

### ISSUE THREAD

**Issue by aiot-maker** [node-red/node-red-dashboard#511]
### What are the steps to reproduce?
In a dashboard with several UI tabs add an ui__control node. Inject different payloads to change the tab.
### What happens?
Even if the ui_control receives a good payload it won't change the tab. 
### What do you expect to happen?
TBAs should change as soon as the ui_control node receives the command to switch. It will only happen when you hover your mouse over other elements of the UI interface.
[Issue more detailed in the Forum](https://discourse.nodered.org/t/ui-control-strange-situation/11884)
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: Dashboard version 2.15.5
- [ ] Node-RED version: Node-RED version: v1.0.0-beta.2
- [ ] node.js version: Node.js  version: v8.11.1
- [ ] npm version:
- [ ] Platform/OS: Windows_NT 10.0.17763 x64 LE
- [ ] Browser: Chrome  75.0.3770.100

**Comment by dceejay** [comment]
Is this the same as #508 ? or different ?
Do you have a simple flow that you can share that demonstrates this ?
Are there any errors in the browser console log when you click the button ?

**Comment by dceejay** [comment]
Was same as #508 - closing
