### ISSUE TITLE
Problem with pushing a button

### ISSUE THREAD

**Issue by LennAl** [node-red/node-red-dashboard#512]
**What are the steps to reproduce?**
I programmed a small survey where I used dasboard buttons to get on the next page.
[Process description.docx](https://github.com/node-red/node-red-dashboard/files/3345179/Process.description.docx)
[Process description.docx](https://github.com/node-red/node-red-dashboard/files/3345181/Process.description.docx)

**What happens?**
When I opend my survey in the browser on a touchscreen device like my tablet/smartphone I had to push the button twice to get to the next page. Then I wrote a Tooltip for my button and than it worked and I only had to push the button once.

**What do you expect to happen?**
I usually should push the button once also without a tooltip.

- [ ] Node-RED-Dashboard version: 2.15.5
- [ ] Node-RED version: 0.20.5
- [ ] Platform/OS: Arm RaspberryPi
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
do you have a small flow file you can share that demonstrates the issue ? Thanks

**Comment by LennAl** [comment]
[{"id":"b4ebb1cb.30f6","type":"tab","label":"Flow 4","disabled":false,"info":""},{"id":"ddfadf83.f571c","type":"ui_button","z":"b4ebb1cb.30f6","name":"Issue","group":"2a1a5e51.89fe72","order":0,"width":0,"height":0,"passthru":false,"label":"button","tooltip":"","color":"","bgcolor":"","icon":"","payload":"+1","payloadType":"str","topic":"","x":380,"y":140,"wires":[["f270412b.5996c","722ffa37.0b1184"]]},{"id":"722ffa37.0b1184","type":"debug","z":"b4ebb1cb.30f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":810,"y":140,"wires":[]},{"id":"15f98b75.43f8d5","type":"debug","z":"b4ebb1cb.30f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":810,"y":60,"wires":[]},{"id":"f270412b.5996c","type":"ui_ui_control","z":"b4ebb1cb.30f6","name":"","x":580,"y":80,"wires":[["15f98b75.43f8d5"]]},{"id":"e645a920.db0278","type":"ui_button","z":"b4ebb1cb.30f6","name":"no issue","group":"1fca0964.2857a7","order":0,"width":0,"height":0,"passthru":false,"label":"button","tooltip":"Tooltip","color":"","bgcolor":"","icon":"","payload":"-1","payloadType":"str","topic":"","x":390,"y":380,"wires":[["49e96ec4.9289e","8810b554.7cb558"]]},{"id":"49e96ec4.9289e","type":"ui_ui_control","z":"b4ebb1cb.30f6","name":"","x":540,"y":340,"wires":[["6bfba989.4277a8"]]},{"id":"6bfba989.4277a8","type":"debug","z":"b4ebb1cb.30f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":780,"y":300,"wires":[]},{"id":"8810b554.7cb558","type":"debug","z":"b4ebb1cb.30f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":770,"y":380,"wires":[]},{"id":"2a1a5e51.89fe72","type":"ui_group","z":"","name":"Issue","tab":"90737fbb.c5fd","disp":true,"width":"6","collapse":false},{"id":"1fca0964.2857a7","type":"ui_group","z":"","name":"No issue","tab":"dfc34a86.2e1d28","disp":true,"width":"6","collapse":false},{"id":"90737fbb.c5fd","type":"ui_tab","z":"","name":"Issue","icon":"dashboard","disabled":false,"hidden":false},{"id":"dfc34a86.2e1d28","type":"ui_tab","z":"","name":"No issue","icon":"dashboard","disabled":false,"hidden":false}]

**Comment by dceejay** [comment]
Is this issue only on smartphone / tablet ? Which browser on there. 
Is working fine so far on desktop.

**Comment by LennAl** [comment]
Yes you are right. On the desktop it works witout a problem but please try it with a touchscreen tablet/smartphone. I tried it there with chrome and apple Safari and on both there was the issue.

**Comment by dceejay** [comment]
OK - have now tried on my iphone Safari - and still all good. Are you sure the cache has been flushed on the phone / tablet ? I suspect it may be same as #508 that was fixed last release.

**Comment by LennAl** [comment]
Hello,
I do not think that it is the same issue like #508 here is a short video I made to illustrate the problem.
https://youtu.be/zO7AJ6vXuE4

**Comment by dceejay** [comment]
tricky, I can show a video of it working for me. I will see if I can find another tablet, but I still think it is a cacheing issue at present.

**Comment by LennAl** [comment]
Thankyou very much for your support 👍. I enpty again my cache and now it works also without a tooltip. I just updatet Node-Red a few days ago and did not notice, that the old version is still saved in my cache.
