### ISSUE TITLE
text-input node automatically sends msg when delay is set to 0 

### ISSUE THREAD

**Issue by OndrejMikes** [node-red/node-red-dashboard#513]
Node-Red 0.20.5
DashBoard 2.15.5
__________________

Text-input node automatically sends msg but delay is set to 0.
I did a restart but it doesnt help.

Do you have any other idea?

Thank you.
Ondrej

**Comment by dceejay** [comment]
When does it send it ? The node sends whatever is there when it loses focus - so that you can tab between fields in a "form".

**Comment by OndrejMikes** [comment]
Ok, yes, in this case it is ok. 
But also it send values when I type text into filed. 
So when I use barcode reader, input field send one value twice (because barcode reader send also Enter).

**Comment by OndrejMikes** [comment]
Seems simular like this: https://github.com/node-red/node-red-dashboard/issues/238

**Comment by dceejay** [comment]
fior now can you use an RBE node to deduplicate ?

**Comment by OndrejMikes** [comment]
Yes, it is also solution :)

**Comment by OndrejMikes** [comment]
But strange is that other inputs in my flows works well.

**Comment by dceejay** [comment]
If will fix the node to only send on loss of focus IF it hasn't already sent on Enter - so you can hit Enter several times and it will send each time ("I said Do it now...!" :-) - but not if you then move away... OR you can tab to next field and it will send.
