### ISSUE TITLE
Color picker can output without direct interaction

### ISSUE THREAD

**Issue by Hugobox** [node-red/node-red-dashboard#514]
### What are the steps to reproduce?

1. Create a dashboard with at least 2 tab pages and a color picker on 1 tab connected to a debug node.
2. Set the color picker's "send" option to "multiple values during editing".
3. Deploy.
4. On the dashboard page, click on each tab, each time you'll open the tab with the color picker, it will output its current value.

### What happens?

On the dashboard page, click on each tab, each time you'll open the tab with the color picker, it will output its current value.

### What do you expect to happen?

Clicking on a dashboard tab shouldn't trigger the color picker to output.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.15.5
- [ ] Node-RED version: 0.20.5
- [ ] node.js version: 8.10.0
- [ ] npm version: 6.1.0
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome 75.0.3770.100

**Comment by Hugobox** [comment]
Not sure if its related, but when the

**Comment by Hugobox** [comment]
Hi! While the color picker doesn't output on page change, it still outputs on page refresh.

**Comment by dceejay** [comment]
Really - I just added a picker connected to debug - deployed - set a colour (got output). Refresh page - nothing - change tabs - nothing - refresh - nothing - back to tab with picker - refresh - nothing. 

Can you show how to re-create the issue you are seeing ?

**Comment by Hugobox** [comment]
@dceejay Do you prefer if I open a new issue?

**Comment by Hugobox** [comment]
Found the culprit setting: the Send "multiple values during editing"

**Comment by dceejay** [comment]
Aha - found it...

**Comment by dceejay** [comment]
Pushed fix to master
