### ISSUE TITLE
Internet Explorer 11 doesn't load ui_base and ui_switch component

### ISSUE THREAD

**Issue by tt92** [node-red/node-red-dashboard#515]
### What happens?

When I open the Node-RED editor in IE11 I get two error messages saying that ui_base and ui_switch failed to load.

The Dashboard itself is accessible and the switches (designed in Chrome) are working as expected.
But they are not displayed correctly in the editor.

### How can we fix this?

The issue seems to be caused by empty jQuery event handlers:

`$(...).on("xy", )`

Currently, there are 7 of these in the source code (6 in ui_base.html (lines 2198, 2200,...), 1 in ui_switch.html).

If you change it to

`$(...).on("xy", function() {})`

the issue seems to be solved.
Maybe they can even be removed completely? I'm not sure what they are actually good for...

### Please tell us about your environment:

- Node-RED-Dashboard version: 2.15.5
- Node-RED version: 0.20.5
- node.js version: 10.16.0
- npm version: 6.9.0
- Platform/OS: Win 10
- Browser: IE 11 (11.0.130)

Cheers, Tobias

**Comment by dceejay** [comment]
hmm - they should have just been `.change();` - but got swept up in a global edit.
Will revert them.

**Comment by dceejay** [comment]
Closed by bb3d87a6f862ff4c6d264b5361a0ad318281322e
