### ISSUE TITLE
Improve embedded node-red dashboard full path resolve

### ISSUE THREAD

**Issue by doino-gretchenliev** [node-red/node-red-dashboard#517]
### What are the steps to reproduce?
1. Setup embedded node-red following [this](https://nodered.org/docs/user-guide/runtime/embedding) guide.
2. Comment out `httpNodeRoot` or `ui.path` setting from `settings.js`
3. Start the server

### What happens?
Several ui nodes fail to initialise. E.G.: `ui_button`
Error: `TypeError: Cannot read property 'replace' of undefined (line:2)`

### Why it fails?
On [this](https://github.com/node-red/node-red-dashboard/blob/master/ui.js#L318) line there is a call to [this](https://github.com/node-red/node-red-dashboard/blob/master/ui.js#L299) `join` function. The `join` function fails when it tries to call `replace` and one of the arguments is `undefined`(in this case `e` variable inside `map`), in that case `httpNodeRoot`.

### How to fix it?
* Merge my [PR](https://github.com/node-red/node-red-dashboard/pull/516)
I think, this is the best resolution to this issue, since the developer may skip `httpNodeRoot` and still get fully working dashboards.
* Improve [documentation](https://nodered.org/docs/user-guide/runtime/embedding), making `httpNodeRoot` mandatory. It is used elsewhere in the example, so probably it's already mandatory, but it could be easily skipped.

### What do you expect to happen?
All ui nodes are available and working.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.15.5
- [ ] Node-RED version: 0.20.7
- [ ] node.js version: 8.16.0
- [ ] npm version: 6.4.1
- [ ] Platform/OS: latest docker [image](https://hub.docker.com/r/nodered/node-red-docker/)
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Closed by merge
