### ISSUE TITLE
Template node: Error while showing html in message

### ISSUE THREAD

**Issue by jewe** [node-red/node-red-dashboard#52]
If i inject a message including html code like this:
`<b>bold</b>`
and i put these mustage tags template in the connected template node
`{{{msg.payload}}}`
i got an error in chrome and firefox:
`Error: $parse:syntax Syntax Error`.

Is there another way to display unescaped html?

**Comment by dceejay** [comment]
Hi - yes - the ui-template actually uses Angular syntax and not moustache... (as does the whole dashboard... )  so what you need in the template is 
    <div ng-bind-html="msg.payload"></div>
(This will  be the default entry in the template going forward - as it will be more useful for the majority of users)
For general questions like this we prefer the mailing list.
