### ISSUE TITLE
Ui buttion issue on iPhone / iPad android phone / tablet

### ISSUE THREAD

**Issue by Toshibass** [node-red/node-red-dashboard#520]
I have a problem when displaying text or background colours on a ui button on a iphone, so I have a simple button that changes colour from red to green when pressed, on Dashboard 2.9.8 the button works fine, press red changes to green press again changes to red, however on Dashboard 2.15.5 press red I get a washed out green colour (like the same as when you hover over the button) until you press somewhere else on a empty part of the screen , I tested this on Safari and google chrome on iphone / android phone ipad and android tablet all show the same issue. (On google chrome on a computer the issue is not present)
I suspect this has something to do with hover on 2.15.5 as hover was not present in 2.9.8

**Comment by dceejay** [comment]
Hi sorry - been on vacation - back now - do you have a simple flow that you can share that shows this ?

**Comment by dceejay** [comment]
ah right yes - will revert for now.
