### ISSUE TITLE
changing theme doesnt work

### ISSUE THREAD

**Issue by joaofgf** [node-red/node-red-dashboard#529]
### What are the steps to reproduce?

just change the theme on node-red dashboard

### What happens?

nothing. the light theme sticks.

### What do you expect to happen?

change to dark theme.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.16.2
- [ ] Node-RED version: 0.20.8
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Linux Ubuntu 18.04
- [ ] Browser: chrome/firefox

I'm using node-red dashboard and no matter how many times i change the theme to dark, the dashboard always keep the light theme. basically, nothing happens if i change the theme to dark.
thanks in advance.

**Comment by dceejay** [comment]
Once you change it - then hit deploy - Is there anything in your browser debug console log ?
(or in the main Node-RED console log ?)

**Comment by dceejay** [comment]
no follow up - closing for now.
