### ISSUE TITLE
Date formating in chart?

### ISSUE THREAD

**Issue by codmpm** [node-red/node-red-dashboard#53]
Hi again,

is it possible to format the timestamp which is displayed as `hh:mm:ss` in a chart? Would be nice to display dates because charts could be used to display data over more than one day.

Cheers,
Patrik

**Comment by dceejay** [comment]
working on it...
![image](https://cloud.githubusercontent.com/assets/5375409/18286264/db3e51f6-7469-11e6-900f-d2246ff8841b.png)

but of course... be careful... the chart widget has a tendency (more a reality) to fill up memory (as it saves all data points within the specified time range - (but usually only displays 2-300px worth on the screen - so do try to limit the amount of data being sent if running over days...

This version will be released hopefully later this week (wk of 5th Sept) but is on Gihub now so closing
