### ISSUE TITLE
Dashboard doesn't load in IE because of Promise usage

### ISSUE THREAD

**Issue by tt92** [node-red/node-red-dashboard#530]
The dashboard does not load in IE because some 3rd-party libraries use promises (which IE doesn't support (https://caniuse.com/#search=promise)).

Of course, this could be escalated to the corresponding libraries.
But maybe adding a promise polyfill is a good alternative to increase robustness.

Cheers,

Tobias

- Node-RED-Dashboard version: 2.16.2
- Node-RED version: 0.20.6
- Browser: Internet Explorer

**Comment by dceejay** [comment]
Which libraries ? (for example)
Is this is in the core of dashboard ?

**Comment by dceejay** [comment]
A quick look suggests https://www.npmjs.com/package/promise-polyfill as a possible option. but that uses import - which is also not supported by IE11...

**Comment by tt92** [comment]
Currently, the error "Promise is undefined" is caused by https://github.com/less/less.js (app.min.js (529,152730)).

IE8+ is on the browser support list of https://www.npmjs.com/package/promise-polyfill.
All imports would be handled by gulp, wouldn't they?

**Comment by dceejay** [comment]
really ? the less.js in Dashboard already includes a polyfill ?

"dependencies": {
    "clone": "^2.1.2",
    "errno": "^0.1.1",
    "graceful-fs": "^4.1.2",
    "image-size": "~0.5.0",
    "mime": "^1.4.1",
    "mkdirp": "^0.5.0",
    "promise": "^7.1.1",
    "request": "^2.83.0",
    "source-map": "~0.6.0"

**Comment by tt92** [comment]
That's what my IE11 console tells me...
It seems like there were some major refactorings last month switching less.js to ES6.
Maybe that broke the IE compatibility...

Are you able to open a dashboard in IE11?
