### ISSUE TITLE
Sidebar doesn't show dashboard

### ISSUE THREAD

**Issue by ChristopheSE** [node-red/node-red-dashboard#533]
Hi,

I lost the sidebar tab for the dashboard. It was there before I installed HostIP Node and reinstalled Dashboard 2.15.5. it's not available in the view too.
I uninstalled and reinstalled dashboard...the tab is still not appearing. I have the same machine with the same version which is working fine. 
In the machine with the issue, if I inspect the nodered webpage, I don't see the ui-tab-dashboard
<li class="red-ui-tab" id="red-ui-tab-info" style="width: 28.4566%;"><a href="#info" class="red-ui-tab-label" title="info" style=""><span class="bidiAware" dir="">info</span></a></li>
<li class="red-ui-tab" id="red-ui-tab-debug" style="width: 28.4566%;"><a href="#debug" class="red-ui-tab-label" title="debug" style=""><span class="bidiAware" dir="">debug</span></a></li>
<li class="red-ui-tab active" id="red-ui-tab-dashboard" style="width: 110px;"><a href="#dashboard" class="red-ui-tab-label" title="dashboard" style=""><span class="bidiAware" dir="">dashboard</span></a><a href="#" class="red-ui-tab-close" style="display: block;"><i class="fa fa-times"></i></a></li>**

Any idea why I lost this tab ?

Thanks

- [ ] Node-RED-Dashboard version: 2.15.5
- [ ] Node-RED version: 0.17.5
- [ ] node.js version:6.10.3
- [ ] npm version:
- [ ] Platform/OS: linux 
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Dashboard now requires node.js version 8 as a minimum
(as does latest Node-RED).

**Comment by ChristopheSE** [comment]
I'm not able to upgrade the node.js. The machine is delivered with that version and we can't upgrade it.

**Comment by dceejay** [comment]
you'll have to revert dashboard to 2.14 or 2.13
(I can't recall when exactly it changed)
you can install manually by  

    cd ~/.node-red  && npm i node-red-dashboard@2.14

**Comment by ChristopheSE** [comment]
Hi,

it starts to work again with version 2.8 and doesn't work with higher version.

Thanks for your help

**Comment by dceejay** [comment]
OK - Made a note. thanks for letting me know.
