### ISSUE TITLE
Dashboard Gauges displaying the wrong flow, then goes back to the right flow. 

### ISSUE THREAD

**Issue by Navybrandon** [node-red/node-red-dashboard#534]
How do I resolve?

Below is my flow. At random times it will grab data from a different flow and display that on the gauge.

`[{"id":"b37e3b86.8e0538","type":"tab","label":"Supply Damper Position","disabled":false,"info":""},{"id":"6ff0484e.2e3098","type":"file","z":"b37e3b86.8e0538","name":"Supply Damper Position file location","filename":"/home/pi/hvac/SupplyDamperPosition.log","appendNewline":true,"createDir":true,"overwriteFile":"false","encoding":"none","x":1550,"y":160,"wires":[[]]},{"id":"f0118fe0.d0431","type":"ui_switch","z":"b37e3b86.8e0538","name":"Supply Damper Position","label":"Supply Damper Position","tooltip":"","group":"9dc2a1a6.c5626","order":2,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"fa-toggle-on","oncolor":"red","offvalue":"false","offvalueType":"bool","officon":"fa-toggle-off","offcolor":"red","x":170,"y":80,"wires":[["a7d4d01.af8463","50945d05.7229e4"]]},{"id":"79e27e99.55af","type":"ui_gauge","z":"b37e3b86.8e0538","name":"Supply Damper Position","group":"7893a32b.67eadc","order":1,"width":0,"height":0,"gtype":"gage","title":"Supply Damper Position","label":"Percent Open","format":"{{value | number:2}}","min":0,"max":"100","colors":["#00ff00","#00ff00","#00ff00"],"seg1":"","seg2":"","x":1370,"y":80,"wires":[]},{"id":"d9941367.52bb8","type":"function","z":"b37e3b86.8e0538","name":"Read Damper Position","func":"//var msg = {};\nconst bacnet1 = global.get('bacnet');\n// Initialize BACStack\nvar client = bacnet1({adpuTimeout: 6000});\nvar state = msg.payload;\n\nconst values = [\n {objectId: {type: 2, instance: 3001594}, values: [\n {property: {id: 85, index: 4294967295}, value: [{type: bacnet1.enum.ApplicationTags.BACNET_APPLICATION_TAG_REAL, value: state}], priority: 15}\n ]}\n];\n\nclient.readProperty('192.168.1.41', {type: 2, instance: 3001594}, 85, (err, value) => {\n msg.payload = {value: value} ;\n node.send(msg);\n});\nreturn msg;","outputs":1,"noerr":0,"x":620,"y":80,"wires":[["71676674.480138"]]},{"id":"b38c432e.0443a","type":"function","z":"b37e3b86.8e0538","name":"Data Capture","func":"var d = new Date();\nvar t = d.getTime();\nvar n = d.getTimezoneOffset();\nvar p = msg.payload\npayload={\"date/time\": d,\"Time Zone Diffrence in minutes\": n,\"Supply Damper Position\": p};\nmsg.payload=payload;\nreturn msg;","outputs":1,"noerr":0,"x":1150,"y":160,"wires":[["2eb1a9c1.086606"]]},{"id":"2eb1a9c1.086606","type":"json","z":"b37e3b86.8e0538","name":"","property":"payload","action":"","pretty":false,"x":1310,"y":160,"wires":[["6ff0484e.2e3098"]]},{"id":"34e8a354.7525ac","type":"trigger","z":"b37e3b86.8e0538","op1":"","op2":"","op1type":"pay","op2type":"payl","duration":"1","extend":false,"units":"hr","reset":"false","bytopic":"all","name":"","x":830,"y":160,"wires":[["b1579d47.72b15"]]},{"id":"a7d4d01.af8463","type":"trigger","z":"b37e3b86.8e0538","op1":"","op2":"","op1type":"date","op2type":"date","duration":"-1","extend":false,"units":"s","reset":"false","bytopic":"all","name":"","x":400,"y":80,"wires":[["d9941367.52bb8"]]},{"id":"71676674.480138","type":"change","z":"b37e3b86.8e0538","name":"","rules":[{"t":"move","p":"payload.value.values[0].value","pt":"msg","to":"SDPdata","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":920,"y":80,"wires":[["63a2f632.0e1ea8"]]},{"id":"63a2f632.0e1ea8","type":"function","z":"b37e3b86.8e0538","name":"","func":"var FB = msg.SDPdata\nvar newMsg = {payload:FB};\nreturn newMsg;\n","outputs":1,"noerr":0,"x":1170,"y":80,"wires":[["34e8a354.7525ac","79e27e99.55af","df28d48f.9bbb98","24fcf8fb.3aaeb8"]]},{"id":"b1579d47.72b15","type":"function","z":"b37e3b86.8e0538","name":"","func":"var FB = msg.payload\nvar newMsg = {payload:FB};\n\nreturn newMsg;\n\n\n","outputs":1,"noerr":0,"x":990,"y":160,"wires":[["b38c432e.0443a"]]},{"id":"50945d05.7229e4","type":"switch","z":"b37e3b86.8e0538","name":"","property":"payload","propertyType":"msg","rules":[{"t":"cont","v":"false","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":370,"y":120,"wires":[["4388dcc.f242624"]]},{"id":"4388dcc.f242624","type":"change","z":"b37e3b86.8e0538","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"OFF","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":600,"y":120,"wires":[["79e27e99.55af"]]},{"id":"df28d48f.9bbb98","type":"debug","z":"b37e3b86.8e0538","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1310,"y":40,"wires":[]},{"id":"24fcf8fb.3aaeb8","type":"link out","z":"b37e3b86.8e0538","name":"","links":["43f303e0.77c99c"],"x":1195,"y":40,"wires":[]},{"id":"9dc2a1a6.c5626","type":"ui_group","z":"","name":"Data Collection","tab":"3660b77a.a38508","disp":true,"width":"10","collapse":true},{"id":"7893a32b.67eadc","type":"ui_group","z":"","name":"Live Data View","tab":"f21fa3ea.1d205","disp":true,"width":10,"collapse":true},{"id":"3660b77a.a38508","type":"ui_tab","z":"","name":"Turn Data Collection On or Off","icon":"dashboard","order":3,"disabled":false,"hidden":false},{"id":"f21fa3ea.1d205","type":"ui_tab","z":"","name":"Live Data","icon":"dashboard","order":4,"disabled":false,"hidden":false}]`

**Comment by dceejay** [comment]
sorry - need a bit more info - what other flow ? what does it display ?
The first function node does this
```
client.readProperty('192.168.1.41', {type: 2, instance: 3001594}, 85, (err, value) => {
 msg.payload = {value: value} ;
 node.send(msg);
});
return msg;`
```
so it will send the original payload first - then the property it reads... so two outputs. Do you need the final return msg ?

**Comment by Navybrandon** [comment]
please see below,

![image](https://user-images.githubusercontent.com/55708884/67025710-1bafa000-f0cc-11e9-8345-ee9a5a5f7399.png)

the gauge below is getting the data mixed up.

![image](https://user-images.githubusercontent.com/55708884/67025809-44379a00-f0cc-11e9-9440-e119f476a883.png)

the below is what the gauges are suppose to read other that the feedback gauge that one will change.

![image](https://user-images.githubusercontent.com/55708884/67025952-7ea13700-f0cc-11e9-886a-174af8a5163e.png)

I think the cure is to make sure the msg.payload is unique to each flow.

**Comment by dceejay** [comment]
This gauge node 
![image](https://user-images.githubusercontent.com/5375409/67046386-09634f80-f128-11e9-97be-8769561f79ae.png)
has two inputs... so it could well show two different values at different times. Unless you are sure they represent the same thing you should use one gauge per reading.

**Comment by Navybrandon** [comment]
one of the inputs gives it the "off" when its toggled off. the other is the payload, that rechecks after so long.

**Comment by dceejay** [comment]
I can see four gauges - your background and font is such I can't read the text under the gauges so I can't tell what is mixed up at all - I am going to have to assume it's a problem with your flow - better suited to the forum for answers, rather than an issue with the dashboard.

**Comment by Navybrandon** [comment]
I was able to reduce the amount of data crossing by changing the msg.payload to msg.example. But the gauges would not display the latest msg.example only the first one. Any advice on how to get the gauge to constantly show value other than payload. the value format reflects the new payload name.

**Comment by dceejay** [comment]
like
![image](https://user-images.githubusercontent.com/5375409/67047886-16ce0900-f12b-11e9-8dcc-50e148bc44b9.png)

**Comment by Navybrandon** [comment]
payload change
![image](https://user-images.githubusercontent.com/55708884/67048040-17e64280-f0f9-11e9-9792-5619b9079386.png)


gauge
![image](https://user-images.githubusercontent.com/55708884/67048014-0d2bad80-f0f9-11e9-9169-92004c4faf39.png)

debug
![image](https://user-images.githubusercontent.com/55708884/67048242-7b707000-f0f9-11e9-851f-b641c84286f3.png)

gauge on dashboard only has the first value.

example flow
![image](https://user-images.githubusercontent.com/55708884/67048285-90e59a00-f0f9-11e9-878e-b3d2887251b1.png)

**Comment by dceejay** [comment]
ah - you can only do angular filters to {{value | ....   which is same effectively same as payload.
any other property does not go via the filters - so you need to use a function to trim if you need to first. But `{{value | number:2}}%` should work (on incoming payload)

**Comment by dceejay** [comment]
```
[{"id":"10b4362f.1aa2da","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"18.123456","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":120,"wires":[["37b68891.16b398"]]},{"id":"37928953.f0e556","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"42.98731","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":180,"wires":[["37b68891.16b398"]]},{"id":"f4585fde.e4a83","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"34.089798","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":240,"wires":[["37b68891.16b398"]]},{"id":"fdd5127c.41754","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"11.9873","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":300,"wires":[["37b68891.16b398"]]},{"id":"553b98ba.186828","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"27.3244234","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":360,"wires":[["37b68891.16b398"]]},{"id":"37b68891.16b398","type":"ui_gauge","z":"5051cb93.cf0d34","name":"","group":"d7051596.4a2848","order":0,"width":0,"height":0,"gtype":"gage","title":"gauge","label":"units","format":"{{value | number:2}}%","min":0,"max":"50","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":370,"y":200,"wires":[]},{"id":"d7051596.4a2848","type":"ui_group","z":"","name":"Default","tab":"3d4dee04.4678f2","disp":true,"width":"6","collapse":false},{"id":"3d4dee04.4678f2","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

**Comment by dceejay** [comment]
Actually both ways...
```
[{"id":"10b4362f.1aa2da","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"18.123456","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":120,"wires":[["37b68891.16b398","29a0e0af.75cf5"]]},{"id":"37928953.f0e556","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"42.98731","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":180,"wires":[["37b68891.16b398","29a0e0af.75cf5"]]},{"id":"f4585fde.e4a83","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"34.089798","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":240,"wires":[["37b68891.16b398","29a0e0af.75cf5"]]},{"id":"fdd5127c.41754","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"11.9873","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":300,"wires":[["37b68891.16b398","29a0e0af.75cf5"]]},{"id":"553b98ba.186828","type":"inject","z":"5051cb93.cf0d34","name":"","topic":"","payload":"27.3244234","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":360,"wires":[["37b68891.16b398","29a0e0af.75cf5"]]},{"id":"37b68891.16b398","type":"ui_gauge","z":"5051cb93.cf0d34","name":"","group":"d7051596.4a2848","order":0,"width":0,"height":0,"gtype":"gage","title":"gauge","label":"units","format":"{{value | number:2}}%","min":0,"max":"50","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":370,"y":200,"wires":[]},{"id":"29a0e0af.75cf5","type":"change","z":"5051cb93.cf0d34","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"$round(payload,2) & ' %'","tot":"jsonata"},{"t":"move","p":"payload","pt":"msg","to":"SDFB","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":320,"wires":[["82886f2f.328c2"]]},{"id":"82886f2f.328c2","type":"ui_gauge","z":"5051cb93.cf0d34","name":"","group":"d7051596.4a2848","order":0,"width":0,"height":0,"gtype":"gage","title":"gauge","label":"units","format":"{{msg.SDFB}}","min":0,"max":"50","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":550,"y":320,"wires":[]},{"id":"d7051596.4a2848","type":"ui_group","z":"","name":"Default","tab":"3d4dee04.4678f2","disp":true,"width":"6","collapse":false},{"id":"3d4dee04.4678f2","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

**Comment by Navybrandon** [comment]
ok that helped a little but upon further investigation I noticed that on some of my flows it is getting data from something not on that flow..  see below. 

Flow Overview
![image](https://user-images.githubusercontent.com/55708884/67108934-18341b80-f195-11e9-889d-81f4c75b0748.png)

Flow Debug view
![image](https://user-images.githubusercontent.com/55708884/67108962-297d2800-f195-11e9-8caf-4fb4c554b2bc.png)

The wrong data is coming from a different flow that none of the msg.payloads are the same.

**Comment by Navybrandon** [comment]
Code from the other flow.

`[{"id":"e618aa97.f26d38","type":"tab","label":"Supply Damper Feedback","disabled":false,"info":""},{"id":"3e7fda63.47d516","type":"file","z":"e618aa97.f26d38","name":"Supply Damper Feedback location","filename":"/home/pi/hvac/SupplyDamperFeedback.log","appendNewline":true,"createDir":true,"overwriteFile":"false","encoding":"none","x":1660,"y":200,"wires":[[]]},{"id":"a3ebf5fc.611ed8","type":"function","z":"e618aa97.f26d38","name":"Data Capture","func":"var d = new Date();\nvar t = d.getTime();\nvar n = d.getTimezoneOffset();\nvar p = msg.payload\npayload={\"date/time\": d,\"Time Zone Diffrence in minutes\": n,\"Supply Damper Feedback\": p};\nmsg.payload=payload;\nreturn msg;","outputs":1,"noerr":0,"x":1270,"y":200,"wires":[["7f74afc6.4228c"]]},{"id":"7f74afc6.4228c","type":"json","z":"e618aa97.f26d38","name":"","property":"payload","action":"","pretty":false,"x":1430,"y":200,"wires":[["3e7fda63.47d516"]]},{"id":"bc41f21e.9827","type":"trigger","z":"e618aa97.f26d38","op1":"","op2":"","op1type":"pay","op2type":"payl","duration":"15","extend":false,"units":"min","reset":"OFF","bytopic":"all","name":"","x":950,"y":200,"wires":[["c6af0b44.c8a828"]]},{"id":"e08312b3.ade71","type":"ui_switch","z":"e618aa97.f26d38","name":"Supply Damper Feedback","label":"Supply Damper Feedback","tooltip":"","group":"9dc2a1a6.c5626","order":1,"width":0,"height":0,"passthru":false,"decouple":"false","topic":"","style":"","onvalue":"1","onvalueType":"str","onicon":"fa-toggle-on","oncolor":"BabyBlue","offvalue":"false","offvalueType":"bool","officon":"fa-toggle-off","offcolor":"BabyBlue","x":310,"y":80,"wires":[["b877569b.5ced58","ec68a56d.e05008"]]},{"id":"8c5adeb9.17f91","type":"ui_gauge","z":"e618aa97.f26d38","name":"Supply Damper Feedback","group":"7893a32b.67eadc","order":2,"width":0,"height":0,"gtype":"gage","title":"Supply Damper Feedback","label":"Percent Open","format":"{{msg.SDFdata}}","min":0,"max":"100","colors":["#00ff00","#00ff00","#00ff00"],"seg1":"","seg2":"","x":1630,"y":80,"wires":[]},{"id":"b13c73c9.9f708","type":"function","z":"e618aa97.f26d38","name":"Read Damper feedback","func":"//var msg = {};\nconst bacnet1 = global.get('bacnet');\n// Initialize BACStack\nvar client = bacnet1({adpuTimeout: 6000});\nvar state = msg.payloadFB;\n\nconst values = [\n {objectId: {type: 2, instance: 3001593}, values: [\n {property: {id: 85, index: 4294967295}, value: [{type: bacnet1.enum.ApplicationTags.BACNET_APPLICATION_TAG_REAL, value: state}], priority: 15}\n ]}\n];\n\nclient.readProperty('192.168.1.41', {type: 2, instance: 3001593}, 85, (err, value) => {\n msg.payloadFB = {value: value} ;\n node.send(msg);\n});","outputs":1,"noerr":0,"x":770,"y":80,"wires":[["1ee5f0e0.6f3f2f"]]},{"id":"b877569b.5ced58","type":"trigger","z":"e618aa97.f26d38","op1":"","op2":"","op1type":"pay","op2type":"pay","duration":"-1","extend":false,"units":"s","reset":"false","bytopic":"all","name":"","x":540,"y":80,"wires":[["b13c73c9.9f708"]]},{"id":"1ee5f0e0.6f3f2f","type":"change","z":"e618aa97.f26d38","name":"","rules":[{"t":"move","p":"payloadFB.value.values[0].value","pt":"msg","to":"SDFdata","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1090,"y":80,"wires":[["c8b549fe.09dd38","526bee26.8665c"]]},{"id":"526bee26.8665c","type":"function","z":"e618aa97.f26d38","name":"","func":"var FB = msg.SDFdata\nvar newMsg1 = {payload:FB};\nreturn newMsg1;\n","outputs":1,"noerr":0,"x":1570,"y":120,"wires":[["6e9c68a6.b89128","3f5b3d1c.a86762"]]},{"id":"c6af0b44.c8a828","type":"function","z":"e618aa97.f26d38","name":"","func":"var FB = msg.SDFdata\nvar newMsg = {payload:FB};\n\nreturn newMsg;\n\n\n","outputs":1,"noerr":0,"x":1110,"y":200,"wires":[["a3ebf5fc.611ed8"]]},{"id":"ec68a56d.e05008","type":"switch","z":"e618aa97.f26d38","name":"","property":"payload","propertyType":"msg","rules":[{"t":"cont","v":"false","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":570,"y":120,"wires":[["a2c5f888.2926d8"]]},{"id":"a2c5f888.2926d8","type":"change","z":"e618aa97.f26d38","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"OFF","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":120,"wires":[["bc41f21e.9827","8c5adeb9.17f91"]]},{"id":"6e9c68a6.b89128","type":"link out","z":"e618aa97.f26d38","name":"","links":["808786bd.c57148","a757ebdd.c414c8","fdd82983.a08d58"],"x":1675,"y":160,"wires":[]},{"id":"3e7ad4a6.119c1c","type":"debug","z":"e618aa97.f26d38","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":970,"y":40,"wires":[]},{"id":"c8b549fe.09dd38","type":"change","z":"e618aa97.f26d38","name":"","rules":[{"t":"set","p":"SDFdata","pt":"msg","to":"$round(SDFdata,2) & ' %'","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1390,"y":80,"wires":[["cc651cce.7061a","8c5adeb9.17f91","bc41f21e.9827"]]},{"id":"cc651cce.7061a","type":"debug","z":"e618aa97.f26d38","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1570,"y":40,"wires":[]},{"id":"3f5b3d1c.a86762","type":"ui_chart","z":"e618aa97.f26d38","name":"","group":"3c00de3b.40aeb2","order":2,"width":0,"height":0,"label":"Supply Damper Feedback","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"0","ymax":"100","removeOlder":"24","removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":1770,"y":120,"wires":[[]]},{"id":"9dc2a1a6.c5626","type":"ui_group","z":"","name":"Data Collection","tab":"3660b77a.a38508","disp":true,"width":"10","collapse":true},{"id":"7893a32b.67eadc","type":"ui_group","z":"","name":"Live Data View","tab":"f21fa3ea.1d205","order":1,"disp":true,"width":10,"collapse":true},{"id":"3c00de3b.40aeb2","type":"ui_group","z":"","name":"History","tab":"24348afd.85b066","disp":true,"width":"6","collapse":false},{"id":"3660b77a.a38508","type":"ui_tab","z":"","name":"Turn Data Collection On or Off","icon":"dashboard","order":3,"disabled":false,"hidden":false},{"id":"f21fa3ea.1d205","type":"ui_tab","z":"","name":"Live Data","icon":"dashboard","order":4,"disabled":false,"hidden":false},{"id":"24348afd.85b066","type":"ui_tab","z":"","name":"History","icon":"dashboard","order":4,"disabled":false,"hidden":false}]`

**Comment by dceejay** [comment]
In your get functions you are using `const bacnet1 = global.get('bacnet');` 
Are we sure that they are completely isolated instances in the two flows ? Or could one be making the request and the other be receiving the answer ?

**Comment by Navybrandon** [comment]
i didn't think about that, let me change the const on each function and try again.

**Comment by Navybrandon** [comment]
@dceejay well you found my oversight it seems. Thank you!

**Comment by Navybrandon** [comment]
@dceejay  after the flows continuously running the data still jumped flows. I will review everything to make sure uniqueness is in all flows.

**Comment by dceejay** [comment]
the other way may be to some sort of trigger signal to fire each request so they can't ever coincide.
