### ISSUE TITLE
Notifications not working on mobile devices

### ISSUE THREAD

**Issue by coolchip** [node-red/node-red-dashboard#536]
### What are the steps to reproduce?

Add a button node, attach a notification node. Press the button.

`[{"id":"b1e34f95.5b2b2","type":"ui_button","z":"d7e2ff7e.047ad","name":"","group":"c9128759.8b00c8","order":3,"width":0,"height":0,"passthru":false,"label":"TEST","tooltip":"","color":"","bgcolor":"","icon":"","payload":"ausführen?","payloadType":"str","topic":"Garagentor schließen","x":90,"y":1360,"wires":[["e991b22.c880b5","ecc791b3.84ee1"]]},{"id":"e991b22.c880b5","type":"debug","z":"d7e2ff7e.047ad","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":1360,"wires":[]},{"id":"ecc791b3.84ee1","type":"ui_toast","z":"d7e2ff7e.047ad","position":"bottom left","displayTime":"3","highlight":"","sendall":true,"outputs":0,"ok":"OK","cancel":"","raw":false,"topic":"topic","name":"name","x":270,"y":1400,"wires":[]},{"id":"c9128759.8b00c8","type":"ui_group","z":"","name":"Garage","tab":"dd77227.9038fe","disp":true,"width":"6","collapse":false},{"id":"dd77227.9038fe","type":"ui_tab","z":"","name":"Service","icon":"fa-wrench","disabled":false,"hidden":false}]`

### What happens?

In Chrome on a PC the notification appears. But no notification is visible on my mobile with Chrome.

### What do you expect to happen?

Appearing notification on the mobile. 

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.17.0
- [ ] Node-RED version: 0.20.8
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.11.3
- [ ] Platform/OS: Ubuntu 18.04.3 LTS
- [ ] Browser: Chrome

This happens since I installed the new v2.17.0. Before everything works as expected.

**Comment by dceejay** [comment]
try new 2.17.1 - fix for notifications in there.

**Comment by coolchip** [comment]
Now it's working again. Great. Thanks a lot!
