### ISSUE TITLE
Notifications broken

### ISSUE THREAD

**Issue by T0T4R4** [node-red/node-red-dashboard#537]
Is that a typo ? 'str' is undefined !
This breaks notifications popups. 

https://github.com/node-red/node-red-dashboard/blob/870382792f679b0a6bbf45b29ca7f6428e51623b/src/main.js#L516

![image](https://user-images.githubusercontent.com/1294511/66478823-9716bd80-eade-11e9-8d6c-2aded0a2bd49.png)

**Comment by dceejay** [comment]
Thanks for spotting that !.

**Comment by T0T4R4** [comment]
No worries, we're using the dashboard quite a lot...  :)

![image](https://user-images.githubusercontent.com/1294511/66623792-a9a10c00-ec30-11e9-9a6e-36b6767ef6a7.png)

**Comment by dceejay** [comment]
OMG - that's awesome...  shout when you name one Node-RED-exoplanet  !
