### ISSUE TITLE
ui_base unknown, flow no longer starts

### ISSUE THREAD

**Issue by jjssoftware** [node-red/node-red-dashboard#538]
Hi guys,

I've just started seeing a flow load failure after updating to 2.17.1.  

The problem appears to be related to `ui_base`, this is what the problem looks like in node red:

![Screenshot 2019-10-13 11:36:33](https://user-images.githubusercontent.com/536164/66714374-e8a89c00-edad-11e9-941e-4e14fb80c32b.png)

I've attempted to remove the existing installed node_modules and pull all packages afresh with `npm install --prefix /home/node-red/.node-red` which has successfully installed all dependencies again but the problem remains.

Any help is appreciated,

Many thanks
Joe

### What are the steps to reproduce?
I updated to / installed node red dashboard 2.17.1

### What happens?
A flow that used to load and work no longer loads. I see an error in the log that advises:
```
13 Oct 11:17:01 - [info] Waiting for missing types to be registered:
13 Oct 11:17:01 - [info]  - ui_base
```

### What do you expect to happen?
A working flow

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.17.1
- [ ] Node-RED version: 0.16.2
- [ ] node.js version: 6.9.1
- [ ] npm version: 3.10.8
- [ ] Platform/OS: linux 3.4.26
- [ ] Browser: Chromium 77.0.3865.90

**Comment by dceejay** [comment]
do you happen to know which version of dashboard node you were using before ?
the node.js version is now too old - you need at least node8 (pref 10) for latest dashboard.

**Comment by jjssoftware** [comment]
I was on 2.16.3 before this most recent upgrade to 2.17.1
Thanks for the pointer about node.js being old, I'll attempt to upgrade that now.

**Comment by jjssoftware** [comment]
Upgrading node.js got it going again, thank you, much appreciated.
