### ISSUE TITLE
Show/hide no

### ISSUE THREAD

**Issue by andydesjardins** [node-red/node-red-dashboard#541]
### What are the steps to reproduce?

1. Create some tabs
2. Name one tab that has the name of "Dual spaces tab"
3. Create a dasbhoard button that send to ui_control msg.playload.tabs.hide: [ "Dual_spaces_tab" ]
4. Create a dasbhoard button that send to ui_control msg.playload.tabs.show: [ "Dual_spaces_tab" ]
5. Deploy
6. Go to the UI
7. Use the buttons to show/hide the "Dual spaces tab"

### What happens?
The tab doesn't hide/show. I tried vith various names. At first, I tought it was the length of the names I was using. But it seems it's to have 2 spaces in the name. Maybe the code uses indexOf and is looking for the first space and replaces it with _ without doing a loop. Consider using split and join to replace spaces with _.

### What do you expect to happen?
The tab should hide and show properly

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.17.1
- [ ] Node-RED version: 1.0.0
- [ ] node.js version: 10.15.3
- [ ] npm version: 6.4.1
- [ ] Platform/OS: Windows 10 pro Enterprise 64 bits
- [ ] Browser: Chromse 77.0.3865.120 (Build officiel) (64 bits)

**Comment by dceejay** [comment]
Thanks - yes just needs a g added to the regex - will fix.

**Comment by andydesjardins** [comment]
Hello dceejay,

I updated Dashboard to 2.19 and Node-RED to 1.0.3, then I putted back names with double spaces, and I still have the same bug. Tabs with double spaces doesn't hide properly.

Is it possible to confirm that the fix is in version 2.19?

Thank you

**Comment by andydesjardins** [comment]
I downgraded to version 2.18 and it works fine. So the fix has been removed in 2.19

**Comment by dceejay** [comment]
Well the fix is in... so need to re-investigate.

**Comment by andydesjardins** [comment]
Ok, I upgraded again at 2.19. It works for now. I'm don't know what when wrong. I restarted Node-RED multiple times.

I'll try to reproduce it.

**Comment by dceejay** [comment]
seems to work for me - can you create a small flow that shows the problem that fails for you ?
This is my simple test 
```
[{"id":"b44b584c.bcc4e8","type":"ui_ui_control","z":"ea593186.4918d","name":"","events":"connect","x":340,"y":300,"wires":[[]]},{"id":"a4c8ce77.2d068","type":"ui_button","z":"ea593186.4918d","name":"","group":"8624d47b.b4f8f8","order":2,"width":0,"height":0,"passthru":false,"label":"to P1","tooltip":"","color":"","bgcolor":"","icon":"","payload":"Another Home Page","payloadType":"str","topic":"","x":150,"y":280,"wires":[["b44b584c.bcc4e8"]]},{"id":"50f27c81.92d324","type":"ui_button","z":"ea593186.4918d","name":"","group":"a654645f.90bbb8","order":2,"width":0,"height":0,"passthru":false,"label":"to P0","tooltip":"","color":"","bgcolor":"","icon":"","payload":"Home Page","payloadType":"str","topic":"","x":150,"y":320,"wires":[["b44b584c.bcc4e8"]]},{"id":"8624d47b.b4f8f8","type":"ui_group","z":"","name":"Default","tab":"b998a734.167558","disp":true,"width":15,"collapse":false},{"id":"a654645f.90bbb8","type":"ui_group","z":"","name":"Charts","tab":"2beb3e69.23fa52","disp":true,"width":"6"},{"id":"b998a734.167558","type":"ui_tab","z":"","name":"Home Page","icon":"dashboard","disabled":false,"hidden":false},{"id":"2beb3e69.23fa52","type":"ui_tab","z":"","name":"Another Home Page","icon":"dashboard","disabled":false,"hidden":false}]
```

**Comment by andydesjardins** [comment]
I can't reproduce it for now. Maybe I'm crazy.

**Comment by andydesjardins** [comment]
I have an idea. When I had the problem, I upgraded from 2.17 to 2.19 with the manage palette tool in Node-RED. Is it possible that npm skipped the 2.18 version while upgrading?
