### ISSUE TITLE
ui_slider cannot handle null as msg.payload

### ISSUE THREAD

**Issue by tt92** [node-red/node-red-dashboard#545]
### What are the steps to reproduce?

Use this demo flow and click on the inject button -> Node-RED will crash:

`[
    {
        "id": "c3982d44.7635a",
        "type": "ui_slider",
        "z": "fde1bc7.2c57d4",
        "group": "129af5cc.6c157a",
        "min": "0",
        "max": "10",
        "x": 1020,
        "y": 120,
        "wires": []
    },
    {
        "id": "12850883.914fb7",
        "type": "inject",
        "z": "fde1bc7.2c57d4",
        "name": "",
        "topic": "",
        "payload": "null",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 810,
        "y": 80,
        "wires": [["c3982d44.7635a"]]
    },
    {
        "id": "129af5cc.6c157a",
        "type": "ui_group",
        "z": "",
        "name": "Test",
        "tab": "7412138f.51d78c",
        "disp": true,
        "width": "6",
        "collapse": false
    },
    {
        "id": "7412138f.51d78c",
        "type": "ui_tab",
        "z": "",
        "name": "Test"
    }
]`

### What happens?

Node-RED crashes when you pass null as msg.payload to a ui_slider node.

### What do you expect to happen?

First idea was to ignore those inputs.

### Please tell us about your environment:

- Node-RED-Dashboard version: 2.17.1
- Node-RED version: 1.0.2

**Comment by dceejay** [comment]
If I try that flow I get an error but not a crash
```
8 Nov 15:18:23 - [error] [ui_slider:276b59d9.dc4546] TypeError: Cannot read property 'toString' of null
```

**Comment by tt92** [comment]
I took a closer look and figured that this is not the ui_slider's fault but a core issue.

It was discussed and fixed here: https://github.com/node-red/node-red/pull/2332 / https://github.com/node-red/node-red/commit/cb8deab1f99b5f7854450eb961d72587a556232a

So I will just wait for the 1.0.3 release.

Sorry for bothering :)

**Comment by dceejay** [comment]
no problem - I like the easy ones :-)
