### ISSUE TITLE
ui_text_input outputting incorrect value when in "time selector" mode

### ISSUE THREAD

**Issue by ryanjohnsontv** [node-red/node-red-dashboard#546]
### What are the steps to reproduce?
Inject a HH:mm:ss formatted value to a ui_text_input box with "time picker" mode selected then change the time in the dashboard.

### What happens?
This seems to cause the node to output the time difference of between the originally injected time and the new time entered.

### What do you expect to happen?
I would expect the node to output the newly entered time in milliseconds from midnight instead of milliseconds since the originally injected time. This issue is solved by changing to a standard text input mode on the node.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.17.1
- [ ] Node-RED version: 1.0.2
- [ ] node.js version: 10.16.3
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Linux 5.0.0-29-generic x64 LE
- [ ] Browser: Tested with Edge and Opera

I've attached a flow I'm working with that takes the input_datetime value from Home Assistant and injects it into the ui_text_input node at state change. Then when I change that time from the dashboard I send the value to a moment node to change it to HH:mm:ss to send back to the Home Assistant input_datetime call service.
`[
    {
        "id": "8be09326.b8e6",
        "type": "ui_text_input",
        "z": "baec6891.8462b8",
        "name": "",
        "label": "Alarm Time:",
        "tooltip": "",
        "group": "26e9592a.402186",
        "order": 17,
        "width": 0,
        "height": 0,
        "passthru": false,
        "mode": "time",
        "delay": "0",
        "topic": "",
        "x": 570,
        "y": 960,
        "wires": [
            [
                "7b4dd97c.7af2b8"
            ]
        ]
    },
    {
        "id": "6d773099.c7135",
        "type": "server-state-changed",
        "z": "baec6891.8462b8",
        "name": "Alarm Time",
        "server": "4ee348e3.abe878",
        "version": 1,
        "entityidfilter": "input_datetime.alarm_clock_time",
        "entityidfiltertype": "exact",
        "outputinitially": false,
        "state_type": "str",
        "haltifstate": "",
        "halt_if_type": "str",
        "halt_if_compare": "is",
        "outputs": 1,
        "output_only_on_state_change": true,
        "x": 370,
        "y": 960,
        "wires": [
            [
                "8be09326.b8e6"
            ]
        ]
    },
    {
        "id": "4d9a78f5.0e41b8",
        "type": "api-call-service",
        "z": "baec6891.8462b8",
        "name": "Sync Time",
        "server": "4ee348e3.abe878",
        "version": 1,
        "debugenabled": false,
        "service_domain": "input_datetime",
        "service": "set_datetime",
        "entityId": "input_datetime.alarm_clock_time",
        "data": "",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "",
        "output_location_type": "none",
        "mustacheAltTags": false,
        "x": 1070,
        "y": 960,
        "wires": [
            []
        ]
    },
    {
        "id": "7b4dd97c.7af2b8",
        "type": "moment",
        "z": "baec6891.8462b8",
        "name": "Current Time",
        "topic": "",
        "input": "payload",
        "inputType": "msg",
        "inTz": "America/Chicago",
        "adjAmount": "0",
        "adjType": "hours",
        "adjDir": "subtract",
        "format": "HH:mm:ss",
        "locale": "C",
        "output": "payload",
        "outputType": "msg",
        "outTz": "America/Chicago",
        "x": 750,
        "y": 960,
        "wires": [
            [
                "f93b23d6.a00fc"
            ]
        ]
    },
    {
        "id": "f93b23d6.a00fc",
        "type": "function",
        "z": "baec6891.8462b8",
        "name": "",
        "func": "msg.payload = { data: { \"time\":msg.payload} }\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 910,
        "y": 960,
        "wires": [
            [
                "4d9a78f5.0e41b8"
            ]
        ]
    },
    {
        "id": "26e9592a.402186",
        "type": "ui_group",
        "z": "",
        "name": "Scenes",
        "tab": "55369c29.7ac9d4",
        "disp": true,
        "width": "6",
        "collapse": true
    },
    {
        "id": "4ee348e3.abe878",
        "type": "server",
        "z": "",
        "name": "Home Assistant",
        "legacy": false,
        "hassio": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true
    },
    {
        "id": "55369c29.7ac9d4",
        "type": "ui_tab",
        "z": "",
        "name": "Alarm Panel",
        "icon": "dashboard",
        "order": 1
    }
]`

**Comment by dceejay** [comment]
In time mode it still expects the input to be in epoch milliseconds format. As is the output.

I don't have the nodes you have so can't use your flow. Here is my simple example
```
[{"id":"b5e2edc9.51748","type":"ui_text_input","z":"5051cb93.cf0d34","name":"","label":"Alarm Time:","tooltip":"","group":"278b5156.fa814e","order":17,"width":0,"height":0,"passthru":true,"mode":"time","delay":"0","topic":"","x":370,"y":100,"wires":[["89f54209.452c9"]]},{"id":"89f54209.452c9","type":"debug","z":"5051cb93.cf0d34","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":580,"y":100,"wires":[]},{"id":"13c9b2af.39f77d","type":"inject","z":"5051cb93.cf0d34","name":"5pm","topic":"","payload":"1573664400000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":60,"wires":[["b5e2edc9.51748"]]},{"id":"fab40c5e.559c3","type":"inject","z":"5051cb93.cf0d34","name":"now","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":100,"wires":[["b5e2edc9.51748"]]},{"id":"278b5156.fa814e","type":"ui_group","z":"","name":"Scenes","tab":"76ea3f8e.a7046","disp":true,"width":"6","collapse":true},{"id":"76ea3f8e.a7046","type":"ui_tab","z":"","name":"Alarm Panel","icon":"dashboard","order":1}]
```
