### ISSUE TITLE
Dashboard gauge sectors  RGB colors not working

### ISSUE THREAD

**Issue by Pietervierbergen** [node-red/node-red-dashboard#547]
### What are the steps to reproduce?
Attached flow
[flows (13).txt](https://github.com/node-red/node-red-dashboard/files/3883604/flows.13.txt)

### What happens?

Gauge sector color not changing within the set parameters, 

### What do you expect to happen?

Gauge should display sector color as defined 

### Please tell us about your environment:

- [2.18.0 ] Node-RED-Dashboard version:
- [1.0.2 ] Node-RED version:
- [10.17.0 ] node.js version:
- [6.11.3 ] npm version:
- [ Rasbian v9 stretch] Platform/OS:
- [any ] Browser:

**Comment by dceejay** [comment]
do you have a simple flow that shows the problem... we don't have access to the database you are using (nor do we want it) - so can you use a slider and  a single gauge configured to show the issue ?

**Comment by dceejay** [comment]
No worries - found it... fixed in master.

**Comment by Pietervierbergen** [comment]
Thanks Dave

Also add a test flow 

Regards

Sent from Mail for Windows 10

**Comment by dceejay** [comment]
aha - not quite fixed then :-)

**Comment by dceejay** [comment]
now it is...
