### ISSUE TITLE
[Suggestion] offline google material icons

### ISSUE THREAD

**Issue by Rotzbua** [node-red/node-red-dashboard#549]
### What are the steps to reproduce?

Watch network monitor in browsers dev mode.

### What happens?

Connection to google servers.

### What do you expect to happen?

No internet dependency.

### Please tell us about your environment:

Node-RED-Dashboard version: 2.18.0

### Possible solution

Serve google icon font like the other fonts bundled as offline font, e.g. fontawesome.

**Comment by dceejay** [comment]
The download for the material icons is huge... we are not going to bundle it for offline use.
A limited set of angular-material icons are built in.

**Comment by Rotzbua** [comment]
The official google material icon repo is huge, but not the font itself.

**Comment by dceejay** [comment]
How small ? (Given that users already complain about how slow the dashboard loads on mobile type devices...)

**Comment by Rotzbua** [comment]
> Given that users already complain about how slow the dashboard loads on mobile type devices...

Connecting to google servers also cost resources (dns resolve, tls handshake, rerender). I guess there would be no negative effect.


The size of the material icon font is about 60kb to 80kb depending on the source.

There are two sources for prebuilt font:

* official google repository https://github.com/google/material-design-icons/
* inofficial repository https://github.com/jossef/material-design-icons-iconfont

### official google repository

The font and css can be found under path `iconfont`. It can be copied from there.
https://github.com/google/material-design-icons/tree/master/iconfont

It is the official way for selfhosting:
https://google.github.io/material-design-icons/#setup-method-2-self-hosting

Sadly google has no interest on self hosted fonts, because they want our data. For those reasons the officially provided fonts are from 2016. A fork tries to fix this issue.

### inoffical repository

This fork provides newer icons and serves only necessary files which results in a much faster checkout.

The css and font can be copied from:
https://github.com/jossef/material-design-icons-iconfont/tree/master/dist

I use this repository in a private angular project and it works.
