### ISSUE TITLE
node-red-dashboard won't show anything 

### ISSUE THREAD

**Issue by cba16** [node-red/node-red-dashboard#55]
I used node-red-contrib-ui which worked fine and now I wanted to change to the newer node-red-dashboard but despite updating my nodes, when I open  http://localhost:1880/ui I can only see the top blue page whitout any graphs. Also on the bottom of the page it shows "The url cannot be loaded into an iframe." 
What is wrong? Any ideas?
Thanks

**Comment by Paul-Reed** [comment]
This is really a support question, better suited to either [Slack](https://node-red.slack.com/) or the [google node-red group](https://groups.google.com/forum/#!forum/node-red), rather than Github which is for tracking is for tracking software issues.

Paul

**Comment by dceejay** [comment]
Hi,
in general we prefer question on the mailing list, keeping this for actual code issues.
Have you fully uninstalled the contrib-ui ? Did you go back into the flow editor and allocate all the nodes to groups and tabs ? Do you have any existing link nodes that may need to be deleted and re-added ?

**Comment by cba16** [comment]
Oh okay I'll ask there then. Thanks! I have done all this yes, but even new nodes won't appear.
