### ISSUE TITLE
After update to 2.19.1 no animation (transition effect) on switch toggle with Material Design icons

### ISSUE THREAD

**Issue by midnight1979** [node-red/node-red-dashboard#552]
### What are the steps to reproduce?
Add switch component with custom Material Design icons 

### What happens?
When toggling switch (on/off) - there is no animation (transision). It was ok in previous version of dashboard.

### What do you expect to happen?
return transision effect to custom icons in switch component as it was in 2.18 version

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.19.1
- [x] Node-RED version: 1.0.3
- [x] node.js version: 10.15.2
- [x] npm version: 6.13.1
- [x] Platform/OS: Linux
- [x] Browser: Chrome

**Comment by Rotzbua** [comment]
Can you provide an example?

**Comment by dceejay** [comment]
looks ok to me 
![image](http://g.recordit.co/gl6F8miblt.gif)

maybe need to flush rebuild the local cache

**Comment by midnight1979** [comment]
> looks ok to me
> ![image](https://camo.githubusercontent.com/784de2e922441819e36743eb8ad43fab3075b843/687474703a2f2f672e7265636f726469742e636f2f676c3646386d69626c742e676966)
> 
> maybe need to flush rebuild the local cache

On your example icons just changing from one to another without any transition (transformation, animation). In previous version of dashboard was effect that was look like some morph or rotation on icon changing. And one icon smoothly changes to another. This effect worked with material design icons only. (with fa - not)

**Comment by midnight1979** [comment]
> Can you provide an example?

I'm afraid that i must to downgrade version of dashboard to make possible to repeat this interface effect, but I would not really like to do this "manipulations"... Maybe developers know why this situation is happened, especially there was some changes about material design icons in last (current) version of dashboard.

**Comment by dceejay** [comment]
OK right yes understand now.  As part of embedding the complete Material Icons webfont I stoped the default use of https://klarsys.github.io/angular-material-icons/ - which I thought had less icons. As the library is still there I shall revert it.

**Comment by midnight1979** [comment]
> OK right yes understand now. As part of embedding the complete Material Icons webfont I stopped the default use of https://klarsys.github.io/angular-material-icons/ - which I thought had less icons. As the library is still there I shall revert it.
> 
Great! Thanks!
It will be fixed in the new version of dashboard??

**Comment by dceejay** [comment]
pushed to master now - will be in next release

**Comment by midnight1979** [comment]
ok, thanks again!

**Comment by dceejay** [comment]
Now
![image](http://g.recordit.co/eb2K8IsKPc.gif)

**Comment by dceejay** [comment]
Ah - bit more testing - there are indeed more icons in the latest webfont vs the angular one - so we have to choose between the animation of the few - or the availability of more icons without animation.

**Comment by midnight1979** [comment]
> Now
> ![image](https://camo.githubusercontent.com/efa62d36b81d6b04a19c5b55597cb98e998e9e41/687474703a2f2f672e7265636f726469742e636f2f6562324b3849734b50632e676966)

Yes - that's it!!! 
why do you can't leave both of them (webfont + angular)???

**Comment by dceejay** [comment]
Well we can of course - but the docs are simpler if there is only one.

**Comment by midnight1979** [comment]
as an example - if i need to use angular icons, i must set "am-fire", and for material design it may be ma-fire... 
it is more flexible in my opinion, and i think that end-users will be happy of this posibility

**Comment by dceejay** [comment]
well currently it is "alarm_on" for angular-material-icons and "mi-alarm_on" for material-icons.
Not sure the animation is really a key feature though so at some point in the future I would prefer the default to be the larger set. But we would have to deprecate the current usage and make it a breaking change via a major version number bump.

**Comment by midnight1979** [comment]
Did I understand correctly that the animated icons will not appear soon?

**Comment by dceejay** [comment]
No. It’s already back in master.

**Comment by midnight1979** [comment]
ok! can close issue?

**Comment by dceejay** [comment]
not yet - as I want to debate about it some more and may to change it again. The only place the animations are visible are on the switch - and then only if both are angular material icons - not exactly a major feature or loss.

**Comment by midnight1979** [comment]
Yes, that's right, animation for switch component only. 
But with this feature it looks much better (as for me), interface looks more "live" (beautifil, smart etc). 
This is of course a minor improvement but all things are made up of little things...
Maybe it is not really impotant to most of dashboard end-users - i don't know... 

In fact - the using of standart icons for switches give animated (smoth) turn on/off effect, and maybe there is a way to make some options (in future releases of course) in component to set some animation settings for toggling action.

**Comment by midnight1979** [comment]
> ... major feature or loss.
why it can be loss??? can you explain shortly?

**Comment by dceejay** [comment]
on the one side we have 900 or so icons that only appear animated when used as pairs on a customised switch. We then have to explain to people why the other icons are animated (if they notice) and why the so called material icons doesn't have the full 1200 or so icons now available in the official set, but can if they add mi- ti the name.

On the other side - we have the full set, and simpler docs - but lose the animation.

**Comment by Prog72** [comment]
If it comes down to a straight choice between one or the other then I'd rather have a greater number of icons than a few animations.

**Comment by midnight1979** [comment]
I hope and believe that developers will find the "golden mean"!

**Comment by midnight1979** [comment]
Dave, do you know how many end users of the node-red-dashboard today?

**Comment by dceejay** [comment]
https://npm-stat.com/charts.html?package=node-red-dashboard&from=2017-01-01&to=2019-12-31

**Comment by midnight1979** [comment]
> https://npm-stat.com/charts.html?package=node-red-dashboard&from=2017-01-01&to=2019-12-31

Very impressive!!!! Great!

**Comment by Bond246** [comment]
Hello,

i would like to reopen this topic.
With the latest version the animations don't work anymore.

**Comment by dceejay** [comment]
OK - have added an animation in another way that seems to support many more of the icons including fa etc.

**Comment by Bond246** [comment]
With the new option my animations on a switch still not work.
![image](https://user-images.githubusercontent.com/8534418/107800785-83790800-6d5f-11eb-9aec-cbbb000dcb1e.png)

**Comment by dceejay** [comment]
In chrome I get
![s0JiDIakxt](https://user-images.githubusercontent.com/5375409/107801531-17df6c80-6d58-11eb-9f12-9d960ae31b70.gif)

**Comment by Bond246** [comment]
Hi,
Sorry seems that it was a caching issue or something like that. I tested with two browsers and is wasn't working but its fine now.

What was the problem with the material morph animation? I really liked it, it was funny.

**Comment by dceejay** [comment]
We support many more icons than just those original 70 or so. So we needed something that is more generic. As I said I’m happy to consider others if anyone prepared one.
