### ISSUE TITLE
external date in template first visible after going to an other page of the dashboard

### ISSUE THREAD

**Issue by stahchde** [node-red/node-red-dashboard#553]
### What are the steps to reproduce?
I added a template widget to show the weather forecast from wetter.com

`[{"id":"c8f6c9f8.9772d8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"424714fa.64f52c","type":"ui_template","z":"c8f6c9f8.9772d8","group":"dad99dd8.d8a87","name":"Wetter","order":1,"width":6,"height":5,"format":"<div id=\"wcom-b68f62c3c6cf0ff37791cbbec8eda20f\" class=\"wcom-default w300x250\" style=\"border: 1px solid rgb(204, 204, 204); background-color: rgb(255, 255, 255); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;\"><link rel=\"stylesheet\" href=\"//cs3.wettercomassets.com/woys/5/css/w.css\" media=\"all\"><div class=\"wcom-city\"><a style=\"color: #000\" href=\"https://www.wetter.com/deutschland/melsungen/DE0006867.html\" target=\"_blank\" rel=\"nofollow\" aria-label=\"Wetter Berlin\" title=\"Wetter Melsungen\">Wetter Melsungen</a></div><div id=\"wcom-b68f62c3c6cf0ff37791cbbec8eda20f-weather\"></div><script type=\"text/javascript\" src=\"//cs3.wettercomassets.com/woys/5/js/w.js\"></script><script type=\"text/javascript\">_wcomWidget({id: 'wcom-b68f62c3c6cf0ff37791cbbec8eda20f',location: 'DE0006867',format: '300x250',type: 'spaces'});</script></div>","storeOutMessages":true,"fwdInMessages":true,"templateScope":"local","x":350,"y":140,"wires":[[]]},{"id":"dad99dd8.d8a87","type":"ui_group","z":"","name":"Wetter","tab":"b9fd59d3.1d613","order":4,"disp":true,"width":"6","collapse":false},{"id":"b9fd59d3.1d613","type":"ui_tab","z":"","name":"Test","icon":"dashboard","disabled":false,"hidden":false}]`
### What happens?
When I open the Dashboard for the first time, the template is just a white box with a black frame and the only thing inside is a hyperlink to wetter.com forecast for my area. When I use the menu to go to an other page and then go back to the page with the template, the complete forecast is shown in the box.

Now, when everything looks good and I use the refresh function of my browsers, the empty box is back with just the link in it

<img width="448" alt="Bildschirmfoto 2019-12-06 um 17 58 12" src="https://user-images.githubusercontent.com/50795531/70353010-b4f96800-186c-11ea-83b1-044fd4980b1f.png">

<img width="414" alt="Bildschirmfoto 2019-12-06 um 17 58 30" src="https://user-images.githubusercontent.com/50795531/70353030-bfb3fd00-186c-11ea-93fa-7b52fb8b34ad.png">

### What do you expect to happen?
I have no idea how to solve this issue 

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.1
- [ ] Node-RED version: 1.0.3
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: Mac + iOS + Android
- [ ] Browser: Safari, Firefox, Chrome

**Comment by dceejay** [comment]
Hi I’m general we prefer initial how to type problems to be raised via the discourse forum so the widest possible community can help rather than rely on the core developers. 

Hopefully we can lol at it soon but it is somewhat busy running up to the year end

**Comment by stahchde** [comment]
Hi, I am with you. I asked in Homematic-Forum and they give me the advise to ask here. For me the topic is not urgent.

**Comment by dceejay** [comment]
Hi - the template when formatted looks like this
```
<div id="wcom-b68f62c3c6cf0ff37791cbbec8eda20f" class="wcom-default w300x250" style="border: 1px solid rgb(204, 204, 204); background-color: rgb(255, 255, 255); border-top-left-radius: 5px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; border-bottom-left-radius: 5px;">
   <link rel="stylesheet" href="//cs3.wettercomassets.com/woys/5/css/w.css" media="all">
   <div class="wcom-city"><a style="color: #000" href="https://www.wetter.com/deutschland/melsungen/DE0006867.html" target="_blank" rel="nofollow" aria-label="Wetter Berlin" title="Wetter Melsungen">Wetter Melsungen</a></div>
   <div id="wcom-b68f62c3c6cf0ff37791cbbec8eda20f-weather"></div>
   <script type="text/javascript" src="//cs3.wettercomassets.com/woys/5/js/w.js"></script>
   <script type="text/javascript">_wcomWidget({id: 'wcom-b68f62c3c6cf0ff37791cbbec8eda20f',location: 'DE0006867',format: '300x250',type: 'spaces'});</script>
</div>
```
There are at least 3 items in there withe the same id - `id: 'wcom-b68f62c3c6cf0ff37791cbbec8eda20f` - which is invalid javascript for a start...  so I would get that fixed up first.

**Comment by dceejay** [comment]
There is obviously some weird timing thing going on where the script int that page isn't fully loaded before it is needed. One hack fix is to retrigger the page on a new connection after a delay like thei
```
[{"id":"c0c7a18.71f216","type":"ui_ui_control","z":"62d100c3.7de61","name":"","events":"connect","x":320,"y":160,"wires":[["6a19c9ee.03ea28"]]},{"id":"cfaf5bd5.b1bba8","type":"change","z":"62d100c3.7de61","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":320,"wires":[["c0c7a18.71f216"]]},{"id":"6a19c9ee.03ea28","type":"delay","z":"62d100c3.7de61","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":320,"y":240,"wires":[["cfaf5bd5.b1bba8"]]}]
```

Really the better answer would be to dig into that fragment and split it so the script and style parts were loaded in one template as part of the page header and  then the actual template just refers to them - as they should then already be loaded.
