### ISSUE TITLE
Gauge Node had an issue, it's overlap with text node at the bottom.

### ISSUE THREAD

**Issue by wongnam** [node-red/node-red-dashboard#555]
### What are the steps to reproduce?
Import this flow :
`[{"id":"764efeaa.94e0a","type":"ui_gauge","z":"dceadd9d.ba53c","name":"","group":"c7daf7a2.12ddf8","order":6,"width":"6","height":"4","gtype":"wave","title":"Level","label":"%","format":"{{value}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":490,"y":2040,"wires":[]},{"id":"36b0e04e.d1302","type":"ui_text","z":"dceadd9d.ba53c","group":"c7daf7a2.12ddf8","order":7,"width":"6","height":"1","name":"","label":"text 2","format":"{{msg.payload}}","layout":"col-center","x":490,"y":2090,"wires":[]},{"id":"bbe9d6f6.5e4148","type":"ui_text","z":"dceadd9d.ba53c","group":"c7daf7a2.12ddf8","order":5,"width":"6","height":"1","name":"","label":"text 1","format":"{{msg.payload}}","layout":"col-center","x":490,"y":1990,"wires":[]},{"id":"c7daf7a2.12ddf8","type":"ui_group","z":"","name":"Water Tank","tab":"e4c93d0f.07007","order":9,"disp":true,"width":"6","collapse":false},{"id":"e4c93d0f.07007","type":"ui_tab","z":"","name":"Home","icon":"home","order":1}]`

### What happens?
The gauge Node has an issue, it's the overlap with the text node at the bottom. see picture.
### What do you expect to happen?
no overlap
### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.19.2
- [x] Node-RED version: 0.20.7
- [x] node.js version: v8.12.0
- [x] npm version: 6.9.0
- [x] Platform/OS: Pi3B+ Raspbian
- [x] Browser: Chrome on PC

### Screen shot
![image](https://user-images.githubusercontent.com/36041520/70387361-163d4a80-19d7-11ea-9715-82cc881b592a.png)

**Comment by dceejay** [comment]
Yes indeed it "*had*" an issue - already fixed.
If you updated recently you may need to flush your browser cache to ensure you have latest at the browser side.

![image](https://user-images.githubusercontent.com/5375409/70387852-140cc900-19a2-11ea-93c0-577de29023cd.png)
