### ISSUE TITLE
Cannot get "Tab" from config

### ISSUE THREAD

**Issue by cherob** [node-red/node-red-dashboard#556]
When I try to custom create a node, how do I get the tab from the settings.

Normally its possible to grab them with 'config.tab' or 'RED.nodes.getNode(config.group).config.tab'

In my case 'config.tab' is _not defined_ such as 'RED.nodes.getNode(config.group).config.tab'

How is it possible to get the tab inside the .js or the .html script?
My setup
- Node-RED version: v0.20.7
- Node-RED-Dashboard version: 2.19.2
- node.js version: v10.13.0
- Platform/OS: Windows
- Browser: Chrome

**Comment by dceejay** [comment]
Widgets won't have a tab until after they are assigned to a group - so unless they have been assigned it won't exist. A widget shouldn't care what tab it is on.
