### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by PierreScerri** [node-red/node-red-dashboard#559]
### What are the steps to reproduce?
Select Dashboard
### What happens?
Get 404 not found error
### What do you expect to happen?
Display dashboard
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.3
- [ ] Node-RED version: 1.0.3
- [ ] node.js version: 12.14.0
- [ ] npm version: ??
- [ ] Platform/OS: Hassio on RPi3 + Node-red add-on
- [ ] Browser: Safari and Chrome

Here is the add-on startup log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 6.0.2
 You are running the latest version of this add-on.
 System: HassOS 3.8  (armv7 / raspberrypi3)
 Home Assistant version: 0.104.1
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] node-red.sh: executing... 
patching file nodes/ui_base.html
Hunk #1 succeeded at 1243 (offset 712 lines).
audited 311 packages in 11.084s
9 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
[cont-init.d] node-red.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:11:58] INFO: Starting Node-RED...
> hassio-addon-node-red@ start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
19 Jan 20:12:06 - [info] 
Welcome to Node-RED
===================
19 Jan 20:12:06 - [info] Node-RED version: v1.0.3
19 Jan 20:12:06 - [info] Node.js  version: v12.14.0
19 Jan 20:12:06 - [info] Linux 4.19.93-v7 arm LE
19 Jan 20:12:08 - [info] Loading palette nodes
19 Jan 20:12:25 - [info] Dashboard version 2.19.3 started at /endpoint/ui
19 Jan 20:12:29 - [info] Settings file  : /etc/node-red/config.js
19 Jan 20:12:29 - [info] Context store  : 'default' [module=memory]
19 Jan 20:12:29 - [info] User directory : /config/node-red/
19 Jan 20:12:29 - [warn] Projects disabled : editorTheme.projects.enabled=false
19 Jan 20:12:29 - [info] Flows file     : /config/node-red/flows.json
19 Jan 20:12:30 - [info] Starting flows
19 Jan 20:12:31 - [error] [debug:State] Invalid JSONata expression: {{payload}}
19 Jan 20:12:33 - [info] Started flows
19 Jan 20:12:33 - [info] Server now running at http://127.0.0.1:46836/
19 Jan 20:12:33 - [error] [api-current-state:AUTO?] Entity could not be found in cache for entity_id: input_select.pool_pump
[20:12:33] INFO: Starting NGinx...
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
19 Jan 20:12:35 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
```

And part of the flow that uses the dashboard:

`[{"id":"989fff09.e4d7","type":"ui_text","z":"991a68b2.94e5f","group":"bca0e06c.c89328","order":1,"width":0,"height":0,"name":"","label":"Voltage","format":"{{msg.payload}} V","layout":"row-spread","x":740,"y":80,"wires":[]},{"id":"e8b94f6d.fd4b2","type":"ha-entity","z":"991a68b2.94e5f","name":"SDM230Voltage","server":"b5fa4db1.0c7bd8","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"sdm230voltage"},{"property":"device_class","value":""},{"property":"icon","value":""},{"property":"unit_of_measurement","value":"V"}],"state":"payload","stateType":"msg","attributes":[],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","x":500,"y":80,"wires":[["989fff09.e4d7"]]},{"id":"9cb1c25.8ad76c","type":"function","z":"991a68b2.94e5f","name":"Voltage","func":"var rawData = new ArrayBuffer(4);\nvar intView = new Uint16Array(rawData);\nvar fltView = new Float32Array(rawData);\n\nintView[0] = msg.payload[1]; //low\nintView[1] = msg.payload[0]; //high\n\nmsg.payload = parseFloat(fltView[0].toFixed(0));\nmsg.topic = \"voltage\";\n\nnode.status({fill:\"blue\",shape:\"ring\",text:msg.topic + \":\" + msg.payload});    \n\nreturn msg;","outputs":1,"noerr":0,"x":340,"y":80,"wires":[["e8b94f6d.fd4b2"]]},{"id":"8d8a2d2d.cb27c","type":"modbus-read","z":"991a68b2.94e5f","name":"SDM 230 Voltage","topic":"","showStatusActivities":true,"logIOActivities":false,"showErrors":true,"unitid":"1","dataType":"InputRegister","adr":"0","quantity":"2","rate":"10","rateUnit":"s","delayOnStart":false,"startDelayTime":"","server":"f921e0ff.bef308","useIOFile":false,"ioFile":"","useIOForPayload":false,"x":140,"y":80,"wires":[["9cb1c25.8ad76c"],[]]},{"id":"bca0e06c.c89328","type":"ui_group","z":"","name":"SDM230","tab":"c65e28f7.b390d8","order":1,"disp":true,"width":"6","collapse":false},{"id":"b5fa4db1.0c7bd8","type":"server","z":"","name":"Home Assistant","legacy":false,"hassio":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true},{"id":"f921e0ff.bef308","type":"modbus-client","z":"","name":"Serial_9600_8_N_1","clienttype":"serial","bufferCommands":true,"stateLogEnabled":false,"tcpHost":"127.0.0.1","tcpPort":"502","tcpType":"DEFAULT","serialPort":"/dev/ttyUSB0","serialType":"RTU-BUFFERD","serialBaudrate":"9600","serialDatabits":"8","serialStopbits":"1","serialParity":"none","serialConnectionDelay":"100","unit_id":"1","commandDelay":"200","clientTimeout":"2000","reconnectOnTimeout":true,"reconnectTimeout":"5000","parallelUnitIdsAllowed":false},{"id":"c65e28f7.b390d8","type":"ui_tab","z":"","name":"Modbus","icon":"dashboard","order":1,"disabled":false,"hidden":false}]`

**Comment by dceejay** [comment]
You don't say where you are trying to browse to ... it should be (based on that log) - /endpoint/ui.
Also there seem to be errors in that flow - Some errrors may indeed cause the dashboard not to display (but in the flow editor it usually report "Flow not running due to ..." type message on deploy.)

**Comment by PierreScerri** [comment]
Yes it is /endpoint/ui.
This was working a few revisions back - can't remember which.
What errors are you referring to?
Flow deploys without any warnings.

**Comment by dceejay** [comment]
The two error lines 

```
19 Jan 20:12:31 - [error] [debug:State] Invalid JSONata expression: {{payload}}

19 Jan 20:12:33 - [error] [api-current-state:AUTO?] Entity could not be found in cache for entity_id: input_select.pool_pump

```

and I'm not sure where that NGINX log line is coming from ? is that Hassio or nginx on top of Hassio ?

We don't use Hassio - so you may need to ask on their forum also.

**Comment by PierreScerri** [comment]
I have no idea where the first error is coming from.  I'll have to disable flows one at a time to weed it out.
The second error is from an input-select entity in Hassio.  It throws that error when node red starts and thereafter it works perfectly.

NGINX is an add-on on Hassio.
