### ISSUE TITLE
level type gauge redraws on update when ui_control is used

### ISSUE THREAD

**Issue by kmarhold** [node-red/node-red-dashboard#561]
What happens:

When ui_control is used to style the level gauge and the gauge is updated with a new value, it is animated to rise from zero to the new value. Because the animation takes a while, if values arrive too fast, the gauge becomes useless, but this should not happen anyway.

What should happen:

The gauge should be animated to increase/decrease to the new value. This is how it works when ui_control isn't being used.

**Comment by dceejay** [comment]
Do you have  a small example flow that shows this problem ?
You don't have to send the ui_control message with every reading - just to set it up.

**Comment by dceejay** [comment]
any update - or Ok to close ?
