### ISSUE TITLE
Chart cubic interpolation

### ISSUE THREAD

**Issue by i8beef** [node-red/node-red-dashboard#562]
### What are the steps to reproduce?

Add a chart widget, would be nice to have a few options exposed by chart.js.

### What happens?

Unable to select cubic interpolation which provides a nicer curve estimate than bezier.

### What do you expect to happen?

Expose chart.js supported cubic interpolation.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.3
- [ ] Node-RED version: 1.0.3
- [ ] node.js version: Docker version
- [ ] npm version: Docker version
- [ ] Platform/OS: Linux
- [ ] Browser: All

**Comment by knolleary** [comment]
As the issue template says, please direct feature requests to the forum. It is not a bug if you are saying the Node-RED Dashboard doesn't provide a feature you want it to have.

**Comment by i8beef** [comment]
Oh sorry, I just saw the "this is only for node-red-dashboard problems" and thought the readme was just saying don't put node-red issues here. I guess Ill put this on the forum.
