### ISSUE TITLE
Chart color selection on incoming message

### ISSUE THREAD

**Issue by i8beef** [node-red/node-red-dashboard#563]
### What are the steps to reproduce?

Create a chart with multiple series inputs, but without manually controlling the order of delivery.

### What happens?

Unable to set a static color choice to the series as it appears to be related to order of delivery?

### What do you expect to happen?

Allow for incoming message topics to set a color choice that overrides the "defaults" in the node itself.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.3
- [ ] Node-RED version: 1.0.3
- [ ] node.js version: Docker version
- [ ] npm version: Docker version
- [ ] Platform/OS: Linux
- [ ] Browser: All

**Comment by savek-cc** [comment]
What happened to this feature?

**Comment by dceejay** [comment]
It is still not possible to do this, apart from by sending null values with the correct topics, in the correct order you wish on start. This thread then shows a nice "trick' to show how to change the one in use dynamically- but switching the topic (and thus the color) based on the payload - https://discourse.nodered.org/t/dashboard-line-chart-color/15380/2

**Comment by i8beef** [comment]
I switched over to Grafana personally. Its awesome that dashboard has these chart types, as it's not a trivial ask for graphing capabilities like this, but I really just outgrew what was here. Someone made a node based on vega (https://vega.github.io/vega/examples/) which seemed super promising, but I didn't have time to learn an entire language to make a chart.

**Comment by savek-cc** [comment]
@i8beef thanks for the hint - will probably also be looking at influxdb+grafana (also as an archive of knx/automation messages)
