### ISSUE TITLE
Input message with payload = null causes exception

### ISSUE THREAD

**Issue by bartbutenaers** [node-red/node-red-dashboard#565]
Hey Dave (@dceejay),

### What are the steps to reproduce?
Inject a message into a custom UI node, with ```msg.payload = null```.

### What happens?
Unfortunately nothing happens...

### What do you expect to happen?
 I had expected the message to arrive on client side (in the ```$scope.watch("msg"```) but that doesn't happen.

While debugging in Chrome, I came across this exception:

![image](https://user-images.githubusercontent.com/14224149/74612208-81a44680-5103-11ea-8186-7d71aac81778.png)

Which seems to be caused by following code snippet:

![image](https://user-images.githubusercontent.com/14224149/74612225-9c76bb00-5103-11ea-8172-f2405f08f189.png)

So when msg.payload = null
Then the conversion = null
Then the conversion.update will cause an exception ...

Perhaps not normal that there is no payload, but would be nice if you could e.g. show a warning or just continue or ...

Thanks!!!
Bart

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.3
- [ ] Node-RED version: v1.0.3
- [ ] node.js version: v12.15.0
- [ ] npm version: v12.15.0
- [ ] Platform/OS: Raspbian
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
convert is a function defined by the node... so really it is up to them to handle it correctly.
(admittedly some of the core ui nodes don't - or rather they handle an `undefined` null ok - but not if you set `msg.payload=null;` - so yes they need to be fixed... but in the case of a custom ui widget - it is up to that widget to handle it correctly.

**Comment by bartbutenaers** [comment]
Ok Dave, thanks for the feedback!!
