### ISSUE TITLE
A group will be deleted when being resized to smaller than widget width

### ISSUE THREAD

**Issue by caozuba** [node-red/node-red-dashboard#566]
### What are the steps to reproduce?
In a dashboard group have a widget whose width is equal to Group width
Change the group width to smaller before changing the widget width 
### What happens?
The group will be deleted and all the widgets inside it will belong to nowhere
Can not Ctrl+Z
### What do you expect to happen?
Block the user to change the width of group to smaller than a 100% width widget
Or tell user know, or auto decrease widget width
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.4
- [ ] Node-RED version: 1.0.3
- [ ] node.js version: 12.14.1
- [ ] npm version: 6.13.7
- [ ] Platform/OS: Raspian, Remote from Windows 
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Which version of dashboard are you using ?
If I try this (set button to 6 wide - then shrink group to 5) I get a warning triangle on the node
![image](https://user-images.githubusercontent.com/5375409/75094586-898d3c00-5584-11ea-93a3-076cb02d4eb9.png)
If I go ahead and deploy I still see the button OK.
If I edit the node I can see the size is invalid (red border)
![image](https://user-images.githubusercontent.com/5375409/75094596-a9246480-5584-11ea-9719-a0b9f5609f32.png)

**Comment by caozuba** [comment]
@dceejay Thank you for replying. Actually now I also can not recreate the issue, it works as you described above. But I did have the problem, maybe it only occurs under a specific condition.
