### ISSUE TITLE
How to make json format and press button then send json via mqtt?

### ISSUE THREAD

**Issue by varunsavita** [node-red/node-red-dashboard#568]
I have 4 string data 
![image](https://user-images.githubusercontent.com/42342764/75603474-a1b90a00-5af4-11ea-98bf-2d3cf6e9b480.png)
I have to send data in JSON format via MQTT whenever press button.
But I'm not able to make JSON format.

**Comment by dceejay** [comment]
As per the issue template you have managed to delete - we prefer general questions via the slack channel or on the discourse forum. Leaving the Issue list for actual bug in the code. Creating things in JSON format really is javascript 101 and can be found in many tutorials on Google.
eg - https://www.w3schools.com/js/js_json.asp
