### ISSUE TITLE
Is it possible to use multi dashboard with one node-red?

### ISSUE THREAD

**Issue by varunsavita** [node-red/node-red-dashboard#571]
Actually, I installed node-red in the cloud.
I have multi-client so I want to install one node-red in the cloud with multi-client.
Please guide me.

**Comment by knolleary** [comment]
Hi @varunsavita 

the issue template you were shown, but have deleted, said this:

> This issue tracker is for problems with the Node-RED-Dashboard only.
> 
> If your issue is:
>   - a general 'how-to' type question,
>   - a feature request or suggestion for a change
> 
>  please use the Dashboard category in the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).


When you ask on the forum, you'll need to explain a bit more what you mean by 'multi dashboard'.

Node-RED Dashboard is not a multi-user dashboard. You create one dashboard and anyone who views it sees the same thing.
