### ISSUE TITLE
colour picker breaks when setting it to "000000"

### ISSUE THREAD

**Issue by RealDekkia** [node-red/node-red-dashboard#572]
### What are the steps to reproduce?
Inject the string "000000" into the colour picker node.

### What happens?
The color in the UI is correctly set to black, but when trying to change the color to something else in the UI it does not work. The little circle does move around but the value stays 000000.

### What do you expect to happen?
To be able the change the color away from black

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.4
- [ ] Node-RED version: 1.0.4
- [ ] node.js version: 11.9.0
- [ ] npm version: 6.5.0
- [ ] Platform/OS: Windows 10
- [ ] Browser: Tested with Chrome, Vivaldi and Firefox

Edit: this bug only exists with the round picker. The square one works fine

**Comment by dceejay** [comment]
Not sure it's a bug - when you set it to 000000 it sets the brightness to 0 - so you need to adjust that slider also - and then colour will appear ok


![image](https://user-images.githubusercontent.com/5375409/76704332-26e51700-66d0-11ea-95ef-02b337fd86d2.png)

**Comment by RealDekkia** [comment]
I'd still consider it a bug, because if I disable the brightness-slider I have no way to get the colour picker out of the 000000-state.

**Comment by dceejay** [comment]
so what would a fix be ? to not let you inject 000000 if brightness slider is not visible ?

**Comment by RealDekkia** [comment]
Maybe setting the brightness based on how close the marker is to the center could work?
When setting the color to 000001 the marker is at the same location as when setting it to 0000FF.
Shouln't it be closer to the center when set to 000001 since it's supposed to be darker?

In addition to that, give the user the option to select if the center color is Black or White. I can't think of a use-case where one would need both.

![image](https://user-images.githubusercontent.com/20802274/76789818-e49a0380-67bd-11ea-9495-ac9fc2285b54.png)
![image](https://user-images.githubusercontent.com/20802274/76789806-dc41c880-67bd-11ea-9b87-e6f2e7937be9.png)
![image](https://user-images.githubusercontent.com/20802274/76789838-efed2f00-67bd-11ea-8027-a407d65c91f6.png)

**Comment by dceejay** [comment]
yeah - sadly this was the "best" angular 1 color picker I found at the time.
I'm sure there may be others that could be made into widgets.

Do you think forcing the lightness slider to be always visible in this mode (and the hue one in "sqaure" mode) would make more sense ?

**Comment by RealDekkia** [comment]
I think this would be the easiest fix.
However, users might be confused when a slider is enabled automatically.

**Comment by dceejay** [comment]
Let's try that and see how it goes.
It will only be enabled by default initially - if the user then sets it off that it up to them.
