### ISSUE TITLE
Dashboard freezes in Brave browser

### ISSUE THREAD

**Issue by bneumann** [node-red/node-red-dashboard#573]
### What are the steps to reproduce?
Use Brave browser and go here (my local server) https://sensors.newbucket.de

### What happens?
Brave becomes unresponsive and (if you are lucky) asks you if you want to close the app. My assumption is, that it is something with the antitracker stuff inside Brave, but I can't switch them of because the page hangs completely.

### What do you expect to happen?
That it works like in Firefox, Chrome and even Edge and I can still use the website

### Please tell us about your environment:
Windows 10 client with latest brave
My Server is an Ubuntu 18.04 LTS x86_64 with a 4.15.0-47-generic running the latest docker-ce version.
Node-red runs inside a docker compose (nodered/node-red:latest) so I fill in the details from the docker file here:
- [x] Node-RED-Dashboard version: 2.19.4
- [x] Node-RED version: 1.0.4
- [x] node.js version: 10.19.0
- [ ] npm version: ?
- [x] Platform/OS: alpine
# Client:
- [x] Browser: Brave

**Comment by dceejay** [comment]
Brave is not a browser we test with. As it works in the major browsers, including others based on Chromium, and you seem to think it is an issue inside the Brave browser I'm not sure what we can do to fix it ?

**Comment by dceejay** [comment]
update - Ok have left it running since 12:39 - now 17:40 - still seems good for me.
(OK so I'm on a Mac  with a clean install of Brave - but... )

**Comment by dceejay** [comment]
err - I have just noticed you say you have node.js 4.9.1 ? and npm2 - those are both well out of date and haven't been supported for a long time... you need at least node 10.x  and pref 12.x LTS...

**Comment by bneumann** [comment]
> Brave is not a browser we test with. 
I thought as much, still thought it might be of interest. 

> err - I have just noticed you say you have node.js 4.9.1 
Man I am not awake today, sorry bout that I looked up the wrong dockerfile. I am using the [latest node-red](https://hub.docker.com/layers/nodered/node-red/latest/images/sha256-f3864508c0c6eaa63b3ac52c375c60185cc0f65a05fe35b7f7eb8e082d46983b?context=explore) so it is of course node 10.19.0 ! I'll update the issue.

Weird enough it runs smooth on my phone as well (also Brave). I cleaned out almost all history and cookies and used incognito mode and it still freezes the whole process. So if you can't reproduce it might as well be on my side here.

**Comment by bneumann** [comment]
So I removed my Local BraveSoftware Cache and started a clean copy. And tadaaa it works. Sorry for the issue, could have tried that in the first place. Closing and thanks for the response

**Comment by bneumann** [comment]
Ok I found the culprit. I disabled my fingerprinting options in Brave:
![image](https://user-images.githubusercontent.com/2605131/76708797-ec906f80-66f9-11ea-9e78-766e76ff0b68.png)
If I set it back to "only block cross site", it works. Maybe someone stumbles across this too. Why is there even fingerprinting on?

**Comment by dceejay** [comment]
as you have closed this I have removed the url to the site you posted above. (just in case etc)
