### ISSUE TITLE
[enhancement] allow scroll wheel to move slider

### ISSUE THREAD

**Issue by chaos511** [node-red/node-red-dashboard#575]
### What are the steps to reproduce?
1) Create a dashboard with a slider
2) Hover over slider and scroll with the scroll wheel on a mouse
### What happens?
If the page is short nothing if the page is tall the whole page scrolls up/down
### What do you expect to happen?
The slider to move like the windows volume slider
### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.4
- [ ] Node-RED version: 0.20.7
- [ ] node.js version: v8.11.1
- [ ] npm version: 6.9.0
- [ ] Platform/OS: Raspberry pi/Raspbian-9
- [ ] Browser: Chrome 80.0.3987.149

**Comment by dceejay** [comment]
Pushed a new feature to master branch on gitub.
