### ISSUE TITLE
Can't move widgets in dashboard layout in 2.20

### ISSUE THREAD

**Issue by GeoffNT** [node-red/node-red-dashboard#577]
I've just updated to 2.20 and now can't move or adjust the size of any widgets in the dashboard layout page. I can lock and unlock the widget but nothing else. Also the widget size in the dashboard layout edit page is not the same as it is displaying on the actual dashboard. This is using Chrome on Windows 10 PC.

**Comment by dceejay** [comment]
have you re-flushed your client side browser cache ? 
Is there anything in your browser client console log ?

**Comment by GeoffNT** [comment]
I'm clearing the cache as we speak but this is what I mean by the display issue. The ui node shows this item at 6x1 and it displays on the dashboard ui as 6x1 but in the dashboard layout page it shows as 3x1 and I can't move or stretch it. 
![Dash_UI](https://user-images.githubusercontent.com/62440007/78502445-300a5680-7759-11ea-8c66-da3517ff08ff.jpg)

**Comment by GeoffNT** [comment]
2.21.0 seems to have fixed this. Thanks very much.

**Comment by jensrossbach** [comment]
I still have this issue with 2.26.1.

**Comment by dceejay** [comment]
This issue was closed last April. Please open a new one - filling in the required info so that we can recreate it.

**Comment by mohdxb** [comment]
> I still have this issue with 2.26.1.

I fixed this issue by disabling the cache from the browser.
