### ISSUE TITLE
Tooltip in dashboard ui_text

### ISSUE THREAD

**Issue by krikkoo** [node-red/node-red-dashboard#578]
I would kindly ask if it possible to add the tooltip feature in the dashboard ui_text.
I tried to do it, I successfully added in the control but it doesn't work.

Sorry for stupid request but in my project could bring a nice aspect in mobile version.

![Schermata 2020-04-10 alle 14 59 12](https://user-images.githubusercontent.com/43918347/78992821-7e926900-7b3c-11ea-8699-c65676dfe322.png)

Thank you in advance

**Comment by dceejay** [comment]
you're correct - currently the tooltip has to be static text - we can look to add the ability.
