### ISSUE TITLE
Formating values in charts?

### ISSUE THREAD

**Issue by codmpm** [node-red/node-red-dashboard#58]
Will it be possible to format the values displayed by the charts?

I can not format the incoming data as it is needed to render the chart correctly but it would be nice to allow formating the output with a `value format` like the gauges offer.

Furthermore will it be possible to format the data to a local value? Like `25,5 °C`? I see that Angular Filters offer [i18n](https://docs.angularjs.org/guide/i18n) but dont know if these are pressent in node-red/node-red-dashbaord and of course not how to use them ;-)

Thank you so much for your hard work. Many thanks!

Cheers,
pm

**Comment by dceejay** [comment]
Hi - which values are you talking about ? The y-axis scale ? or the hover over ?
We use https://angularjs-nvd3-directives.github.io/angularjs-nvd3-directives/line.chart.html
So not sure yet how exposed that would be.

**Comment by codmpm** [comment]
The y-axis is no problem thanks to you and the 2.0.2 release.
I am talking about the values in the hover.

In generel I think it would be nice to format numbers printed on the ui elements. As for i18n like my example.

**Comment by dceejay** [comment]
Hi,
ok - will have a look - as I hinted above the library we use does not appear to support i18n - so we won't be able to add that, though some form of reformating may be possible.

**Comment by codmpm** [comment]
Don't be to hard on this one. i18n for node-red-dashboard in generel would be nice sometime. But formating will help till then :-)

Thank you!

**Comment by dceejay** [comment]
Will leave this until #38 is resolved... as it may mean a change in underlying library.

**Comment by dceejay** [comment]
Going to close this one now as we are (nearly) moved to charts.js library... so will wait for someone to open a new version.
