### ISSUE TITLE
After cloning project to new env, every ui node shows 'invalid properties - width'

### ISSUE THREAD

**Issue by mhamiltonj** [node-red/node-red-dashboard#582]
### What are the steps to reproduce?
 * Enable projects in nodred  settings.js
 * Create a project with UI nodes in it. 
 * Push project to remote git repo
 * Import project to clean enviroment
 * Install dependencies

### What happens?
All ui nodes show  
'invalid properties -width'

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.19.4
- [ ] Node-RED version: 1.0.5
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: docker
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
where do they show that ? can you add a screenshot ?

**Comment by mhamiltonj** [comment]
> 
> 
> where do they show that ? can you add a screenshot ?

Little red triangle appears on each node (the normal graphical error indication) if you hover over it the error details appear. Sorry, I just fixed them all, forgot to take a screenshot. Easy enough fix I've found, open the settings for each node and click done, it's just a bit tedious with lots of nodes.

**Comment by dceejay** [comment]
thanks

**Comment by mhamiltonj** [comment]
It doesn't actually seem to prevent the nodes functioning, it just means they all look like they aren't configured correctly, and when you try to deploy you get a long list of warnings, ignore them and everything seems to behave as normal.

**Comment by dceejay** [comment]
yes - less than ideal. but never seen or heard of it before so hopefully easy to re-create or could be a pain.

**Comment by mhamiltonj** [comment]
New docker container, with non-permenant volumes (so no data from the old enviroment should have come accross). NR, host OS and Docker versions all the same.
Importing by cloning the project from gitlab (I suspect this might be due to the NR projects feature, since it's still in beta), then reinistalling dependencies:
```{
    "node-red-contrib-calc": "1.0.1",
    "node-red-contrib-dashboard-bar-chart-data": "0.9.6",
    "node-red-contrib-influxdb": "0.4.0",
    "node-red-contrib-maxcube2": "0.3.1",
    "node-red-contrib-moment": "3.0.3",
    "node-red-contrib-os": "0.1.7",
    "node-red-contrib-simple-gate": "0.2.4",
    "node-red-contrib-simplejs": "0.0.4",
    "node-red-contrib-ui-led": "0.3.1",
    "node-red-contrib-ui-level": "0.1.24",
    "node-red-dashboard": "2.19.4",
    "node-red-node-ping": "0.1.0",
    "node-red-node-ui-lineargauge": "0.3.6"
}

**Comment by dceejay** [comment]
in fact you just need to refresh the browser one time and it clears them all without having to edit. It is obviously something timing wise with when the validation of fields gets done versus the actual new nodes being loaded correctly first time through. I'll have a deeper look but it's such an edge case I'm not really concerned about it.

**Comment by mhamiltonj** [comment]
OK, that's fine. Thanks for looking.

**Comment by pbarreneche** [comment]
Encontre una manera mucho mas facil, muy facil, demaciado facil!
hay que entrar a la seccion dashboard y ahi hay que poner editar layout y listo! desaparecen todos juntos!
