### ISSUE TITLE
Pass though msg if payload matches new state

### ISSUE THREAD

**Issue by Nachtfalke49** [node-red/node-red-dashboard#583]
### What happens?
Pass though msg if payload matches new state is not working. If the switch is already set to On, On will still be switched through if an On is sent again with mqtt in. A time loop after the switch starts again and again.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.20.0
- [ ] Node-RED version: 1.0.4
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Are you able to provide an example flow that demonstrates the issue?

**Comment by dceejay** [comment]
I guess the label should read  "Pass though msg if payload is a valid state" rather than new. The input has to match both the type and value eg string 0 in order to be accepted.

**Comment by Nachtfalke49** [comment]
This is my Flow:

[{"id":"11b5b5bc.e2fa7a","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"aa7f97d.1d5ee68","type":"ui_switch","z":"11b5b5bc.e2fa7a","name":"","label":"Bad","tooltip":"","group":"cfca06b3.bf9728","order":7,"width":3,"height":1,"passthru":true,"decouple":"false","topic":"shellies/shelly1-2C0C13/relay/0/command","style":"","onvalue":"on","onvalueType":"str","onicon":"","oncolor":"","offvalue":"off","offvalueType":"str","officon":"","offcolor":"","x":450,"y":240,"wires":[["5dcaa62.1838958","a5117944.72b448","3666eef3.520782"]]},{"id":"161db61b.09d0ea","type":"mqtt in","z":"11b5b5bc.e2fa7a","name":"Bad state","topic":"shellies/shelly1-2C0C13/relay/0","qos":"0","datatype":"auto","broker":"6c1b92.8caa047","x":280,"y":300,"wires":[["aa7f97d.1d5ee68","5dcaa62.1838958"]]},{"id":"234e0c80.c54c74","type":"stoptimer2","z":"11b5b5bc.e2fa7a","duration":"1","durationType":"num","units":"Minute","payloadtype":"str","payloadval":"off","name":"1 min.","x":750,"y":240,"wires":[[],["5dcaa62.1838958","3666eef3.520782"]]},{"id":"5dcaa62.1838958","type":"function","z":"11b5b5bc.e2fa7a","name":"LED","func":"msg.color = (msg.payload === \"on\")?\"lime\":\"black\";\nreturn msg;","outputs":1,"noerr":0,"x":950,"y":320,"wires":[["2c63249.a647fdc"]]},{"id":"2c63249.a647fdc","type":"ui_text","z":"11b5b5bc.e2fa7a","group":"cfca06b3.bf9728","order":8,"width":1,"height":1,"name":"Bad LED","label":"","format":"<font color={{msg.color}} ><i class=\"fa fa-circle\" style=\"font-size:24px;\"></i></font>","layout":"row-center","x":1200,"y":320,"wires":[]},{"id":"a5117944.72b448","type":"switch","z":"11b5b5bc.e2fa7a","name":"on","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"on","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":610,"y":240,"wires":[["234e0c80.c54c74"]]},{"id":"3666eef3.520782","type":"mqtt out","z":"11b5b5bc.e2fa7a","name":"","topic":"","qos":"","retain":"","broker":"6c1b92.8caa047","x":810,"y":60,"wires":[]},{"id":"cfca06b3.bf9728","type":"ui_group","z":"","name":"Licht","tab":"5fee4e37.e97d2","order":1,"disp":true,"width":"4","collapse":false},{"id":"6c1b92.8caa047","type":"mqtt-broker","z":"","name":"MQTT","broker":"192.168.1.50","port":"1885","clientid":"","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"5fee4e37.e97d2","type":"ui_tab","z":"","name":"Home","icon":"dashboard","order":1,"disabled":false,"hidden":false}]

**Comment by dceejay** [comment]
and if you add an rbe node in front of the mqtt out node ?

**Comment by Nachtfalke49** [comment]
Oh yes, now it works with rbe. Thank you dceejay!

But that should also work with Pass through msg if payload matches new state or?

**Comment by dceejay** [comment]
as I said above the label is slightly misleading... need to fix that.

**Comment by akalikin1** [comment]
Hello, now I am on 2.30 version, and label is still "new state" instead of "valid state"
