### ISSUE TITLE
Feature Request - Labels for Line Chart Series

### ISSUE THREAD

**Issue by pacmac** [node-red/node-red-dashboard#584]
Hope you can enable the labels for line charts, as my lines now represent bluetooth sensors with mac IDS, each sensor is associated with a specific location, and this location would be the series label.

Presently the design of line charts is to use the series ID for the label in line charts, and this has a limitation that the end user sees the mac address of the sensor instead of it's associated location, and the mac id is meaningless to an end user, what they need to see is the location, i.e. Upstairs, Downstairs, Outside etc.

If I use the location rather than the mac address for the series ID, then it means that if the location name is changed all of the previous data is lost, so the mac address should really be used for it's series ID.

Series labels are available in Bar Charts, but not in Line Charts and it would be great if you could enable this feature also in Bar Charts

Thanks

**Comment by dceejay** [comment]
The chart is just a visualisation of the data you already have so nothing is "lost".  If you change the location name then the data you are showing IS representing something DIFFERENT at least to the end user as it now shows a different location. If you want to translate the mac address into something more human - like "sensor A" - you can do that in a previous node to map them across to something constant of your choosing.

**Comment by pacmac** [comment]
Thanks, I know that I can convert during loading and saving of data but that means adding a lot of load / save function nodes to many charts and is pretty inefficient.

Having a series label function would avoid all of this additional code and allow users to have a different series and data label :-)

**Comment by dceejay** [comment]
well it would be just as inefficient if done inside the node also, as it would be the same translation. You don't have to save the data coming out of the node - you can save the raw data going in (with the mac address) - so there is only one lookup (just for display).
