### ISSUE TITLE
Gauge value font became too small since 2.18.0 version

### ISSUE THREAD

**Issue by radionoise** [node-red/node-red-dashboard#585]
I encountered this issue in `2.21.0` after upgrading from `2.14.0`. Afterwards I started to downgrade to see which version caused the problem.

Version `2.17.1`
<img width="161" alt="normal" src="https://user-images.githubusercontent.com/1556082/80069421-6108ca80-8552-11ea-8c1e-5dc13a4a03e2.png">

Version `2.18.0`
<img width="165" alt="small" src="https://user-images.githubusercontent.com/1556082/80069429-636b2480-8552-11ea-81d6-929ff4e7a118.png">

Node-RED version: v1.0.4
Node.js  version: v12.12.0
Darwin 19.4.0 x64 LE (macOS 10.15.4)
Safari 13.1

**Comment by robertsLando** [comment]
Could be caused by: https://github.com/node-red/node-red-dashboard/blob/master/src/components/ui-gauge/ui-gauge.js#L93 ?

**Comment by dceejay** [comment]
Hopefully improved if not fixed - by c932b7954fd5fc29362e51bc2ca739c9b4f84e1f
