### ISSUE TITLE
If gauge last on page cause creating 2 vertical scroll bars and messes up scrolling

### ISSUE THREAD

**Issue by raulsimcic** [node-red/node-red-dashboard#59]
Hi,

I'm playing with the dashboard and I discovered that if I place the gauge as last item on page it cause some problems with vertical scroll bars. It creates two scroll bars and shortens the page view as described in picture "node-red-dashboard problem.PNG". If I set something else (chart in this example) as last item on page, it renders the page as it should as shown on picture "node-red-dashboard no problem.PNG".

I use:
node-red-dashboard 2.0.2
nodejs 4.5.0
npm 2.15.9

I also tried with nodejs 6.5.0

Installed on Raspberry PI 2, tried on full image and lite version. OS version is from date: 27.5.2016

No problem
--------------
chart is the last item.

![node-red-dashboard no problem](https://cloud.githubusercontent.com/assets/1160556/18544122/927bf7b8-7b33-11e6-9f0f-49cde828959e.PNG)

With problem
--------------
gauge is the last item. Two scrollbars

![node-red-dashboard problem](https://cloud.githubusercontent.com/assets/1160556/18544123/9283d23a-7b33-11e6-82f0-1da62b46e83f.PNG)

**Comment by dceejay** [comment]
Hi - which browser ? which OS ?

**Comment by raulsimcic** [comment]
I'm remote connecting to raspberry pi from linux and windows machine. Tried Chrome, firefox and on windows the edge browser. always the same problem. I didn't tried directly from raspberry because I'm using only the console not the desktop.
