### ISSUE TITLE
ui_dropdown crashes node-red

### ISSUE THREAD

**Issue by offr3al** [node-red/node-red-dashboard#591]
Hi,

I use node-red-dashboard of actual version (2.22.1), and node-red (1.0.6).

(node-red-dashboard was updated today, but flows and dashboard UI was created few month ago on early version node-red-dashboard)

I created dropdown with day_of_week items, and select new option "Allow multiple selections".
After updating page in my browser, items in created dropdown has no checkboxes. It looks like usual dropdown.
When I clicked to one of them, node-red crashed with this error:

```
May 14 09:10:36 raspberrypi Node-RED[10820]: 14 May 09:10:36 - TypeError: msg.payload.includes is not a function
May 14 09:10:36 raspberrypi Node-RED[10820]:     at Object.beforeSend (/home/pi/.node-red/node_modules/node-red-dashboard/nodes/ui_dropdown.js:136:59)
May 14 09:10:36 raspberrypi Node-RED[10820]:     at EventEmitter.handler (/home/pi/.node-red/node_modules/node-red-dashboard/ui.js:287:26)
May 14 09:10:36 raspberrypi Node-RED[10820]:     at EventEmitter.emit (events.js:203:15)
May 14 09:10:36 raspberrypi Node-RED[10820]:     at Socket.emit (events.js:198:13)
May 14 09:10:36 raspberrypi Node-RED[10820]:     at /home/pi/.node-red/node_modules/socket.io/lib/socket.js:528:12
May 14 09:10:36 raspberrypi Node-RED[10820]:     at process._tickCallback (internal/process/next_tick.js:61:11)
May 14 09:10:36 raspberrypi systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
May 14 09:10:36 raspberrypi systemd[1]: nodered.service: Failed with result 'exit-code'.
May 14 09:10:36 raspberrypi systemd[1]: nodered.service: Service RestartSec=100ms expired, scheduling restart.
May 14 09:10:36 raspberrypi systemd[1]: nodered.service: Scheduled restart job, restart counter is at 3.
```
Dropdowns without multiple selection not cause the crash.

Trying to:
1.
- stop nodered service
- npm uninstall node-red-dashboard
- npm install node-red-dashboard
- start nodered

Not solved

2.
Open page in private mode. And it works! Checkboxes here are, multi selection working, and it not cause crashes.

One strange thing: when I reload page in typical (not private) mode, I get this error (in Developer Tools console):

```
Application Cache Error event: /ui/#!/0?socketid=<socketid>:1 
Resource fetch failed (404) https://<siteaddr>/ui/gs/gridstack.jQueryUI.min.js
```

In private mode, this error is not!

- [x] Node-RED-Dashboard version: 2.22.1 
- [x] Node-RED version: 1.0.6
- [x] node.js version: v10.19.0
- [x] npm version: 6.14.1
- [x] Platform/OS: Raspberry Pi CM1, Raspbian GNU/Linux 10 (buster), Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
- [x] Browser: Chrome 81.0.4044.138

**Comment by dceejay** [comment]
Have you flushed the browser cache fully ?

**Comment by offr3al** [comment]
> Have you flushed the browser cache fully ?

Thanx, for idea!
I found that dashboard.appcache loads every time from disk, even if the cache is disabled in Dev Tools.
Comparing the local cache with /.node-red/node_modules/node-red-dashboard/dist/dashboard.appcache is different.

I removed dashboard.appcache from chrome://appcache-internals/#, and it fixed half the problem - checkboxes in multiselect dropdown appeared.

But... How did it come to this? I see it not normal, when my browser issue can cause crashing node-red backend.

**Comment by offr3al** [comment]
Hmm, looks like this crash issue is fixed in actual code on github:
node-red-dashboard/nodes/ui_dropdown.js:
```
} else if (node.multiple && Array.isArray(msg.payload) && msg.payload.includes(control.options[i].value)) {
                        val.push(control.options[i].label);
                    }
```

but still not updated on npm

**Comment by dceejay** [comment]
usually a ctrl-shift-r or similar to force a reload should be enough to reload it. - But yes the browsers need to reload the new the cache somehow.

**Comment by offr3al** [comment]
> usually a ctrl-shift-r or similar to force a refresh should be enough to reload it. - But yes the browsers need to reload the new cache somehow.

Ok, Im understood.
In [this commit](https://github.com/node-red/node-red-dashboard/commit/dcf464ae54b8bb5e9652ed2ed354b938544377e8#diff-f3c8e37dd0a73713fe739364dd4bcd98) you disable appcache.

I created my flows before this commit, and it was working with old version dashboard untill to its be updated. When my browser dowloaded new index.html there are not reference to new .appcache cause it disabled. But, old appcache still be stored in browser.

Correct me, if I mistaken.
Thanx for reply!
