### ISSUE TITLE
Hide/show groups not initialized when accessing via browser

### ISSUE THREAD

**Issue by Kudhoh** [node-red/node-red-dashboard#593]
Hi,

I'm using Node-red dashboard on Pi4 with a touchscreen for data acquisition and visualization. I'm using the ui control node to show one group containing one chart or a group of gauges, and hide other groups. The user can then switch from one group to another with buttons. It's working correctly on the touchscreen : first group is shown at deployment and others are hidden. But when accessing the interface remotely via ip address with a web browser, all groups are shown. Pressing the buttons then works fine. I've tried Firefox, Brave, Chromium and Chrome to access the ui remotely, same behavior on every browser.

### What are the steps to reproduce?
- Run node-red dashboard via chromium on pi 4.
- Run the ui nodes to manage visibility of groups
- Access the dashboard remotely with ip adress
### What happens?
![Remote access](https://user-images.githubusercontent.com/31036126/82806666-8a38b580-9e86-11ea-8c31-dbc853cf0064.jpg)

### What do you expect to happen?
![Pi 4](https://user-images.githubusercontent.com/31036126/82806853-f0bdd380-9e86-11ea-8e2a-5f2f077950b9.jpg)

### Please tell us about your environment:

- Node-RED-Dashboard version: 2.22.1
- Node-RED version: 1.0.4
- Platform/OS: Raspberry Pi 4, windows 10
- Browser: Chromium on Pi 4, Firefox/Brave/Chrome/Chromium on win10

Code : [{"id":"435abb72.06b4b4","type":"ui_ui_control","z":"298bf828.76949","name":"","events":"all","x":720,"y":1620,"wires":[[]]},{"id":"888e85c9.16ef68","type":"ui_button","z":"298bf828.76949","name":"","group":"92840a2b.bf1cf","order":5,"width":4,"height":1,"passthru":false,"label":"Values And Controls","tooltip":"","color":"","bgcolor":"","icon":"visibility","payload":"Sulfu 2 Flow Values And Controls","payloadType":"str","topic":"","x":320,"y":1920,"wires":[["435abb72.06b4b4"]]},{"id":"8d7488cd.2d59f","type":"ui_button","z":"298bf828.76949","name":"","group":"6f52ca5f.c9548c","order":1,"width":4,"height":1,"passthru":false,"label":"Channel 1","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_2\",\"Sulfu_2_Flow_Values_And_Controls_Gas_3\",\"Sulfu_2_Flow_Values_And_Controls_Gas_4\"],\"show\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_1\"]}}","payloadType":"json","topic":"","x":330,"y":1520,"wires":[["435abb72.06b4b4"]]},{"id":"428438d3.30d","type":"inject","z":"298bf828.76949","name":"Initialize Flows Tab","topic":"","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_2\",\"Sulfu_2_Flow_Values_And_Controls_Gas_3\",\"Sulfu_2_Flow_Values_And_Controls_Gas_4\"],\"show\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_1\"]}}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":330,"y":1480,"wires":[["435abb72.06b4b4"]]},{"id":"c208836f.112b28","type":"ui_button","z":"298bf828.76949","name":"","group":"6f52ca5f.c9548c","order":2,"width":4,"height":1,"passthru":false,"label":"Channel 2","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_1\",\"Sulfu_2_Flow_Values_And_Controls_Gas_3\",\"Sulfu_2_Flow_Values_And_Controls_Gas_4\"],\"show\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_2\"]}}","payloadType":"json","topic":"","x":330,"y":1560,"wires":[["435abb72.06b4b4"]]},{"id":"b207a1b3.758ab","type":"ui_button","z":"298bf828.76949","name":"","group":"6f52ca5f.c9548c","order":3,"width":4,"height":1,"passthru":false,"label":"Channel 3","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_1\",\"Sulfu_2_Flow_Values_And_Controls_Gas_2\",\"Sulfu_2_Flow_Values_And_Controls_Gas_4\"],\"show\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_3\"]}}","payloadType":"json","topic":"","x":330,"y":1600,"wires":[["435abb72.06b4b4"]]},{"id":"6668b3c2.66e2b4","type":"ui_button","z":"298bf828.76949","name":"","group":"6f52ca5f.c9548c","order":4,"width":4,"height":1,"passthru":false,"label":"Channel 4","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_1\",\"Sulfu_2_Flow_Values_And_Controls_Gas_2\",\"Sulfu_2_Flow_Values_And_Controls_Gas_3\"],\"show\":[\"Sulfu_2_Flow_Values_And_Controls_Gas_4\"]}}","payloadType":"json","topic":"","x":330,"y":1640,"wires":[["435abb72.06b4b4"]]},{"id":"ad25357e.7fbc","type":"ui_button","z":"298bf828.76949","name":"","group":"6f52ca5f.c9548c","order":5,"width":0,"height":0,"passthru":false,"label":"Flow Charts","tooltip":"","color":"","bgcolor":"","icon":"show_chart","payload":"Sulfu 2 Flow Charts","payloadType":"str","topic":"","x":350,"y":1680,"wires":[["435abb72.06b4b4"]]},{"id":"5d0f55c3.e05c74","type":"ui_button","z":"298bf828.76949","name":"","group":"92840a2b.bf1cf","order":1,"width":4,"height":1,"passthru":false,"label":"Channel 1","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Charts_Channel_2\",\"Sulfu_2_Flow_Charts_Channel_3\",\"Sulfu_2_Flow_Charts_Channel_4\"],\"show\":[\"Sulfu_2_Flow_Charts_Channel_1\"]}}","payloadType":"json","topic":"","x":310,"y":1760,"wires":[["435abb72.06b4b4"]]},{"id":"c853971.95c6168","type":"ui_button","z":"298bf828.76949","name":"","group":"92840a2b.bf1cf","order":2,"width":4,"height":1,"passthru":false,"label":"Channel 2","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Charts_Channel_1\",\"Sulfu_2_Flow_Charts_Channel_3\",\"Sulfu_2_Flow_Charts_Channel_4\"],\"show\":[\"Sulfu_2_Flow_Charts_Channel_2\"]}}","payloadType":"json","topic":"","x":310,"y":1800,"wires":[["435abb72.06b4b4"]]},{"id":"2e7c057c.cbaa1a","type":"ui_button","z":"298bf828.76949","name":"","group":"92840a2b.bf1cf","order":3,"width":4,"height":1,"passthru":false,"label":"Channel 3","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Charts_Channel_1\",\"Sulfu_2_Flow_Charts_Channel_2\",\"Sulfu_2_Flow_Charts_Channel_4\"],\"show\":[\"Sulfu_2_Flow_Charts_Channel_3\"]}}","payloadType":"json","topic":"","x":310,"y":1840,"wires":[["435abb72.06b4b4"]]},{"id":"6d82deae.1b5878","type":"ui_button","z":"298bf828.76949","name":"","group":"92840a2b.bf1cf","order":4,"width":4,"height":1,"passthru":false,"label":"Channel 4","tooltip":"","color":"","bgcolor":"","icon":"redo","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Charts_Channel_1\",\"Sulfu_2_Flow_Charts_Channel_2\",\"Sulfu_2_Flow_Charts_Channel_3\"],\"show\":[\"Sulfu_2_Flow_Charts_Channel_4\"]}}","payloadType":"json","topic":"","x":310,"y":1880,"wires":[["435abb72.06b4b4"]]},{"id":"38cb41a2.ef7a96","type":"inject","z":"298bf828.76949","name":"Initialize Charts Tab","topic":"","payload":"{\"group\":{\"hide\":[\"Sulfu_2_Flow_Charts_Channel_2\",\"Sulfu_2_Flow_Charts_Channel_3\",\"Sulfu_2_Flow_Charts_Channel_4\"],\"show\":[\"Sulfu_2_Flow_Charts_Channel_1\"]}}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":320,"y":1720,"wires":[["435abb72.06b4b4"]]},{"id":"92840a2b.bf1cf","type":"ui_group","z":"","name":"Go To","tab":"2da1f5ad.a7370a","order":1,"disp":true,"width":4,"collapse":false},{"id":"6f52ca5f.c9548c","type":"ui_group","z":"","name":"Go To","tab":"10ba4d54.fbb02b","order":1,"disp":true,"width":"4","collapse":false},{"id":"2da1f5ad.a7370a","type":"ui_tab","z":"","name":"Sulfu 2 Flow Charts","icon":"dashboard","order":3,"disabled":false,"hidden":true},{"id":"10ba4d54.fbb02b","type":"ui_tab","z":"","name":"Sulfu 2 Flow Values And Controls","icon":"dashboard","order":2,"disabled":false,"hidden":false}]

**Comment by dceejay** [comment]
As per the issue template we prefer general how-to question to be raised via the forum or slack channel first so the widest audience can try to help.
You need to initialise the show/hide to the local instance - so you need to use a ui_control node to detect a new connection and then set them for that browser session.

**Comment by Kudhoh** [comment]
That's it. Couldn't find something related elsewhere. I tried the forum but didn't get any answers, so i thought this could be some kind of bug.

Thanks
