### ISSUE TITLE
Is it possible to change Navbar to the right side?

### ISSUE THREAD

**Issue by pepp86** [node-red/node-red-dashboard#594]
Hi all,

I want to have the navbar on the right side and was able to do the required chages in code within Chromes developer tools. But I'm not able to find the appropriate points I need to change within the node-red-dashboard code. Maybe it's quite easy and could be implemented as an option?

KR
pepp

**Comment by dceejay** [comment]
Only via the source and rebuilding it. The side nav is mainly defined in src/partials/main.html and src/main.less (and the colour in src/theme.less

**Comment by pepp86** [comment]
Got it working. Thanks for your hint.
