### ISSUE TITLE
notification OK/Cancel dialog with input - not working on node-red 1.1.0

### ISSUE THREAD

**Issue by gemini86** [node-red/node-red-dashboard#596]
### What are the steps to reproduce?

Pass any payload to the notification node, configured for "ok/cancel dialog with input", click 'ok' on dashboard, see message in debug pane.

Example flow"

`[{"id":"984cbadb.cdf4f8","type":"inject","z":"9b47271e.315198","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1230,"y":1100,"wires":[["26dcfa9d.be1486"]]},{"id":"26dcfa9d.be1486","type":"ui_toast","z":"9b47271e.315198","position":"prompt","displayTime":"3","highlight":"","sendall":true,"outputs":1,"ok":"OK","cancel":"","raw":false,"topic":"","name":"","x":1390,"y":1100,"wires":[["77f6332a.b76d2c"]]},{"id":"77f6332a.b76d2c","type":"debug","z":"9b47271e.315198","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1620,"y":1100,"wires":[]}]`

### What happens?

msg.payload is changed to "OK". 

### What do you expect to happen?

in this configuration, msg.payload should be the input from the inject node, which in the example flow is a timestamp.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.22.1
- [X] Node-RED version: 1.1.0
- [X] node.js version: v12.18.2
- [X] npm version: 6.14.5
- [X] Platform/OS: Ubuntu server 18.04.4
- [X] Browser: Chrome - Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by dceejay** [comment]
the payload input is just for the notification text. The output is either the text entered in the dialog box (if ok and cancel options re present) or Ok if only the OK option is present.
