### ISSUE TITLE
Switch node icon does not change - using iconify icons

### ISSUE THREAD

**Issue by johndparker** [node-red/node-red-dashboard#597]
### What are the steps to reproduce?

Create a switch node that uses 2 different iconify icons and a template node to add the JS to the head section.
```
[{"id":"45d3918e.d6c64","type":"ui_switch","z":"2e51b358.2d29fc","name":"","label":"Front Door","tooltip":"","group":"4d81769a.718908","order":8,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"","style":"","onvalue":"true","onvalueType":"bool","onicon":"iconify-bi:door-open","oncolor":"red","offvalue":"false","offvalueType":"bool","officon":"iconify-bi:door-closed","offcolor":"green","x":350,"y":120,"wires":[[]]},{"id":"4d81769a.718908","type":"ui_group","z":"","name":"test","tab":"bdd3aca7.591bb","order":1,"disp":true,"width":"20","collapse":false},{"id":"bdd3aca7.591bb","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```
### What happens?

Colour changes on switch operation but icon does not change.

### What do you expect to happen?

Both colour and icon should change.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: latest from master branch 
- [ ] Node-RED version: 1.0.6
- [ ] node.js version: 10.21.0
- [ ] npm version: 5.8.0
- [ ] Platform/OS: Raspberry Pi / Raspbian 
- [ ] Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit) on linux

**Comment by johndparker** [comment]
Forgot to add, if you refresh the page, the icon changes.

John

**Comment by dceejay** [comment]
if I inspect the page while clicking the icon I can see that the container changes - but the icon does not - This seems to be something iconify specific - I can see some reports on google about it not honouring the DOM mutation observer - but I can't see how to force it. I think this make take some time for someone to dig into it so don't hold your breath.

In the meantime I've been using `fa-folder fa-rotate-90` and `fa-folder-open-o fa-rotate-90` for closed and open doors.

**Comment by johndparker** [comment]
Thanks dceejay.

If I get time I'll do some more digging.

I see there is a version 2.0.0 of iconify in beta - I may look at that too to see if it helps.

Thanks again.

John
