### ISSUE TITLE
Groups layout seems to be broken

### ISSUE THREAD

**Issue by natcl** [node-red/node-red-dashboard#6]
When I add a second group, both groups seem to appear on top of each other:

```
[{"id":"4dfaa44a.b2055c","type":"ui_group","z":"2216ac32.dde954","order":"1","name":"Sliders","width":"6"},{"id":"a85539f6.57aac8","type":"ui_group","z":"2216ac32.dde954","order":"1","name":"Main","width":"6"},{"id":"c127f435.3ed808","type":"ui_tab","z":"2216ac32.dde954","name":"Home","icon":"dashboard","order":"1"},{"id":"17c6ec40.e83914","type":"ui_button","z":"2216ac32.dde954","tab":"c127f435.3ed808","group":"a85539f6.57aac8","order":1,"width":3,"height":1,"name":"button","label":"label","color":"","icon":"","payload":"","topic":"","x":280,"y":100,"wires":[[]]},{"id":"6f9bce30.90643","type":"ui_text_input","z":"2216ac32.dde954","tab":"c127f435.3ed808","group":"a85539f6.57aac8","order":1,"width":6,"height":1,"name":"","mode":"text","delay":300,"label":"Name","topic":"","x":460,"y":100,"wires":[[]]},{"id":"966b5b1a.6994a8","type":"ui_slider","z":"2216ac32.dde954","tab":"c127f435.3ed808","group":"4dfaa44a.b2055c","order":1,"width":6,"height":1,"name":"slider","label":"label","topic":"","min":0,"max":10,"x":270,"y":160,"wires":[[]]}]
```
![capture d ecran 2016-05-10 a 12 00 41](https://cloud.githubusercontent.com/assets/77556/15153362/fc60b3c2-16a6-11e6-8432-8542e9080b13.png)

**Comment by jdp1g09** [comment]
Hi @natcl, what browser and OS are you using for this? Struggling to re-create the issue at the moment. Are there any errors appearing in the browser's console in the developer tools?

**Comment by natcl** [comment]
Latest Safari on Mac OS 10.11

**Comment by natcl** [comment]
Will check for errors shortly

**Comment by natcl** [comment]
![capture d ecran 2016-05-11 a 13 20 29](https://cloud.githubusercontent.com/assets/77556/15189928/47e70772-177b-11e6-9a34-cb050ba82fee.png)

**Comment by jdp1g09** [comment]
Have managed to narrow this down to being on window widths of 1405px and up only, is this in line with what you're seeing too?

**Comment by natcl** [comment]
Yes, feel silly not finding it, I always run by apps fullscreen ;)
So indeed seems to only happen > 1405px
