### ISSUE TITLE
Missing "When msg arrives, pass through to output" in numeric node

### ISSUE THREAD

**Issue by codmpm** [node-red/node-red-dashboard#60]
Hi again,

right now I'm implementing  many of the dashboard items to simply change some value in mqtt. To not get a "race condition" as described here https://github.com/node-red/node-red-dashboard/issues/51, I use the "When msg arrives, pass through to output"-Checkbox. Perfect!

But this checkbox is missing on the numeric node? Did I just miss something?

Cheers,
Patrik

**Comment by dceejay** [comment]
you didn't miss anything - apart the the line at the end of the issue where I said I had only applied it to the slider and switch :-) 
Will look to add it here also.

**Comment by codmpm** [comment]
You are absolutely stunning! Thanks!
