### ISSUE TITLE
For UI Chart object, 'Blank Label' property does not accept msg part value, like 'Label' property does?

### ISSUE THREAD

**Issue by dachshund-digital** [node-red/node-red-dashboard#603]
On chart UI object?  'Blank Label' property does not accept a msg part like the Label property?  Setting Label to {{msg.topic}} is allowed, but not so with 'Blank Label' apparently?  Please add this feature..

**Comment by dceejay** [comment]
Why is it helpful for this to be dynamic ? What is the use case for this ? I'm not even sure it would work, as you have to send in a msg in order to set it, and the sending in of data would then mean data arrived so it would then no longer be displayed, as the message is only show n until data arrives.

**Comment by dachshund-digital** [comment]
The use case is straight forward, I have flow that has multiple states, before the data is sent to the chart.  I would like to customize the message based on the scenario the flow presents.  If I can set the title of the chart dynamically, setting the blank message dynamically should also be possible, based on the state of the flow.  Moreover, why not make it dynamic, so that is more flexible and responsive to the need of the flow developer?  I am surprised it is not dynamic, it seems obvious to me, that it should be.

**Comment by Paul-Reed** [comment]
I've also a user case, I have a chart that shows data relevant to a specific source.
There are 3 sources, and each source is selected via a dashboard button.
If I could pass the source name in as msg.label, users would be in no doubt as to which data they were viewing.

![chart](https://user-images.githubusercontent.com/973580/87886959-d46a8d00-ca18-11ea-97f3-1b26798f88ab.gif)

**Comment by dceejay** [comment]
you can always send a ui_control message to set it - see https://github.com/node-red/node-red-dashboard/blob/master/config-fields.md

eg
```
msg.payload = [];
msg.ui_control = {nodata:"My new label"};
return msg;
```

**Comment by Nodi-Rubrum** [comment]
Oh, yeah.  Sorry for got to reply.
