### ISSUE TITLE
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".

### ISSUE THREAD

**Issue by diginfo** [node-red/node-red-dashboard#604]
Browser = Chrome, latest, dashboard version, latest.

Over a period of hours, I am getting hundreds of these errors in the console.log and eventually the page will just hang.

```
Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".
index.js:83 WebSocket is already in CLOSING or CLOSED state.
app.min.js:148 SideNav 'left' is not available! Did you use md-component-id='left'?
```

Any idea what the cause of these might be ?

**Comment by dceejay** [comment]
for general questions we prefer the use of the nodered discourse forum as per the issue template you have deleted.
the error looks to be from svg element. This may be an added node you have added ? or the svg added within it.
I'm going to close it here as the guys doing the svg ui widgets don't hang out here and you will get better response on the forum.

**Comment by diginfo** [comment]
Thanks so much, but I don't understand this: 

> This may be an added node you have added ? or the svg added within it.

The only thing I have added is a template that contains a few divs with labels, but I have not added any svg elements ?

Many Thanks

**Comment by dceejay** [comment]
most odd then as we don't either.
if you want to re-open this then please add back in the info from the issue template - how to recreate - example flow - versions of nodejs, node-red, dashboard, hardware, browser etc.
