### ISSUE TITLE
2 dashboard icon after reinstalling node-red-dashboard library 

### ISSUE THREAD

**Issue by farooqhasny** [node-red/node-red-dashboard#606]
after reinstalling node-red-dashboard node i am getting 2 dashboard icon in navigation pan 

### What are the steps to reproduce?
install node-red-dashboard 
uninstall
and then reinstall
### What do you expect to happen?
2 dashboard icon in navigation pan 
[https://i.imgur.com/pZroqny.png](https://i.imgur.com/pZroqny.png)
### Please tell us about your environment:

- [1.1.2 ] Node-RED version:
- [10.21.0 ] Node.js version:
- [ ] npm version:
- [alpine (docker) ] Platform/OS:
- [chrome latest ] Browser:

**Comment by dceejay** [comment]
@knolleary 
currently we do 
```
onpaletteremove: function() {
                RED.sidebar.removeTab("dashboard");
                RED.events.off("editor:save",editSaveEventHandler);
                RED.events.off("nodes:add",nodesAddEventHandler);
                RED.events.off("nodes:remove",nodesRemoveEventHandler);
                RED.events.off("layout:update",layoutUpdateEventHandler); // Dashboard layout tool
            },
```
Is that not sufficient ?
