### ISSUE TITLE
Dashboard Gauge node: missing value format when "level" (water level) is selected

### ISSUE THREAD

**Issue by hazymat** [node-red/node-red-dashboard#607]
Animated GIF screenshot of issue [here on the Node-RED forum](https://discourse.nodered.org/t/possible-bug-missing-value-format-field-from-gauge-node-type-level/31193/3)

- Edit a Dashboard Gauge node in Node-RED (Chrome / Firefox, not tested on other browsers).
- Set the gauge type to "level" (the water meter style visualisation)
- The form field labelled "value format" disappears. This should not disappear, as it is still required for this gauge type.
- This is because the containing DIV with id="ui-gauge-format" has its style set to display:none, when you set the gauge type to "Level"

(A workaround for setting the value format is to change the gauge to any other type, edit the field, then set it back to level.)

I am running NodeRED v1.1.2

**Comment by dceejay** [comment]
Right - so the reason it is hidden is that the field doesn't accept Angular filters like the other gauges do - so you can't do things like truncate the number of decimals etc...  as this is a completely different library. 

So if we enable it so you can use {{msg.foo}} then someone will no doubt try {{msg.foo | number:0}} and then that won't work  - so which is worse...  ?
