### ISSUE TITLE
Sidebar in dark the is not dark anymore

### ISSUE THREAD

**Issue by Bond246** [node-red/node-red-dashboard#610]
### What happend?
I made an Update of my Dashboard-Plugin-Version vom 2.22.1 to 2.23.2 some days ago. Since that update the background-color of the sidebar in the dark theme is not dark anymore.

### What do you expect to happen?
Normaly the sidebar background hat the same lighter grey like the widget-backgrounds.

For the moment it helped to make a custom dark theme but the coloring effects some widgets like the level-gauge which hase not the lightblue-color for the moment.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.32.2
- [ ] Node-RED version: 1.1.3
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: Ubuntu 20.04.1 LTS with original node-red docker-image
- [ ] Browser: Edge (Chromium), Firefox

**Comment by dceejay** [comment]
Are you able to share some of your flow - or screenshot that shows the issue ?
Have you flushed the browser cache since upgrading to ensure the client also has the latest code ?

**Comment by Bond246** [comment]
Hello @dceejay,
actual to solve this i made a custom config which looks like that:
![image](https://user-images.githubusercontent.com/8534418/91871339-7ec00c00-ec77-11ea-8349-95c1d4a5b8f7.png)

When i use the pre-configured dark theme it looks like that:
![image](https://user-images.githubusercontent.com/8534418/91872355-11f94180-ec78-11ea-8694-290a3b10190d.png)

Before my latest update it looked like what i rebuild with my custom theme in first screenshot. With one difference. As you can see the gauge is always blue in preconfigured themes. In my custome theme it is green and i don't know how to change this, changing my green configured fields to something else has no effect on the gauge-color.

**Comment by dceejay** [comment]
You can customise level gauge colours by using the ui_control message - see last line of https://github.com/node-red/node-red-dashboard/blob/master/config-fields.md for an example.
