### ISSUE TITLE
Please enhance the description in the node help

### ISSUE THREAD

**Issue by Mannshoch** [node-red/node-red-dashboard#615]
### What are the steps to reproduce?
Insert a slider and got to the node help of this slider and finde out what imput data is possible.

### What happens?
No information how to setup the pre-selected value

### What do you expect to happen?
Information about how I have to configure it.
(same appearance on all dashboard nodes)

### How a dashboard ui help for the dropdown node could look like
<Details> 

> Adds a dropdown select box to the user interface.
> Multiple value / label pairs can be added as required. If the label is not specified the value will be used for both.
> 
> ## Input (optional)
> ```
> msg.topic = "A Topic"
> // Topic of the dropdown
>
> msg.options = [ "Choice 1", "Choice 2", {"Choice 3":"3"}, {"Choice 4":"4"} ] 
> // If just text then the value will be the same as the label, otherwise you can specify both by using an object of "label":"value" pairs
> 
> Payload = [ "3", "4" ] 
> // Pre-select this value ( use array for multiselect dropdown )
> 
> return msg
> ```
> ## Node dropdown
> The configured value of the selected item will be returned as msg.payload.
> Optionally the Topic field can be used to set the msg.topic property.
> If you wish to be able to select more than one item, select "Allow multiple selections"
> 
> ## Output 
> If the "Allow multiple selections" output option is enabled - the result will be returned as an array instead of a string.
> 

</Details>

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.23.2
- [x] Node-RED version: 1.0.3
- [x] node.js version: v12.18.3
- [x] npm version: 6.14.6
- [x] Platform/OS: raspbian
- [x] Browser: Firefox 80

**Comment by dceejay** [comment]
Hi - happy to consider a pull request with this change.

**Comment by Mannshoch** [comment]
I'm new in node-red. I'm not even sure that every thing is right what I wrote above. I tried to use the slider and was not able to find out how it's input works The only dashboard Item that I was able to use with Input data was the dropdown.

**Comment by dceejay** [comment]
Hi - Ok. the default expectation in Node-RED is that msg.payload should contain the default data of interest. That may be a single value or an object. So all nodes should accept a value in msg.payload to do something. They may also accept other properties as well but they should all (by default) look at msg.payload... so for dashboard widgets - sending them a value in msg.payload should set them. As this is default behaviour we have never specified it for every single node.

**Comment by Mannshoch** [comment]
Should I create an issue for "Specify Input the same way for all User-clickable dashboard Items"

**Comment by dceejay** [comment]
not when you can rename this one if needed. But now I'm not sure exactly what you are proposing. If the inputs are User-clickable - then the input is by definition - the click. If you mean how to preset the widget value then it is by the msg.payload which is the default for all nodes (not just dashboard) so shouldn't really need to be specified every single time.

**Comment by Mannshoch** [comment]
As an Example.
What value is needed to tell slider what state it should have? 0/1, true/false, on/off (description in the UI),Value1/Value2.

In my opinion. This is an Information that have to bee in the help-text of every node. If i'ts every time the same, you could unify the text and use it everywhere.
