### ISSUE TITLE
Store chart data in a file like excel

### ISSUE THREAD

**Issue by rubeng0182** [node-red/node-red-dashboard#616]
I have been trying to get my chart data stored in a file, to make it  easy to check. maybe convert it so it has a date every point.

i cant get it to work

**Comment by dceejay** [comment]
As per the issue template you have managed to delete we prefer general how-to questions via either slack or the discourse forum. As this is not an issue with Dashboard I'm going to close it here.

**Comment by rubeng0182** [comment]
maybe you can get me in a direction on what i could do, or someone or a video

**Comment by knolleary** [comment]
The best thing to do will be to ask on the forum - https://discourse.nodered.org - that way the whole community can help.

**Comment by dceejay** [comment]
the chart outputs an array of data that contains all the points it has. You would need to manipulate that into whatever format you require to save to a file - probably using a function node - then output to a file node.

**Comment by rubeng0182** [comment]
thank you i will definetly check that out
