### ISSUE TITLE
Chart time limit doesn't apply to "all in one" data payload

### ISSUE THREAD

**Issue by OneHoopyFrood** [node-red/node-red-dashboard#617]
### What are the steps to reproduce?
Input a long (temporally) data series into a chart node as a single message. In my case, from a file. Set the chart to line, and the x-axis limit to a shorter duration than the input data covers. (e.g. 4 weeks of data fed into a chart that limits to 2 weeks)

### What happens?
4 weeks of data are displayed until a new single-entry message is fed into the chart.

### What do you expect to happen?
Chart should be limited to 2 weeks of data, despite the larger input.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.23.2
- [x] Node-RED version: 1.1.3
- [x] node.js version: 12.18.3
- [x] npm version: 6.14.7
- [x] Platform/OS: Raspian
- [x] Browser: Chrome

**Comment by dceejay** [comment]
correct - this is working as designed. This allows the user to plot what they want. You can trigger the filters by sending new data point as you have found. Note the filters apply both length and time so if we always applied them then you could never plot data older than the window selected, and could never plot "fake realtime data" where you just use numbers for the x-axis instead of time.

It would also be much more efficient to truncate your data on the server side before sending.

**Comment by OneHoopyFrood** [comment]
I see. I would argue that this is a bit anti-intuitive, but I seen your points.
It seems to me that if the user wanted to show a larger data set the way you indicate, they would simply set the limits wider or remove them entirely before sending the data.
As to the need to post fake realtime data, well I don't understand that use case. I'd still expect the solution to be not putting in a limit.

Yes, if I were using a database, limiting the data retrieved would be there right move, but this is coming from a flat file on the same machine as the node red server.

**Comment by dceejay** [comment]
If the data is coming from a file surely its still easy to only send x lines worth, rather than the whole file, either by reassigning the length or using slice.

**Comment by OneHoopyFrood** [comment]
> If the data is coming from a file surely it's still easy to only send x lines worth, rather than the whole file, either by reassigning the length or using slice.

Yes, but the file in utility that comes with node red doesn't support that. I suspect other users might end up having my same confusion. Lol.
I knew I'd need to truncate the file eventually.

I ended up writing a function block to do dump data, then later moved it to a sqlite instance.

I could see how this inefficiency could end up causing performance issues that would confuse the class of users I'm thinking of though (folks playing with node red who might not know how to play with sql). Perhaps if the data dump is significant it would merit raising a warning?

**Comment by dceejay** [comment]
pushed fix to master.
