### ISSUE TITLE
Text input node / Time picker not activate onscreen keyboard

### ISSUE THREAD

**Issue by mikko80** [node-red/node-red-dashboard#618]
When using text input node / Time picker and click to chance value, on screen keyboard will not activated.
When text input node is normal text input or password etc. keyboard has activated.

So time values can't be chance  when using touch screen with out real keyboard. 

V.2.23.3
V1.1.3
node.js v10.22.0
npm 6.14.6
RaspberryPI / Raspian Buster 10
Chrome browser

**Comment by dceejay** [comment]
this is just html5 - do the basic examples here work ? https://www.w3schools.com/html/html_form_input_types.asp

**Comment by kwithus** [comment]
For me the input works fine (iPad with iOS 14), touching the time opens a number keyboard, I can then select the hours or minutes and change the values.
