### ISSUE TITLE
Button texts don't show mostly

### ISSUE THREAD

**Issue by stofferr** [node-red/node-red-dashboard#624]
I use the buttons for several of my lights. In the dashboard page they show up and functionally work, so icons, messages received and sent do work, however occasionally, the button texts don't show.

As example see this discourse topic: https://discourse.nodered.org/t/button-texts-dont-show-occasionally-go-missing/33488

### What are the steps to reproduce?
I can trigger the issue usually by moving to another flow, and then come back to the flow with the buttons.

### What happens?
button texts do not show (most of the time, but not always)

### What do you expect to happen?
visible button texts

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.23. 4
- [ ] Node-RED version: 1.1.3
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS: Android 8, Android 10, Windows 10
- [ ] Browser: Chrome, Edge, FullyKiosk Browser
- [ ] on nodered/node-red -> latest

**Comment by dceejay** [comment]
weird one... seems to be an interaction with your choice of property name :-)...  the name "color" seems to upset it.. - so the workaround seems to be to pick another variable name for now...

**Comment by stofferr** [comment]
workaround works :) Thanks!
