### ISSUE TITLE
Problem with layout when changing tabs

### ISSUE THREAD

**Issue by FBDr** [node-red/node-red-dashboard#63]
A grey rectangle is visible when selecting a different tab. The rectangle is the same color as the background. I'm using Chrome on Windows and Ubuntu. 

![strange](https://cloud.githubusercontent.com/assets/5618259/18711107/aaf2cd2e-8008-11e6-99c6-0d849ae39102.png)

Node.JS version: v6.6.0
Node-red version v0.14.6
Node-red-dashboard: cloned latest version from git.

**Comment by dceejay** [comment]
If you mean the grey area at the bottom then already fixed by 6a7b46d6a38d5c7b03d8ddbf8c30645157b6337e
If you mean the top right part of the screen that is as designed.
