### ISSUE TITLE
Chart performance issues/crashes

### ISSUE THREAD

**Issue by erythana** [node-red/node-red-dashboard#630]
First of all, i am new to NodeRED so please keep that in mind - thanks! :)

### What are the steps to reproduce?
Create a Chart-Node, set it to keep track of it for a week
Put 8 of those bad boys into a dashboard
Send one item every minute to each dashboard

### What happens?
After starting the flow, everything is gradually getting slower. After a while, maybe 8 hours, it even crashes the Browser (at least on my RPi4 4GB --> Chromium "Aw Snap" message and sometimes "Connection lost"). On my PC (Firefox on Linux) it just loads the Dashboard very slow.
The RAM usage of node-red is quite low according to "PM2" with about 120MB.
When the "Aw snap" error appears and i reload the page it loads on the Pi for a loooong time (all graphs empty) and it loads them one by one, after that it blanks out again and i get "Connection lost" or sometimes the Aw snap again.

### What do you expect to happen?
No crashing, pleasant would be moderate loading times too

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: latest available
- [x] Node-RED version: latest available
- [x] node.js version: latest available
- [x] npm version: latest available
- [x] Platform/OS: Raspian on RPi4, Manjaro on PC
- [x] Browser: Chromium on RPi4, Firefox on PC

Questions:
Are this too many datapoints? I've red that it also depends on the size of the chart, pixel wise. In that case, it is pretty small. (480x600 px on my RPi, and there i fit like 20 controls on it, 8 of them are charts). It wouldnt change a lot probably when i set the samplin gto like 10 minutes or even 30?!

**Comment by dceejay** [comment]
Just think about it for a minute...
1 data per minute for a week  = 1 * 60 * 24 * 7 = 10080 pixels worth of data - is somewhat larger than 600 pixels across even full screen... * 8 charts.... and so yes too much data. You need to think of a way to sample it down to something reasonable.

PS - as per the form you filled in please ask general questions on the forum or slack channel.
