### ISSUE TITLE
Dropdown dismissed upon clicking on its search box

### ISSUE THREAD

**Issue by namgk** [node-red/node-red-dashboard#631]
### What are the steps to reproduce?
Create a dropdown elements with about 10 items so that the search box appear.

Click on the search box.

### What happens?
The dropdown dismissed.

### What do you expect to happen?
The dropdown remains open and we're able to type into the search box.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.24.0
- [ ] Node-RED version: v1.1.3
- [ ] node.js version: v12.14.0
- [ ] npm version: 6.13.4
- [ ] Platform/OS: 19.5.0
- [ ] Browser: Safari + Chrome

Last worked on 2.23.2.

**Comment by dceejay** [comment]
This is working for me - can you share your dropdown config so i can try it ?

**Comment by namgk** [comment]
Sorry Dave, I dropped the ball on this. 

Here is the sample flow:

>[{"id":"222b763e.858aaa","type":"ui_dropdown","z":"1b6c108d.061e2f","name":"","label":"","tooltip":"","place":"Select option","group":"19896f85.4f71e","order":0,"width":0,"height":0,"passthru":true,"multiple":false,"options":[{"label":"a","value":"1","type":"str"},{"label":"b","value":"2","type":"str"},{"label":"c","value":"3","type":"str"},{"label":"d","value":"4","type":"str"},{"label":"e","value":"5","type":"str"},{"label":"f","value":"6","type":"str"},{"label":"g","value":"7","type":"str"},{"label":"h","value":"8","type":"str"}],"payload":"","topic":"","x":480,"y":220,"wires":[[]]},{"id":"19896f85.4f71e","type":"ui_group","z":"","name":"Test","tab":"ea6105fa.e8e448","order":1,"disp":true,"width":"6","collapse":false},{"id":"ea6105fa.e8e448","type":"ui_tab","z":"","name":"Test","icon":"dashboard","disabled":false,"hidden":false}]

![dropdown](https://user-images.githubusercontent.com/1003424/99713697-78ad2080-2a59-11eb-8b8c-7baa986853de.gif)

**Comment by dceejay** [comment]
Hi I think I may have already fixed it on the beta I released on npm.
