### ISSUE TITLE
Dropdown items return empty values after first click

### ISSUE THREAD

**Issue by zinen** [node-red/node-red-dashboard#632]
### What are the steps to reproduce?
Video of how I see it:
![2020-11-09_13-43-21](https://user-images.githubusercontent.com/9595798/98543795-45b5a080-2293-11eb-91d6-2ebe798956b5.gif)

To reproduce import this flow:
```
[{"id":"6a9255e1.a43f5c","type":"ui_button","z":"f9fbb1e7.cd626","name":"","group":"f2a742b4.c9de6","order":7,"width":0,"height":0,"passthru":false,"label":"Make dropdown","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":170,"y":1040,"wires":[["c2b61e7e.2f3df"]]},{"id":"c2b61e7e.2f3df","type":"template","z":"f9fbb1e7.cd626","name":"","field":"options","fieldType":"msg","format":"javascript","syntax":"mustache","template":"[ {\"Choice 1\":\"1\"}, {\"Choice 2\":\"2\"}, {\"Choice 3\":\"3\"} ]","output":"json","x":380,"y":1040,"wires":[["3e19c84e.850348"]]},{"id":"3e19c84e.850348","type":"ui_dropdown","z":"f9fbb1e7.cd626","name":"","label":"","tooltip":"","place":"Select option","group":"f2a742b4.c9de6","order":8,"width":0,"height":0,"passthru":true,"multiple":false,"options":[{"label":"","value":"","type":"str"}],"payload":"","topic":"","x":580,"y":1040,"wires":[["d722cf27.b77b9"]]},{"id":"d722cf27.b77b9","type":"ui_text_input","z":"f9fbb1e7.cd626","name":"","label":"","tooltip":"","group":"f2a742b4.c9de6","order":9,"width":0,"height":0,"passthru":true,"mode":"text","delay":300,"topic":"","x":760,"y":1040,"wires":[[]]},{"id":"f2a742b4.c9de6","type":"ui_group","z":"","name":"test","tab":"73a53871.7f0ce8","order":2,"disp":true,"width":"6","collapse":false},{"id":"73a53871.7f0ce8","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

### What happens?
_Note that the multiple selection is unticked in dropdown node._

When clicking an item in dropdown. The payload is returned, when clicking another item the payload is returned. When clicking the first item again, an empty string is returned as payload. The same empty string is returned when clicking the second item again. When clicking the third item the payload is returned just fine.

### What do you expect to happen?
I would not expect to see any empty strings returned. This issue does not happen when inputting a simple array as the options, only when inputting an array of objects.
Simple array: `["Choice 1", "Choice 2", "Choice 3" ]`
Array of objects: `[ {"Choice 1":"1"}, {"Choice 2":"2"}, {"Choice 3":"3"} ]`

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.23.4
- [x] Node-RED version: 1.1.3
- [x] node.js version: 10.22.0
- [x] npm version: 6.14.8
- [x] Platform/OS: Debian GNU/Linux 10 (buster)
- [x] Browser: Chrome Version 86.0.4240.183

**Comment by dceejay** [comment]
Already fixed in master - https://github.com/node-red/node-red-dashboard/commit/f248498828e615702df40ac0ade3e2600cf6b172
