### ISSUE TITLE
Dashboard sidebar not visible

### ISSUE THREAD

**Issue by Marooned-MB** [node-red/node-red-dashboard#633]
### What are the steps to reproduce?
This is generally the same as issue #533 but newer. On one tab I have 3 groups, 2 of them have 2 nodes, 3rd one has 4 nodes. It was always Chart then Gauge below. I decided to change one Chart X axis (30 to 7 days) and it jumped below the Gauge in the same group. So this is first issue (but this report is not on this one). I decided to fix this unexpected and unwanted change and remember that there should be order of nodes in the Dashboard sidebar.. but that sidebar is not visible.

### What happens?
Dashboard sidebar is not visible.

### What do you expect to happen?
Dashboard sidebar to be visible. (Also, order of nodes inside groups should not change when altering their parameters)

### Please tell us about your environment:
This is generally fresh install from scratch done about a week ago (newest OS and other packages)
- [ ] Node-RED-Dashboard version: 2.10.1
- [ ] Node-RED version: 1.2.3
- [ ] node.js version: 12.19.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Rasbberry Pi Model B Rev 2 / Linux raspberrypi 5.4.72+ #1356 Thu Oct 22 13:56:00 BST 2020 armv6l GNU/Linux
- [ ] Browser: Firefox 82.0.3

**Comment by dceejay** [comment]
please can you upgrade to latest version of dashboard as there have been some fixes in this area.

**Comment by Marooned-MB** [comment]
Yeah, ok, mea culpa. I haven't noticed there is a newer version. Having in mind that I installed it a week ago I (wrongly) assumed I have newest version.
After update to 2.24.0 both issues have been fixed: Dashboard sidebar is present and the order of nodes in groups are like before my last change.
All is good.
Thanks.
