### ISSUE TITLE
Chart Problems

### ISSUE THREAD

**Issue by LionyxML** [node-red/node-red-dashboard#637]
To help us understand the issue, please fill-in as much of the following information as you can:
-->

### What are the steps to reproduce?
Install node-js
Install node-red
install node-red-dashboard

Use anything with a CHART, such as:
[{"id":"7c689e8a.f21e4","type":"debug","z":"2a1484f5.ae623c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":620,"y":660,"wires":[]}]

I even used the example from the end of the documentation: 
https://github.com/node-red/node-red-dashboard/blob/master/Charts.md

All charts are shown blank.

This happened today with a Windows machine and macOS.

### What happens?
Charts are displayed blank.

### What do you expect to happen?
Charts to populate.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.24.1-beta
- [x] Node-RED version: 1.2.5
- [x] node.js version: 15.2.0
- [x] npm version: 7.0.10
- [x] Platform/OS: macos
- [x] Browser: google chrome

**Comment by dceejay** [comment]
The node you have posted is just a debug node. Can you paste your real example ?
and ideally a screen shot to show what you mean ? - by default the chart will be empty until you send it some data. You can configure it to show some text of your choice until data arrives if you like.

**Comment by LionyxML** [comment]
Thank you very much for your response!

This is the exactly thing I am trying to work:

`[{"id":"6ce224ed.8e861c","type":"tab","label":"Estação Solarimétrica","disabled":false,"info":""},{"id":"4c455910.a247a8","type":"ui_chart","z":"6ce224ed.8e861c","name":"","group":"9b736fc5.c56c7","order":2,"width":0,"height":0,"label":"chart","chartType":"line","legend":"false","xformat":"auto","interpolate":"linear","nodata":"","dot":false,"ymin":"0","ymax":"50","removeOlder":1,"removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"useUTC":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"outputs":1,"x":390,"y":440,"wires":[[]]},{"id":"baf853bd.16f08","type":"inject","z":"6ce224ed.8e861c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":180,"y":220,"wires":[["c6c09998.bfcc18"]]},{"id":"67af69dd.f3e048","type":"csv","z":"6ce224ed.8e861c","name":"Dados_Estacao_Solarimetrica","sep":",","hdrin":"","hdrout":"none","multi":"mult","ret":"\\n","temp":"data, sequencia, temperatura, umidade, pot1, pot2, precipitacao, velocidade, direcao","skip":"4","strings":true,"include_empty_strings":"","include_null_values":"","x":270,"y":300,"wires":[["5850e8c8.67f978"]]},{"id":"c6c09998.bfcc18","type":"file in","z":"6ce224ed.8e861c","name":"","filename":"./SOLAR_Tabela.dat","format":"utf8","chunk":false,"sendError":false,"encoding":"none","x":360,"y":220,"wires":[["67af69dd.f3e048"]]},{"id":"5850e8c8.67f978","type":"function","z":"6ce224ed.8e861c","name":"","func":"var temp_array = [];\n\nfor (var i=0; i<msg.payload.length; i++){\n    if (msg.payload[i].temperatura == \"NAN\"){\n        temp_array.push(0);\n    } else {\n    temp_array.push(msg.payload[i].temperatura);\n    }\n}\n\n\nmsg.payload = [{\n    \"series\": [\"Temperatura\"],\n    \"data\": [ temp_array ],\n    \"labels\": [ \"\" ]\n}]\n\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":200,"y":380,"wires":[["bf56e88e.3eba88","4c455910.a247a8"]]},{"id":"bf56e88e.3eba88","type":"debug","z":"6ce224ed.8e861c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":370,"y":380,"wires":[]},{"id":"9b736fc5.c56c7","type":"ui_group","name":"Estação Solarimétrica","tab":"9160e1e4.7c35b","order":1,"disp":true,"width":"6","collapse":false},{"id":"9160e1e4.7c35b","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]`

This is what I am getting:

![image](https://user-images.githubusercontent.com/16169950/99699282-87eb9880-2a70-11eb-9383-ebb68b0a7dfa.png)

CSV source file is: 
[SOLAR_Tabela.dat.zip](https://github.com/node-red/node-red-dashboard/files/5568524/SOLAR_Tabela.dat.zip)


I just want all "Temperatura" values from the csv to be shown :) 

The reason I am claiming something seems to be wrong is that all document examples are appearing as blank charts, even on another machine I have here around.

Thank you again!

**Comment by LionyxML** [comment]
Well well.

I think I made a mistake before. I'll explain here:

This is the flow:
![image](https://user-images.githubusercontent.com/16169950/99737853-f009a100-2aa7-11eb-8fdf-536b47cdb70f.png)

"Dados_Estacao_Solarimetrica" is a CSV parser that feeds in one line the function.

Function is:
`var temp_array = [];
var labe_array = [];

for (var i=0; i<msg.payload.length; i++){
    if (msg.payload[i].temperatura == "NAN"){
        temp_array.push(0);
    } else {
        temp_array.push(msg.payload[i].temperatura);
    }
    labe_array.push(i);
}


msg.payload = [{
    "series": ["Temperatura"],
    "data": [ temp_array ],
    "labels": labe_array
}]


return msg;`

I was under the impression that you should have one label per series, but it is one label per entry inside data. I'll suggest something to avoid this misreading on the docs latter.

Also, it seems that chart has a limit with data points. My 52K data is way too much for the por thing to deal with.

**Comment by dceejay** [comment]
well unless you have a monitor with 52k pixels across then yes - probably too many data points... - some filtering/decimation/averaging may be required :-)

And yes - clarification for docs would be much appreciated.

**Comment by LionyxML** [comment]
Thanks again Dave!

I think this is discussed enough to be a closed case.
