### ISSUE TITLE
[action required] Relicense as Apache 2.0 to bring inline with other node-red projects

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-dashboard#64]
We want to change the license under which Node-RED Dashboard is made available to Apache 2.0. It is currently under an MIT license. This will bring it inline with all of the other Node-RED repositories and make for a consistent experience.

To do this relicensing I would like to get the explicit approval of everyone who has committed a change. All are already covered by the project's CLA (or internal IBM approval), but I want to make sure everyone is on board.

I have added a list of contributors below. If you support this change in license please add a comment to this issue stating so.

- [x] @andrei-tatar 
- [x] @knolleary
- [x] @dceejay 
- [x] @pelis 
- [x] @jdp1g09 
- [x] @natcl 
- [x] @hrhrprasath

Please respond by the end of Friday 7th October.

**Comment by knolleary** [comment]
I support relicensing the project to Apache 2.0.

**Comment by dceejay** [comment]
I support relicensing the project to Apache 2.0.

**Comment by natcl** [comment]
I support relicensing the project to Apache 2.0.

**Comment by andrei-tatar** [comment]
I support relicensing the project to Apache 2.0.

**Comment by jdp1g09** [comment]
I support relicensing the project to Apache 2.0.

**Comment by hrhrprasath** [comment]
I support relicensing the project to Apache 2.0.

**Comment by pelis** [comment]
I support relicensing the project to Apache 2.0.

**Comment by knolleary** [comment]
🎉  100% support. Thanks all.

**Comment by dceejay** [comment]
Closed by 09da48035637fbd37166376fd5615feddba469c5
