### ISSUE TITLE
AngularTheme and --nr-dashboard-variables

### ISSUE THREAD

**Issue by fellinga** [node-red/node-red-dashboard#640]
### What are the steps to reproduce?
Change the following settings:
node-red-flow-editor -> dashboard -> Site -> Options -> AngularThemeEverywhere
node-red-flow-editor -> dashboard -> Angular -> Primary-> Purple

### What happens?
The site header changes to Purple 👍 
The nr-dashboard variables like --nr-dashboard-pageTitlebackgroundColor are not affected 👎 

### What do you expect to happen?
That the --nr-dashboard variables would update accordingly.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.24.1
- [ ] Node-RED version: 1.2.6
- [ ] node.js version: 14.15.1
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Debian
- [ ] Browser: Chrome

Not sure if this is a bug report or a feature request. I am also not sure if the nr-dashboard variables are designed to only populate the "node-red-theme" settings. But if they would populate the current data no matter what theme was chosen, that would be quite nice, especially for contrib-ui-nodes.

**Settings:**
![settings](https://user-images.githubusercontent.com/26927863/100345680-f4234a80-2fe2-11eb-8968-2c54e6285bc1.png)

**Output:**
![output](https://user-images.githubusercontent.com/26927863/100345674-f1c0f080-2fe2-11eb-8efb-76902c3f3336.png)

**Comment by dceejay** [comment]
As you guessed they are indeed designed o be used for when Node-RED has control of the the theme - When we set Angular everywhere, we try to get out of the way and delegate the theme down to the built in Angular Material themes. So even if we manage to extract the colours from their themes - then we don't apply any of our styles from theme.less - see https://github.com/node-red/node-red-dashboard/blob/master/src/theme.less#L46.

**Comment by fellinga** [comment]
I didn't mean to extract something from the theme. I thought about assigning the existing Angular color dropdowns to the nr-dashboard variables, so that they don't show wrong information (after the user switched to Angular Theme). Like so:

If theme = angular then
--nr-dashboard-pageTitlebarBackgroundColor = Angular.Primary
--nr-dashboard-widgetBackgroundColor = Angular.Primary
--nr-dashboard-widgetColor = Angular.Primary		
--nr-dashboard-groupTextColor = Angular.Primary
--nr-dashboard-pageSidebarBackgroundColor = Angular.Background
--nr-dashboard-groupBackgroundColor = Angular.Background
--nr-dashboard-widgetBorderColor = Angular.Background
--nr-dashboard-widgetBgndColor = Angular.Background
--nr-dashboard-pageBackgroundColor = #fafafa
--nr-dashboard-widgetTextColor = #111111;
--nr-dashboard-pageBackgroundColor = #111111
--nr-dashboard-widgetTextColor = #eeeeee;

**Comment by dceejay** [comment]
Happy to consider a pull request if you want to create one.

**Comment by dceejay** [comment]
I've had a bit of a look and the angular themeProvider only provides the names of the palette, it doesn't provide the exact colour value - For example if you define the background as yellow it shows as 
![image](https://user-images.githubusercontent.com/5375409/100554889-e7774e80-328f-11eb-8002-3ee11240c806.png)
where the lighter shade is the page background and the darker are the group and widget backgrounds - and neither are html "yellow"  - so given there are three variable names to set for backgrounds (4 including sidebar) - (as you show above) - then they can't all be set to "yellow" as a) they aren't actually the same and b) even that is incorrect.

**Comment by fellinga** [comment]
Yes you are right, that was really just to provide an idea of what I meant. I also took a look today and since Angular really only provides "Primary", "Accents" and "Background" (don't think we can use "Warnings" anywhere) it seems as if it might be even better to only update certain values and not all. Like I did in an early commit here:
https://github.com/fellinga/node-red-dashboard/commit/def1f4a851f0e8b19d617d5dd141c91393314b48

This would only update "page-titlebar-backgroundColor" and "widget-textColor", but of course we could add more.
My understanding so far is that all of the --nr-dashboard values are just wrong if the users selects Angular at the moment, correcting some of them would not be a complete solution but it would be an improved solution.

**Comment by dceejay** [comment]
But some being right give a false sense of correctness - as most will be wrong. Not sure what value it brings or how to document it.

**Comment by fellinga** [comment]
The value would be that contrib-ui node creators could still rely those values. Because if they programmed their node like this:

			.myClass1{
				color: var(--nr-dashboard-widgetTextColor);
				background-color: var(--nr-dashboard-pageTitlebarBackgroundColor);
			}
			.myClass2{
				background-color: var(--nr-dashboard-pageTitlebarBackgroundColor);
			}

then Angular Mode is obviously not compatible with that.

It seems as if this a little bit more complex than I thought when I created this issue. Do you think we should leave it as it is?

**Comment by dceejay** [comment]
"could still rely on those values." - well not really if only some of the variables are approximately correct. But we could of course just try it and see - and yes the isDark for Angular should just reflect the setting of light or dark in the sidebar - so that does need to be fixed also.

**Comment by dceejay** [comment]
I have pushed a branch set-css-ang-var that also attempts to fix the isDark. Would be grateful if you get a chance to try them and let me know what you think.

**Comment by fellinga** [comment]
That's pretty good already!! This is definitely a big improvement. Just two ideas:

1. We could follow the current coloring for **widgetTextColor**, which would be:
lessObj["@widgetTextColor"] = (main.isDark === true ? "#EEEEEE" : "#111111");

2. Until now **widgetBackgroundColor** and **page-titlebar-backgroundColor** had the exact same color. I think its good to keep that, and therefore change it to:
lessObj["@widgetBackgroundColor"] = main.angularColors.primary.name;

There is a problem with all the color values that contain a dash, something like light-blue for example does not work if the variable is used like this:

Also (you mentioned this already) the colors are not the exact same since Angular seem to convert them to some RGB values, while the browser just used indigo for example.
I converted all the values to RGB, so if you want to include this Object:

**Comment by dceejay** [comment]
thanks

re 1 - I was copying the colours than Angular actually picked by default - which seems to bee full white and black rather than the ones we use for our theme  - so...   

re 2 - and color names with - in. Yes your solution looks fine - if you care to test and PR it.

**Comment by dceejay** [comment]
@felinga - Merged your fix into master - can you check it before release ? thanks
(also added you to contributors in package.json if that's ok with you)

**Comment by fellinga** [comment]
Just cloned master to another machine - looks good to me.

Of course, my honor to be on the list 👍
