### ISSUE TITLE
opening / closing the group via ui_control does not work after display / hide

### ISSUE THREAD

**Issue by SuperNinja73** [node-red/node-red-dashboard#642]
### What are the steps to reproduce?

https://discourse.nodered.org/t/collapse-expand-open-close-group-via-ui-control/36461/3?u=superninja

### What happens?
![ScreenRecorderProject6](https://user-images.githubusercontent.com/53425740/100387937-90704000-3029-11eb-8ac0-e2788a035a6e.gif)

If we close a group with the ui_control command or with the arrow to the right of the group:
  `msg = {payload:{"group": {"close": [ "testGroupOpenClose_myHtmlCodeExample" ]}}}`

And then we hide the group:
`msg = {payload:{"group": {"hide": [ "testGroupOpenClose_myHtmlCodeExample" ]}}}`

Then we show the group again:
`msg = {payload:{"group": {"show": [ "testGroupOpenClose_myHtmlCodeExample" ]}}}`

So we can no longer open the group. Neither by the arrow (to the right of the group on the dashboard), nor with the ui_control command  : 
`msg = {payload:{"group": {"open": [ "testGroupOpenClose_myHtmlCodeExample" ]}}}`

The group must be open before hiding it if we want it to reappear when we want to show it again.

### What do you expect to happen?
The group must be able to open and close after having hidden it. Whatever position he was before hiding it.

### Please tell us about your environment:
- [ ] Node-RED-Dashboard version: 2.24.1
- [ ] Node-RED version:1.2.6
- [ ] node.js version:10.23.0
- [ ] npm version:6.14.8
- [ ] Platform/OS: raspbian Buster
- [ ] Browser: Chrome on Win10

**Comment by dceejay** [comment]
Can you provide a flow that demonstrates this - I created my own and it's working fine for me of course if I follow the sequence you gave.

**Comment by SuperNinja73** [comment]
Yes this is the flow : 
```[{"id":"3dadcb0.fb1fa36","type":"ui_template","z":"891d9857.40c7e8","group":"4e669598.5ef6dc","name":"nodeRedButton","order":0,"width":"0","height":"0","format":"<!DOCTYPE html>\n<html>\n    <head>\n        <style>\n            .button {\n                background-color: #086A87;\n                border: none;\n                color: white;\n                padding: 16px 32px;\n                text-align: center;\n                text-decoration: none;\n                font-size: 16px;\n                margin: 3px 1px;\n                cursor: pointer;\n                border-radius: 4px;\n            }\n            .button_over:hover {\n                background-color: #187A97;\n                color: white;\n            }\n        </style>\n    </head>\n    <body>\n        <a href=\"https://nodered.org/\" target=\"_blank\" class=\"button button_over\">Node-Red Home</a>\n    </body>\n </html>\n","storeOutMessages":false,"fwdInMessages":true,"resendOnRefresh":false,"templateScope":"local","x":110,"y":1580,"wires":[["b698ed46.36f2a"]]},{"id":"9a129cc4.88c6d","type":"ui_button","z":"891d9857.40c7e8","name":"","group":"1d5d2d12.f1a4b3","order":0,"width":"0","height":"0","passthru":false,"label":"simpleButton","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":260,"y":1620,"wires":[[]]},{"id":"d448649b.2c87f8","type":"ui_template","z":"891d9857.40c7e8","group":"4e669598.5ef6dc","name":"youtube","order":0,"width":0,"height":0,"format":"<!DOCTYPE html>\n<html>\n<body>\n <iframe width=\"540\" height=\"400\"\nsrc=\"https://www.youtube.com/embed/Fl61uiyRQdM\">\n</iframe> \n</body>\n</html>","storeOutMessages":false,"fwdInMessages":false,"resendOnRefresh":false,"templateScope":"local","x":90,"y":1610,"wires":[[]]},{"id":"71910f5a.de751","type":"comment","z":"891d9857.40c7e8","name":"========================== html button ==============================","info":"bouton perso et clic vers site web\n+ iframe d'une video youtube","x":300,"y":1540,"wires":[]},{"id":"947f0972.106f98","type":"function","z":"891d9857.40c7e8","name":"open / close","func":"var load = msg.payload\nvar topic = msg.topic\n\n \nif (load === 0){\nmsg =\n    {\n    payload: {   \n    \"group\": {\n        \"close\": [\n            \"testGroupOpenClose_myHtmlCodeExample\"   \n            ]\n        }}}\n}\nif (load === 1){\n  msg =\n    {\n    payload: {   \n        \"group\": {\n            \"open\": [\n                \"testGroupOpenClose_myHtmlCodeExample\"\n            ]\n        }}}  \n} \n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":220,"y":1710,"wires":[["3af2f2a8.e10d5e"]]},{"id":"3af2f2a8.e10d5e","type":"ui_ui_control","z":"891d9857.40c7e8","name":"","events":"change","x":390,"y":1750,"wires":[[]]},{"id":"4a32a1ca.33e81","type":"inject","z":"891d9857.40c7e8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"num","x":80,"y":1690,"wires":[["947f0972.106f98"]]},{"id":"252ab6ac.b090ba","type":"inject","z":"891d9857.40c7e8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"0","payloadType":"num","x":80,"y":1730,"wires":[["947f0972.106f98"]]},{"id":"f8235f2e.7edc3","type":"function","z":"891d9857.40c7e8","name":"show / hide","func":"var load = msg.payload\nvar topic = msg.topic\n\n \nif (load === 0){\nmsg =\n    {\n    payload: {   \n    \"group\": {\n        \"hide\": [\n            \"testGroupOpenClose_myHtmlCodeExample\"   \n            ]\n        }}}\n}\nif (load === 1){\n  msg =\n    {\n    payload: {   \n        \"group\": {\n            \"show\": [\n                \"testGroupOpenClose_myHtmlCodeExample\"\n            ]\n        }}}  \n} \n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":220,"y":1790,"wires":[["3af2f2a8.e10d5e"]]},{"id":"659fc171.c6ecd","type":"inject","z":"891d9857.40c7e8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"num","x":80,"y":1770,"wires":[["f8235f2e.7edc3"]]},{"id":"fdcb725.b0f2b9","type":"inject","z":"891d9857.40c7e8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"0","payloadType":"num","x":80,"y":1810,"wires":[["f8235f2e.7edc3"]]},{"id":"b698ed46.36f2a","type":"ui_ui_control","z":"891d9857.40c7e8","name":"","events":"all","x":260,"y":1580,"wires":[["287088db.0cb3a8"]]},{"id":"287088db.0cb3a8","type":"debug","z":"891d9857.40c7e8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":380,"y":1580,"wires":[]},{"id":"4e669598.5ef6dc","type":"ui_group","name":"myHtmlCodeExample","tab":"cf789d38.b69fa","order":1,"disp":true,"width":"10","collapse":true},{"id":"1d5d2d12.f1a4b3","type":"ui_group","name":"nothingGroup","tab":"cf789d38.b69fa","order":2,"disp":true,"width":"8","collapse":true},{"id":"cf789d38.b69fa","type":"ui_tab","name":"testGroupOpenClose","icon":"face","order":14,"disabled":false,"hidden":false}]```

**Comment by dceejay** [comment]
Thanks  - weirdly it just seems to be the ui_templates that disappear. Other types in the collapsed section reappear ok.

**Comment by dceejay** [comment]
A partial fix pushed to master (not yet on npm). seems to fix this case but there will be others.

**Comment by SuperNinja73** [comment]
Yes, by setting the size to 10 (for example) and not to Auto, the group reappears again. (Again on v2.24.1) Great. I put the info back in the original Topic.
PS Thanks for the Head and Body info.
