### ISSUE TITLE
Chart loading full data error 

### ISSUE THREAD

**Issue by sebeksd** [node-red/node-red-dashboard#647]
### What are the steps to reproduce?
Pass JSON series/data/labels (formatted like in documentation) into Chart input.

Example (short version, full version contains more then 3 values in "data"):
`[
	{
		"series": [
			"OutdoorTemp"
		],
		"data": [
			[
				{
					"x": 1607036412000,
				}
					"y": -3.3
			],
			[
				{
					"x": 1607036532000,
					"y": -3.3
				}
			],
			[
				{
					"x": 1607036712000,
					"y": -3.2
				}
			]
		],
		"labels": [
			""
		]
	}
]`

Example (exact data):
[ChartData.txt](https://github.com/node-red/node-red-dashboard/files/5648761/ChartData.txt)

### What happens?
![Obraz ze schowka (9)](https://user-images.githubusercontent.com/18705953/101280207-204f8000-37c8-11eb-9ad5-ec5abe0a1c56.png)

### What do you expect to happen?
Display chart data correctly (like in v.0.23.3)

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.24.2
- [x] Node-RED version: 1.2.5
- [x] node.js version: 10.23.0
- [x] npm version: 6.14.8
- [x] Platform/OS: official Node-Red docker image running on Debian Buster
- [x] Browser: Chrome

### Full "story":
I'm using node-red for years, today I upgraded dashboard from 2.23.3 to 2.24.2 (before that I read change log to see if there is anything that can break), after restart my charts didn't load from DB, I've got an warning on debug "Bad data inject", I was vaguely remembering that I was using old format so I blame it on that and redone my scripts to use new format (even when there was no mention in changelog that node-red-dashboard dropped support for old format!).
After changing my scripts to output new format like in chart documentation I'm now getting strange results as shown on screenshot. Whats going on, is it a bug, something not documented correctly or maybe my fault ?

**Comment by dceejay** [comment]
Hi

sorry about that. You are almost there with the newer format...

the short version should look like this
```
msg.payload = [ 
    { 
        "series": [ "OutdoorTemp" ], 
        "data": [ 
            [ 
                { "x": 1607036412000,  "y": -3.3 },
                { "x": 1607036532000, "y": -3.3 },
                { "x": 1607036712000, "y": -3.2 } 
            ] 
        ], 
        "labels": [ "" ] 
        
    } 
]
```

the only slight difference being in between each data pair
eg `{"x":1607036412000,"y":-3.3}**]**,**[**{"x":1607036532000,"y":-3.3}`
you have an extra pair of ] [ braces... which makes them each into separate series - hence the massive legend you are seeing...
 they all need to be like `...,{"x":1607036412000,"y":-3.3},{"x":1607036532000,"y":-3.3},.... `

**Comment by sebeksd** [comment]
Thanks, it's working now :)

I was thinking that data was grouped
['A', 'B', 'C'], ['A', 'B', 'C'], ['A', 'B', 'C'] 
but it's looks like it is
['A', 'A', 'A'], ['B', 'B', 'B'], ['C', 'C', 'C'] (which is much more logical).

Not sure why I was thinking that first one was correct. Thanks again.
