### ISSUE TITLE
Chart not updating and theme undefined in console

### ISSUE THREAD

**Issue by colinl** [node-red/node-red-dashboard#650]
### What are the steps to reproduce?

From forum - https://discourse.nodered.org/t/dashboard-empty-in-ui/37492/2

Stop node-red, remove any flows file, ensure node-red-dashboard is installed and restart node-red.
Refresh the browser to show the empty flow.
Import the flow below (courtesy of @Steve-Mcl) and Deploy.
Open the dashboard and click the button.  The chart does not update and in the browser console can be seen the error
`TypeError: o.theme is undefined`

Even if a new chart is added it still does not show anything.

I was hoping that this would replicate the error seen occasionally `TypeError: Cannot read property 'themeState' of undefined` but it doesn't.  I suspect this error may well be related however.

```
[{"id":"2fc607c3.337dd8","type":"ui_chart","z":"64ce1d00.d049e4","name":"","group":"2fda441c.bc393c","order":1,"width":0,"height":0,"label":"chart","chartType":"line","legend":"false","xformat":"HH:mm:ss","interpolate":"linear","nodata":"","dot":false,"ymin":"","ymax":"","removeOlder":"10","removeOlderPoints":"","removeOlderUnit":"1","cutout":0,"useOneColor":false,"useUTC":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"outputs":1,"x":1110,"y":220,"wires":[[]]},{"id":"4e7a5d6d.8cd514","type":"ui_button","z":"64ce1d00.d049e4","name":"","group":"2fda441c.bc393c","order":0,"width":0,"height":0,"passthru":false,"label":"button","tooltip":"","color":"","bgcolor":"","icon":"","payload":"","payloadType":"str","topic":"","x":750,"y":220,"wires":[["641a70a.fc5dc9"]]},{"id":"389cdf43.3602a","type":"ui_numeric","z":"64ce1d00.d049e4","name":"","label":"numeric","tooltip":"","group":"2fda441c.bc393c","order":2,"width":0,"height":0,"wrap":false,"passthru":true,"topic":"","format":"{{value}}","min":0,"max":10,"step":1,"x":1120,"y":280,"wires":[[]]},{"id":"6ec79e30.d3872","type":"ui_gauge","z":"64ce1d00.d049e4","name":"","group":"2fda441c.bc393c","order":3,"width":0,"height":0,"gtype":"gage","title":"gauge","label":"units","format":"{{value}}","min":0,"max":10,"colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":1110,"y":340,"wires":[]},{"id":"41b5a030.9bdf3","type":"debug","z":"64ce1d00.d049e4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":400,"wires":[]},{"id":"641a70a.fc5dc9","type":"change","z":"64ce1d00.d049e4","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"($random() * 10)  + 1","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":900,"y":220,"wires":[["2fc607c3.337dd8","389cdf43.3602a","6ec79e30.d3872","41b5a030.9bdf3"]]},{"id":"2fda441c.bc393c","type":"ui_group","name":"Default","tab":"d1171ce9.84d9","order":1,"disp":true,"width":"6","collapse":false},{"id":"d1171ce9.84d9","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]
```

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 1.2.6
- [ ] Node-RED version: 2.25.0
- [ ] node.js version: 12.20.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Ubuntu 20.04
- [ ] Browser: Waterfox

**Comment by hotNipi** [comment]
I'll try to describe repro case
Requirements: node-red-dashboard installed 
Start node red with empty flows and zero configuration nodes.
Open the Config tab
NB! Do not change the tab to dashboard during the test  
Drag in the chart node.
Double-click to open config page and follow the tab and group configuration path. Create them with default values.
Press Done
Press Deploy (all).

In browser, open new tab and type manually (or use what browser remembers) and open the ui.
Open dev tools and the error is here.

```
app.min.js:150 TypeError: Cannot read property 'themeState' of undefined
    at loadConfiguration (app.min.js:604)
    at app.min.js:604
    at m.$digest (app.min.js:174)
    at m.$apply (app.min.js:177)
    at app.min.js:193
    at Yg.completeTask (app.min.js:189)
    at app.min.js:73
```
In the editor, at this point  there is no ui_base configuration created
![image](https://user-images.githubusercontent.com/35291460/102120134-c34c6d80-3e4a-11eb-9e93-58990706d88c.png)
If you navigate to the the dashboard tab, the deploy button goes red and the ui_base config is created. But the error still stays, probably the cached situation in browser is kind of broken.

**Comment by dceejay** [comment]
@hotNipi @colinl Ok - have pushed a change to master to ensure the base node is available early... well ok  in fact it now creates it when the editor is created... So this should nail this... BUT the downside is that if you have dashboard in your palette - it will end up creating a base node in your flow whether you use the dashboard or not. (Not actually a big problem - but is just cruft in your flow).

**Comment by hotNipi** [comment]
Will do tomorrow

**Comment by dceejay** [comment]
Updated with slightly better fix - now no longer forces itself in every time - only when you add a widget to a tab.

**Comment by hotNipi** [comment]
Success. 
Tested cases: 
1. drag in 1 node without visiting the dashboard tab (chart, gauge, text, artless-gauge, button) 
2. import flow to the zero config situation (single node, complex flow, multi tab flow, random flow from discourse)

**Comment by dceejay** [comment]
Thanks - is this the same use/test case as @colin ?
(I think so but just checking)

**Comment by colinl** [comment]
Also working for me for the case described in the original description.  Thanks.

**Comment by gregbradley** [comment]
Maybe related to this [issue](https://github.com/hassio-addons/addon-node-red/issues/1096).
