### ISSUE TITLE
Bootstrap Collapsable List-group stop working in template node

### ISSUE THREAD

**Issue by gidoUninova** [node-red/node-red-dashboard#652]
### What are the steps to reproduce?

Adding bootstrap to dashboard template node and create a collapsable list-group.

### What happens?

The list works fine, when clicked it opens the group and when clicked again the group is collapsed. However, If I change tab and after go back to the tab of the list-group, the list only open, i.e. when clicked it opens the groups but when clicked again the group is not collapsed, but if the page is refreshed the list-group starts working again as it expected.

### What do you expect to happen?

Actually the list-group should always work even if I navigate through the tabs.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.25.0
- [ ] Node-RED version: 1.26.1
- [ ] node.js version: v12
- [ ] npm version:
- [ ] Platform/OS: in docker as well as MacOs
- [ ] Browser: Safari and Firefox (I have nnot tested in Chrome)

https://user-images.githubusercontent.com/7241756/102685879-93e78900-41db-11eb-9159-4d846ed8fdc7.mov

**Comment by knolleary** [comment]
You'll need to provide some actual code if you want us to look at this. We don't provide bootstrap or make any claims about using it in a template node.

**Comment by gidoUninova** [comment]
Thank you very much for your prompt answer. I found the problem and it is actually related to the way I am using the ui_emplate node. In particular the way external libraries should be imported. I will close the issue.
