### ISSUE TITLE
Dragging of elements in layout editor not working

### ISSUE THREAD

**Issue by jensrossbach** [node-red/node-red-dashboard#666]
### What are the steps to reproduce?
- Create some dashboard with UI elements.
- Open the layout editor to modify the layout of a tab.
- Try to drag elements inside the available area.

### What happens?
- Elements do not move.
- Label texts of elements get selected/highlighted.

### What do you expect to happen?
- Elements should move to a new position following mouse moves.

### Please tell us about your environment:

- [x] Node-RED-Dashboard version: 2.26.1
- [x] Node-RED version: 1.2.6
- [x] node.js version: 12.20.0
- [x] npm version: 6.14.8
- [x] Platform/OS: Raspberry PI / Linux
- [x] Browser: Chromium-based Microsoft Edge

### Additional information:
Problem is only reproducible on Chromium-based Microsoft Edge. Everything is working well on Google Chrome, Mozilla Firefox and Opera.

**Comment by dceejay** [comment]
So where is Edge running ? If I use version Version 87.0.664.66 (Official build) (64-bit) on Win 10 it is working fine...

**Comment by jensrossbach** [comment]
I'm using Microsoft Edge version 87.0.664.66 (64-bit) on Windows 10 version 20H2 (build 19042.685).

**Comment by jensrossbach** [comment]
Surprisingly, today it is working now also in Edge on my side while it didn't work all the time in the past. I will keep an eye on this, if it remains working, the ticket can be closed.

**Comment by rz7k9k** [comment]
just discoverd that this is NOT working with Edge. Windows 11 Enterprise
22H2  OS BUILD  22621.1413

**Comment by rz7k9k** [comment]
haha, i checked edge version now. edge says restart for update, and it is working now .
