### ISSUE TITLE
Adding a warning when the node-red server go's offline.

### ISSUE THREAD

**Issue by nielsnl68** [node-red/node-red-dashboard#67]
When the node-red server go's offline you get a warning message in the editor about it. 
It would be nice to have the same message in the dashboard ui as well.

**Comment by dceejay** [comment]
so - should this just be the existing (Dashboard) toast/notification popup - so that in future it can be styled as part of the theme ?
Or different to be "obvious" ?
Or not a toast at all ?

**Comment by nielsnl68** [comment]
I think, Just the same as in the editor. Otherwise i let it be on you guys to deside. As long it is clear that the dashboard has lost his connection with the server.

**Comment by Paul-Reed** [comment]
I'd of thought that the existing (Dashboard) toast/notification popup would give more flexibility.

**Comment by dceejay** [comment]
Easy enough to do a toast... 
![image](https://cloud.githubusercontent.com/assets/5375409/19113682/b5a0332e-8b02-11e6-9b9e-965e75243a6c.png)
stays for 100 mins (or whatever we want), cleared when connection returns...  
but is that adequate ? Could it be better ? other options ?

**Comment by nielsnl68** [comment]
Not of this is possibly or not. Do you have the option of other background colors like red or something like that. other then it looks okay to me.

**Comment by Paul-Reed** [comment]
Looks good to me as it is. IMO a red background may be too intrusive.

Paul

**Comment by dceejay** [comment]
hmm - not liking the red idea so much - even when tamed down...
![image](https://cloud.githubusercontent.com/assets/5375409/19131933/4d35e79c-8b49-11e6-834e-2cb75287b5e8.png)
![image](https://cloud.githubusercontent.com/assets/5375409/19132020/ac4f27ac-8b49-11e6-8823-5f62ab88756b.png)
![image](https://cloud.githubusercontent.com/assets/5375409/19132274/b451d868-8b4a-11e6-9296-3d677ab8e52f.png)
orangey-yellow may be a bit less shouty
![image](https://cloud.githubusercontent.com/assets/5375409/19132316/d03bfff4-8b4a-11e6-960e-fff0c639b32f.png)
or just plain white ???

**Comment by Paul-Reed** [comment]
The red text would be my preferred option.
red = important
...and it's important if you're accessing stale data.

Paul
