### ISSUE TITLE
dashboard 2.26.2 Button text color not accepted

### ISSUE THREAD

**Issue by IngoDe** [node-red/node-red-dashboard#670]
### What are the steps to reproduce?
I updated to dashboard 2.26.2
Setup a button like this:

![210118_button_issue](https://user-images.githubusercontent.com/76224345/104909002-89114700-5987-11eb-91b7-d2be4bc8f9a5.png)

### What happens?
the result is:

![210118_button_result](https://user-images.githubusercontent.com/76224345/104909072-9f1f0780-5987-11eb-98a9-2bb175b7c81c.png)

### What do you expect to happen?
Textcolor is always white, I tested it with various buttons on different flows.
I expected that text appears in the chosen color.

### Please tell us about your environment:
[info] Node-RED Version: v1.2.6
[info] Node.js  Version: v10.19.0
[info] Linux 5.4.0-62-generic x64 LE
[info] Dashboard version 2.26.2 started at /ui

 Browser: Chromium Version 87.0.4280.141 (Offizieller Build) snap (64-Bit)

Thanks in advance to the team, sorry I have not too much experience in reporting issues.

**Comment by dceejay** [comment]
mea culpa - apologies...
fixed in master
