### ISSUE TITLE
Feature request: text control option to append rather than replace text, so that it can act as a debug window.

### ISSUE THREAD

**Issue by ghuser** [node-red/node-red-dashboard#672]
### What are the steps to reproduce?

Connect the text control to some payload generating control, or even to tail (from a file that is constantly growing)

### What happens?

You only see one line at a time.

### What do you expect to happen?

A new control (e.g. log-text), or an option in text control, to append each newly received payload, rather than replacing.

This way we have a debug window (in the dashboard) which can show whatever we want to send to it.
Note: an additional option like max-line-buffer would probably be required also.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.27.0
- [ ] Node-RED version: 1.2.7
- [ ] node.js version: v12.20.1
- [ ] npm version: 6.14.10
- [ ] Platform/OS: Raspbian 10.7
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
the ui_text widget is meant to be a simple single line of text type widget. For much more complicated multi-line text you can easily use a ui_template node, preceded by a function node to accumulate the data as you wish. As you indicate there can be many extra parameters that could/would be needed to handle things like number of lines visible, overflow, formatting/line splits, resetting/clearing - and so on - which can be easily customised in a function node plus ui_template.
