### ISSUE TITLE
Menu doesn't hide on mobile after selecting an option (Moves content to the right).

### ISSUE THREAD

**Issue by juancgalvez** [node-red/node-red-dashboard#674]
### What are the steps to reproduce?

Simply activating menu and selecting an option.

### What happens?

After selecting an option from the menu, it never hides again.

### What do you expect to happen?

The menu should hide after I choose an option.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.27.0
- [ ] Node-RED version: 1.2.7
- [ ] node.js version: 12.14.1
- [ ] npm version: 6.13.4
- [ ] Platform/OS: Server: Raspbian (Debian) buster, Client: Android 9.
- [ ] Browser: Firefox 85.1.1

**Comment by dceejay** [comment]
I don't see Firefox 85 in the app store yet. Works fine with 84 on Android 9 for me.

**Comment by juancgalvez** [comment]
Believe me. I am using Firefox 85.1.1 on my Android 9 Samsung Galaxy A50 phone (In Spanish).

What Node-RED and Node-RED_Dashboard versions are you using?

The issue can also be reproduced using **Firefox 85,0 (64 bits)** on Windows 10 when configured in **Responsive Design Mode** (pressing CTRL+SHIFT+F12) emulating iPhone X/XS iOS 12 Safari 12. The same happens with **Chrome Version 81.0.4044.113 (Official Build) (64-bit)** on Windows 10 (Pressing CTRL+SHIFT+M).

**Comment by juancgalvez** [comment]
Issue solved. I upgraded Node-RED and Node-RED-Dashboard a couple of days ago and the problem appeared. Redeploying fixed the issue. Thank you @dceejay for your support.

**Comment by dceejay** [comment]
Thanks for letting me know.
