### ISSUE TITLE
UI dropdown - Unable to set a preselected option

### ISSUE THREAD

**Issue by giuseppeg88** [node-red/node-red-dashboard#675]
### What are the steps to reproduce?

Send a msg (with a string in msg.payload) to a dropdown node.

### What do you expect to happen & what happens?

Until the release 1.2.5, the dropdown node was correctly updated with the text contained in the received payload.
With the new release (1.2.7) this does not happen.

### Please tell us about your environment:

- [ ] Node-RED version: 1.2.7
- [ ] Platform/OS: Windows 10
- [ ] Browser: Chrome 88.0.4324.104

**Comment by number005** [comment]
As this is closed I guess its solved from 2.28.0 on? Right?

**Comment by knolleary** [comment]
@number005 yes. The commit that closed this issue was included in 2.28
