### ISSUE TITLE
add vue and apache echarts

### ISSUE THREAD

**Issue by cmdares** [node-red/node-red-dashboard#681]
It is suggested to use Vue as the basic framework and echarts as the overall charts control.
Ecarts has rich components and many control parameters.
I hope the community can upgrade.
Thanks.

**Comment by knolleary** [comment]
Hi @cmdares 

Please use the issue template. This is not the first time I have asked you to do this.

There are no plans to change the underlying framework of Dashboard. That would be a complete rewrite and a whole new dashboard that is not backward compatible in any way.

We so not have the time and resources to do that.

If you want to raise future feature requests, as the template describes, please do so on the community forum.
