### ISSUE TITLE
Slider send null, om release

### ISSUE THREAD

**Issue by E1cid** [node-red/node-red-dashboard#682]
### What are the steps to reproduce?
Run provided flow
`[{"id":"da442025.20f108","type":"ui_slider","z":"5a245aa1.510164","name":"on release","label":"slider","tooltip":"","group":"8b5cde76.edd58","order":4,"width":0,"height":0,"passthru":false,"outs":"end","topic":"","min":0,"max":10,"step":1,"x":250,"y":1720,"wires":[["e5852e4d.53c5c"]]},{"id":"e5852e4d.53c5c","type":"debug","z":"5a245aa1.510164","name":"release np","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":450,"y":1720,"wires":[]},{"id":"8b5cde76.edd58","type":"ui_group","name":"","tab":"8f03e639.85956","order":1,"disp":true,"width":"6","collapse":false},{"id":"8f03e639.85956","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]`
### What happens?
when slider is moved, it moves by self to far left and displays Nan. Debug payload is null
### What do you expect to happen?
For it to move and display position, and debug payload to be a number from 1-10
### Please tell us about your environment:

- [ ] Dashboard 2.28.0
- [ ] Node-RED version: 1.2.9
- [ ] node.js version: 12.13
- [ ] npm version: ?
- [ ] Platform/OS: android 8+ 
- [ ] Browser Firefox

**Comment by dceejay** [comment]
When you say platform is android 8 - is that the browser device or the server ?
If I use Android 9 device I have it is working fine with chrome and firefox and firefox beta browsers pointed at either Mac or Pi running Node-RED.

**Comment by E1cid** [comment]
Node-red running on android 8 via termux, browser on another machine android 8 using firefox

**Comment by dceejay** [comment]
termux is not really a supported environment - if it works great - if not then will need someone to dig into it... which may or may not happen.

**Comment by E1cid** [comment]
Ok, no problem, I am betting it is a browser issue. Will check others, but i never liked the feel of any others , to many clicks. I will report back if issue is browser related

**Comment by dceejay** [comment]
hmm - managed to install nodejs 14 on termux on Android 9 - still fine on Firefox and chrome when browsing locally - or via pc back to android.

**Comment by E1cid** [comment]
Ok yes it appears to be firefox on my android device, may be javascript issue, working on firefox focus, and brave. Not much you can do about this then i will close issue
