### ISSUE TITLE
Empty dropdown node causes node red to crash

### ISSUE THREAD

**Issue by jha-sudo** [node-red/node-red-dashboard#684]
npm -v: 7.5.4

reproduce steps: 
1 add dropdown node to flow
2. leave connections empty
3. assign to group
4. go to dashboard
5. click on dropdown

output:
\node_modules\node-red-dashboard\nodes\ui_dropdown.js:178
                    msg.payload = emitOptions.value;
                                              ^

TypeError: Cannot read property 'value' of undefined
    at Object.beforeSend (C:\Users\.....\node_modules\node-red-dashboard\nodes\ui_dropdown.js:178:47)
    at EventEmitter.handler (C:\Users\....\node_modules\node-red-dashboard\ui.js:285:22)
    at EventEmitter.emit (events.js:215:7)
    at Socket.emit (events.js:210:5)
    at C:\Users\.....\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
 node-red-dashboard@2.28.1
- [ ] Node-RED version:
node-red@1.2.9
- [ ] node.js version:
 v12.13.0
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:

**Comment by knolleary** [comment]
Can you fill in some of the version numbers in the template? Most importantly is the dashboard version you are hitting this with.

**Comment by jha-sudo** [comment]
Updated. I tried doing a pull request with a potential fix. I don't have permission. Which is fine. 

I changed line 34 in nodes\ui_dropdown.js to 
`var emitOptions = { value: undefined };`

and haven't been able to reproduce the error after.

**Comment by knolleary** [comment]
You can't push to this repo directly so you'll need to fork it first, push the fix to your repo and then open the PR over to this repo.

**Comment by dceejay** [comment]
closed by #686
