### ISSUE TITLE
ui_button sending wrong topic when configured as empty string

### ISSUE THREAD

**Issue by colinl** [node-red/node-red-dashboard#687]
### Steps to reproduce?
Import the flow below and deploy.
Click the dashboard button and note the debug output
Click the inject node then the dashboard button again. Note the debug output.

### What happens?
On the first press the button sends a message with no topic.
On the second button press, after firing the inject, the topic in the sent message is that which was sent in via the inject node.  So the operation is as if the configuration for the topic in the button had been set to `msg.topic`.

### What do you expect to happen?
The sent message should not contain a topic

### Please tell us about your environment:

- Node-RED-Dashboard version: 2.28.1
- Node-RED version: 1.2.9
- node.js version: 12.21.0
- npm version: 6.14.11
- Platform/OS: Ubuntu 20.04
- Browser: Waterfox

```
[{"id":"feced108.12695","type":"ui_button","z":"37f5b818.697af8","name":"","group":"d20ab961.4f8e68","order":3,"width":"3","height":"1","passthru":false,"label":"Press  me","tooltip":"","color":"","bgcolor":"","icon":"","payload":"Button pressed","payloadType":"str","topic":"","topicType":"str","x":240,"y":840,"wires":[["d66390c7.30c458"]]},{"id":"ce4918b2.2f33b","type":"inject","z":"37f5b818.697af8","name":"setup","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"TOPIC_FROM_INJECT","payload":"payload from inject","payloadType":"str","x":90,"y":840,"wires":[["feced108.12695"]]},{"id":"d66390c7.30c458","type":"debug","z":"37f5b818.697af8","name":"Button output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":410,"y":840,"wires":[]},{"id":"d20ab961.4f8e68","type":"ui_group","name":"Group 3","tab":"9979cb8a.2a3238","order":3,"disp":true,"width":6},{"id":"9979cb8a.2a3238","type":"ui_tab","name":"TEST","icon":"dashboard","order":20,"disabled":false,"hidden":false}]
```

**Comment by colinl** [comment]
I note that this not only fixes the issue if a message is passed into the node, but also changes the behaviour if an empty string is configured, but no message is fed in. 
On 2.28.1 if an empty string is configured for the topic (which will be the situation for anyone who upgraded from earlier versions before the typed input was introduced) then, provided no message is passed to the node, the messages sent will contain no topic.  With this change a topic containing an empty string is sent which could cause existing flows to fail.

**Comment by colinl** [comment]
There has been a further commit to fix the behaviour if an empty string is configured, but unfortunately that seems to have broken the operation when Passthrough is not set and a msg property is defined for the topic.  In this flow, if the Inject node is triggered and then the button pressed the message sent should have the property set to topic1, but it has no topic at all.
```
[{"id":"233a4bbc.3b1b64","type":"debug","z":"37f5b818.697af8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":470,"y":720,"wires":[]},{"id":"58a81137.6c262","type":"ui_button","z":"37f5b818.697af8","name":"","group":"d20ab961.4f8e68","order":3,"width":0,"height":0,"passthru":false,"label":"button topic test","tooltip":"","color":"","bgcolor":"","icon":"","payload":"1","payloadType":"str","topic":"test","topicType":"msg","x":320,"y":720,"wires":[["233a4bbc.3b1b64"]]},{"id":"57e7e1be.269268","type":"inject","z":"37f5b818.697af8","name":"msg.test: topic1","props":[{"p":"test","v":"topic1","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"str","x":120,"y":720,"wires":[["58a81137.6c262"]]},{"id":"d20ab961.4f8e68","type":"ui_group","name":"Group 3","tab":"9979cb8a.2a3238","order":3,"disp":true,"width":6},{"id":"9979cb8a.2a3238","type":"ui_tab","name":"TEST","icon":"dashboard","order":20,"disabled":false,"hidden":false}]
```

**Comment by dceejay** [comment]
actually this is a different issue :-) - I wasn't saving the property that you actually asked for (msg.test in this case)- it was always saving msg.topic. But now pushed a ix for that also.
