### ISSUE TITLE
CSS variable not declared

### ISSUE THREAD

**Issue by bonanitech** [node-red/node-red-dashboard#688]
I noticed that the CSS variable `--nr-db-mid-grey` found on lines [153](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_base.html#L153) and [208](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_base.html#L208) in [nodes/ui_base.html](https://github.com/node-red/node-red-dashboard/blob/master/nodes/ui_base.html) is not declared anywhere.

**Comment by dceejay** [comment]
Thanks - well spotted.
