### ISSUE TITLE
Is it posible to add output to Audio Out node???

### ISSUE THREAD

**Issue by midnight1979** [node-red/node-red-dashboard#689]
i need to some audio alerts in my system and my flow send several audio files to "audio out" node.
I need to know when audio playing will ended for send next "voice message" (otherwise the sounds are superimposed on each other) - how i can do this? 
Maybe (if it's not very hard) add one output to "audio out" node with status messages sending?

**Comment by dceejay** [comment]
The node already provides status below the node - this can be caught by using a status node configured to point at the audio node - the data arrives on msg.status

**Comment by midnight1979** [comment]
sorry really didn't think about that
