### ISSUE TITLE
how to use apach echarts on template node

### ISSUE THREAD

**Issue by PmcFizz** [node-red/node-red-dashboard#696]
hi
how to use echarts on template node ?
do you have a example ?

when i add ` <script src="https://cdn.jsdelivr.net/npm/echarts@5/dist/echarts.min.js"></script>`

then  `var myChart = window.echarts.init(document.getElementById('main'));`

the error happen 

no init function

**Comment by knolleary** [comment]
Please use the issue template.

For general how-to questions, please use the forum linked from the template - discourse.nodered.org.

**Comment by PmcFizz** [comment]
thanks
