### ISSUE TITLE
Text input/Time picker shows time in wrong format (am/pm instead of 24h) on iOS 14.5

### ISSUE THREAD

**Issue by kwithus** [node-red/node-red-dashboard#698]
### What are the steps to reproduce?
I‘ve implemented a text input field / time picker on my dashboard and display the dashboard on iPad / iPhone under iOS 14.5

### What happens?
When I click the field I do get the input field in 24 hrs format, however after hitting ok the time is shown in 12 hrs format without am/pm
### What do you expect to happen?
I would like to see the display in 24h format

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:2.29.0
- [ ] Node-RED version: redmatic 7.2.1
- [ ] node.js version:
- [ ] npm version:
- [ ] Platform/OS:iOS 14.5
- [ ] Browser:Safari on iOS 14.5

**Comment by dceejay** [comment]
the rendering of the text input under html is dependent on the device browser and locale - see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time
so I don't think there is anything we can do about it.

**Comment by kwithus** [comment]
First thanks for fast answer. Well, I already assumed that it is more browser related, however being no as good in html etc. I wondered whether there are other reasons as well. I do have the same issue in Safari on IOS and in Chrome on iOS , furthermore when I change settings in iOS to 12hrs, refresh and set it back to 24hrs and refresh, the display is accurate, anyhow only for a inconsistent long period of time.
I just want to be sure before I (try to) report to Apple

**Comment by dceejay** [comment]
well you should be able to also test it on other pages like the one linked above.

**Comment by kwithus** [comment]
Shows the same bug, so it must be related to iOS / iPadOS. I‘ve reported it to Apple. Thanks again
