### ISSUE TITLE
Default margin on template 

### ISSUE THREAD

**Issue by dceejay** [node-red/node-red-dashboard#7]
the default inner margin on the template node is 0
![image](https://cloud.githubusercontent.com/assets/5375409/15164441/9eacab18-1706-11e6-9ee1-ed682d22f197.png)
which doesn't look great - I know it's the template so can be hacked as I wish - but it would be nice if the default looked basically OK to start with.

**Comment by natcl** [comment]
I'm also not too sure about that think gray line to separate groups, the old UI looked better in my opinion...

**Comment by dceejay** [comment]
all sorted by recent updates. Thanks @jdp1g09
