### ISSUE TITLE
dropdown input works only first time

### ISSUE THREAD

**Issue by brnnrc** [node-red/node-red-dashboard#70]
Hi,
setting 'msg.payload' will pre-select the value in the dropdown... only first time!
I think the line
`return emitOptions.isOptionsValid ? emitOptions : undefined; `
should be
`return emitOptions.isOptionsValid || emitOptions.fromInput ? emitOptions : undefined; `
otherwise setting the payload from input node does not fires the return.

**Comment by dceejay** [comment]
is this on master version 2.0.3 ? or npm 2.0.2 ?

**Comment by brnnrc** [comment]
I'm on 2.0.2 but the bug seems to be in 2.0.3 too. When You deploy,  first inject sets the default dropdown value. Other injects (with other values) don't set dropdown value and don't go to output...

**Comment by brnnrc** [comment]
`[{"id":"3832e0c0.5a31","type":"inject","z":"d05b3dd0.44a5a","name":"","topic":"0","payload":"off","payloadType":"str","repeat":"","crontab":"","once":false,"x":93.75,"y":314.375,"wires":[["89fae30.c15b6a"]]},{"id":"fd8de91f.a498c","type":"inject","z":"d05b3dd0.44a5a","name":"","topic":"1","payload":"on","payloadType":"str","repeat":"","crontab":"","once":false,"x":96.875,"y":286.25,"wires":[["89fae30.c15b6a"]]},{"id":"89fae30.c15b6a","type":"ui_dropdown","z":"d05b3dd0.44a5a","name":"","label":"control","group":"1bb99985.663e56","order":0,"width":"3","height":"1","options":[{"label":"on","value":"on"},{"label":"off","value":"off"}],"payload":"","topic":"","x":108,"y":366.0000305175781,"wires":[["7bd26695.2ca718","ba96aadd.1bdd4"]]},{"id":"ba96aadd.1bdd4","type":"debug","z":"d05b3dd0.44a5a","name":"","active":true,"console":"false","complete":"payload","x":576.75,"y":396.75,"wires":[]},{"id":"1bb99985.663e56","type":"ui_group","z":"d05b3dd0.44a5a","name":"termostato","tab":"5a509af6.c3dd74","disp":true,"width":"6"},{"id":"5a509af6.c3dd74","type":"ui_tab","z":"d05b3dd0.44a5a","name":"Home","icon":"dashboard"}]`

**Comment by pelis** [comment]
In your flow, you are just trying to change the selection of the dropdown.
You are not trying to change the options - is this what you are trying to achieve?
Why would you do that rather than just passing 'on' or 'off' to the node connected to your dropdown?

**Comment by brnnrc** [comment]
Correct! I want not change the options but the current selection based on programmatic settings.
If I pass 'on' or 'off' to the node connected to dropdown output (debug in this example), the dashboard does not show the correct dropdown status.
So, the idea is: input node can change current dropdown status, You can see current status in dashboard and change it if you want.

**Comment by dceejay** [comment]
hmmm - that works for me...
http://recordit.co/ofqDKzfb1a

**Comment by brnnrc** [comment]
I see: It is wonderful but not for me! I reinstalled node-red-dashboard (npm) too,  I don't get the debug output you have...
If I change the code it works. I digged deeper and:
if I reload the dashboard page, I get the debug output then I push the inject and I get the correct debug output. If I push the inject again nothing happens... Any idea?
So, it seems a personal issue. sorry

**Comment by dceejay** [comment]
yeah - going to be tricky if I can't replicate... - 
what platform ? OS ? Browser ?

**Comment by brnnrc** [comment]
I know! I'm on ubuntu 15.10 virtual machine, node-red 0.14.6, node.js 6.6.0, dashboard 2.0.2, chrome or mozilla tested.
I reinstalled all the environment starting from npm down to dashboard... nothing.
Looking in the code: it seems if you send a msg.payload to dropdown but not msg.option, the node does not return a msg. I can wrong! Let me know. Thanks a lot
Enrico

**Comment by dceejay** [comment]
Hi,

ok have checked your flow on my VM - (Ubuntu 16.04 - Node-RED 0.14.6 and Dashboard 2.0.3) -and yes it all still works for me - are you sure when you tried 2.0.3 dashboard you reloaded the page a few times to flush the browser cache ?

**Comment by brnnrc** [comment]
OK I installed dashboard 2.1.0 and no issue! Reinstalled 2.0.2 and the issue was back. Thanks a lot!
