### ISSUE TITLE
Form gets cleared after saving data since Version 2.29.1

### ISSUE THREAD

**Issue by emc02** [node-red/node-red-dashboard#701]
### What are the steps to reproduce?
Fill data to "form", click save

### What happens?
form is getting empty and after refresh of the browser window, the old values reappear
The new values are sent to the next node, but the values are not "stored" in the form itself
On Version 2.28.1 everything worked fine!

### What do you expect to happen?
form stays at new entered values

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.29.1
- [ ] Node-RED version: v1.3.5
- [ ] node.js version: v12.22.1
- [ ] npm version: 6.14.12
- [ ] Platform/OS: RaspiOS
- [ ] Browser: Chrome and Firefox

**Comment by dceejay** [comment]
Yes. It makes more sense to clear the form ready for next input once you submit it.
If you really do want the old values back you can feed them back into the input (you will need to go via a dummy node as you can't link output to input directly).

**Comment by emc02** [comment]
was this changed in Version 2.29.1?
I am feeding the old values back, if someone enters wrong values, but that isn't working too. It just works once after starting nodered. With the same configuration but Version 2.28.1 everything works fine.

**Comment by dceejay** [comment]
Yes it was changed to clear the values properly when you hit clear - Issue #692

**Comment by emc02** [comment]
ok, but they are cleared when I hit "save". Clearing worked good for me in previous versions

**Comment by dceejay** [comment]
They were (or should have been) always cleared - but they shouldn't come back on refresh - which is what the the previous fix was for.  If say I entered my secret details then hit save and the form goes blank... all good. hit refresh should not bring back my secret details for the next person to see.

**Comment by emc02** [comment]
ok, that makes sense, but in my case I am filling the form with data on Startup (from PersistStore).
On pressing Save in the form (with or without editing data), it gets cleared, but on refreshing the page (without refilling the form from persiststore or anything else) the data is back again!
Interesting point here is, when editing the data, the "new" data is sent and form is cleared, but on refreshing the page, the "old" data is visible and can't be updated by resending new data to the form.

**Comment by dceejay** [comment]
errr - ok - now I'm confused :-)... any chance you can share the relevant part of your flow so I can see if it's the same here ?

prefill - should work
save - should then clear it. - and stay cleared. - but the refresh may retrigger a prefill if that is how you set it up. (but should be the prefill data not the new data just sent unless you are saving that back to the persist.
Sending in any new data should update the fields.
