### ISSUE TITLE
Form Element of type 'Multiline' has extra rows above 1 row and entries progressively encroach on the label

### ISSUE THREAD

**Issue by Dowster64** [node-red/node-red-dashboard#703]
Hi All,
I have looked for this issue and it does not appear to have been raised.  Thank you for looking at this.

*Note* negative row numbers are allowed

### What are the steps to reproduce?
Create a simple form with elements of type multiline, choose rows above 1 and test (example below)
### What happens?
Rows above 1 have the following actual rows before scroll bars appear:
1 -> 1
2 -> 3
3 -> 5
4 -> 6
(not tested further)
Also the entry text incrementally encroaches on the label text as rows are added.
### What do you expect to happen?
Multiline element to respect the rows selected (until exceeded and then scroll) and not cover part of the label

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 2.28.2, 2.29.0 & 2.29.1
- [ ] Node-RED version: 1.2.5, 1.3.3, & 1.3.4
- [ ] node.js version: 12.22.1 (all platforms)
- [ ] npm version: 6.14.12
- [ ] Platform/OS: Centos, Raspberry OS, & Windows Server 2019 Datacenter
- [ ] Browser: Firefox and Edge (image from firefox - same behaviour in Edge)

![rows in multiline form](https://user-images.githubusercontent.com/13059464/120252036-b58a8780-c2c6-11eb-9f33-713f1b8b8dd6.PNG)

[multiline.json.txt](https://github.com/node-red/node-red-dashboard/files/6572670/multiline.json.txt)

**Comment by dceejay** [comment]
Ah right yes - the rows in this instance is the number of UI widget rows - so that the overall height of the form widget can fit nicely alongside other widgets on the page eg
![image](https://user-images.githubusercontent.com/5375409/120288367-08a90e00-c2b8-11eb-9fa4-ed99fa6baf14.png)
I can re-label the column header to UiRows I suppose. 
Yes we can look at the overlap.

**Comment by Dowster64** [comment]
Thanks, Sorry for the misunderstanding.  The help does show that it is UI rows but the help could easily say UI widget rows which might allow the penny to drop :-) instead of changing the label in the configuration area.  If one did not grasp that UI rows was in regards to the widget and not the multiline element (it's hidden for the rest) then it might just be clutter.

Anyway the overlap is a 'real' thing.  Thanks again for your hard work on this tool,

Steve
