### ISSUE TITLE
ui_dropdown: No result object in payload, when option containing property "id"

### ISSUE THREAD

**Issue by weberhannis** [node-red/node-red-dashboard#707]
If an option is used that has an "id" property, the payload object is not assigned to the selected option object.
Is there any special magic when using "id" as property?
```
msg.options = [{
        "A": {
            "id": "14",
            "type": "tab"
        }
    }, {
        "B": {
            xid: "12",
            type: "tab"
        }
    }
]
```
- [ ] Node-RED-Dashboard version: 2.29.3
- [ ] Node-RED version: 1.2.6
- [ ] node.js version: v10.23.0
- [ ] npm version: 6.14.8
- [ ] Platform/OS: Linux 4.14.24-qnap x64 LE / Docker
- [ ] Browser: Firefox

**Comment by dceejay** [comment]
HI - hmm yes - does appear to be so - will be fixed.
