### ISSUE TITLE
adding custom headers

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#71]
Hi! 

I'm very excited about node-red-dashboard, that's a really awesome project! 

One question: did you already think about giving the user the possibility to add custom headers? I'd like to prevent zooming on the iphone, so I would have to add `<meta name=”viewport” content=”width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;” />`

I could just add it in the right file, but then I guess it will be lost on every update. Do you think it would make sense to make custom headers configurable? I think this could also be useful for including custom css, favicon or js files.

Kind Regards,
Sebastian

**Comment by jroux1** [comment]
Whilst we are at it, also afd to choose to only view in Portrait (or
landscape) and turning the device willnot change the view.

**Comment by dceejay** [comment]
Hi,
we prefer ideas and suggestions on the google group or slack - to keep the issues list for actual bugs and issues.

**Comment by dceejay** [comment]
I don't think we can force portrait or landscape on a mobile device... nor do we want to tie ourselves to particular browser special commands.

**Comment by hobbyquaker** [comment]
I think you got me wrong. I don't suggest to implement a "deactivate zoom feature", I'd like to see a possibility to add custom headers of any kind. This could also be a `<link rel...` for a stylesheet or a favicon or any other `<meta>` or `<script>` tag.

A comment on deactivating zoom: If the user creates a Home-Screen Bookmark on iOS and uses the Dashboard as "Web App" deactivating the zoom is a good choice - it's normal and expected behavior for apps on iOS.

**Comment by dceejay** [comment]
So far people have managed to add stylesheets and extra js libs via the template node, so there is a workaround there.  But yes I understand about the general need. Will see if it makes sense to add to the overall custom theming piece of work.

**Comment by shrickus** [comment]
Hobbyquaker,
Now that the 0.17 branch is released, a ui_template node can be used to augment the <head> element of the dashboard pages. Does this now satisfy your request for including <link> and <meta> tags in the page header?
If so, can this issue be closed?

**Comment by hobbyquaker** [comment]
@shrickus yes - just tried it with the meta tag to prevent zoom on iOS safari and it works. Great, thx! :)
