### ISSUE TITLE
UI Chart - View is messed up with values of several series taken at the same timestamp

### ISSUE THREAD

**Issue by Darwin1986** [node-red/node-red-dashboard#710]
According to the examples here the following structure should be supported for charts in order to show preloaded data:

`[{
"series": ["A", "B", "C"],
"data": [
    [{ "x": 1504029632890, "y": 5 },
     { "x": 1504029636001, "y": 4 },
     { "x": 1504029638656, "y": 2 }
    ],
    [{ "x": 1504029633514, "y": 6 },
     { "x": 1504029636622, "y": 7 },
     { "x": 1504029639539, "y": 6 }
    ],
    [{ "x": 1504029634400, "y": 7 },
     { "x": 1504029637959, "y": 7 },
     { "x": 1504029640317, "y": 7 }
    ]
],
"labels": [""]
}]`

This leads to the following result (as expected)
![image](https://user-images.githubusercontent.com/44569827/125080221-da8fc880-e0c4-11eb-80a8-df305f2c3388.png)

However, I noticed that in this example the values for the different series are not taken at the exact same time which is the case for me since I want to have a consistent state in the application. This leads for example to something like this: 

`[{
"series": ["A", "B", "C"],
"data": [
    [{ "x": 1504029632890, "y": 5 },
     { "x": 1504029632890, "y": 4 },
     { "x": 1504029632890, "y": 2 }
    ],
    [{ "x": 1504029633514, "y": 6 },
     { "x": 1504029633514, "y": 7 },
     { "x": 1504029633514, "y": 6 }
    ],
    [{ "x": 1504029634400, "y": 7 },
     { "x": 1504029634400, "y": 7 },
     { "x": 1504029634400, "y": 7 }
    ]
],
"labels": [""]
}]`

Unfortunately that messes up the chart heavily. It seems to me that the differentiation between the series is no longer possible, if the timestamps are the same for all avaliable series. The data also seems to be interpreted differently. The result looks more as if each array in the data array is interpreted as its own series, instead of a series being created by each first, second and third element of the array. Below you find a screenshot of the result:

![image](https://user-images.githubusercontent.com/44569827/125078442-ab785780-e0c2-11eb-866a-cf1fc848af9c.png)

Is there something I am doing wrong, or is some additional configuration required to achive a standard trend chart for several variables?

This is executed on 
node: 12.22.1
node-red: 1.3.5
node-red-dashboard: 2.29.3

**Comment by dceejay** [comment]
For general queries we prefer people to use the discourse forum or slack channel so the widest audience can offer help. You seem to have set all the timestamps for each series to be the same so they will just render as vertical lines. I assume what you really wanted to do was set the first point of each series to the same time instead.
