### ISSUE TITLE
disable switch

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#72]
I'm using the switch to visualize a windows opening state with icons and colors:

![bildschirmfoto 2016-10-09 um 16 51 04](https://cloud.githubusercontent.com/assets/2503307/19221292/cde58678-8e40-11e6-8556-01e53e0bf1c4.png)
![bildschirmfoto 2016-10-09 um 16 50 46](https://cloud.githubusercontent.com/assets/2503307/19221293/cdfc03b2-8e40-11e6-8831-b6ea8e7b933a.png)

It would be great for this usecase to have the possiblity to disable the switch (make it non-clickable). And perhaps it makes sense to disable it by default if nothing is connected to its output.

**Comment by dceejay** [comment]
As per the README 
"Any widget can be disabled by passing in a msg.enabled property set to false;. Note: this doesn't stop the widget receiving messages but does stop inputs being active and does re-style the widget."

**Comment by hobbyquaker** [comment]
Cool, thx for the Info, sry for not reading the readme :)

**Comment by dceejay** [comment]
np.
