### ISSUE TITLE
collapsible groups

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#73]
I think it would be great to be able to configure a group as a collapsible element. So it just shows the header in collapsed state and can be expanded via click.

**Comment by dceejay** [comment]
Hi,
we prefer ideas and suggestions on the google group or slack - to keep the issues list for actual bugs and issues.

(But not a bad idea :-)

**Comment by hobbyquaker** [comment]
Ah ok, sry. This is the last suggestion I put in the issue tracker, promised! :)

**Comment by dceejay** [comment]
Does need some thinking about/discussion as collapsing will cause the rest of the UI to reconfigure/redraw. OK on a single column mobile device - but probably really ugly on anything else...

**Comment by aleonnet** [comment]
Hi @dceejay Dave!
Do you have any example code to hide/unhide or collapse/uncollapse groups in node-red dashboard?
Thanks

**Comment by dceejay** [comment]
Not yet. Anyone else ?

**Comment by Hugobox** [comment]
Sent a PR!
