### ISSUE TITLE
ui_control node does not switch tabs in response to a ui_control 

### ISSUE THREAD

**Issue by kapet** [node-red/node-red-dashboard#731]
I have a circular flow that essentially routes the output of a ui_control node through a delay and back to the ui_control node again. This implements an automatic "go back to home tab" function. Like this: (Ignore rightmost node for now.)
[dashboard flow.json.txt](https://github.com/node-red/node-red-dashboard/files/7333262/dashboard.flow.json.txt)
![dashboard flow](https://user-images.githubusercontent.com/6137365/137031889-15d0077d-23bd-43eb-a471-9e1fd43d41ab.PNG)

This does not work, the delayed tab switch never happens. I traced it down to this code line:
https://github.com/node-red/node-red-dashboard/blob/256b5261bbaf6418e7f1597e2936e9393352f087/src/main.js#L674

I don't understand what this does, but once I start deleting the msg.socketid attribute inside my flow (like in the example flow above), things start to work.

**Comment by ikidd** [comment]
This has been driving me around the bend because it would work very occasionally, then I'd have my UI stuck in a mode that I could not send UIcontrol messages to change.

I will try the workaround mentioned by kapet

**Comment by dceejay** [comment]
the line mentioned was released from the latest version of dashboard.

**Comment by dceejay** [comment]
OK - this was reverted as it was pointed out why the line was there... specifically to stop the feedback going t other browsers that were open at the time... so yes the answer is indeed to remove the socketid as the correct way to do this.

**Comment by kapet** [comment]
Ok, thanks. Do you know why that's not working properly in my case? I mean I am sending the request back to the exact same browser window after all. Or is the 5s delay in the middle "breaking" the flow in such a way that the connection ID will have changed by the time the flow reaches the UI control node again?

**Comment by dceejay** [comment]
So. Yes you need delete the msg.socketid
