### ISSUE TITLE
cant do multiline in label

### ISSUE THREAD

**Issue by SDWaps** [node-red/node-red-dashboard#734]
### What are the steps to reproduce?
Feed data with a newline to a label

### What happens?
Newlines dont show

### What do you expect to happen?
That \n would work, causing newlines to appear

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:
- [ ] ?
- [ ] Node-RED version:
- [ ] ?
- [ ] node.js version:
- [ ] ?
- [ ] npm version:
- [ ] ?
- [ ] Platform/OS:
- [ ] RPI w\raspbian buster
- [ ] Browser:
- [ ] chrome

**Comment by dceejay** [comment]
do you have a simple example flow to show what you mean ?

**Comment by SDWaps** [comment]
Here it is:
[{"id":"f5bc2771.13bae8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"cbee75cd.175988","type":"ui_form","z":"f5bc2771.13bae8","name":"","label":"Post to chat","group":"3279700c.8a597","order":0,"width":0,"height":0,"options":[{"label":"Name","value":"name","type":"text","required":true,"rows":null},{"label":"Message","value":"msg","type":"multiline","required":true,"rows":5}],"formValue":{"name":"","msg":""},"payload":"","submit":"Send","cancel":"Clear","topic":"topic","topicType":"msg","splitLayout":"","className":"","x":550,"y":120,"wires":[["a41cb16f.fe3db"]]},{"id":"a41cb16f.fe3db","type":"function","z":"f5bc2771.13bae8","name":"convertforfile","func":"msg.payload = \"\\n\" + msg.payload[\"name\"] + \": \" + msg.payload[\"msg\"] + \"\\n\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":710,"y":120,"wires":[["3ed8b0a3.15aef"]]},{"id":"3ed8b0a3.15aef","type":"file","z":"f5bc2771.13bae8","name":"Send","filename":"/home/pi/houltranet/chat.txt","appendNewline":true,"createDir":false,"overwriteFile":"false","encoding":"utf8","x":830,"y":120,"wires":[[]]},{"id":"beca1c48.5dd7b","type":"watch","z":"f5bc2771.13bae8","name":"","files":"/home/pi/houltranet/chat.txt","recursive":"","x":640,"y":160,"wires":[["2fc50f60.80021"]]},{"id":"2fc50f60.80021","type":"file in","z":"f5bc2771.13bae8","name":"","filename":"/home/pi/houltranet/chat.txt","format":"lines","chunk":false,"sendError":false,"encoding":"none","x":890,"y":160,"wires":[["6953eff1.5014e"]]},{"id":"6953eff1.5014e","type":"ui_text","z":"f5bc2771.13bae8","group":"3279700c.8a597","order":1,"width":0,"height":0,"name":"","label":"","format":"{{msg.payload}}","layout":"col-center","className":"","x":1010,"y":160,"wires":[]},{"id":"3279700c.8a597","type":"ui_group","name":"Chat","tab":"42cf326f.bc079c","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"42cf326f.bc079c","type":"ui_tab","name":"Chat","icon":"chat","order":2,"disabled":false,"hidden":false}]

**Comment by dceejay** [comment]
Even with your example I can't see what you mean - which label are to trying to make multi-line ?
You can use <br/> if you want in the label eg
![image](https://user-images.githubusercontent.com/5375409/140502244-38f92eba-ce74-4f37-9548-edd0949796a7.png)
gives
![image](https://user-images.githubusercontent.com/5375409/140502302-6781a644-4d7d-4286-82bc-c3027cf52deb.png)
