### ISSUE TITLE
Dialog Output Error when Input is 1 or 1.0

### ISSUE THREAD

**Issue by sniicker** [node-red/node-red-dashboard#736]
### What are the steps to reproduce?
use this code and try to type in 1 or 1.0
`[{"id":"63af6413.8622b4","type":"ui_toast","z":"07f069d764f0858f","position":"prompt","displayTime":"3","highlight":"","sendall":false,"outputs":1,"ok":"OK","cancel":"Abbrechen","raw":false,"className":"","topic":"","name":"","x":830,"y":180,"wires":[["1330ba77f264681d"]]},{"id":"1330ba77f264681d","type":"debug","z":"07f069d764f0858f","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":990,"y":180,"wires":[]},{"id":"f55fd63d2b8281d7","type":"inject","z":"07f069d764f0858f","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Type in a Number","payloadType":"str","x":610,"y":180,"wires":[["63af6413.8622b4"]]}]`

### What happens?
the payload has now the string of the OK Button - thats NOT GOOD !
![image](https://user-images.githubusercontent.com/67097444/141286125-824cc03b-74a3-4f90-9a16-255175f46d77.png)

### What do you expect to happen?
the msg.payload should be 1 or 1.0 - because i typed that in

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 3.0.4 & 3.1.1
- [ ] Node-RED version:2.1.3
- [ ] node.js version:12.20.2
- [ ] npm version:
- [ ] Platform/OS: Win10
- [ ] Browser: Firefox Chrome Brave

**Comment by dceejay** [comment]
?!?!? weird/// thanks
