### ISSUE TITLE
google material icons not loaded correctly

### ISSUE THREAD

**Issue by Bond246** [node-red/node-red-dashboard#737]
Hello,

i generated a new "kitchen"-tab in my dashboard and searched for a suitable icon which i found in the google material pack. I tooked "mi-soup_kitchen" that looks like a ladle: https://fonts.google.com/icons?selected=Material+Icons+Outlined:assignment_returned&icon.query=soup_kitchen

1st problem is the dashboard just loads the icon of a fridge not the ladle.
2nd problem is that the left margin of the icon gets really wide. I briefly checked that with firefox dev-tools and it looks like that the space comes from the word "soup_kitchen".

If i use the google icon for other dashboards elements, not for tabs the space-problems seems to be the same.

![grafik](https://user-images.githubusercontent.com/8534418/141808005-817e2bfc-239c-47a4-ae7a-1b66af05e8e6.png)

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 3.1.1
- [ ] Node-RED version: 2.1.3
- [ ] node.js version: latest docker-version
- [ ] npm version: latest docker-version
- [ ] Platform/OS: linux/docker
- [ ] Browser: Firefox/Desktop, Chrome/Android

**Comment by dceejay** [comment]
Hmm - works for me
![image](https://user-images.githubusercontent.com/5375409/141809363-0de2a862-c8ad-4d7e-bea3-9bfab58f601d.png)
![image](https://user-images.githubusercontent.com/5375409/141809589-86043466-1171-4456-b4f3-f6d11a2bd736.png)

**Comment by Bond246** [comment]
Thanks for testing!

hmm... any idea how to get closer to the problem?

**Comment by dceejay** [comment]
maybe share a small part of your flow that shows the problem ?

**Comment by Bond246** [comment]
`[{"id":"bf9d665380e6fd07","type":"ui_text","z":"8ae6f2d337b2f477","group":"989324d0e799fc86","order":3,"width":3,"height":1,"name":"","label":"Präsenz:","format":"{{msg.payload}}","layout":"row-left","className":"","x":460,"y":200,"wires":[]},{"id":"9be05f1947325bb1","type":"ui_text","z":"8ae6f2d337b2f477","group":"989324d0e799fc86","order":4,"width":3,"height":1,"name":"","label":"Lum.:","format":"{{msg.payload.lux}}lux","layout":"row-right","className":"","x":450,"y":240,"wires":[]},{"id":"989324d0e799fc86","type":"ui_group","name":"Schalter","tab":"679850fbcb7b789c","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"679850fbcb7b789c","type":"ui_tab","name":"Küche","icon":"mi-soup_kitchen","order":4,"disabled":false,"hidden":false}]`

**Comment by dceejay** [comment]
indeed - still ok here
![image](https://user-images.githubusercontent.com/5375409/141820959-860f650b-9371-4442-a752-0127c55c432d.png)
Not sure what to suggest apart from restart server and making sure browser cache clear - and that internet connection is working. - Is there anything in the browser debug console ?

**Comment by sniicker** [comment]
i had the exact same Problem and got the same msg in the browser. 

Updated the dashboard palette to the actual version helped me to display the icon properly

**Comment by Bond246** [comment]
i haven't thought about it anymore and just used "restaurant" instead.
But yes, with my latest version it works too for me. 

Thanks 💯
