### ISSUE TITLE
Wrong socketid displayed by ui-control node

### ISSUE THREAD

**Issue by ninoflorj** [node-red/node-red-dashboard#738]
With the newest version of Node-Red Dashboard (3.1.2), the UI-Control node outputs the wrong Socket IDs (msg.socketid) when an event (connect, disconnect...) happens in the Dashboard.
So, if i want to send a command to a dashboard node with the socketid given by the UI-Control, nothing happens.
But if i use the socketid given by the Browser-URL of the dashboard client, everything works, and the command is only sent to this browser-session.

In an older version of the Dashboard (tested with 2.9) everything works just fine, and the ui-control Node outputs the correct socketid.

Here is the very simple test flow:
`[
    {
        "id": "d116089fae0c7727",
        "type": "debug",
        "z": "b2f3636efc080de3",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 730,
        "y": 400,
        "wires": []
    },
    {
        "id": "ad9205e0bc9619f1",
        "type": "ui_ui_control",
        "z": "b2f3636efc080de3",
        "name": "",
        "events": "connect",
        "x": 480,
        "y": 400,
        "wires": [
            [
                "d116089fae0c7727"
            ]
        ]
    }
]`

### Please tell us about your environment:

- Node-RED-Dashboard version: 2.1.3
- Node-RED version: 2.0.6
- node.js version: 14.17.6
- Platform/OS: Docker on Synology Nas
- Browser: Chrome

**Comment by dceejay** [comment]
Thanks - yes for some reason the socketid seems to have "moved" - it may have been due to one of the socketio updates - but yes fix pushed to master. (not yet on npm - will be in v3.1.3)
