### ISSUE TITLE
Filtered multiselect in dashboard dropdown node returns all options instead of only selected

### ISSUE THREAD

**Issue by DoIt79** [node-red/node-red-dashboard#747]
I'm using actual NodeRed Dashboard (NodeRed 2.1.4 and node-red-dashboard 3.1.2 running on Ubuntu 20.04 and 21.10. Browser Edge, Chromium, Firefox).

I have an issue with the dorpdown node - find the flow below.

I have many entries. As long I select some entries, everything worked fine - same values on the ui as in the payload of the output message. If I filter and then select all, the node isn't working correct. E.g.:

Filter for 2 in the UI -> dropdown shows 2 and 22 -> click select all (next to the filter) -> 2 and 22 are selected in the dropdownlist -> close drop down -> 2, 22 are the values shown in the dropdown element, what was expected BUT the payload of the outputmessage contains all vallues 1,11,2,22,3,33, ... . I think the payload of the outputmessage should also only have 2 and 22 in the array, same like you select them without filtering.

I think this is a bug or is there an option to change the behavior? Can anybody help?

![image](https://user-images.githubusercontent.com/68516352/149458190-ec361e69-e201-4bd3-a994-f36cec49e1d3.png)

![image](https://user-images.githubusercontent.com/68516352/149458253-77703ef6-7507-4c40-922f-66fc0e84e9a2.png)

![image](https://user-images.githubusercontent.com/68516352/149458295-d0c4a8e9-794e-4aca-965a-b4653a43b671.png)

![image](https://user-images.githubusercontent.com/68516352/149458381-7f025fd8-bdfc-4781-8cbe-c8a076c42c29.png)

```
[{"id":"69033524b9fb7368","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"dc3be8ab6bf92dcd","type":"ui_dropdown","z":"69033524b9fb7368","name":"","label":"","tooltip":"","place":"Select option","group":"cd3ed408879c58d8","order":0,"width":0,"height":0,"passthru":true,"multiple":true,"options":[{"label":"","value":1,"type":"num"},{"label":"","value":"11","type":"str"},{"label":"","value":"2","type":"str"},{"label":"","value":"22","type":"str"},{"label":"","value":"3","type":"str"},{"label":"","value":"33","type":"str"},{"label":"","value":"4","type":"str"},{"label":"","value":"44","type":"str"},{"label":"","value":"5","type":"str"},{"label":"","value":"55","type":"str"},{"label":"","value":"6","type":"str"},{"label":"","value":"66","type":"str"},{"label":"","value":"7","type":"str"},{"label":"","value":"77","type":"str"},{"label":"","value":"8","type":"str"},{"label":"","value":"88","type":"str"},{"label":"","value":"9","type":"str"},{"label":"","value":"99","type":"str"}],"payload":"","topic":"topic","topicType":"msg","className":"","x":550,"y":240,"wires":[["5cb4c9a03b4b194f"]]},{"id":"5cb4c9a03b4b194f","type":"debug","z":"69033524b9fb7368","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":710,"y":240,"wires":[]},{"id":"cd3ed408879c58d8","type":"ui_group","name":"Group 1","tab":"004e56d80f68394d","order":1,"disp":true,"width":6},{"id":"004e56d80f68394d","type":"ui_tab","name":"Tab 3","icon":"dashboard","order":3}]
```

**Comment by DoIt79** [comment]
Thanks for the super fast fix BUT unfortunately now there is another problem.

If I but in a filter and than select all no output message is send anymore. Can you reopen this issue or should i create a new issue.

**Comment by dceejay** [comment]
odd works for me. what happens if you deselect and reselect ?

**Comment by dceejay** [comment]
Weird .. I get this
![xQX8erczFM](https://user-images.githubusercontent.com/5375409/149554476-fbd708b6-3e1c-4344-a4f6-68fac2680178.gif)

**Comment by DoIt79** [comment]
It was Chrome on Windows. Node Red running on Linux. I will recheck this on another machine.

**Comment by DoIt79** [comment]
I rechecked it now on a windows 10 machine with fresh node.js and node red installation.

![image](https://user-images.githubusercontent.com/68516352/149611984-4bcfaa35-2d63-4eac-aa38-d75877a72ccf.png)

I configured the dropdown with the same options as you did, but - as you can see - it has another behavior (same as on my other machine).
Took the video after fresh restart of node red.

![Animation2](https://user-images.githubusercontent.com/68516352/149612337-e3b69e53-95b0-4996-a56b-8f821ed9ee15.gif)

What's also very interesting, as you can see, the first multiselect after the restart gets the old behavior. Also what's different, that your installation is sending the values immediately, mine after lose of focus.

I tried it with chrome, edge and firefox - all the same.

**Comment by DoIt79** [comment]
Got it! Options have to be declared as string.

I did the options as 'number'.
If I do the options as 'string' everything works like in your installation.
