### ISSUE TITLE
Pre-fill datetime picker (text input node) doesn’t show date and time

### ISSUE THREAD

**Issue by vladaurosh** [node-red/node-red-dashboard#757]
### What are the steps to reproduce?

Use this flow:
`[ { "disabled" : false, "env" : [], "id" : "6a07369735a2c313", "info" : "", "label" : "Flow 1", "type" : "tab" }, { "finalize" : "", "func" : "msg = { payload: new Date('2015-03-25') };\nreturn msg;\n", "id" : "e4918f5f7fb0f29d", "initialize" : "", "libs" : [], "name" : "insert time", "noerr" : 0, "outputs" : 1, "type" : "function", "wires" : [ [ "89be3210cf95b107" ] ], "x" : 270, "y" : 160, "z" : "6a07369735a2c313" }, { "events" : "change", "id" : "b6de6bbbf69d167b", "name" : "", "type" : "ui_ui_control", "wires" : [ [ "e4918f5f7fb0f29d" ] ], "x" : 100, "y" : 100, "z" : "6a07369735a2c313" }, { "active" : false, "complete" : "payload", "console" : false, "id" : "83148cc35f7dca57", "name" : "", "statusType" : "auto", "statusVal" : "", "targetType" : "msg", "tosidebar" : true, "tostatus" : false, "type" : "debug", "wires" : [], "x" : 590, "y" : 60, "z" : "6a07369735a2c313" }, { "className" : "", "delay" : 300, "group" : "afdd5870dddac354", "height" : 0, "id" : "89be3210cf95b107", "label" : "Start Time", "mode" : "datetime-local", "name" : "", "order" : 2, "passthru" : true, "sendOnBlur" : true, "tooltip" : "", "topic" : "", "topicType" : "str", "type" : "ui_text_input", "width" : 0, "wires" : [ [ "83148cc35f7dca57" ] ], "x" : 510, "y" : 160, "z" : "6a07369735a2c313" }, { "className" : "", "collapse" : false, "disp" : true, "id" : "afdd5870dddac354", "name" : "test", "order" : 1, "tab" : "f9d9dee5b5dc26ae", "type" : "ui_group", "width" : "6" }, { "icon" : "dashboard", "id" : "f9d9dee5b5dc26ae", "name" : "Tab 5", "order" : 5, "type" : "ui_tab" } ]`

### What happens?

I have pretty simple flow where I have "Date picker node" and "Text input node" (set to time picker mode), and a function that injects date and time to these 2 node. Function just has pretty much this:
msg.payload = new Date()};

This works fine and I have date and time pre-filled in these 2 nodes.

Now I want to use Text input node set to datetime picker mode instead of separate time and date nodes. But prefill doesn't work here, date and time are not shown, I get just "dd-----yyyy --:--".

I am using same principle to load date into this node. What's interesting, I get correct time and date as output of this node, just it's not shown in gui.
Forum thread with same details and screenshots.
https://discourse.nodered.org/t/pre-fill-datetime-picker-text-input-node-doesnt-show-date-and-time/58771

### What do you expect to happen?

Expected is to see data and time prepopulated in gui.

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 3.1.6
- [ ] Node-RED version: 2.2.0
- [ ] node.js version: 17.5.0
- [ ] npm version: 8.5.0
- [ ] Platform/OS: Asus Tinker Board with DietPi v8.1
- [ ] Browser: Chrome, Firefox

**Comment by evazzoler** [comment]
Why was this issue closed? The problem is still here with node-red-dashboard 3.6.5...
