### ISSUE TITLE
Disabled widgets accessible by pressing TAB

### ISSUE THREAD

**Issue by soyszala** [node-red/node-red-dashboard#758]
In my case, when I disable a widget I don't want to let the user access them in any way. But I noticed, after setting _"enabled"_ to _false_ you can still get focus of the widget by pressing TAB, so you can still type in a text field or press a button for example. 

I'm sure there is a workaround by creating a template similar to a widget and change this one thing, but I think it would be convinient, if there was a way to set "ng-disabled" property, not just "enabled". Unless there's a simpler way to achieve this, what I don't know about.

Minimal example to recreate the issue:
`[
    {
        "id": "81a6a15ed9991219",
        "type": "inject",
        "z": "2e90051e0d95284d",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 160,
        "wires": [
            [
                "0363ded5965b024f"
            ]
        ]
    },
    {
        "id": "8c28833a112cb93c",
        "type": "inject",
        "z": "2e90051e0d95284d",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 200,
        "wires": [
            [
                "8920b53d7eee5b59"
            ]
        ]
    },
    {
        "id": "0363ded5965b024f",
        "type": "function",
        "z": "2e90051e0d95284d",
        "name": "Enable",
        "func": "\nreturn {enabled : true};",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 320,
        "y": 160,
        "wires": [
            [
                "b42eb594798aa17a"
            ]
        ]
    },
    {
        "id": "8920b53d7eee5b59",
        "type": "function",
        "z": "2e90051e0d95284d",
        "name": "Disable",
        "func": "\nreturn {enabled : false};",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 320,
        "y": 200,
        "wires": [
            [
                "b42eb594798aa17a"
            ]
        ]
    },
    {
        "id": "b42eb594798aa17a",
        "type": "ui_text_input",
        "z": "2e90051e0d95284d",
        "name": "",
        "label": "",
        "tooltip": "",
        "group": "45a87283.4150ac",
        "order": 6,
        "width": 0,
        "height": 0,
        "passthru": true,
        "mode": "text",
        "delay": 300,
        "topic": "topic",
        "sendOnBlur": true,
        "className": "",
        "topicType": "msg",
        "x": 500,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "45a87283.4150ac",
        "type": "ui_group",
        "name": "User Login",
        "tab": "dadd1654.354a78",
        "order": 1,
        "disp": true,
        "width": 16,
        "collapse": false,
        "className": ""
    },
    {
        "id": "dadd1654.354a78",
        "type": "ui_tab",
        "name": "Login",
        "icon": "dashboard",
        "order": 1,
        "disabled": false,
        "hidden": true
    }
]`

- Node-RED-Dashboard version: 3.1.6
- Node-RED version: v2.0.6
- node.js version: v14.19.0
- Platform/OS: Ubuntu 18.04
- Browser: Firefox

**Comment by dceejay** [comment]
I have pushed a fix to the master branch - can you check that it fixes it for you ?
(not yet on npm ... )

https://github.com/node-red/node-red-dashboard/commit/e5254683d3f41028df7f1f7c0ebc892d9db37038
