### ISSUE TITLE
Notification node (ui_toast) - Layout Dialog - Class not applied

### ISSUE THREAD

**Issue by panandreas** [node-red/node-red-dashboard#776]
### What are the steps to reproduce?
I am inserting a notification node (ui_toast). In Properties is select a layout "OK/Cancel Dialog" or "OK/Cancel Dialog with Input". Then I add a Class to the node. 

### What happens?
The class is not applied on the notification node.

### What do you expect to happen?
I except my custom class to be applied to the notification node, so I can target it with CSS

### Please tell us about your environment:

- [X] Node-RED-Dashboard version: 3.2.0
- [X] Node-RED version: 3.0.2
- [X] node.js version: 16.13.2
- [X] npm version: 8.1.2
- [X] Platform/OS: Windows 10 / Ubuntu 22.04
- [X] Browser: Independent

### Solution:

The problem is solved by changing line 630 in "main.js":
from
`confirm._options.template = '<md-dialog md-theme="{{ dialog.theme || dialog.defaultTheme }}" aria-label="{{ dialog.ariaLabel }}" >' +"`

to 
`confirm._options.template = '<md-dialog md-theme="{{ dialog.theme || dialog.defaultTheme }}" aria-label="{{ dialog.ariaLabel }}" class="' + msg.toastClass + ' >' +"`

**Comment by dceejay** [comment]
pushed to master - not yet on npm

**Comment by dceejay** [comment]
Now published
