### ISSUE TITLE
Charts - force series order

### ISSUE THREAD

**Issue by adi-dev** [node-red/node-red-dashboard#779]
Not a real issue, more like question/request: is there a way to force the data series to be in preset order - when I colour chart series color, for example first red for load, second green for output, the order changes on next restart depending on what comes first.

**Comment by dceejay** [comment]
General How-to type questions are best asked on the discourse forum so the widest audience can help.
The simplest answer is to set an inject node to send a message on start with an array of messages containing the topics (load, output, etc) and all with a payload of null. eg [{"topic":"load","payload:null},{"topic":"output","payload:null}, ... ] etc

**Comment by adi-dev** [comment]
@dceejay thanks, sorry for trouble.
