### ISSUE TITLE
Configurable data volume limits for charts?

### ISSUE THREAD

**Issue by mountaindude** [node-red/node-red-dashboard#78]
After a few days or running a fairly basic dashboard, I keep getting warnings like these:

11 Oct 09:45:31 - [warn] [ui_chart:42989845.8dfda8] More than 8349 datapoints
11 Oct 09:45:44 - [warn] [ui_chart:42989845.8dfda8] More than 8349 datapoints
11 Oct 09:46:06 - [warn] [ui_chart:42989845.8dfda8] More than 8349 datapoints
11 Oct 14:34:33 - [warn] [ui_chart:42989845.8dfda8] More than 9108 datapoints
11 Oct 14:34:40 - [warn] [ui_chart:42989845.8dfda8] More than 9108 datapoints

While I totally understand that there will be limits to how many data points that can be visualised, 9k points seems a bit on the low side... But even it if it is - is it possible to configure limits somehow? Maybe allocating more memory to handling of the data to be plotted?
Maybe not possible at all, just brainstorming..

**Comment by dceejay** [comment]
Hi,

We added the warning just to keep a track on number of points - it doesn't stop anything happening. (Though typically the chart is only a few hundred pixels wide so having 1000s of data points doesn't add too much.)

this is related to Issue #38 so I'll close this one .

We prefer discussion and ideas over on slack or the mailing list.

**Comment by hj91** [comment]
pi@raspberrypi:~ $ 25 Dec 20:34:25 - [warn] [ui_chart:Ambient Humidity] More than 200 datapoints

I am trying to display my sensehat humidity data and i get this message on cli. I also observed that i need to redeploy my code after some time so i start getting proper reading once again. Is this because i am exceeding allowed number of points?

**Comment by hj91** [comment]
here is the nodered flow code i am using 

https://gist.github.com/hj91/a26eaf3e752786b904d11d65e466ac83

**Comment by dceejay** [comment]
this is a closed issue so no point in adding to it as we may easily miss it.
Which version of dashboard is this, the latest 2.2.0 or 2.2.1 does not have this warning message I believe as we changed the charting library we used to one that didn't crash so often.

**Comment by hj91** [comment]
I think I am on old version - 2.1.0 that came pre-installed with default
raspbian version. I will check updated version.

--sent from mobile device--
