### ISSUE TITLE
ui_form: Keep input msg structure for output 

### ISSUE THREAD

**Issue by ostauss** [node-red/node-red-dashboard#781]
### What are the steps to reproduce?
```[{"id":"b8be05311ead80ca","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"ebb59703826a2ab0","type":"ui_form","z":"b8be05311ead80ca","name":"","label":"form","group":"5749dfff.2a222","order":0,"width":0,"height":0,"options":[{"label":"Test","value":"test","type":"text","required":true,"rows":null}],"formValue":{"test":""},"payload":"","submit":"submit","cancel":"","topic":"topic","topicType":"msg","splitLayout":"","className":"","x":590,"y":500,"wires":[["32050a04307ba809"]]},{"id":"5cd9c6909deae708","type":"ui_ui_control","z":"b8be05311ead80ca","name":"trigger","events":"change","x":310,"y":500,"wires":[["79280b1196529423"]]},{"id":"79280b1196529423","type":"change","z":"b8be05311ead80ca","name":"init","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"test\":\"test\"}","tot":"json"},{"t":"set","p":"param1","pt":"msg","to":"1","tot":"num"},{"t":"set","p":"param2","pt":"msg","to":"2","tot":"num"},{"t":"set","p":"topic","pt":"msg","to":"topic","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":500,"wires":[["ebb59703826a2ab0","bfe1d7777d76a4c1"]]},{"id":"32050a04307ba809","type":"debug","z":"b8be05311ead80ca","name":"debug form","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":750,"y":500,"wires":[]},{"id":"bfe1d7777d76a4c1","type":"debug","z":"b8be05311ead80ca","name":"debug init","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":740,"y":580,"wires":[]},{"id":"5749dfff.2a222","type":"ui_group","name":"Default","tab":"8d16f8ce.591d18","order":1,"disp":true,"width":"6","collapse":false},{"id":"8d16f8ce.591d18","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]```

### What happens?
Input (msg): 
```{"payload" :{"test":"test"},
"tab":2,
"name":"Home",
"socketid":"d3TGLMok9lb2tDQ0AAAl",
"socketip":"aaa.bbb.ccc.ddd",
"params":{},
"_msgid":"a3d38d7c3a13a725",
"param1":1,
"param2":2,
"topic":"topic"}
```

Output (msg):
```{"payload":{"test":"test"},
"topic":"topic",
"socketid":"d3TGLMok9lb2tDQ0AAAl",
"_msgid":"087aeeba6a06d281"}
```

### What do you expect to happen?
"route" all untouched JSON properties from input to output. 

Expected Output (msg) 
```{"payload" :{"test":"test"},
"tab":2,
"name":"Home",
"socketid":"d3TGLMok9lb2tDQ0AAAl",
"socketip":"aaa.bbb.ccc.ddd",
"params":{},
"_msgid":"087aeeba6a06d281",
"param1":1,
"param2":2,
"topic":"topic"}
```

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: 3.2.0
- [ ] Node-RED version: 2.2.2
- [ ] node.js version: 16.18.0
- [ ] npm version: 8.19.2
- [ ] Platform/OS: Rasberry / Buster
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Yes - UI nodes do not behave like that - as we do not want to pass potentially massive objects (and maybe credentials) to the browser and back. 
 Indeed as most are UI elements they have the capability of creating new messages of their own (eg the form) and cannot create extra properties. This is working as designed.
If you need the message the other side of the node just add another wire around the ui node.
