### ISSUE TITLE
side menu is always visible

### ISSUE THREAD

**Issue by ghedolo** [node-red/node-red-dashboard#782]
even if i choose "click to show side menu", 
the side menu is always visible.
Using NR 3.0.1 it works but it does not work with 3.0.2

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version:3.2.0
- [ ] Node-RED version: 3.0.2
- [ ] node.js version:v14.20.1
- [ ] npm version:6.14.17
- [ ] Platform/OS:raspberry/debian 11.5
- [ ] Browser:chrome 107.0....

**Comment by dceejay** [comment]
As long as I deploy then this seems to work fine. Going to need more details to re-create.

**Comment by ghedolo** [comment]
after some trial seems to me  i found the right path :
from dashboard-> site
set hide the title  bar
set always show side menu
deploy
again dashboard-> site 
show the title bar
click to show the side menu
deploy again
Now the side menu is hide...

meanwhile i have  upgrade things on my raspberry..

**Comment by dceejay** [comment]
Again that sequence is working on latest version so leaving this closed.
