### ISSUE TITLE
Changes to copy of chart affects the original

### ISSUE THREAD

**Issue by Geving** [node-red/node-red-dashboard#783]
### What are the steps to reproduce?

Create a chart with the label "Chart A"
Set to display last 10 days or 5000 datapoints.
Deploy changes
Feed it 1000 random datapoints and observe that it displays them.

Make a copy of the chart node using Ctrl+C/Ctrl+V
Change the copy to display "Chart B".
Change the copy to display last 1 days or 100 datapoints.
Connect the output of "Chart A" to the input of "Chart B".
Deploy changes

### What happens?
Both "Chart A" and "Chart B" displays only 100 datapoints.

### What do you expect to happen?
"Chart A" should keep displaying the 1000 datapoints, and "Chart B" should only display 100 datapoints.

Node-RED-Dashboard version: 3.2.0
Node-RED version: 3.0.2

**Comment by Geving** [comment]
It looks like the issue might be the daisy chaining of the two charts.

**Comment by dceejay** [comment]
nodejs passes object by reference - so if it is the same object then changing it later may also affect other version of it. You could try inserting a change node set to  deep copy the data eg - which would break the reference.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/5375409/202165343-7b32660e-2975-472f-a7ea-d872d9c5370f.png">
