### ISSUE TITLE
hide "link" using ui_control node

### ISSUE THREAD

**Issue by raullink** [node-red/node-red-dashboard#785]
Hi there.
In my navigation bar I have tabs and links.
I use the ui_control node to hide/show tabs or groups, but I dont know how to hide the "link" ones.

I've tried:

```
msg.payload = {
    "tabs": {
        "hide": "my_tab_1"
    },
    "links": {
        "hide": "my_link_1"
    }
}
```
Tried "link" instead "links", but no success.

**Comment by dceejay** [comment]
It should just be "another tab" - so within the tabs: hide array - but it doesn't work... so will be fixed.
