### ISSUE TITLE
When in-UI contents is vertically shorter than the side-menu, the menu scrolls unnecessarily

### ISSUE THREAD

**Issue by linuxkidd** [node-red/node-red-dashboard#79]
![screenshot from 2016-10-14 20-21-27](https://cloud.githubusercontent.com/assets/6115364/19407102/7c174510-924c-11e6-9528-d8deef0049ec.png)

NOTE: The light grey area below the darkened grey is still part of the browser display area, but the UI ends forcing the menu to scroll, instead of the UI consuming 100% vertical height of the display window.

**Comment by dceejay** [comment]
Is this latest 2.1.0 version from npm ? Version is printed in console.log when node-red starts.

**Comment by linuxkidd** [comment]
This was based on a git clone / npm install as of about an hour prior to the creation of the issue.

log entry from start (GMT)
Oct 15 03:20:10 raspberrypi Node-RED[9922]: 15 Oct 03:20:10 - [info] Dashboard version 2.1.0 started at /ui

**Comment by dceejay** [comment]
OK. Which OS? Browser?

**Comment by linuxkidd** [comment]
On vacation, sorry for the late response... And.. I'm happy to report.. this seemed to be a cache issue (I was testing from airline Wi-Fi).   Apologies for the errant report.
