### ISSUE TITLE
Certain combinations of UI elements cause overlapping UI panes

### ISSUE THREAD

**Issue by linuxkidd** [node-red/node-red-dashboard#80]
![screenshot from 2016-10-14 20-29-20](https://cloud.githubusercontent.com/assets/6115364/19407120/1c83ac5a-924d-11e6-8838-f9317ce18a56.png)

NOTE: 'Misc' pane overlaps almost 2 full vertical units of the 'Your Email Address' pane.  Bottom UI element of 'Your Email Address' pane is 1 vertical unit x 6 horizontal unit ui-template node used to provide feedback.  Next level up are two, 1 vertical unit x 3 horizontal unit ui-buttons.

This was corrected in a previous github compiled version of node-red-dashboard ( Sep 12th was the pull / npm install.. this was fixed in that pull ), if that helps identify and correct the trigger.

**Comment by dceejay** [comment]
Is this the latest 2.1.0 version of it ? Version is reported in console.log at start.

**Comment by linuxkidd** [comment]
This was based on a git clone / npm install as of about an hour prior to the creation of the issue.

log entry from start (GMT)
Oct 15 03:20:10 raspberrypi Node-RED[9922]: 15 Oct 03:20:10 - [info] Dashboard version 2.1.0 started at /ui

**Comment by dceejay** [comment]
Are you able to share the flow for those elements so we can recreate. Thanks

**Comment by linuxkidd** [comment]
On vacation, sorry for the late response... And.. I'm happy to report.. this seemed to be a cache issue (I was testing from airline Wi-Fi). Apologies for the errant report.

**Comment by dceejay** [comment]
great - thanks for letting us know
