### ISSUE TITLE
Black border on web icon on iOS

### ISSUE THREAD

**Issue by vollstock** [node-red/node-red-dashboard#801]
### What are the steps to reproduce?

In Safari add the Node-RED Dashboard to the home screen (as a web app).

### What happens?

The icon has a black border around the white background.

<img width="250" alt="Screenshot" src="https://user-images.githubusercontent.com/4962676/228797894-9e4fa83c-7166-46b5-b1f0-142dadff7652.png">

The reason for this is, that your icons (e. g. [this one](https://github.com/node-red/node-red-dashboard/blob/master/src/icon192x192.png)) have a transparent border and pre-composed rounded corners.  
iOS does not allow for transparent icons and fills transparency with black. It will also compose rounded corners itself.

I have attached files, that look correct. However it would be a little more work to make the best out of the icon on all different platforms.  
A [Favicon Generator](https://realfavicongenerator.net/) helps with that.

![Node-RED Icon](https://user-images.githubusercontent.com/4962676/228796017-7d347106-e21b-42aa-8665-5abdb5ad2225.svg)
![icon64x64](https://user-images.githubusercontent.com/4962676/228796061-5908f470-0340-4949-a194-e5a85c5091b6.png)
![icon120x120](https://user-images.githubusercontent.com/4962676/228796068-06152188-c4e9-41fd-9d02-cd97a7e5e5c3.png)
![icon192x192](https://user-images.githubusercontent.com/4962676/228796070-88f24c1f-6818-4792-8da9-95ee1e0c4d42.png)
![icon512x512](https://user-images.githubusercontent.com/4962676/228796072-7be69118-01bf-4bf8-bf49-d92d5f6c7ab1.png)

**Comment by dceejay** [comment]
Thanks - I'll update them.
