### ISSUE TITLE
Mobile "Save to homescreen" icons

### ISSUE THREAD

**Issue by i8beef** [node-red/node-red-dashboard#81]
Would be nice if these metadata items were added to the head so that when one does a "Save to homescreen" action on iPhone or Android it gets an appropriate icon: https://developer.chrome.com/multidevice/android/installtohomescreen

**Comment by dceejay** [comment]
for me it already adds to home screen on my Android phone ok.
![image](https://cloud.githubusercontent.com/assets/5375409/19539759/1d3162e6-9653-11e6-8a7e-e01fe9153251.png)
gives me
![image](https://cloud.githubusercontent.com/assets/5375409/19539744/046872ae-9653-11e6-9843-6b3f90e225af.png)

**Comment by i8beef** [comment]
Hmm that's odd then... I get a red square icon with a white "1" in it. Only thing I can think is because maybe I'm using a self signed cert on my node red instance for SSL? I get it on all three of my devices...

**Comment by i8beef** [comment]
After some research, I think the self signed cert is the issue here. Closing as it isn't your issue.

**Comment by dceejay** [comment]
Do you have any links to that ?

**Comment by i8beef** [comment]
Well, there are a few places I've found weird behavior mentioned around SSL for this, mostly in random comments on random pages, but not really DOCUMENTED anywhere I can find...

The icon looks like a warning icon, or a notification icon you might display like "1 error with certificate" or "1 new email", etc... so I'm guessing it's like Chrome's default icon for when it has a certificate error or something. Doesn't appear to be a way around it unless I can setup a certificate authority for my Android devices, or get a real SSL cert from StarSSL or something

**Comment by dceejay** [comment]
most odd indeed. I tried a tablet with Android 6 and get what you see... - the phone I tried that worked was Android 5, (Chrome 53)
