### ISSUE TITLE
angular v1 announcement

### ISSUE THREAD

**Issue by mrkazoodle** [node-red/node-red-dashboard#812]
Hi,

There is an announcement on the start of the readme that this project is based on angular v1.

Even though it continues to say that the project needs to be considered to be on 'life support' it remains supported and there are new releases, which might lead people to believe that it is ok to use it, not knowing that a port from angular v1 to angular current means rewriting the project.

Is there a possibility of the project being ported to a different framework? You have probably the biggest user base of all dashboard solutions (others being flexdash and uibuilder), so many people can contribute, and many would benefit.

If not, please extend the announcement with an advice to use another solution, such as flexdash or uibuilder.

**Comment by dceejay** [comment]
Well, the team at Flowforge recently posted this https://flowforge.com/blog/2023/06/dashboard-announcement/ - so there may be light ahead - but nothing is decided or available yet - so the status of this project is unchanged. We can of course update the readme to make the angular v1 link explicit.

**Comment by dceejay** [comment]
See also https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/82

**Comment by dceejay** [comment]
Full Blog here - https://flowfuse.com/blog/dashboard/

closing
