### ISSUE TITLE
Unintentional tab change

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#82]
When I use a slider it often happens that the tab changes unwanted. (Only on iPhone, in the Browser it seems not to occur).

**Comment by knolleary** [comment]
This will be related to the swipe-left/right action for changing tabs.

**Comment by hobbyquaker** [comment]
Safari on iPhone7, iOS 10.0.2

**Comment by dceejay** [comment]
Now being looked at as part of the styling configuration work
(default now reverted to no swipe on master as there were multiple complaints about it being too sensitive)

**Comment by dceejay** [comment]
now on master
