### ISSUE TITLE
Property element of Link misssing/not open after update 3.1.0 (Dashboard 3.6.0)

### ISSUE THREAD

**Issue by Rawpnzl** [node-red/node-red-dashboard#820]
Properties of a Link does not open when click on EDIT or DOUBLE click on the link. The property window / side element does not appear anymore. It doesn't matter if it is new added link or an exisiting one. The "bug"(?) appeared after update to version 3.1.0. I can reproduce this issue on a second pc with a completely separate Node Red instance.

Node-RED-Dashboard version: 3.6.0
Node-RED version: 3.1.0
node.js version: 18.18.0
npm version: 9.8.1
Platform/OS: raspios buster
Browser: Chrome and Edge Windows 10 / Windows 11

![image](https://github.com/node-red/node-red-dashboard/assets/76262830/f77e799a-a1de-458c-9c38-3e0de11a364c)

Thank you very much and many greetings

**Comment by Rawpnzl** [comment]
Click on edit droped the following error in Chrome Console:

![image](https://github.com/node-red/node-red-dashboard/assets/76262830/dd582471-d291-4f9f-907a-67c6263f16cd)

**Comment by dceejay** [comment]
fixed in v3.6.1
