### ISSUE TITLE
Enable color picker on top of Drop down

### ISSUE THREAD

**Issue by Josov** [node-red/node-red-dashboard#821]
Once this issue was repaired but already since quite some time (months) the flaw re-appeared. When the Color picker is enabled the Color Picker always appears on top of the Drop down list (when working correct the list comes over the Color picker and is hiding the Color picker). 
This does not happen when the Color picker is disabled and the Color picker remains invisible 'behind' the drop down, this works well as it should be.

Dashboard: v3.6.1
Node-RED: v3.1.0
node.js: v16.20.2
npm: v8.19.4
Raspberry Pi OS 4 and 5

**Comment by dceejay** [comment]
can you share a small example flow that demonstrates this - so we get the exact order/layout correct
Thanks

**Comment by Josov** [comment]
Yes, thank you Dave,

Find here the sample flow and its code:
[
<img width="471" alt="image" src="https://github.com/node-red/node-red-dashboard/assets/41926094/3e10a294-c17f-40e8-8af8-9dbc46813afd">
](url)


`[{"id":"1f2610695a3a9684","type":"tab","label":"Dave Conway-Jones","disabled":false,"info":"","env":[]},{"id":"4152ee9860bc508b","type":"ui_dropdown","z":"1f2610695a3a9684","name":"","label":"Sample dropdown","tooltip":"","place":"Select option","group":"8114c4dafb2c8798","order":3,"width":"10","height":"1","passthru":false,"multiple":false,"options":[{"label":"","value":"","type":"str"}],"payload":"","topic":"topic","topicType":"msg","className":"","x":990,"y":1540,"wires":[[]]},{"id":"7455d35b2a50a51e","type":"ui_ui_control","z":"1f2610695a3a9684","name":"","events":"all","x":480,"y":1540,"wires":[["a1dd4ea3fa2596ca"]]},{"id":"a1dd4ea3fa2596ca","type":"function","z":"1f2610695a3a9684","name":"options","func":"msg.options = [\n    'a',\n    'b',\n    'c',\n    'd',\n    'e',\n    'f',\n    'g',\n    'h',\n    'i',\n    'j',\n    'l',\n    'm',\n    'n',\n    'o',\n    'p'\n]\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":660,"y":1540,"wires":[["4152ee9860bc508b"]]},{"id":"d009f87d5fd5c968","type":"ui_button","z":"1f2610695a3a9684","name":"","group":"8114c4dafb2c8798","order":1,"width":0,"height":0,"passthru":false,"label":"Enable Color Picker","tooltip":"","color":"","bgcolor":"","className":"","icon":"","payload":"true","payloadType":"bool","topic":"topic","topicType":"msg","x":520,"y":1400,"wires":[["b225269bf38b918b"]]},{"id":"9b03b7de663a73e8","type":"ui_button","z":"1f2610695a3a9684","name":"","group":"8114c4dafb2c8798","order":2,"width":0,"height":0,"passthru":false,"label":"Disable Color Picker","tooltip":"","color":"","bgcolor":"","className":"","icon":"","payload":"false","payloadType":"bool","topic":"topic","topicType":"msg","x":520,"y":1460,"wires":[["b225269bf38b918b"]]},{"id":"6657a184c58bd673","type":"ui_colour_picker","z":"1f2610695a3a9684","name":"","label":"Color picker node","group":"8114c4dafb2c8798","format":"hex","outformat":"string","showSwatch":true,"showPicker":true,"showValue":false,"showHue":false,"showAlpha":false,"showLightness":true,"square":"false","dynOutput":"false","order":4,"width":"8","height":"8","passthru":false,"topic":"topic","topicType":"msg","className":"","x":990,"y":1440,"wires":[[]]},{"id":"b225269bf38b918b","type":"function","z":"1f2610695a3a9684","name":"enable / disable","func":"msg.enabled = msg.payload;\nmsg.payload =  \"#ffa616\";\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":760,"y":1440,"wires":[["6657a184c58bd673"]]},{"id":"8114c4dafb2c8798","type":"ui_group","name":"Test Color Picker Node","tab":"b5a18cf1ef4edf26","order":1,"disp":true,"width":"10","collapse":false,"className":""},{"id":"b5a18cf1ef4edf26","type":"ui_tab","name":"Dave Conway-Jones","icon":"dashboard","disabled":false,"hidden":false}]`
