### ISSUE TITLE
ui_chart Label set by message cleared when another NR ui tab opened or switched in any instance (including self) of NR ui web page

### ISSUE THREAD

**Issue by WombatHollow** [node-red/node-red-dashboard#823]
### What are the steps to reproduce?
create a ui_chart object that has a slow update rate (ie minutes rather than < 1 second), and populate the Label field in the configuration to display the contents of a input message (ie {{msg.Label}})
Send it a new data every 60 seconds and include msg.Label

### What happens?
Once the first msg.Label is sent, the title on the Chart in the ui is displayed as expected.  but if you then open the ui in another browser tab or Browser, or switch this tab to another NR ui tab and back, the Chart title is cleared until the ui_chart node recieves a message with msg.Label set.
NB changing Browser Tabs has no effect, this is opening a NR UI in a browser Tab, or changing between NR UI tabs (incluidng between two other tabs than the one with affected CHart.

### What do you expect to happen?
Once set the Chart title should persist, and not be cleared by other users opening the ui, or even switching back and forth between ui tabs

### Please tell us about your environment:

- [ ] Node-RED-Dashboard version: latest 3.6.2
- [ ] Node-RED version: 3.1.0
- [ ] node.js version: v18.18.2
- [ ] npm version: 9.8.1
- [ ] Platform/OS: Raspi 3B running "Raspbian GNU/Linux 11 (bullseye)"
- [ ] Browser: Both Edge and Chrome on Windows 10

**Comment by dceejay** [comment]
Yes - that is the way it works. The workaround is to use the ui_control node to notify you of a change of tab or reload and use that to resend any extra data you require.

As the development of Dashboard v1 is no longer on-going  - then adding this capability will not happen.

(see Dashboard v2 instead for new features)
