### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by jeroenpeeters** [node-red/node-red-dashboard#83]
I'm not sure if this is the right place to ask, but I will do so anyway.

How can I customize the dashboards' theme? Is it possible to have my own theme appear at the dashboard theme dropdown?

Could you please direct me to the best way possible to achieve a custom look and feel.

**Comment by knolleary** [comment]
Hi, we prefer questions to be asked on the mailing list - linked at the bottom of https://nodered.org

We don't currently support custom themes, but it is very high on the todo list.

Currently you can inject your own css into your dashboard using the ui_template node. Very manually, but doable.

**Comment by dceejay** [comment]
It's on the todo list - https://github.com/node-red/node-red-dashboard/projects/1
