### ISSUE TITLE
Dropdown generates message when opening tab

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#84]
When I open a tab containing a dropdown the dropdown generates a message, even if the checkbox "If msg arrives on input, pass through to output" is not checked.

**Comment by dceejay** [comment]
closed by c23c1f4

**Comment by hobbyquaker** [comment]
thx for the fix. Just ran into a little bit of confusion because 2.1.1 isn't published on npm yet, so I opened https://github.com/node-red/node-red-dashboard/pull/97 to prevent this confusion in future ;-)

**Comment by dceejay** [comment]
what was the confusion? (so we don't do whatever it is...)

**Comment by knolleary** [comment]
`package.json` has been updated to say `2.1.1`... something we don't normally do until we're doing the release.

**Comment by dceejay** [comment]
ah ok - can undo that until we are ready :-)

**Comment by hobbyquaker** [comment]
Hehe, sorry to go on your nerves with this. I just thought "yeah, this bug is fixed" and did a npm install node-red-dashboard@latest and was confused because the bug was still there... never mind :)

**Comment by dceejay** [comment]
ah - npm i node-red/node-red-dashboard  will pull it from git

**Comment by hobbyquaker** [comment]
thx!

**Comment by dceejay** [comment]
I'm tracking todos on the "project" page - https://github.com/node-red/node-red-dashboard/projects/1
