### ISSUE TITLE
Menu icon alignment

### ISSUE THREAD

**Issue by hobbyquaker** [node-red/node-red-dashboard#85]
Would be nice if the icons and texts could be aligned in the menu

![bildschirmfoto 2016-10-23 um 10 26 38](https://cloud.githubusercontent.com/assets/2503307/19624961/414eb31c-990b-11e6-88e4-144d33f971f8.png)

**Comment by dceejay** [comment]
which icon set are you using ? Are you mixing fa-icons (variable width) with material icons (fixed) ?

**Comment by hobbyquaker** [comment]
You're right, that was a mixture. I now reconfigured the icons, using fa- only and added the fa-fw. Now it's like I wanted, thank you! :-)

![bildschirmfoto 2016-10-23 um 15 36 04](https://cloud.githubusercontent.com/assets/2503307/19626645/87778348-9936-11e6-83cd-0162380861fb.png)

**Comment by dceejay** [comment]
thanks - I have also fixed css slightly so if you do want to use material icons they will also align* with the fa icons (as long as you also use fa-fw).

* not in master yet - but will get there.

**Comment by dceejay** [comment]
now in Master 0dbf26ff7e304a1041c98ec9706d013117b33b99
