### ISSUE TITLE
Chart not appearing on browser

### ISSUE THREAD

**Issue by yonas124** [node-red/node-red-dashboard#86]
Hello, my chart doesn't appear on browser for some reason. Any idea why?
Thank you

nodejs v0.10.29
npm 2.15.11
raspbian jessie

![nodered_issue](https://cloud.githubusercontent.com/assets/23074849/19722351/7da72b36-9ba0-11e6-96d4-333192772e6d.png)

**Comment by dceejay** [comment]
which browser ? is the browser running on the Pi also ?
which version of Node-RED and dashboard ? (both printed out in the console when Node-RED starts)

**Comment by yonas124** [comment]
Hi dceejay,

Node-RED version: v0.15.1
Node.js  version: v0.10.29
Linux 4.4.11-v7+ arm LE
Dashboard version 2.1.0

Browser is running on my pc. I used browser on my cellphone too with same result.

Occasionally it shows something like this:
27 Oct 04:46:42 - [error] [ui_gauge:c3b04fbd.6e52d] TypeError: Cannot call method 'toString' of undefined

**Comment by knolleary** [comment]
Does that error message appear when node-red starts its flows or when a message arrives at the gauge node?

What is that Temperature node? I don't recognise it. Can you add a Debug node set to log the complete msg object alongside the chart node and capture the messages you're passing to it?

**Comment by yonas124** [comment]
knolleary

The Temperature node is node-red-contrib-modbus library
When I post the issue, the data type was string -> [0] so I thought this is the culprit
Now I converted it to number so the msg is: **{ "payload": 51, "_msgid": "1c2156ef.e3dea9" }**
Chart responded: **TypeError: Cannot read property 'length' of undefined** everytime msg arrives

**Comment by yonas124** [comment]
Hi Dave,

 

Node-RED version: v0.15.1

Node.js  version: v0.10.29

Linux 4.4.11-v7+ arm LE

Dashboard version 2.1.0

 

Browser is running on my pc. I used browser on my cellphone too with same result.

 

Regards

Yonas

**Comment by yonas124** [comment]
Occasionally it shows something like this:

27 Oct 04:46:42 - [error] [ui_gauge:c3b04fbd.6e52d] TypeError: Cannot call method 'toString' of undefined

 

From: Andreas Yonas [mailto:andreas.yonas@syntek.co.id] 
Sent: Thursday, October 27, 2016 11:00 AM
To: 'node-red/node-red-dashboard'; 'node-red/node-red-dashboard'
Cc: 'Author'
Subject: RE: [node-red/node-red-dashboard] Chart not appearing on browser (#86)

 

Hi Dave,

 

Node-RED version: v0.15.1

Node.js  version: v0.10.29

Linux 4.4.11-v7+ arm LE

Dashboard version 2.1.0

 

Browser is running on my pc. I used browser on my cellphone too with same result.

 

Regards

Yonas

**Comment by dceejay** [comment]
Hi - can you share the actual flow here - not sure I recognise those input nodes. (not that they should matter - but as you say we seem not to be handling whatever they are sending)

**Comment by dceejay** [comment]
you can't feed that output from the chart into the next gauge (as that is sending an array for saving the history of the chart)  - just wire it in parallel.

If the message really is { "payload": 51, "_msgid": "1c2156ef.e3dea9" }
AND is really an object and not a string - then it should work fine...

**Comment by yonas124** [comment]
dceejay

It should work but it didn't so I decided to install different version of nodejs: v4.6.1, before it was Jessie stock 0.10.29
Now it works fine.

I guessed there's some sort of incompatibility between the Dashboard and nodejs version.

Thanks guys, see you around.
