### ISSUE TITLE
Cant choose some Groups in some Flows

### ISSUE THREAD

**Issue by WookieFPV** [node-red/node-red-dashboard#88]
I started splitting my Node into seperate Flows.
But if i copy some node to another flow i cant chose the group that it belongs to.
In the picture you can see that there is no Group "PC". But in the Dashboard config there is still the "PC" group.
If i click in the Dashboard setting on the red marked item "CPU" (which is in the group "PC")  for example it shows me that this node doesnt belong to the group "PC".

Looks really weird to me. 

Im using:
- node.js v0.10.29 
- node red0.14.6
- I think im using Dashboard  Version 2.0.1 (that was the lastest entry in the changelog.md)

![bug2](https://cloud.githubusercontent.com/assets/18392496/19869400/7bb8d120-9fac-11e6-8b76-0fbab60207dd.png)

![bug](https://cloud.githubusercontent.com/assets/18392496/19869136/4dfd6aee-9fab-11e6-8ac2-bbc65242805a.png)

**Comment by knolleary** [comment]
In Node-RED 0.14, the group/tab nodes get scoped to the flow you're on when you create them. That causes this confusion.

You can change their scope using the dropdown at the bottom of their edit dialogs. Set it to 'global' or 'all flows' and you'll be able to select them from everywhere.

In Node-RED 0.15 we default to globally scoped to avoid this.

**Comment by WookieFPV** [comment]
thank you for the answer, i will update Node-RED to 0.15 or later than.

**Comment by dceejay** [comment]
if you are on Pi - then  sudo apt-get update && sudo apt-get upgrade nodered  should do it

**Comment by WookieFPV** [comment]
I just gave my pi the chance to update everything :+1: 

and by the way, i really love node red. Keep up the awesome work.

**Comment by WookieFPV** [comment]
just a hint for everyone, never change a running system.

**Comment by dceejay** [comment]
Do you recall which nodes broke ?

did you flush the npm cache ? and rebuild any that had binary extensions ?
http://nodered.org/docs/getting-started/upgrading
