### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by fcgdam** [node-red/node-red-dashboard#9]
Before making a pull request (if needed), some quick notes:

I've installed this repository under my Node-red installation and had the following issues:

- An error at the initial page: Couldn't GET /ui/%7B%7Bmain.selectedTab.link%7D%7D
    I've solved this by modifying the partials/main.html page line from:
            iframe class="iframe" src="{{main.selectedTab.link}}" 
    to
           frame class="iframe" **ng-src**="{{main.selectedTab.link}}"

- Gauges weren't displayed at all. Missing raphael.min.js file.  The npm install command failed to find the raphael defined version in package.json, so I've installed the latest. Gauges now appear, but do not work.  I've also had to change the index.html file to refer to raphel.min.js instead of raphel-min.js.

I'm migrating from the npm repository node-red-contrib-ui version, so I've alread had some ui elements defined. 

EDIT: Also shouldn't the README.md file refer to instructions for installing this repository, not Adrea's Tatar repository? Otherwise many people might be confused... :)

**Comment by knolleary** [comment]
@fcgdam thanks for raising this. We're still working on this code ahead of getting a stable release done, so appreciate your feedback. I'll let @jdp1g09 comment on the specifics, but I don't have any issues with gauges when I run. Also, your suggested change to parials/main.html has dropped off your comment.

**Comment by fcgdam** [comment]
I've removed the greater and less than symbols, so we can see the change that I've made.
As I referred I've started not from a clean installation, but from a configuration that already had some configured ui nodes. I'll investigate further if the issue is related to that or not.

**Comment by dceejay** [comment]
in meantime - I have slightly edited the readme to at least point to the correct project... plenty more to do.

**Comment by fcgdam** [comment]
I've re run the npm install, and this time raphael installed. Probably a glitch from my side.

**Comment by greeka** [comment]
Hello, I have the same problem.
My environment: 
RPi3 with Raspbian
Node-RED version: v0.15.2
Node.js  version: v0.10.29
Dashboard version 2.1.0 started at /ui
When I run /ui I see request to /ui/%7B%7B%20main.selectedTab.link%20%7D%7D
How to fix it without upgrading to nodejs 4.x?

**Comment by dceejay** [comment]
try the latest dashboard 2.2.0, should have fixed it.

**Comment by greeka** [comment]
The same with 2.2.0

**Comment by dceejay** [comment]
which browser ? os ?
which ui nodes have you used ?

**Comment by greeka** [comment]
Tested on FF 50.0.2, Chrome 54.0.2840.99 m, Windows 7.
I have installed node-red-dashboard, also have additional module node-modbus. The rest is default set of modules.

**Comment by greeka** [comment]
Any news?

**Comment by knolleary** [comment]
@greeka as this issue is closed it isn't being looked at. If you are hitting this issue, and you are certain you are running the latest release of dashboard, and that you've refreshed your browser cache to be certain you're running the latest release of dashboard, then please raise a new issue.
