### ISSUE TITLE
External modules

### ISSUE THREAD

**Issue by gillerman** [node-red/node-red-dashboard#90]
I am trying to reuse a 3rd party GUI widget library in a node red dashboard.  But the dashboard doesn't load the 3rd party module in application module.  How to load external modules to main module?

**Comment by dceejay** [comment]
Hi For general how-to questions we prefer the mailing list - keeping this for actual issues and bug reports etc. https://groups.google.com/forum/#!forum/node-red
or the slack channel

**Comment by gillerman** [comment]
Is there a google group for the new dashboard?

**Comment by dceejay** [comment]
just the general Node-RED one - link above

**Comment by gillerman** [comment]
OK, thank you.
