### ISSUE TITLE
Menu Link not resolving server localhost urls

### ISSUE THREAD

**Issue by isramos** [node-red/node-red-dashboard#91]
In my dashboard, I want to have an iframe menu link to my server's http://localhost:1880/mypage
Right now it resolves the localhost of the client and not the server.

**Comment by knolleary** [comment]
You need to use the servers IP address, not localhost.

**Comment by isramos** [comment]
right, but my node-red is running in a server with dynamic IP, so that not practical to use hardcode its IP address.

**Comment by knolleary** [comment]
Ok, so we would need to add some special syntax that tells the dashboard the link is relative to the current page and figure out the right IP/host to use based in that dynamically... Or did you have another suggestion for how it should work?

**Comment by dceejay** [comment]
if your server can use mDNS - Bonjour/Avahi - then it may be resolvable locally as "yourservers_hostname.local" - where yourserver_hostname is the hostname of your server...

**Comment by knolleary** [comment]
@dceejay was thinking about this earlier - seems reasonable that if the configured URL starts with a `/` then the dashboard could auto-add the appropriate parts from `document.location` to make a proper URL.

**Comment by dceejay** [comment]
surely if it starts with anything not http:// etc then it'll be relative to where it is now... ie the server. ?

**Comment by knolleary** [comment]
huh, I thought an iframe src attribute had to be fully qualified... but it appears not.

@isramos so just set your link's url to `/mypage` and it should just work. Let us know if not.
