### ISSUE TITLE
ui_switch no updating on UI

### ISSUE THREAD

**Issue by Aietes** [node-red/node-red-dashboard#94]
The ui_switch is not working properly for me. When fed from a node it doesn't render the state change on the UI. When I manually trigger the same input via an inject node, the ui_switch updates on the UI without problem. Of course I double checked, and tried various different inputs, from JSON to a boolean value.

**Comment by knolleary** [comment]
Could you provide some concrete examples that are failing for you?

**Comment by Aietes** [comment]
I'm using a hue input node, and parse the result in a function node. The value I then pass on to the ui_switch is either {"on":true} or {"on":false}. I set the ui_switch ON/OFF states respectively. I checked via a debug node if the function node actually fires, and it does, but the ui_switch doesn't update in the UI. When sending the same object manually via inject, it works.

**Comment by dceejay** [comment]
which Hue node are you using ? Does it return boolean true and false ? The type of input must match the type you set in the ui_switch (default boolean).

**Comment by Aietes** [comment]
The type of input does match, I'm using a function node to parse the output of the hue node, and pass on one of two json objects:  {"on":true} or {"on":false}. I did set the ON/OFF values in the switch to the same values respectively.

**Comment by dceejay** [comment]
Hi - any chance you can share a portion of the flow here that exhibits the problem ?
thanks

**Comment by dceejay** [comment]
Hi is this still a problem ? can you share some code so we can see the problem ? or can we close it ?

**Comment by luigisaetta** [comment]
I don't know if I'm hitting the same problem. The doc is not clear on what message should be passed in input to the switch. From a function node I tried with this code.. but nothing happen to the visible state of the switch

msg.enabled = true;
if (msg.payload.state.on === true)
{
    msg.payload = {"on":true};
}
else
{
    msg.payload = {"on":false};
}
return msg;

**Comment by dceejay** [comment]
Hi the switch is expecting the payload to match whatever you have set it to output. By defualt this si boolean true/false... so you function only need to set
     msg.payload = true;
or   msg.payload = false;
rather than an object.

**Comment by luigisaetta** [comment]
Ok, thanks, I got.
